# Generated by Django 4.2.23 on 2026-10-01 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vault', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gervazy', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, max_length=998)),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('is_inbound', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'mail attachment',
                'verbose_name_plural': 'mail attachments',
                'ordering': ['filename'],
            },
        ),
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('personal', 'Personal'), ('system', 'System')], db_index=True, default='personal', max_length=10)),
                ('label', models.CharField(help_text="What to call this account, e.g. 'Work' or 'Platform mail'.", max_length=120)),
                ('email_address', models.EmailField(help_text='The address this account sends as.', max_length=254)),
                ('host', models.CharField(blank=True, max_length=255)),
                ('port', models.PositiveIntegerField(default=587)),
                ('use_tls', models.BooleanField(default=True, help_text='STARTTLS, the usual choice on port 587.')),
                ('use_ssl', models.BooleanField(default=False, help_text='Implicit TLS, the usual choice on port 465.')),
                ('username', models.CharField(blank=True, help_text='The login for both SMTP and IMAP, when they share one.', max_length=255)),
                ('timeout', models.PositiveIntegerField(default=10)),
                ('imap_host', models.CharField(blank=True, help_text='Leave blank if this account only sends.', max_length=255)),
                ('imap_port', models.PositiveIntegerField(default=993)),
                ('imap_use_ssl', models.BooleanField(default=True)),
                ('folder', models.CharField(blank=True, default='INBOX', max_length=255)),
                ('keyholder', models.CharField(choices=[('person', "The owner's own strongbox"), ('platform', 'The platform strongbox')], default='person', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, help_text='What the mail server last said, verbatim.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'mailbox',
                'verbose_name_plural': 'mailboxes',
                'ordering': ['kind', 'label'],
            },
        ),
        migrations.CreateModel(
            name='MailQuotaPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('metric_code', models.CharField(db_index=True, max_length=100)),
                ('limit', models.DecimalField(decimal_places=10, max_digits=30)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime')], default='daily', max_length=20)),
                ('mode', models.CharField(choices=[('track', 'Track only'), ('warn', 'Warn'), ('block', 'Block')], default='block', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mail quota policy',
                'verbose_name_plural': 'Mail quota policies',
                'ordering': ['metric_code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, max_length=998)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='queued', max_length=10)),
                ('error', models.TextField(blank=True)),
                ('jess_message_id', models.PositiveIntegerField(blank=True, null=True)),
                ('campaign_ref', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_records', to='mail.mailbox')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mail_sent_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sent record',
                'verbose_name_plural': 'sent records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MailUsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_code', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=30)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('source_type', models.CharField(blank=True, max_length=100)),
                ('source_id', models.CharField(blank=True, max_length=255)),
                ('source_label', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('recorded', 'Recorded'), ('voided', 'Voided')], default='recorded', max_length=20)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mail usage event',
                'verbose_name_plural': 'Mail usage events',
                'ordering': ['-occurred_at'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='mailquotapolicy',
            constraint=models.UniqueConstraint(fields=('metric_code',), name='mail_mailquotapolicy_one_per_metric'),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Empty for the system mailbox: it belongs to the platform rather than to any person.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mailboxes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='secret',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mailboxes', to='gervazy.encryptedsecret'),
        ),
        migrations.AddField(
            model_name='mailattachment',
            name='mailbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mail.mailbox'),
        ),
        migrations.AddField(
            model_name='mailattachment',
            name='vault_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_attachments', to='vault.vaultfile'),
        ),
        migrations.AddIndex(
            model_name='sentrecord',
            index=models.Index(fields=['mailbox', '-created_at'], name='mail_sentre_mailbox_b972ad_idx'),
        ),
        migrations.AddIndex(
            model_name='sentrecord',
            index=models.Index(fields=['status'], name='mail_sentre_status_84ec24_idx'),
        ),
        migrations.AddIndex(
            model_name='mailusageevent',
            index=models.Index(fields=['metric_code', 'occurred_at'], name='mailusageevent_mtime'),
        ),
        migrations.AddIndex(
            model_name='mailusageevent',
            index=models.Index(fields=['user', 'metric_code'], name='mailusageevent_umetric'),
        ),
        migrations.AddConstraint(
            model_name='mailusageevent',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('idempotency_key',), name='mail_mailusageevent_idem'),
        ),
        migrations.AddConstraint(
            model_name='mailbox',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False)), fields=('owner', 'email_address'), name='mail_one_account_per_address'),
        ),
        migrations.AddIndex(
            model_name='mailattachment',
            index=models.Index(fields=['mailbox', 'message_id'], name='mail_mailat_mailbox_38d3ad_idx'),
        ),
    ]
