# Generated by Django 4.2.23 on 2026-05-31 14:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_remove_asset_mint_transaction_type'),
        ('mission_economy', '0002_migrate_from_kanban'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practitionerallowance',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='practitionerallowance',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='practitionerallowance',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='practitionerincomeprofile',
            name='default_income_account',
            field=models.ForeignKey(blank=True, help_text='Default account receiving salary, vesting releases, bonuses, or lease payments.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='practitioner_income_profiles', to='assets.ledgeraccount'),
        ),
    ]
