# Generated by Django 4.2.23 on 2026-06-04 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jsonform.models.fields
import toto.api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gervazy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('provider', models.CharField(choices=[('generic', 'Generic'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('github', 'GitHub'), ('custom', 'Custom'), ('rule_based', 'Rule-based (no API key)')], default='generic', max_length=40)),
                ('base_url', models.URLField(blank=True, help_text='Base API URL, e.g. https://api.openai.com/v1/')),
                ('auth_type', models.CharField(choices=[('none', 'No authentication'), ('api_key_header', 'API key header'), ('bearer_token', 'Bearer token'), ('query_param', 'Query parameter'), ('hmac', 'HMAC signature'), ('signature', 'Asymmetric request signature'), ('custom', 'Custom')], default='bearer_token', max_length=40)),
                ('auth_config', django_jsonform.models.fields.JSONField(blank=True, default=dict, help_text='Non-secret auth config such as header name or timeout.')),
                ('extra', django_jsonform.models.fields.JSONField(blank=True, default=dict, help_text='Non-secret provider-specific configuration.', validators=[toto.api.models._reject_secret_like_json])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_slow', models.BooleanField(default=True, help_text='When enabled (default), inference is queued via Celery and the workflow engine. Disable only for connectors with sub-second latency.')),
                ('api_secret', models.ForeignKey(blank=True, help_text='Encrypted API key/token stored in Gervazy.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_api_connectors', to='gervazy.encryptedsecret')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('signing_key', models.ForeignKey(blank=True, help_text='Encrypted private key for signed API requests.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_signing_keys', to='gervazy.encryptedprivatekey')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='steven/agent_avatars/')),
                ('system_prompt', models.TextField(default='You are Steven, a helpful AI agent manager. Be accurate, concise, and safe.')),
                ('model_name', models.CharField(default='openai:gpt-4.1-mini', max_length=120)),
                ('temperature', models.FloatField(default=0.2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='steven.agentconnector')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steven_agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='steven.agentprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='steven.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_prompt', models.TextField()),
                ('result', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='steven.agentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('echo', 'Echo'), ('calculator', 'Calculator'), ('current_time', 'Current time'), ('graph_cypher_qa', 'Graph Cypher QA (ravioli Neo4j)')], max_length=80)),
                ('enabled', models.BooleanField(default=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='steven.agentprofile')),
            ],
            options={
                'ordering': ['agent__name', 'key'],
                'unique_together': {('agent', 'key')},
            },
        ),
    ]
