# Generated by Django 4.2.23 on 2026-05-13 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gervazy', '0004_remove_encryptedfilechunk_unique_chunk_index_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('steven', '0003_agentconnector_inherit_apiconnector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentconnector',
            name='api_secret',
            field=models.ForeignKey(blank=True, help_text='Encrypted API key/token stored in Gervazy.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_api_connectors', to='gervazy.encryptedsecret'),
        ),
        migrations.AlterField(
            model_name='agentconnector',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agentconnector',
            name='provider',
            field=models.CharField(choices=[('generic', 'Generic'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('github', 'GitHub'), ('custom', 'Custom')], default='generic', max_length=40),
        ),
        migrations.AlterField(
            model_name='agentconnector',
            name='signing_key',
            field=models.ForeignKey(blank=True, help_text='Encrypted private key for signed API requests.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_signing_keys', to='gervazy.encryptedprivatekey'),
        ),
    ]
