# Generated by Django 4.2.23 on 2026-05-17 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('people', '0001_initial'),
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_events', to='people.person'),
        ),
        migrations.AddField(
            model_name='event',
            name='route',
            field=models.ForeignKey(blank=True, help_text='Route connected to this event, if movement is involved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='locations.route'),
        ),
        migrations.AddField(
            model_name='event',
            name='zone',
            field=models.ForeignKey(blank=True, help_text='Zone for this event, if it is geographically scoped.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='locations.zone'),
        ),
    ]
