# Generated by Django 4.2.23 on 2026-05-11 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_maplayer_owner'),
        ('events', '0002_event_uid_eventcategory_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.ForeignKey(blank=True, help_text='Specific address for this event, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='locations.address'),
        ),
        migrations.AddField(
            model_name='event',
            name='route',
            field=models.ForeignKey(blank=True, help_text='Route connected to this event, if movement is involved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='locations.route'),
        ),
        migrations.AddField(
            model_name='event',
            name='zone',
            field=models.ForeignKey(blank=True, help_text='Zone for this event, if it is geographically scoped.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='locations.zone'),
        ),
    ]
