# Generated by Django 4.2.23 on 2026-05-20 02:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('availability_type', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('busy', 'Busy'), ('reserved', 'Reserved'), ('out_of_office', 'Out of office')], max_length=30)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('blocks_scheduling', models.BooleanField(default=True, help_text='Whether this availability blocks scheduling.')),
            ],
            options={
                'verbose_name': 'availability',
                'verbose_name_plural': 'availabilities',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledEvent',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('public', models.BooleanField(default=True, help_text='Check if this event is publicly visible.')),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Maximum number of participants, if limited.', null=True)),
                ('requires_registration', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'scheduled event',
                'verbose_name_plural': 'scheduled events',
                'ordering': ['-start_time'],
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='address',
        ),
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='event',
            name='route',
        ),
        migrations.RemoveField(
            model_name='event',
            name='zone',
        ),
    ]
