# Generated by Django 4.2.23 on 2026-05-20 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_initial'),
        ('people', '0002_initial'),
        ('bazaar', '0007_alter_product_event'),
        ('events', '0004_availability_scheduledevent_remove_event_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='address',
            field=models.ForeignKey(blank=True, help_text='Specific address for this event, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_events', to='locations.address'),
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_events', to='events.eventcategory'),
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_scheduled_events', to='people.person'),
        ),
        migrations.AddField(
            model_name='availability',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='people.person'),
        ),
    ]
