# Generated by Django 4.2.23 on 2026-05-20 02:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_initial'),
        ('events', '0005_delete_event_scheduledevent_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventInvite',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='events.scheduledevent')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_invites', to='people.person')),
            ],
            options={
                'verbose_name': 'event invite',
                'verbose_name_plural': 'event invites',
                'ordering': ['sent_at'],
                'unique_together': {('event', 'person')},
            },
        ),
    ]
