# Generated by Django 4.2.23 on 2026-05-20 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_initial'),
        ('events', '0006_eventinvite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledevent',
            name='organizer',
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='organizers',
            field=models.ManyToManyField(blank=True, help_text='People who can manage this event and send invites.', related_name='organized_events', to='people.person'),
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Person who created this event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_events', to='people.person'),
        ),
    ]
