# Generated by Django 4.2.23 on 2026-08-25 01:52

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('choice', models.CharField(choices=[('for', 'For'), ('against', 'Against'), ('abstain', 'Abstain')], max_length=16)),
                ('weight', models.DecimalField(decimal_places=6, max_digits=24)),
                ('active', models.BooleanField(default=True)),
                ('cast_at', models.DateTimeField(auto_now_add=True)),
                ('cast_by_ref', models.CharField(blank=True, max_length=255)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('auth_evidence', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('proposition', 'cast_at'),
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('scope_type', models.CharField(blank=True, max_length=80)),
                ('scope_uid', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('configuration_snapshot', models.JSONField(blank=True, default=dict)),
                ('record_date', models.DateField(default=django.utils.timezone.localdate)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('held_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('eligible_weight', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=24)),
                ('present_weight', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=24)),
                ('eligible_voters', models.PositiveIntegerField(default=0)),
                ('present_voters', models.PositiveIntegerField(default=0)),
                ('quorum_met', models.BooleanField(default=False)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-held_at', '-scheduled_for', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=180)),
                ('resolution_text', models.TextField()),
                ('rationale', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('attachment_ref', models.CharField(blank=True, max_length=255)),
                ('attachment_hash', models.CharField(blank=True, max_length=128)),
                ('attachment_label', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('configuration_snapshot', models.JSONField(blank=True, default=dict)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('block_uid', models.UUIDField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('meeting', 'order'),
            },
        ),
        migrations.CreateModel(
            name='RollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source', models.CharField(choices=[('shareholders', 'Shareholders, by voting weight'), ('members', 'Company members, one vote each'), ('selected', 'Manually selected people')], default='selected', max_length=24)),
                ('voter_ref', models.CharField(max_length=255)),
                ('voter_name', models.CharField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=24)),
                ('eligible', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('excluded', 'Excluded')], default='absent', max_length=16)),
                ('represented_by', models.CharField(blank=True, help_text="Who is voting on this voter's behalf, if anyone.", max_length=255)),
                ('evidence_ref', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'roll entries',
                'ordering': ('meeting', 'voter_name'),
            },
        ),
        migrations.CreateModel(
            name='VotingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('scope_type', models.CharField(blank=True, max_length=80)),
                ('scope_uid', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('quorum_basis', models.CharField(choices=[('weight', 'Represented voting weight'), ('members', 'Represented voters')], default='weight', max_length=16)),
                ('quorum_percent', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5)),
                ('majority_basis', models.CharField(choices=[('cast', 'Ballots cast'), ('decisive', 'For and against votes'), ('present', 'Present voting weight'), ('eligible', 'All eligible voting weight')], default='cast', max_length=16)),
                ('majority_percent', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5)),
                ('abstention_rule', models.CharField(choices=[('include', 'Include in the majority denominator'), ('exclude', 'Exclude from the majority denominator'), ('against', 'Count as against')], default='include', max_length=16)),
                ('threshold_mode', models.CharField(choices=[('strict', 'Must be more than the threshold'), ('inclusive', 'May equal the threshold')], default='strict', max_length=16)),
                ('is_default', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('scope_type', 'scope_uid', 'name'),
            },
        ),
        migrations.AddConstraint(
            model_name='votingconfiguration',
            constraint=models.UniqueConstraint(fields=('scope_type', 'scope_uid', 'slug'), name='bc_one_voting_config_slug_per_scope'),
        ),
        migrations.AddConstraint(
            model_name='votingconfiguration',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('scope_type', 'scope_uid'), name='bc_one_default_voting_config'),
        ),
        migrations.AddConstraint(
            model_name='votingconfiguration',
            constraint=models.CheckConstraint(check=models.Q(('quorum_percent__gte', 0), ('quorum_percent__lte', 100)), name='bc_quorum_percent_range'),
        ),
        migrations.AddConstraint(
            model_name='votingconfiguration',
            constraint=models.CheckConstraint(check=models.Q(('majority_percent__gte', 0), ('majority_percent__lte', 100)), name='bc_majority_percent_range'),
        ),
        migrations.AddField(
            model_name='rollentry',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roll', to='voting.meeting'),
        ),
        migrations.AddField(
            model_name='rollentry',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bc_roll_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposition',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bc_propositions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposition',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propositions', to='voting.meeting'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='chaired_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bc_meetings_chaired', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meeting',
            name='configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meetings', to='voting.votingconfiguration'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='cast_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bc_ballots_cast', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ballot',
            name='proposition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ballots', to='voting.proposition'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='roll_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ballots', to='voting.rollentry'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='supersedes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='voting.ballot'),
        ),
        migrations.AddConstraint(
            model_name='rollentry',
            constraint=models.UniqueConstraint(fields=('meeting', 'voter_ref'), name='bc_one_roll_entry_per_voter'),
        ),
        migrations.AddConstraint(
            model_name='rollentry',
            constraint=models.CheckConstraint(check=models.Q(('weight__gte', 0)), name='bc_roll_weight_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='proposition',
            constraint=models.UniqueConstraint(fields=('meeting', 'slug'), name='bc_one_proposition_slug_per_meeting'),
        ),
        migrations.AddConstraint(
            model_name='proposition',
            constraint=models.UniqueConstraint(fields=('meeting', 'order'), name='bc_one_proposition_order_per_meeting'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['scope_type', 'scope_uid'], name='bc_meeting_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.UniqueConstraint(fields=('scope_type', 'scope_uid', 'slug'), name='bc_one_meeting_slug_per_scope'),
        ),
        migrations.AddIndex(
            model_name='ballot',
            index=models.Index(fields=['proposition', 'active'], name='bc_ballot_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='ballot',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('proposition', 'roll_entry'), name='bc_one_active_ballot'),
        ),
        migrations.AddConstraint(
            model_name='ballot',
            constraint=models.CheckConstraint(check=models.Q(('weight__gte', 0)), name='bc_ballot_weight_non_negative'),
        ),
    ]
