# Generated by Django 4.2.23 on 2026-08-24 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('key', models.SlugField(max_length=180)),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('company', 'Company actions'), ('department', 'Department decisions'), ('voting', 'Voting decisions'), ('generic', 'Other')], default='generic', max_length=24)),
                ('scope_type', models.CharField(blank=True, max_length=80)),
                ('scope_uid', models.UUIDField(blank=True, null=True)),
                ('algorithm', models.CharField(default='sha256', max_length=32)),
                ('format_version', models.CharField(default='bc-ledger-xml-1', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sequence', models.PositiveIntegerField()),
                ('previous_hash', models.CharField(blank=True, max_length=128)),
                ('entry_hash', models.CharField(editable=False, max_length=128)),
                ('payload_xml', models.TextField()),
                ('algorithm', models.CharField(default='sha256', max_length=32)),
                ('format_version', models.CharField(default='bc-ledger-xml-1', max_length=32)),
                ('actor_ref', models.CharField(blank=True, max_length=255)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_type', models.CharField(blank=True, max_length=100)),
                ('source_uid', models.UUIDField(blank=True, null=True)),
                ('source_ref', models.CharField(blank=True, max_length=255)),
                ('signature', models.TextField(blank=True)),
                ('signature_key_id', models.CharField(blank=True, max_length=128)),
                ('signature_algorithm', models.CharField(blank=True, max_length=32)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bc_ledger_entries_recorded', to=settings.AUTH_USER_MODEL)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ledger.ledger')),
            ],
            options={
                'verbose_name_plural': 'ledger entries',
                'ordering': ('ledger', 'sequence'),
            },
        ),
        migrations.AddIndex(
            model_name='ledger',
            index=models.Index(fields=['scope_type', 'scope_uid'], name='bc_ledger_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledger',
            constraint=models.UniqueConstraint(fields=('scope_type', 'scope_uid', 'key'), name='bc_one_ledger_key_per_scope'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['source_type', 'source_uid'], name='bc_entry_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.UniqueConstraint(fields=('ledger', 'sequence'), name='bc_one_sequence_per_ledger'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('sequence__gt', 1)), fields=('ledger', 'previous_hash'), name='bc_one_successor_per_block'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('source_uid__isnull', False)), fields=('ledger', 'source_type', 'source_uid'), name='bc_one_source_per_ledger'),
        ),
    ]
