# Generated by Django 4.2.23 on 2026-08-14 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0002_voting_core'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(blank=True, db_index=True, max_length=40)),
                ('scope_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('title', models.CharField(max_length=150)),
                ('outcome', models.CharField(choices=[('winner', 'Winner'), ('tie', 'Tie'), ('no_ballots', 'No ballots')], max_length=12)),
                ('winner_label', models.CharField(blank=True, max_length=60)),
                ('electorate_key', models.CharField(blank=True, max_length=40)),
                ('electorate_size', models.PositiveIntegerField(default=0)),
                ('total_ballots', models.PositiveIntegerField(default=0)),
                ('total_weight', models.PositiveIntegerField(default=0)),
                ('turnout', models.FloatField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'decision',
                'verbose_name_plural': 'decisions',
                'ordering': ['-decided_at'],
            },
        ),
        migrations.CreateModel(
            name='PollsQuotaPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('metric_code', models.CharField(db_index=True, max_length=100)),
                ('limit', models.DecimalField(decimal_places=10, max_digits=30)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime')], default='daily', max_length=20)),
                ('mode', models.CharField(choices=[('track', 'Track only'), ('warn', 'Warn'), ('block', 'Block')], default='block', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Polls quota policy',
                'verbose_name_plural': 'Polls quota policies',
                'ordering': ['metric_code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PollsUsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_code', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=30)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('source_type', models.CharField(blank=True, max_length=100)),
                ('source_id', models.CharField(blank=True, max_length=255)),
                ('source_label', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('recorded', 'Recorded'), ('voided', 'Voided')], default='recorded', max_length=20)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Polls usage event',
                'verbose_name_plural': 'Polls usage events',
                'ordering': ['-occurred_at'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='pollsquotapolicy',
            constraint=models.UniqueConstraint(fields=('metric_code',), name='polls_pollsquotapolicy_one_per_metric'),
        ),
        migrations.AddField(
            model_name='decision',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='decision',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='decision', to='polls.question'),
        ),
        migrations.AddIndex(
            model_name='pollsusageevent',
            index=models.Index(fields=['metric_code', 'occurred_at'], name='pollsusageevent_mtime'),
        ),
        migrations.AddIndex(
            model_name='pollsusageevent',
            index=models.Index(fields=['user', 'metric_code'], name='pollsusageevent_umetric'),
        ),
        migrations.AddConstraint(
            model_name='pollsusageevent',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('idempotency_key',), name='polls_pollsusageevent_idem'),
        ),
        migrations.AddIndex(
            model_name='decision',
            index=models.Index(fields=['scope_type', 'scope_id', '-decided_at'], name='polls_decis_scope_t_c7e5b6_idx'),
        ),
        migrations.AddIndex(
            model_name='decision',
            index=models.Index(fields=['outcome'], name='polls_decis_outcome_34cb31_idx'),
        ),
    ]
