# Generated by Django 4.2.23 on 2026-08-14 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_electorates_ledger_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='procedural_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rollentry',
            name='presence',
            field=models.CharField(choices=[('present', 'Present'), ('represented', 'Represented by proxy'), ('absent', 'Absent')], default='present', max_length=12),
        ),
        migrations.AddField(
            model_name='rollentry',
            name='represented_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.CreateModel(
            name='VoteProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electorate_weight', models.PositiveBigIntegerField(default=0)),
                ('represented_weight', models.PositiveBigIntegerField(default=0)),
                ('eligible_weight', models.PositiveBigIntegerField(default=0)),
                ('members_total', models.PositiveIntegerField(default=0)),
                ('members_represented', models.PositiveIntegerField(default=0)),
                ('frozen_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='procedure', to='polls.question')),
            ],
            options={
                'verbose_name': 'voting procedure',
                'verbose_name_plural': 'voting procedures',
            },
        ),
    ]
