# Generated by Django 4.2.23 on 2026-08-14 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0006_voting_procedure'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='electoratemember',
            name='uniq_electorate_member',
        ),
        migrations.AddField(
            model_name='electoratemember',
            name='label',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='electoratemember',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='electorate_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='electoratemember',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('electorate', 'user'), name='uniq_electorate_member'),
        ),
    ]
