# Generated by Django 4.2.23 on 2026-08-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_voter_exclusions'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuorumRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('mode', models.CharField(choices=[('none', 'No additional quorum'), ('percent', 'Minimum represented weight, percent'), ('absolute', 'Minimum represented weight, absolute'), ('manual', 'Manual confirmation')], default='none', max_length=10)),
                ('threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'quorum rule',
                'verbose_name_plural': 'quorum rules',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='convening_mode',
            field=models.CharField(blank=True, default='formal', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='quorum_mode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='quorum_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='question',
            name='quorum_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
