# Generated by Django 4.2.23 on 2026-08-15 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0009_quorum_convening'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(blank=True, db_index=True, max_length=40)),
                ('scope_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('entry_count', models.PositiveIntegerField()),
                ('head_hash', models.CharField(max_length=64)),
                ('algorithm', models.CharField(max_length=32)),
                ('payload', models.TextField()),
                ('taken_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, help_text="Why this checkpoint was taken, e.g. 'before the 2026 audit'.", max_length=200)),
                ('signature', models.CharField(blank=True, max_length=128)),
                ('signed_key_id', models.CharField(blank=True, max_length=64)),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_checkpoints_signed', to=settings.AUTH_USER_MODEL)),
                ('taken_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_checkpoints_taken', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ledger checkpoint',
                'verbose_name_plural': 'ledger checkpoints',
                'ordering': ['-taken_at', '-pk'],
                'indexes': [models.Index(fields=['scope_type', 'scope_id', '-entry_count'], name='polls_ledge_scope_t_3a3a5a_idx')],
            },
        ),
    ]
