# Generated by Django 4.2.23 on 2026-08-15 11:17
from django.db import migrations, models
import django.db.models.deletion


def user_to_person(apps, schema_editor):
    """Carry every membership from its login to that login's Person.

    Order matters: the person column is added and FILLED before the user
    column goes away, so no membership is lost. A login with no Person row
    keeps its label and becomes a person-less member — the same shape an
    institution or an estate already had — rather than vanishing from the
    roll silently.
    """
    ElectorateMember = apps.get_model("polls", "ElectorateMember")
    Person = apps.get_model("people", "Person")
    by_user = {p.user_id: p.pk for p in Person.objects.exclude(user__isnull=True)}
    carried = orphaned = 0
    for member in ElectorateMember.objects.exclude(user__isnull=True):
        person_pk = by_user.get(member.user_id)
        if person_pk is None:
            orphaned += 1
            continue
        member.person_id = person_pk
        member.save(update_fields=["person"])
        carried += 1
    if orphaned:
        print(f"  polls: {carried} memberships carried to Person, "
              f"{orphaned} had no Person and kept their label only")


def person_to_user(apps, schema_editor):
    """Reverse: put the person's login back on the row."""
    ElectorateMember = apps.get_model("polls", "ElectorateMember")
    for member in ElectorateMember.objects.exclude(person__isnull=True).select_related("person"):
        member.user_id = member.person.user_id
        member.save(update_fields=["user"])


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_deprecate_is_federal_agent'),
        ('polls', '0011_decision_secret_ballot'),
    ]

    operations = [
        # The old constraint names `user`; it has to go before the column can.
        migrations.RemoveConstraint(
            model_name='electoratemember',
            name='uniq_electorate_member',
        ),
        migrations.AddField(
            model_name='electoratemember',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='electorate_memberships', to='people.person'),
        ),
        migrations.RunPython(user_to_person, person_to_user),
        migrations.RemoveField(
            model_name='electoratemember',
            name='user',
        ),
        migrations.AddConstraint(
            model_name='electoratemember',
            constraint=models.UniqueConstraint(condition=models.Q(('person__isnull', False)), fields=('electorate', 'person'), name='uniq_electorate_member'),
        ),
    ]
