# Generated by Django 4.2.23 on 2026-08-15 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0013_decision_electorate'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_count', models.PositiveIntegerField()),
                ('head_hash', models.CharField(max_length=64)),
                ('algorithm', models.CharField(default='sha256-fold-ns1', max_length=32)),
                ('payload', models.TextField()),
                ('ledger_modified_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('electorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_snapshots', to='polls.electorate')),
                ('first_seen_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_snapshots_seen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ledger snapshot',
                'verbose_name_plural': 'ledger snapshots',
                'ordering': ['-entry_count', '-first_seen_at'],
                'indexes': [models.Index(fields=['electorate', '-entry_count'], name='polls_ledge_elector_7e65b5_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='ledgersnapshot',
            constraint=models.UniqueConstraint(fields=('electorate', 'head_hash'), name='uniq_snapshot_per_ledger_state'),
        ),
    ]
