# Generated by Django 4.2.23 on 2026-06-04 19:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('availability_type', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('busy', 'Busy'), ('reserved', 'Reserved'), ('out_of_office', 'Out of office')], max_length=30)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('blocks_scheduling', models.BooleanField(default=True, help_text='Whether this availability blocks scheduling.')),
            ],
            options={
                'verbose_name': 'availability',
                'verbose_name_plural': 'availabilities',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventInvite',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'event invite',
                'verbose_name_plural': 'event invites',
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledEvent',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('public', models.BooleanField(default=True, help_text='Check if this event is publicly visible.')),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Maximum number of participants, if limited.', null=True)),
                ('requires_registration', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'scheduled event',
                'verbose_name_plural': 'scheduled events',
                'ordering': ['-start_time'],
            },
        ),
    ]
