# Generated by Django 4.2.23 on 2026-06-04 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledevent',
            name='address',
            field=models.ForeignKey(blank=True, help_text='Specific address for this event, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_events', to='locations.address'),
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_events', to='events.eventcategory'),
        ),
    ]
