# Generated by Django 4.2.23 on 2026-06-04 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledevent',
            name='organizers',
            field=models.ManyToManyField(blank=True, help_text='People who can manage this event and send invites.', related_name='organized_events', to='people.person'),
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Person who created this event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_events', to='people.person'),
        ),
        migrations.AddField(
            model_name='eventinvite',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='events.scheduledevent'),
        ),
        migrations.AddField(
            model_name='eventinvite',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_invites', to='people.person'),
        ),
        migrations.AddField(
            model_name='availability',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='people.person'),
        ),
        migrations.AlterUniqueTogether(
            name='eventinvite',
            unique_together={('event', 'person')},
        ),
    ]
