# Generated by Django 4.2.23 on 2025-12-29 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_fractionalownership_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='fractionalownership',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ownerships_received', to='finance.company'),
            preserve_default=False,
        ),
    ]
