# Generated by Django 4.2.23 on 2026-01-11 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verbena', '0002_tag_remove_page_tags_page_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
        migrations.RemoveField(
            model_name='image',
            name='order',
        ),
        migrations.RemoveField(
            model_name='image',
            name='section',
        ),
        migrations.AddField(
            model_name='section',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='verbena.image'),
        ),
    ]
