# Generated by Django 4.2.23 on 2026-06-04 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vault', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VodCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('access_mode', models.CharField(choices=[('public', 'Public'), ('private', 'Private — readers list only')], default='public', max_length=24)),
                ('allow_downloads', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('bucket', models.ForeignKey(blank=True, help_text='Vault bucket used for source media and generated HLS paths.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vod_collections', to='vault.bucket')),
                ('cover_file', models.ForeignKey(blank=True, help_text='Optional VaultFile image used as collection cover.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vod_collection_covers', to='vault.vaultfile')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vod_collections', to=settings.AUTH_USER_MODEL)),
                ('readers', models.ManyToManyField(blank=True, help_text='Users who can watch private content in this collection.', related_name='vod_readable_collections', to=settings.AUTH_USER_MODEL)),
                ('writers', models.ManyToManyField(blank=True, help_text='Users who can upload and manage videos in this collection.', related_name='vod_writable_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position', 'title'],
            },
        ),
        migrations.CreateModel(
            name='VodVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('title', models.CharField(max_length=240)),
                ('slug', models.SlugField(max_length=260)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('published', 'Published'), ('failed', 'Failed'), ('archived', 'Archived')], default='draft', max_length=24)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('hls_playlist_path', models.CharField(blank=True, max_length=600)),
                ('hls_ready', models.BooleanField(default=False)),
                ('hls_built_at', models.DateTimeField(blank=True, null=True)),
                ('hls_error', models.TextField(blank=True)),
                ('hls_segment_seconds', models.PositiveIntegerField(default=6)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='vod.vodcollection')),
                ('hls_bucket', models.ForeignKey(blank=True, help_text='Optional bucket override for generated HLS assets.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vod_hls_outputs', to='vault.bucket')),
                ('poster_file', models.ForeignKey(blank=True, help_text='Optional VaultFile image poster.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vod_posters', to='vault.vaultfile')),
                ('source_file', models.ForeignKey(help_text='Original unencrypted VaultFile video.', on_delete=django.db.models.deletion.PROTECT, related_name='vod_source_videos', to='vault.vaultfile')),
            ],
            options={
                'ordering': ['collection', 'position', 'title'],
            },
        ),
        migrations.CreateModel(
            name='VodPlaybackEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('event', models.CharField(choices=[('impression', 'Impression'), ('play', 'Play'), ('progress', 'Progress'), ('complete', 'Complete'), ('error', 'Error')], default='play', max_length=24)),
                ('session_key', models.CharField(blank=True, max_length=80)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('seconds_watched', models.PositiveIntegerField(default=0)),
                ('referrer', models.URLField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playback_events', to='vod.vodvideo')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VodAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='pending', max_length=24)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='vod.vodcollection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vod_access_grants', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='vod.vodvideo')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vodvideo',
            index=models.Index(fields=['collection', 'status'], name='vod_vodvide_collect_0ab3ad_idx'),
        ),
        migrations.AddIndex(
            model_name='vodvideo',
            index=models.Index(fields=['status', 'hls_ready'], name='vod_vodvide_status_69f54f_idx'),
        ),
        migrations.AddIndex(
            model_name='vodvideo',
            index=models.Index(fields=['slug'], name='vod_vodvide_slug_a7e4d9_idx'),
        ),
        migrations.AddConstraint(
            model_name='vodvideo',
            constraint=models.UniqueConstraint(fields=('collection', 'slug'), name='uniq_vod_video_slug_per_collection'),
        ),
        migrations.AddIndex(
            model_name='vodplaybackevent',
            index=models.Index(fields=['video', 'event', 'created_at'], name='vod_vodplay_video_i_b5c5d1_idx'),
        ),
        migrations.AddIndex(
            model_name='vodplaybackevent',
            index=models.Index(fields=['user', 'created_at'], name='vod_vodplay_user_id_2778c0_idx'),
        ),
        migrations.AddIndex(
            model_name='vodplaybackevent',
            index=models.Index(fields=['session_key'], name='vod_vodplay_session_1d25be_idx'),
        ),
        migrations.AddIndex(
            model_name='vodcollection',
            index=models.Index(fields=['access_mode', 'position'], name='vod_vodcoll_access__9d8457_idx'),
        ),
        migrations.AddIndex(
            model_name='vodcollection',
            index=models.Index(fields=['slug'], name='vod_vodcoll_slug_b91271_idx'),
        ),
        migrations.AddIndex(
            model_name='vodaccessgrant',
            index=models.Index(fields=['user', 'status'], name='vod_vodacce_user_id_c35240_idx'),
        ),
        migrations.AddIndex(
            model_name='vodaccessgrant',
            index=models.Index(fields=['collection', 'status'], name='vod_vodacce_collect_29ae44_idx'),
        ),
        migrations.AddIndex(
            model_name='vodaccessgrant',
            index=models.Index(fields=['video', 'status'], name='vod_vodacce_video_i_7c2c3c_idx'),
        ),
    ]
