# Generated by Django 4.2.23 on 2026-05-31 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vod', '0004_collection_readers_writers'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='vodaccessgrant',
            new_name='vod_vodacce_user_id_c35240_idx',
            old_name='vod_vodacce_user_id_0b5e67_idx',
        ),
        migrations.RenameIndex(
            model_name='vodaccessgrant',
            new_name='vod_vodacce_collect_29ae44_idx',
            old_name='vod_vodacce_collect_6119db_idx',
        ),
        migrations.RenameIndex(
            model_name='vodaccessgrant',
            new_name='vod_vodacce_video_i_7c2c3c_idx',
            old_name='vod_vodacce_video_i_33b975_idx',
        ),
        migrations.RenameIndex(
            model_name='vodaccessgrant',
            new_name='vod_vodacce_invoice_39173f_idx',
            old_name='vod_vodacce_invoice_f029fd_idx',
        ),
        migrations.RenameIndex(
            model_name='vodaccessgrant',
            new_name='vod_vodacce_subscri_4f2e20_idx',
            old_name='vod_vodacce_subscri_6f7398_idx',
        ),
        migrations.RenameIndex(
            model_name='vodcollection',
            new_name='vod_vodcoll_access__9d8457_idx',
            old_name='vod_vodcoll_access__a0a872_idx',
        ),
        migrations.RenameIndex(
            model_name='vodcollection',
            new_name='vod_vodcoll_slug_b91271_idx',
            old_name='vod_vodcoll_slug_d5f612_idx',
        ),
        migrations.RenameIndex(
            model_name='vodplaybackevent',
            new_name='vod_vodplay_video_i_b5c5d1_idx',
            old_name='vod_vodplay_video_i_d43f91_idx',
        ),
        migrations.RenameIndex(
            model_name='vodplaybackevent',
            new_name='vod_vodplay_user_id_2778c0_idx',
            old_name='vod_vodplay_user_id_8998d9_idx',
        ),
        migrations.RenameIndex(
            model_name='vodplaybackevent',
            new_name='vod_vodplay_session_1d25be_idx',
            old_name='vod_vodplay_session_71cdcf_idx',
        ),
        migrations.RenameIndex(
            model_name='vodvideo',
            new_name='vod_vodvide_collect_0ab3ad_idx',
            old_name='vod_vodvide_collect_status_idx',
        ),
        migrations.RenameIndex(
            model_name='vodvideo',
            new_name='vod_vodvide_status_69f54f_idx',
            old_name='vod_vodvide_status_eb8792_idx',
        ),
        migrations.RenameIndex(
            model_name='vodvideo',
            new_name='vod_vodvide_slug_a7e4d9_idx',
            old_name='vod_vodvide_slug_362340_idx',
        ),
    ]
