"""Routes and map layers kept to circles (2026-09-29): two through tables,
nothing backfilled — a row with none is what it always was. No geometry
column, so the file is identical in migrations/ and migrations_nogis/, as
every locations migration is.
"""

# Generated by Django 4.2.23 on 2026-09-29 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialhub', '0015_circle_regen_speeds'),
        ('locations', '0007_geocoding_usage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteCircle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circle', models.ForeignKey(limit_choices_to={'is_circle': True}, on_delete=django.db.models.deletion.PROTECT, related_name='route_rows', to='socialhub.community')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circle_rows', to='locations.route')),
            ],
        ),
        migrations.CreateModel(
            name='MapLayerCircle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circle', models.ForeignKey(limit_choices_to={'is_circle': True}, on_delete=django.db.models.deletion.PROTECT, related_name='map_layer_rows', to='socialhub.community')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circle_rows', to='locations.maplayer')),
            ],
        ),
        migrations.AddConstraint(
            model_name='routecircle',
            constraint=models.UniqueConstraint(fields=('route', 'circle'), name='locations_route_circle_once'),
        ),
        migrations.AddConstraint(
            model_name='maplayercircle',
            constraint=models.UniqueConstraint(fields=('layer', 'circle'), name='locations_layer_circle_once'),
        ),
    ]
