# Generated by Django 4.2.23 on 2026-09-29 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialhub', '0014_clearances'),
        ('locations', '0007_geocoding_usage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clearance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_rows', to='socialhub.clearance')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearance_rows', to='locations.route')),
            ],
        ),
        migrations.CreateModel(
            name='MapLayerClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clearance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='map_layer_rows', to='socialhub.clearance')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearance_rows', to='locations.maplayer')),
            ],
        ),
        migrations.AddConstraint(
            model_name='routeclearance',
            constraint=models.UniqueConstraint(fields=('route', 'clearance'), name='locations_route_clearance_once'),
        ),
        migrations.AddConstraint(
            model_name='maplayerclearance',
            constraint=models.UniqueConstraint(fields=('layer', 'clearance'), name='locations_layer_clearance_once'),
        ),
    ]
