# Generated by Django 4.2.23 on 2026-08-13 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vault', '0015_remove_vaultquotapolicy_vault_vaultquotapolicy_one_default_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scan_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'scan preference',
            },
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_sha256', models.CharField(db_index=True, help_text='The bytes this verdict is about. Not necessarily current.', max_length=64)),
                ('file_type', models.CharField(max_length=16)),
                ('verdict', models.CharField(choices=[('clean', 'Clean'), ('refused', 'Refused')], max_length=16)),
                ('reason', models.CharField(blank=True, max_length=64)),
                ('detail', models.TextField(blank=True)),
                ('line', models.PositiveIntegerField(default=0)),
                ('door', models.CharField(blank=True, max_length=32)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_results', to='vault.vaultfile')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'scan result',
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['verdict', '-scanned_at'], name='antivirus_s_verdict_6c2b15_idx'), models.Index(fields=['file', 'content_sha256'], name='antivirus_s_file_id_3b9386_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='scanresult',
            constraint=models.UniqueConstraint(fields=('file', 'content_sha256'), name='antivirus_one_verdict_per_content'),
        ),
    ]
