# Generated by Django 4.2.23 on 2025-11-11 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='portfolio.company'),
        ),
    ]
