# Generated by Django 4.2.23 on 2025-11-11 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='venture',
            new_name='company',
        ),
    ]
