# Generated by Django 4.2.23 on 2025-12-27 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_communitymember_communities'),
        ('events', '0003_alter_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(blank=True, db_comment='organized_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_events', to='community.communitymember'),
        ),
    ]
