# Generated by Django 4.2.23 on 2026-06-04 19:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputeKernel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('env', models.JSONField(blank=True, null=True)),
                ('timeout_ms', models.IntegerField(default=5000, help_text='Per-cell execution timeout in milliseconds.')),
                ('startup_timeout_ms', models.IntegerField(default=120000, help_text='How long to wait for the kernel process to become ready, in milliseconds. Increase this for slow Docker environments or when installing many dependencies.')),
                ('auto_close', models.BooleanField(default=True, help_text='Automatically stop this kernel when the user leaves the notebook page.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bucket', models.ForeignKey(blank=True, help_text="Vault bucket attached to this notebook. Files are injected as vault_files dict so you can open(vault_files['name']).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notebooks', to='vault.bucket')),
                ('kernel', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notebook', to='mandragora.computekernel')),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('stdout', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cell_type', models.CharField(choices=[('code', 'Code'), ('markdown', 'Markdown')], default='code', max_length=20)),
                ('position', models.PositiveIntegerField(default=0)),
                ('execution_count', models.PositiveIntegerField(default=0)),
                ('rich_output', models.JSONField(blank=True, null=True)),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='mandragora.notebook')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='KernelDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=255)),
                ('version_spec', models.CharField(blank=True, help_text='e.g. ">=1.21", "==2.0.0", or blank for latest', max_length=100)),
                ('install_status', models.CharField(choices=[('pending', 'Pending'), ('installing', 'Installing'), ('installed', 'Installed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('install_log', models.TextField(blank=True)),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
                ('kernel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kernel_dependencies', to='mandragora.computekernel')),
            ],
            options={
                'verbose_name_plural': 'kernel dependencies',
                'unique_together': {('kernel', 'package_name')},
            },
        ),
    ]
