# Generated by Django 4.2.23 on 2025-10-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latextile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatexCompilationProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('log', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('tex_path', models.CharField(max_length=512)),
                ('aux_path', models.CharField(blank=True, max_length=512, null=True)),
                ('pdf_path', models.CharField(blank=True, max_length=512, null=True)),
                ('output_dir', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
    ]
