# Generated by Django 4.2.23 on 2025-10-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latextile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texfile',
            name='file',
            field=models.FileField(blank=True, upload_to='tex_sources/'),
        ),
    ]
