# Generated by Django 4.2.23 on 2025-10-22 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_vaultfile_content_hash_vaultfile_key_and_more'),
        ('latextile', '0002_alter_texfile_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatexTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('json_schema', models.JSONField(blank=True, null=True)),
                ('check_schema', models.BooleanField(default=True)),
                ('tex_template_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vault.vaultfile')),
            ],
        ),
        migrations.CreateModel(
            name='LatexGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.JSONField()),
                ('filename', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latex_generators', to='latextile.latexproject')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='latextile.latextemplate')),
            ],
        ),
    ]
