# Generated by Django 4.2.23 on 2025-10-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latextile', '0003_latextemplate_latexgenerator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latextemplate',
            name='tex_template_file',
            field=models.FileField(blank=True, default='', upload_to='latex_templates/'),
            preserve_default=False,
        ),
    ]
