# Generated by Django 4.2.23 on 2026-08-01 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vault', '0010_alter_vaultfile_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.TextField(help_text='The Univer workbook snapshot JSON at save time.')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primula_versions', to=settings.AUTH_USER_MODEL)),
                ('sheet_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_versions', to='vault.vaultfile')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['sheet_file', 'created_at'], name='primula_she_sheet_f_b9f019_idx')],
            },
        ),
    ]
