# Generated by Django 4.2.23 on 2026-08-12 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primula', '0002_primulaquotapolicy_primulausageevent_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SheetVersion',
        ),
    ]
