# Generated by Django 4.2.23 on 2026-08-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primula', '0003_delete_sheetversion'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='primulaquotapolicy',
            name='primula_primulaquotapolicy_one_default',
        ),
        migrations.RemoveConstraint(
            model_name='primulaquotapolicy',
            name='primula_primulaquotapolicy_one_per_user',
        ),
        migrations.RemoveField(
            model_name='primulaquotapolicy',
            name='user',
        ),
        migrations.AddConstraint(
            model_name='primulaquotapolicy',
            constraint=models.UniqueConstraint(fields=('metric_code',), name='primula_primulaquotapolicy_one_per_metric'),
        ),
    ]
