# Generated by Django 5.2.17 on 2026-10-06 09:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('geography', '0001_initial'),
        ('socialhub', '0005_remove_community_is_federal_tribe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('op_key', models.CharField(max_length=36)),
                ('forum_thread', models.CharField(blank=True, default='', max_length=200)),
                ('hidden_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pin_link', to='geography.address')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geography_pins', to='socialhub.community')),
                ('hidden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Community pin',
                'verbose_name_plural': 'Community pins',
                'ordering': ('-created_at', '-id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommunityZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('op_key', models.CharField(max_length=36)),
                ('forum_thread', models.CharField(blank=True, default='', max_length=200)),
                ('hidden_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geography_zones', to='socialhub.community')),
                ('hidden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('zone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_link', to='geography.zone')),
            ],
            options={
                'verbose_name': 'Community zone',
                'verbose_name_plural': 'Community zones',
                'ordering': ('-created_at', '-id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PinComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='comments.comment')),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_links', to='geography.communitypin')),
            ],
        ),
        migrations.CreateModel(
            name='ZoneComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='comments.comment')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_links', to='geography.communityzone')),
            ],
        ),
        migrations.AddConstraint(
            model_name='communitypin',
            constraint=models.UniqueConstraint(fields=('author', 'op_key'), name='geography_communitypin_author_op'),
        ),
        migrations.AddConstraint(
            model_name='communityzone',
            constraint=models.UniqueConstraint(fields=('author', 'op_key'), name='geography_communityzone_author_op'),
        ),
    ]
