# Generated by Django 4.2.23 on 2026-05-25 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('detections', '0001_initial'),
        ('locations', '0001_initial'),
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionhandle',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_handles', to='people.person'),
        ),
        migrations.AddField(
            model_name='detectionhandle',
            name='detection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handles', to='detections.detection'),
        ),
        migrations.AddField(
            model_name='detectioncategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='detections.detectioncategory'),
        ),
        migrations.AddField(
            model_name='detection',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='locations.address'),
        ),
        migrations.AddField(
            model_name='detection',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='detections.detectioncategory'),
        ),
        migrations.AddField(
            model_name='detection',
            name='involved_persons',
            field=models.ManyToManyField(blank=True, related_name='involved_detections', to='people.person'),
        ),
        migrations.AddField(
            model_name='detection',
            name='mitigation_task',
            field=models.ForeignKey(blank=True, help_text='Kanban task that mitigates or resolves this detection.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detection_mitigations', to='kanban.task'),
        ),
        migrations.AddField(
            model_name='detection',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_detections', to='people.person'),
        ),
        migrations.AddField(
            model_name='detection',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='locations.route'),
        ),
        migrations.AddField(
            model_name='detection',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='locations.zone'),
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['status', 'severity'], name='detections__status_2a8e8e_idx'),
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['detection_type'], name='detections__detecti_9e4a23_idx'),
        ),
    ]
