# Generated by Django 4.2.23 on 2026-06-04 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vault', '0001_initial'),
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTransform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lambda_function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_transforms', to='workflows.lambdafunction')),
            ],
        ),
        migrations.CreateModel(
            name='OcrImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=50)),
                ('language', models.CharField(default='eng', max_length=20)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OcrProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='shared_ocr_projects', to=settings.AUTH_USER_MODEL)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_projects', to='vault.bucket')),
            ],
            options={
                'verbose_name': 'Workspace',
                'verbose_name_plural': 'Workspaces',
            },
        ),
        migrations.CreateModel(
            name='OcrLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('left', models.IntegerField()),
                ('top', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('confidence', models.IntegerField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ocr.ocrimage')),
            ],
        ),
        migrations.AddField(
            model_name='ocrimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ocr.ocrproject'),
        ),
        migrations.AddField(
            model_name='ocrimage',
            name='vault_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocr_images', to='vault.vaultfile'),
        ),
        migrations.CreateModel(
            name='ImageTransformParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('min_value', models.IntegerField(default=0)),
                ('max_value', models.IntegerField(default=100)),
                ('default_value', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=64)),
                ('step', models.IntegerField(default=1)),
                ('transform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='ocr.imagetransform')),
            ],
        ),
    ]
