# Generated by Django 4.2.23 on 2026-05-31 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ocrproject',
            options={'verbose_name': 'Workspace', 'verbose_name_plural': 'Workspaces'},
        ),
    ]
