# Generated by Django 4.2.23 on 2026-05-25 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegraphChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='telegraph_channels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TelegraphMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegraph_members', to='telegraph.telegraphchannel')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegraph_memberships', to='people.person')),
            ],
            options={
                'ordering': ['person__display_name'],
            },
        ),
        migrations.AddField(
            model_name='telegraphchannel',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='telegraph_channels', through='telegraph.TelegraphMember', to='people.person'),
        ),
        migrations.AddConstraint(
            model_name='telegraphmember',
            constraint=models.UniqueConstraint(condition=models.Q(('person__isnull', False)), fields=('channel', 'person'), name='unique_telegraph_channel_member'),
        ),
        migrations.AddConstraint(
            model_name='telegraphmember',
            constraint=models.CheckConstraint(check=models.Q(('person__isnull', False)), name='telegraph_member_must_have_person'),
        ),
    ]
