# Generated by Django 4.2.23 on 2026-06-14 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegraph', '0004_telegraphmessage_encryption_telegraphmessage_iv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegraphchannel',
            name='pin_key_id',
        ),
        migrations.DeleteModel(
            name='TelegraphPin',
        ),
    ]
