# Generated by Django 4.2.23 on 2025-10-12 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Git repository', max_length=255)),
                ('url', models.URLField(help_text='URL of the Git repository')),
                ('access_key', models.TextField(help_text='Access key or token for authentication')),
                ('provider', models.CharField(help_text='Git hosting provider (e.g., GitHub, GitLab, Bitbucket)', max_length=100)),
                ('linked_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the repository was linked')),
            ],
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(help_text='Branch where the file is located', max_length=255)),
                ('file_path', models.CharField(help_text='Path to the file in the repository', max_length=1024)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='gitops.gitrepository')),
            ],
        ),
    ]
