# Generated by Django 4.2.23 on 2025-10-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='file_content',
            field=models.TextField(blank=True, help_text='Contents of the file after pull'),
        ),
    ]
