# Generated by Django 4.2.23 on 2025-10-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitops', '0002_artifact_file_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='file_content',
        ),
        migrations.AddField(
            model_name='artifact',
            name='file_blob',
            field=models.FileField(blank=True, help_text='Stored file content after pull', null=True, upload_to='artifacts/'),
        ),
    ]
