# Generated by Django 4.2.23 on 2025-10-18 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_bucket_vaultfile_bucket'),
        ('gitops', '0003_remove_artifact_file_content_artifact_file_blob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='file_blob',
        ),
        migrations.AddField(
            model_name='artifact',
            name='bucket',
            field=models.ForeignKey(blank=True, help_text='Bucket where the artifact is stored', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='vault.bucket'),
        ),
    ]
