# Generated by Django 4.2.23 on 2026-05-22 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0011_tokenization_default_state'),
        ('people', '0003_person_is_federal_agent'),
        ('socialhub', '0003_community_is_federal_tribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_type', models.CharField(help_text='rule / transaction_fee / poll_tax / general_decision', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('content', models.JSONField(help_text='Immutable decision payload.')),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('prev_hash', models.CharField(blank=True, help_text='Hash of the previous decision in this community.', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assembly_decisions', to='socialhub.community')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssemblyProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_type', models.CharField(choices=[('rule', 'Rule'), ('decision', 'Decision'), ('asset_tax', 'Asset Transaction Tax'), ('poll_tax', 'Poll Tax')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('passed', 'Passed'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('opens_at', models.DateTimeField(blank=True, null=True)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('quorum', models.PositiveIntegerField(default=0, help_text='Minimum yes+no votes for a valid result (0 = no minimum).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_proposals', to='socialhub.community')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assembly_proposals_opened', to='people.person')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_amount_base_units', models.BigIntegerField(default=0, help_text='Flat per-member amount (head tax component).')),
                ('wealth_rate_bps', models.PositiveIntegerField(default=0, help_text="Rate in basis points applied to member's wealth_asset balance.")),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('one_time', 'One-time')], default='yearly', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_taxes', to='socialhub.community')),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enacted_poll_taxes', to='assembly.assemblydecision')),
                ('payment_asset', models.ForeignKey(help_text='Asset in which the tax is collected.', on_delete=django.db.models.deletion.PROTECT, related_name='poll_taxes_payment', to='assets.asset')),
                ('wealth_asset', models.ForeignKey(blank=True, help_text='Asset used to measure member wealth. Null = no wealth component.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='poll_taxes_wealth', to='assets.asset')),
            ],
            options={
                'ordering': ['community'],
            },
        ),
        migrations.CreateModel(
            name='CommunityTransactionFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_bps', models.PositiveIntegerField(help_text='Fee in basis points (100 = 1%).')),
                ('set_by', models.CharField(choices=[('admin', 'Admin'), ('assembly', 'Assembly')], default='admin', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, help_text='Null = applies to all assets of this community.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_transaction_fees', to='assets.asset')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_fees', to='socialhub.community')),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enacted_fees', to='assembly.assemblydecision')),
            ],
            options={
                'ordering': ['community', 'asset'],
            },
        ),
        migrations.CreateModel(
            name='CommunityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='socialhub.community')),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enacted_rules', to='assembly.assemblydecision')),
            ],
            options={
                'ordering': ['community', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssemblyVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('abstain', 'Abstain')], max_length=10)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='assembly.assemblyproposal')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_votes', to='people.person')),
            ],
            options={
                'ordering': ['voted_at'],
            },
        ),
        migrations.AddField(
            model_name='assemblydecision',
            name='proposal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decision', to='assembly.assemblyproposal'),
        ),
        migrations.CreateModel(
            name='PollTaxPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_label', models.CharField(max_length=20)),
                ('head_amount_paid_base_units', models.BigIntegerField(default=0)),
                ('wealth_amount_paid_base_units', models.BigIntegerField(default=0)),
                ('total_paid_base_units', models.BigIntegerField(default=0)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_tax_payments', to='people.person')),
                ('poll_tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='assembly.polltax')),
            ],
            options={
                'ordering': ['-paid_at'],
                'indexes': [models.Index(fields=['poll_tax', 'person'], name='assembly_po_poll_ta_acdcd1_idx'), models.Index(fields=['person', 'period_label'], name='assembly_po_person__f78fce_idx')],
                'unique_together': {('poll_tax', 'person', 'period_label')},
            },
        ),
        migrations.AddIndex(
            model_name='polltax',
            index=models.Index(fields=['community', 'active'], name='assembly_po_communi_05de5e_idx'),
        ),
        migrations.AddIndex(
            model_name='communitytransactionfee',
            index=models.Index(fields=['community', 'active'], name='assembly_co_communi_9be9ee_idx'),
        ),
        migrations.AddIndex(
            model_name='communitytransactionfee',
            index=models.Index(fields=['asset'], name='assembly_co_asset_i_094a81_idx'),
        ),
        migrations.AddIndex(
            model_name='communityrule',
            index=models.Index(fields=['community', 'active'], name='assembly_co_communi_e455d4_idx'),
        ),
        migrations.AddIndex(
            model_name='assemblyvote',
            index=models.Index(fields=['proposal'], name='assembly_as_proposa_dff47c_idx'),
        ),
        migrations.AddIndex(
            model_name='assemblyvote',
            index=models.Index(fields=['voter'], name='assembly_as_voter_i_689439_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assemblyvote',
            unique_together={('proposal', 'voter')},
        ),
        migrations.AddIndex(
            model_name='assemblyproposal',
            index=models.Index(fields=['community', 'status'], name='assembly_as_communi_69ceb4_idx'),
        ),
        migrations.AddIndex(
            model_name='assemblyproposal',
            index=models.Index(fields=['proposal_type'], name='assembly_as_proposa_173b7a_idx'),
        ),
        migrations.AddIndex(
            model_name='assemblyproposal',
            index=models.Index(fields=['closes_at'], name='assembly_as_closes__56cb79_idx'),
        ),
        migrations.AddIndex(
            model_name='assemblydecision',
            index=models.Index(fields=['community', 'created_at'], name='assembly_as_communi_70b8dd_idx'),
        ),
        migrations.AddIndex(
            model_name='assemblydecision',
            index=models.Index(fields=['decision_type'], name='assembly_as_decisio_962a60_idx'),
        ),
    ]
