# Generated by Django 4.2.23 on 2026-05-22 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_tokenization_default_state'),
        ('socialhub', '0003_community_is_federal_tribe'),
        ('assembly', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assemblyproposal',
            name='quorum',
        ),
        migrations.AddField(
            model_name='assemblyproposal',
            name='is_repeal',
            field=models.BooleanField(default=False, help_text='For rule proposals: True means this repeals/removes an existing rule.'),
        ),
        migrations.AlterField(
            model_name='assemblyproposal',
            name='proposal_type',
            field=models.CharField(choices=[('rule', 'Rule'), ('asset_tax', 'Asset Transaction Tax')], max_length=20),
        ),
        migrations.AlterField(
            model_name='communitytransactionfee',
            name='asset',
            field=models.ForeignKey(blank=True, help_text='Null = blanket fee for all assets in this community.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_transaction_fees', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='communitytransactionfee',
            name='fee_bps',
            field=models.IntegerField(help_text='Fee in basis points (100 = 1%). Negative allowed for per-asset adjustments.'),
        ),
        migrations.CreateModel(
            name='CommunityAssemblyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quorum_fraction', models.DecimalField(decimal_places=4, default='0.5100', help_text='Fraction of yes/(yes+no) votes required to pass a proposal (e.g. 0.51 = simple majority).', max_digits=5)),
                ('community', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_config', to='socialhub.community')),
            ],
            options={
                'verbose_name': 'Assembly configuration',
                'verbose_name_plural': 'Assembly configurations',
            },
        ),
    ]
