# Generated by Django 4.2.23 on 2026-05-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0002_remove_assemblyproposal_quorum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemblyproposal',
            name='proposal_type',
            field=models.CharField(choices=[('rule', 'Rule'), ('asset_tax', 'Asset Transaction Tax'), ('emg_declare', 'Emergency Declaration')], max_length=20),
        ),
    ]
