# Generated by Django 4.2.23 on 2026-05-23 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialhub', '0003_community_is_federal_tribe'),
        ('people', '0003_person_is_federal_agent'),
        ('assembly', '0005_impeachment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblyproposal',
            name='senate_deadline',
            field=models.DateTimeField(blank=True, help_text='Set when proposal passes popular vote and enters senate review. Senate must veto before this deadline or the proposal is enacted.', null=True),
        ),
        migrations.AlterField(
            model_name='assemblyproposal',
            name='proposal_type',
            field=models.CharField(choices=[('rule', 'Rule'), ('asset_tax', 'Asset Transaction Tax'), ('emg_declare', 'Emergency Declaration'), ('mag_elect', 'Magistrate Election'), ('impeach', 'Impeachment'), ('senate_appoint', 'Senate Appointment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='assemblyproposal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('pending_senate', 'Pending Senate Review'), ('passed', 'Passed'), ('rejected', 'Rejected'), ('vetoed', 'Vetoed by Senate'), ('expired', 'Expired')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='SenateVeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, help_text='Public explanation of why the senate is blocking this proposal.')),
                ('vetoed_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='senate_veto', to='assembly.assemblyproposal')),
                ('senator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senate_vetoes', to='people.person')),
            ],
            options={
                'verbose_name': 'Senate veto',
                'verbose_name_plural': 'Senate vetoes',
            },
        ),
        migrations.CreateModel(
            name='CommunitySenate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('veto_window_days', models.PositiveIntegerField(default=7, help_text='Days the senate has to veto a proposal after it passes the popular assembly.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='senate', to='socialhub.community')),
                ('members', models.ManyToManyField(blank=True, help_text='Senators. A senator is excluded from voting in the popular assembly.', related_name='senate_memberships', to='people.person')),
            ],
            options={
                'verbose_name': 'Community senate',
                'verbose_name_plural': 'Community senates',
            },
        ),
    ]
