# Generated by Django 4.2.23 on 2026-06-04 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import secrets
import toto.backup.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('file', models.FileField(upload_to=toto.backup.models.stored_backup_upload_to)),
                ('apps', models.JSONField(blank=True, default=list)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('magic_token', models.CharField(default=secrets.token_urlsafe, help_text='High-entropy URL token required before API-key auth is checked.', max_length=128, unique=True)),
                ('api_key_hash', models.CharField(blank=True, max_length=255)),
                ('api_key_hint', models.CharField(blank=True, help_text='Last characters of the generated API key. The full key is shown only once.', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_pulled_at', models.DateTimeField(blank=True, null=True)),
                ('pull_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stored_backups_created', to=settings.AUTH_USER_MODEL)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stored_backups', to='core.platform')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify_key', models.TextField(blank=True, help_text='Public key PEM used to verify incoming backup signatures.', null=True)),
                ('platform', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backup_profile', to='core.platform')),
            ],
        ),
    ]
