# Generated by Django 4.2.23 on 2026-06-04 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backup', '0001_initial'),
        ('gervazy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupprofile',
            name='signing_key',
            field=models.ForeignKey(blank=True, help_text='Private key used to sign outbound backup packages.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_profiles', to='gervazy.encryptedprivatekey'),
        ),
    ]
