# Generated by Django 4.2.23 on 2025-11-28 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0001_initial'),
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='References', max_length=255)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bibliographies', to='editor.document')),
                ('items', models.ManyToManyField(blank=True, related_name='bibliographies', to='library.referenceitem')),
            ],
        ),
    ]
