# Generated by Django 4.2.23 on 2025-11-07 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
