# Generated by Django 4.2.23 on 2025-11-07 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_remove_document_tags_delete_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Figure',
        ),
    ]
