# Generated by Django 4.2.23 on 2026-01-17 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('federal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_crypto', models.BooleanField(default=True)),
                ('decimals', models.PositiveIntegerField(default=8)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('conversion_rate', models.DecimalField(decimal_places=8, default=1.0, help_text='Rate from source currency to destination currency.', max_digits=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('destination', models.ForeignKey(db_comment='destination_account', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_incoming', to='finance.account')),
                ('source', models.ForeignKey(db_comment='source_account', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_outgoing', to='finance.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(db_comment='denominated_in', on_delete=django.db.models.deletion.CASCADE, to='finance.currency'),
        ),
        migrations.AddField(
            model_name='account',
            name='manager',
            field=models.ForeignKey(blank=True, db_comment='managed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(db_comment='owned_by', on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='federal.identityprofile'),
        ),
    ]
