# Generated by Django 4.2.23 on 2025-12-23 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0002_alter_community_federation_alter_community_head_and_more'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(db_comment='denominated_in', on_delete=django.db.models.deletion.CASCADE, to='finance.currency'),
        ),
        migrations.AlterField(
            model_name='account',
            name='manager',
            field=models.ForeignKey(blank=True, db_comment='managed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(db_comment='owned_by', on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='community.socialentity'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='base_currency',
            field=models.ForeignKey(db_comment='base_in', on_delete=django.db.models.deletion.CASCADE, related_name='base_rates', to='finance.currency'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='quote_currency',
            field=models.ForeignKey(db_comment='quoted_in', on_delete=django.db.models.deletion.CASCADE, related_name='quote_rates', to='finance.currency'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.ForeignKey(db_comment='denominated_in', on_delete=django.db.models.deletion.CASCADE, to='finance.currency'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='destination',
            field=models.ForeignKey(db_comment='destination_account', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_incoming', to='finance.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.ForeignKey(db_comment='source_account', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_outgoing', to='finance.account'),
        ),
    ]
