# Generated by Django 4.2.23 on 2025-11-08 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_exchangerate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Obligation',
        ),
    ]
