# Generated by Django 4.2.23 on 2026-06-04 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('storage_quota_mb', models.PositiveIntegerField(blank=True, help_text='Storage quota per user in MB. Leave blank for unlimited.', null=True)),
                ('storage_backend', models.CharField(choices=[('local', 'Local'), ('s3', 'S3-compatible'), ('remote_toto', 'Remote Toto Server')], default='local', help_text='Storage backend for files in this bucket.', max_length=16)),
                ('storage_config', models.JSONField(blank=True, default=dict, help_text='Non-secret backend config. S3: bucket_name, region_name, prefix, use_ssl, addressing_style, aws_profile. remote_toto: server_url, bucket_slug, api_token_env. Credentials must come from environment variables, not this field.')),
                ('public_base_url', models.URLField(blank=True, default='', help_text='Optional CDN or public base URL (e.g. https://cdn.example.com/vault/). When set, get_public_file_url() returns a direct link per file.')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bucket',
                'verbose_name_plural': 'Buckets',
            },
        ),
        migrations.CreateModel(
            name='StorageProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=64, unique=True)),
                ('display_name', models.CharField(max_length=128)),
                ('endpoint_url_template', models.CharField(blank=True, help_text='Endpoint URL, optionally with {region} or {account_id} placeholders. Leave blank for AWS default routing.', max_length=256)),
                ('default_region', models.CharField(blank=True, max_length=64)),
                ('addressing_style', models.CharField(choices=[('path', 'Path'), ('virtual', 'Virtual'), ('auto', 'Auto')], default='auto', max_length=8)),
                ('use_ssl', models.BooleanField(default=True)),
                ('is_builtin', models.BooleanField(default=True, help_text='Seeded by ingress — safe to re-run ingress to reset.')),
            ],
            options={
                'verbose_name': 'Storage Provider',
                'verbose_name_plural': 'Storage Providers',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='VaultDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allowed_users', models.ManyToManyField(blank=True, help_text='Leave empty to allow all authenticated users.', related_name='accessible_directories', to=settings.AUTH_USER_MODEL)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directories', to='vault.bucket')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_directories', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdirectories', to='vault.vaultdirectory')),
            ],
            options={
                'verbose_name': 'Vault Directory',
                'verbose_name_plural': 'Vault Directories',
                'unique_together': {('bucket', 'parent', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FileGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('make_public', models.BooleanField(default=False, help_text='If enabled, all files uploaded through this gateway become public.')),
                ('max_file_size', models.PositiveIntegerField(default=10240, help_text='Maximum allowed file size in KB.')),
                ('allowed_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateways', to='vault.bucket')),
                ('directory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gateway', to='vault.vaultdirectory')),
            ],
            options={
                'verbose_name': 'File Gateway',
                'verbose_name_plural': 'File Gateways',
            },
        ),
        migrations.CreateModel(
            name='BucketCopyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_count', models.PositiveIntegerField(default=1)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('from_bucket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies_out', to='vault.bucket')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('to_bucket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies_in', to='vault.bucket')),
            ],
            options={
                'verbose_name': 'Bucket Copy Log',
                'verbose_name_plural': 'Bucket Copy Logs',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.AddField(
            model_name='bucket',
            name='provider',
            field=models.ForeignKey(blank=True, help_text='Provider preset used when storage_backend is S3-compatible.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buckets', to='vault.storageprovider'),
        ),
        migrations.CreateModel(
            name='VaultFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('key', models.SlugField(blank=True, max_length=255)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('file', models.FileField(upload_to='vault/files/')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('html', 'HTML'), ('text', 'Text File'), ('json', 'JSON'), ('yaml', 'YAML'), ('xml', 'XML'), ('latex', 'LaTeX'), ('bib', 'Bibliography'), ('csv', 'CSV'), ('svg', 'SVG File'), ('audio', 'Audio'), ('video', 'Video')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False, help_text='If true, file is visible to others')),
                ('notes', models.TextField(blank=True, null=True)),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0, help_text='File size in bytes, captured at upload time.')),
                ('bucket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='vault.bucket')),
                ('directory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='vault.vaultdirectory')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vault File',
                'verbose_name_plural': 'Vault Files',
                'unique_together': {('bucket', 'key')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='bucket',
            unique_together={('name', 'owner')},
        ),
    ]
