# Generated by Django 4.2.23 on 2026-06-17 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0005_alter_vaultfile_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaultfile',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('html', 'HTML'), ('text', 'Text File'), ('json', 'JSON'), ('yaml', 'YAML'), ('xml', 'XML'), ('presentation', 'Presentation'), ('latex', 'LaTeX'), ('bib', 'Bibliography'), ('csv', 'CSV'), ('svg', 'SVG File'), ('audio', 'Audio'), ('video', 'Video'), ('python', 'Python'), ('notebook', 'Notebook'), ('neojson', 'NeoJSON'), ('contract', 'Contract')], max_length=16),
        ),
    ]
