# Generated by Django 4.2.23 on 2026-08-12 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import toto.vault.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vault', '0012_alter_vaultfile_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionBlob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_hash', models.CharField(help_text='sha256 of the bytes. Unique — this is the dedupe.', max_length=64, unique=True)),
                ('data', models.FileField(upload_to=toto.vault.models.version_blob_path)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Version blob',
                'verbose_name_plural': 'Version blobs',
            },
        ),
        migrations.CreateModel(
            name='FileVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, max_length=200)),
                ('is_conflict', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_versions', to=settings.AUTH_USER_MODEL)),
                ('blob', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='vault.versionblob')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='vault.vaultfile')),
            ],
            options={
                'verbose_name': 'File version',
                'verbose_name_plural': 'File versions',
                'ordering': ['-number'],
                'indexes': [models.Index(fields=['file', '-number'], name='vault_version_file_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='fileversion',
            constraint=models.UniqueConstraint(fields=('file', 'number'), name='vault_one_version_per_number'),
        ),
    ]
