# Generated by Django 4.2.23 on 2026-08-12 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vault', '0013_versionblob_fileversion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='edit_lock', to='vault.vaultfile')),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='held_file_locks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File editing lock',
                'verbose_name_plural': 'File editing locks',
            },
        ),
    ]
