# Generated by Django 4.2.23 on 2026-08-12 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0014_filelock'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vaultquotapolicy',
            name='vault_vaultquotapolicy_one_default',
        ),
        migrations.RemoveConstraint(
            model_name='vaultquotapolicy',
            name='vault_vaultquotapolicy_one_per_user',
        ),
        migrations.RemoveField(
            model_name='vaultquotapolicy',
            name='user',
        ),
        migrations.AddConstraint(
            model_name='vaultquotapolicy',
            constraint=models.UniqueConstraint(fields=('metric_code',), name='vault_vaultquotapolicy_one_per_metric'),
        ),
    ]
