# Generated by Django 4.2.23 on 2026-08-13 14:44

from django.db import migrations, models
import toto.vault.storage


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0015_remove_vaultquotapolicy_vault_vaultquotapolicy_one_default_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaultfile',
            name='file',
            field=models.FileField(storage=toto.vault.storage.private_storage, upload_to='vault/files/'),
        ),
    ]
