# Generated by Django 4.2.23 on 2026-08-15 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """The metadata mirror: origin-tagged stubs, the staleness stamp, and the
    refresh run row. Mirror rows are the peer's listing — deleting them never
    touches remote bytes, and the levy already excludes them."""


    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vault', '0018_bucket_peering'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='last_refreshed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaultfile',
            name='origin',
            field=models.CharField(choices=[('native', 'Native'), ('mirror', 'Mirrored')], db_index=True, default='native', help_text="Mirrored rows are the peer's listing, not this host's bytes; their metadata is changed on the origin host.", max_length=8),
        ),
        migrations.CreateModel(
            name='BucketRefreshRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Done'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error', models.TextField(blank=True)),
                ('total_remote', models.PositiveIntegerField(blank=True, null=True)),
                ('stubs_created', models.PositiveIntegerField(default=0)),
                ('stubs_updated', models.PositiveIntegerField(default=0)),
                ('stubs_deleted', models.PositiveIntegerField(default=0)),
                ('stubs_unchanged', models.PositiveIntegerField(default=0)),
                ('pages_read', models.PositiveIntegerField(default=0)),
                ('skips', models.JSONField(blank=True, default=list)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('workflow_run_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_runs', to='vault.bucket')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bucket_refresh_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'bucket refresh run',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['bucket', '-created_at'], name='vault_bucke_bucket__ce9ccf_idx'), models.Index(fields=['status'], name='vault_bucke_status_7543f9_idx')],
            },
        ),
    ]
