# Generated by Django 4.2.23 on 2026-08-15 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """The transfer run: a queued copy with a same-transaction cursor, frozen
    denominator, per-file skips, and SET_NULL bucket links so a deleted
    bucket cannot erase the record that bytes moved and were billed."""


    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vault', '0019_metadata_mirror'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_ids', models.JSONField(blank=True, default=list)),
                ('copy_policy', models.CharField(choices=[('add_suffix', 'Add suffix on conflict'), ('replace', 'Replace existing'), ('fail', 'Skip on conflict')], default='add_suffix', max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Done'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error', models.TextField(blank=True)),
                ('total_files', models.PositiveIntegerField(blank=True, null=True)),
                ('files_done', models.PositiveIntegerField(default=0)),
                ('files_skipped', models.PositiveIntegerField(default=0)),
                ('bytes_done', models.PositiveBigIntegerField(default=0)),
                ('bytes_estimated', models.PositiveBigIntegerField(default=0)),
                ('skips', models.JSONField(blank=True, default=list)),
                ('cursor', models.PositiveIntegerField(default=0)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('workflow_run_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('dest_bucket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_in', to='vault.bucket')),
                ('dest_directory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_in', to='vault.vaultdirectory')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vault_transfer_runs', to=settings.AUTH_USER_MODEL)),
                ('source_bucket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='vault.bucket')),
            ],
            options={
                'verbose_name': 'transfer run',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', '-created_at'], name='vault_trans_owner_i_a14bfe_idx'), models.Index(fields=['status'], name='vault_trans_status_335bdc_idx')],
            },
        ),
    ]
