# Generated by Django 4.2.23 on 2026-05-15 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socialhub', '0003_alter_community_head_alter_person_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='fa-solid fa-award', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['group__order', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SkillGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SkillBadgePrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_links', to='competence.skillbadge')),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_for_links', to='competence.skillbadge')),
            ],
        ),
        migrations.AddField(
            model_name='skillbadge',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='competence.skillgroup'),
        ),
        migrations.AddField(
            model_name='skillbadge',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='unlocks', through='competence.SkillBadgePrerequisite', to='competence.skillbadge'),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('place', models.CharField(blank=True, max_length=200)),
                ('started_at', models.DateField(blank=True, null=True)),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='socialhub.person')),
            ],
            options={
                'ordering': ['order', '-started_at', 'title'],
            },
        ),
        migrations.AddConstraint(
            model_name='skillbadgeprerequisite',
            constraint=models.UniqueConstraint(fields=('badge', 'prerequisite'), name='unique_badge_prerequisite'),
        ),
        migrations.AddConstraint(
            model_name='skillbadgeprerequisite',
            constraint=models.CheckConstraint(check=models.Q(('badge', models.F('prerequisite')), _negated=True), name='badge_cannot_require_itself'),
        ),
        migrations.AddConstraint(
            model_name='skillbadge',
            constraint=models.UniqueConstraint(fields=('group', 'slug'), name='unique_badge_slug_per_group'),
        ),
    ]
