# Generated by Django 4.2.23 on 2026-05-25 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competence', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='people.person'),
        ),
        migrations.AddConstraint(
            model_name='skillbadgeprerequisite',
            constraint=models.UniqueConstraint(fields=('badge', 'prerequisite'), name='unique_badge_prerequisite'),
        ),
        migrations.AddConstraint(
            model_name='skillbadgeprerequisite',
            constraint=models.CheckConstraint(check=models.Q(('badge', models.F('prerequisite')), _negated=True), name='badge_cannot_require_itself'),
        ),
        migrations.AddConstraint(
            model_name='skillbadge',
            constraint=models.UniqueConstraint(fields=('group', 'slug'), name='unique_badge_slug_per_group'),
        ),
    ]
