# Generated by Django 4.2.23 on 2026-05-16 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('competence', '0002_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='experience',
                    name='person',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='people.person'),
                ),
            ],
            database_operations=[],
        ),
    ]
