# Generated by Django 4.2.23 on 2026-08-14 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(default=1)),
                ('cast_at', models.DateTimeField(auto_now_add=True)),
                ('revised_at', models.DateTimeField(blank=True, null=True)),
                ('revisions', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['cast_at'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('text', models.CharField(blank=True, max_length=300)),
                ('value', models.IntegerField(default=0)),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['position', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('poll', 'Poll'), ('vote', 'Vote')], default='poll', max_length=8)),
                ('title', models.CharField(max_length=150)),
                ('question_text', models.CharField(max_length=300)),
                ('body', models.TextField(blank=True, help_text='The case for and against, for a formal vote. Shown above the options.')),
                ('slug', models.SlugField(blank=True, max_length=170)),
                ('scope_type', models.CharField(blank=True, db_index=True, max_length=40)),
                ('scope_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('opens_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closes_at', models.DateTimeField(blank=True, help_text='When voting ends. A question with no closing time stays open until somebody closes it.', null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=10)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('revisability', models.CharField(choices=[('open', 'Answers may be changed while open'), ('final', 'A ballot is cast once and is final')], default='open', max_length=8)),
                ('visibility', models.CharField(choices=[('live', 'Results visible while open'), ('on_close', 'Results visible once closed'), ('on_close_private', 'Results visible once closed, to voters only')], default='live', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_opened', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
                'ordering': ['-created_at'],
            },
        ),
        # HAND-EDITED. The autodetector emitted three RemoveFields on `vote`
        # before the DeleteModels; on SQLite a RemoveField is a whole-table
        # remake, and remaking a table that is about to be dropped is both
        # pointless and a known way for this migration to die. Dropping the
        # three tables in FK order does the same thing and can only succeed:
        # Vote points at Poll and Option, so it goes first.
        migrations.DeleteModel(
            name='Vote',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polls.question'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='polls.choice'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='polls.question'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['scope_type', 'scope_id', '-created_at'], name='polls_quest_scope_t_596160_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['kind', 'status'], name='polls_quest_kind_80d4fd_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['closes_at'], name='polls_quest_closes__1e5911_idx'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('scope_type', 'scope_id', 'slug'), name='uniq_question_slug_per_scope'),
        ),
        migrations.AddConstraint(
            model_name='choice',
            constraint=models.UniqueConstraint(fields=('question', 'label'), name='uniq_choice_label_per_question'),
        ),
        migrations.AddIndex(
            model_name='ballot',
            index=models.Index(fields=['question', 'choice'], name='polls_ballo_questio_62ce24_idx'),
        ),
        migrations.AddConstraint(
            model_name='ballot',
            constraint=models.UniqueConstraint(fields=('question', 'voter'), name='uniq_ballot_per_voter'),
        ),
    ]
