# Generated by Django 4.2.23 on 2026-08-14 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion




def _backfill_chain(apps, schema_editor):
    """Hash the decisions that predate the ledger, per scope, in pk order.

    The chain must start from the rows that already exist — a verify that
    fails on day one because history predates the feature would teach
    operators to ignore it.
    """
    import hashlib
    import json

    Decision = apps.get_model("polls", "Decision")
    scopes = (Decision.objects.values_list("scope_type", "scope_id")
              .distinct())
    for scope_type, scope_id in scopes:
        prev = ""
        for row in (Decision.objects
                    .filter(scope_type=scope_type, scope_id=scope_id)
                    .order_by("pk")):
            canonical = json.dumps(row.content, sort_keys=True, default=str)
            content_hash = hashlib.sha256(
                (canonical + prev).encode()).hexdigest()
            Decision.objects.filter(pk=row.pk).update(
                prev_hash=prev, content_hash=content_hash)
            prev = content_hash

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0004_quizzes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsensusProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'consensus profile',
                'verbose_name_plural': 'consensus profiles',
                'ordering': ['percent', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Electorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('equal', 'Equal — one member, one vote'), ('weighted', 'Weighted — members carry set weights')], default='equal', max_length=10)),
                ('scope_type', models.CharField(blank=True, db_index=True, max_length=40)),
                ('scope_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electorates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'electorate',
                'verbose_name_plural': 'electorates',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='decision',
            name='adopted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='decision',
            name='content_hash',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='decision',
            name='prev_hash',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='question',
            name='decision_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='decision_header',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='rule_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='question',
            name='rule_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='ElectorateMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveBigIntegerField(default=1)),
                ('electorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='polls.electorate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electorate_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-weight', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='electorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='polls.electorate'),
        ),
        migrations.CreateModel(
            name='RollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=150)),
                ('weight', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roll', to='polls.question')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'roll entry',
                'verbose_name_plural': 'roll entries',
                'ordering': ['-weight', 'pk'],
                'indexes': [models.Index(fields=['question', 'user'], name='polls_rolle_questio_d18a80_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='rollentry',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('question', 'user'), name='uniq_roll_entry_user'),
        ),
        migrations.AddConstraint(
            model_name='electoratemember',
            constraint=models.UniqueConstraint(fields=('electorate', 'user'), name='uniq_electorate_member'),
        ),
        migrations.AddConstraint(
            model_name='electorate',
            constraint=models.UniqueConstraint(fields=('scope_type', 'scope_id', 'slug'), name='uniq_electorate_slug_per_scope'),
        ),
            migrations.RunPython(_backfill_chain,
                              migrations.RunPython.noop),
    ]
