# Generated by Django 4.2.23 on 2026-08-14 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0007_member_without_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteprocedure',
            name='excluded_weight',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voteprocedure',
            name='members_excluded',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='VoteExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=150)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('excluded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vote_exclusions_made', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to='polls.question')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'voter exclusion',
                'verbose_name_plural': 'voter exclusions',
                'ordering': ['pk'],
                'indexes': [models.Index(fields=['question', 'user'], name='polls_votee_questio_90dd6e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='voteexclusion',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('question', 'user'), name='uniq_vote_exclusion_user'),
        ),
    ]
