# Generated by Django 4.2.23 on 2026-08-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_ledger_snapshot'),
    ]

    operations = [
        # Constraints FIRST, and this ordering is the whole reason this
        # migration is not purely autogenerated. SQLite implements a dropped
        # column by rebuilding the table, and it rebuilds it with the
        # constraints the migration state still carries — so removing
        # `electoratemember.electorate` while `uniq_electorate_member` still
        # names that column fails with "NewElectorateMember has no field named
        # 'electorate'". The autodetector removes foreign keys before models to
        # break dependency cycles and does not know about this one.
        # Indexes have the same problem as constraints on SQLite: the table
        # rebuild recreates them from state, and one that names a dropped
        # column fails the rebuild.
        migrations.RemoveIndex(
            model_name='ledgersnapshot', name='polls_ledge_elector_7e65b5_idx'),
        migrations.RemoveIndex(
            model_name='decision', name='polls_decis_scope_t_c7e5b6_idx'),
        migrations.RemoveIndex(
            model_name='decision', name='polls_decis_outcome_34cb31_idx'),
        migrations.RemoveConstraint(
            model_name='electoratemember', name='uniq_electorate_member'),
        migrations.RemoveConstraint(
            model_name='electorate', name='uniq_electorate_slug_per_scope'),
        migrations.RemoveConstraint(
            model_name='ledgersnapshot', name='uniq_snapshot_per_ledger_state'),
        migrations.RemoveConstraint(
            model_name='rollentry', name='uniq_roll_entry_user'),
        migrations.RemoveConstraint(
            model_name='voteexclusion', name='uniq_vote_exclusion_user'),
        migrations.DeleteModel(
            name='ConsensusProfile',
        ),
        migrations.RemoveField(
            model_name='decision',
            name='decided_by',
        ),
        migrations.RemoveField(
            model_name='decision',
            name='electorate',
        ),
        migrations.RemoveField(
            model_name='decision',
            name='question',
        ),
        migrations.RemoveField(
            model_name='electorate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='electoratemember',
            name='electorate',
        ),
        migrations.RemoveField(
            model_name='electoratemember',
            name='person',
        ),
        migrations.RemoveField(
            model_name='ledgercheckpoint',
            name='signed_by',
        ),
        migrations.RemoveField(
            model_name='ledgercheckpoint',
            name='taken_by',
        ),
        migrations.RemoveField(
            model_name='ledgersnapshot',
            name='electorate',
        ),
        migrations.RemoveField(
            model_name='ledgersnapshot',
            name='first_seen_by',
        ),
        migrations.DeleteModel(
            name='QuorumRule',
        ),
        migrations.RemoveField(
            model_name='rollentry',
            name='question',
        ),
        migrations.RemoveField(
            model_name='rollentry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='voteexclusion',
            name='excluded_by',
        ),
        migrations.RemoveField(
            model_name='voteexclusion',
            name='question',
        ),
        migrations.RemoveField(
            model_name='voteexclusion',
            name='user',
        ),
        migrations.RemoveField(
            model_name='voteprocedure',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='convening_mode',
        ),
        migrations.RemoveField(
            model_name='question',
            name='decision_comment',
        ),
        migrations.RemoveField(
            model_name='question',
            name='decision_header',
        ),
        migrations.RemoveField(
            model_name='question',
            name='electorate',
        ),
        migrations.RemoveField(
            model_name='question',
            name='procedural_notes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quorum_mode',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quorum_name',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quorum_threshold',
        ),
        migrations.RemoveField(
            model_name='question',
            name='rule_name',
        ),
        migrations.RemoveField(
            model_name='question',
            name='rule_percent',
        ),
        migrations.AlterField(
            model_name='question',
            name='kind',
            field=models.CharField(choices=[('poll', 'Poll')], default='poll', max_length=8),
        ),
        migrations.DeleteModel(
            name='Decision',
        ),
        migrations.DeleteModel(
            name='Electorate',
        ),
        migrations.DeleteModel(
            name='ElectorateMember',
        ),
        migrations.DeleteModel(
            name='LedgerCheckpoint',
        ),
        migrations.DeleteModel(
            name='LedgerSnapshot',
        ),
        migrations.DeleteModel(
            name='RollEntry',
        ),
        migrations.DeleteModel(
            name='VoteExclusion',
        ),
        migrations.DeleteModel(
            name='VoteProcedure',
        ),
    ]
