# Generated by Django 4.2.23 on 2026-08-11 18:52

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('dimension', models.CharField(blank=True, max_length=50)),
                ('app_label', models.CharField(blank=True, max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['dimension', 'code'],
            },
        ),
        migrations.CreateModel(
            name='BillingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('dimension', models.CharField(blank=True, max_length=50)),
                ('app_label', models.CharField(blank=True, max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['dimension', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('source_type', models.CharField(blank=True, max_length=100)),
                ('source_id', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_asset', models.ForeignKey(blank=True, help_text="Currency this tariff prices in. Items may still override it per metric; leave empty to use the host's gas asset.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_for_tariffs', to='assets.asset')),
                ('owner', models.ForeignKey(blank=True, help_text='Only this user can edit the tariff and its items.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_tariffs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TariffItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price_per_unit_display', models.DecimalField(decimal_places=18, help_text='Human-readable price in asset display units', max_digits=30)),
                ('price_per_unit_base_units', models.BigIntegerField(blank=True, help_text='Price in asset base units — derived from the display price on save.')),
                ('unit_quantity', models.DecimalField(decimal_places=6, default=Decimal('1'), help_text='Denominator: price applies per this many units, e.g. 1000 for per-1000-tokens pricing', max_digits=20)),
                ('minimum_charge_base_units', models.BigIntegerField(default=0, help_text='Minimum charge per usage event, in base units (0 = no minimum)')),
                ('rounding_mode', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('nearest', 'Nearest')], default='up', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charged_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tariff_items', to='assets.asset')),
                ('metric', models.ForeignKey(help_text='Billing metric this item charges for, e.g. storage.request, ai.input_tokens', on_delete=django.db.models.deletion.PROTECT, related_name='tariff_items', to='tariffs.billingmetric')),
                ('receiving_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tariff_items_receiving', to='assets.ledgeraccount')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tariffs.tariff')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tariff_items', to='tariffs.billingunit')),
            ],
            options={
                'ordering': ['metric__code'],
            },
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('metric_code', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=30)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('source_type', models.CharField(blank=True, max_length=100)),
                ('source_id', models.CharField(blank=True, max_length=255)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('rated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('rated', 'Rated'), ('posted', 'Posted'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ledger_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usage_records', to='assets.ledgertransaction')),
                ('payer_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_records_as_payer', to='assets.ledgeraccount')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_records', to='tariffs.tariff')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=30)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('price_per_unit_base_units', models.BigIntegerField()),
                ('amount_base_units', models.BigIntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('charged_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_charges', to='assets.asset')),
                ('payer_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_charges_as_payer', to='assets.ledgeraccount')),
                ('receiving_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_charges_as_receiver', to='assets.ledgeraccount')),
                ('tariff_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='tariffs.tariffitem')),
                ('usage_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='tariffs.usagerecord')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='billingmetric',
            name='default_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metrics', to='tariffs.billingunit'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['tariff', 'status'], name='tariffs_usa_tariff__e6831a_idx'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['payer_account', 'status'], name='tariffs_usa_payer_a_53277a_idx'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['metric_code'], name='tariffs_usa_metric__b2cfff_idx'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['status'], name='tariffs_usa_status_1dd79a_idx'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['source_type', 'source_id'], name='tariffs_usa_source__e122fb_idx'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['occurred_at'], name='tariffs_usa_occurre_b68b97_idx'),
        ),
        migrations.AddIndex(
            model_name='tariffitem',
            index=models.Index(fields=['tariff', 'active'], name='tariffs_tar_tariff__baa8c5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tariffitem',
            unique_together={('tariff', 'metric')},
        ),
        migrations.AddIndex(
            model_name='tariff',
            index=models.Index(fields=['status'], name='tariffs_tar_status_e4bb02_idx'),
        ),
        migrations.AddIndex(
            model_name='tariff',
            index=models.Index(fields=['code'], name='tariffs_tar_code_c6f488_idx'),
        ),
        migrations.AddIndex(
            model_name='tariff',
            index=models.Index(fields=['source_type', 'source_id'], name='tariffs_tar_source__f29187_idx'),
        ),
    ]
