# Generated by Django 4.2.23 on 2026-07-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffitem',
            name='price_per_unit_base_units',
            field=models.BigIntegerField(blank=True, help_text='Price in asset base units — derived from the display price on save.'),
        ),
    ]
