# Generated by Django 4.2.23 on 2026-08-07 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_ledgertransaction_origin_platform_and_more'),
        ('tariffs', '0002_alter_tariffitem_price_per_unit_base_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='default_asset',
            field=models.ForeignKey(blank=True, help_text="Currency this tariff prices in. Items may still override it per metric; leave empty to use the host's gas asset.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_for_tariffs', to='assets.asset'),
        ),
    ]
