# Generated by Django 4.2.23 on 2025-09-27 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('slug', models.SlugField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_articles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CategoryLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kodama.category')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('import_url', models.URLField()),
                ('fallback', models.CharField(default='sans-serif', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.ImageField(upload_to='subsection_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('heading', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='kodama.article')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('domain', models.URLField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('creation_year', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('head_slogan', models.CharField(default='Peaceful Power', max_length=150)),
                ('foot_slogan', models.CharField(default='Engineered with electrons', max_length=150)),
                ('footer_about', models.TextField(blank=True, default='Kodama is a digital sanctuary for slow thought, cultural clarity, and independent voices.')),
                ('banner_image', models.ImageField(blank=True, help_text='Upload a banner image for the site header', null=True, upload_to='site_banners/')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_sites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('light_bg_top', models.CharField(default='#ffffff', max_length=7)),
                ('light_bg_bottom', models.CharField(default='#ffffff', max_length=7)),
                ('light_text_main', models.CharField(default='#000000', max_length=7)),
                ('light_text_muted', models.CharField(default='#666666', max_length=7)),
                ('light_accent', models.CharField(default='#0077ff', max_length=7)),
                ('light_border', models.CharField(default='#00f0ff', max_length=7)),
                ('light_card_bg', models.CharField(default='#f4f4f4', max_length=7)),
                ('light_footer_bg', models.CharField(default='#f4f4f4', max_length=7)),
                ('light_nav_bg_start', models.CharField(default='#d0eaff', max_length=7)),
                ('light_nav_bg_end', models.CharField(default='#e0f7fa', max_length=7)),
                ('light_nav_text', models.CharField(default='#0077ff', max_length=7)),
                ('light_nav_shadow', models.CharField(default='rgba(0, 119, 255, 0.25)', max_length=30)),
                ('light_banner_overlay', models.CharField(default='rgba(0, 119, 255, 0.25)', max_length=30)),
                ('dark_bg_top', models.CharField(default='#0a0a0a', max_length=7)),
                ('dark_bg_bottom', models.CharField(default='#1a1a1a', max_length=7)),
                ('dark_text_main', models.CharField(default='#ffffff', max_length=7)),
                ('dark_text_muted', models.CharField(default='#cccccc', max_length=7)),
                ('dark_accent', models.CharField(default='#00ff99', max_length=7)),
                ('dark_border', models.CharField(default='#0077ff', max_length=7)),
                ('dark_card_bg', models.CharField(default='#1a1a1a', max_length=7)),
                ('dark_footer_bg', models.CharField(default='#1a1a1a', max_length=7)),
                ('dark_nav_bg_start', models.CharField(default='#003344', max_length=7)),
                ('dark_nav_bg_end', models.CharField(default='#001a33', max_length=7)),
                ('dark_nav_text', models.CharField(default='#00ff99', max_length=7)),
                ('dark_nav_shadow', models.CharField(default='rgba(0, 255, 153, 0.25)', max_length=30)),
                ('dark_banner_overlay', models.CharField(default='rgba(0, 255, 153, 0.25)', max_length=30)),
                ('body_font', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='body_themes', to='kodama.font')),
                ('heading_font', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heading_themes', to='kodama.font')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_set', to='kodama.site')),
            ],
        ),
        migrations.CreateModel(
            name='SubSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsections', to='kodama.image')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='kodama.section')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='site',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='kodama.theme'),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('categories', models.ManyToManyField(related_name='menus', through='kodama.CategoryLink', to='kodama.category')),
                ('category_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kodama.category')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='kodama.site')),
            ],
        ),
        migrations.AddField(
            model_name='categorylink',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_links', to='kodama.menu'),
        ),
        migrations.AddField(
            model_name='category',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_set', to='kodama.site'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='kodama.category'),
        ),
        migrations.AddField(
            model_name='article',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='kodama.site'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='kodama.tag'),
        ),
        migrations.AlterUniqueTogether(
            name='categorylink',
            unique_together={('menu', 'category')},
        ),
    ]
