# Generated by Django 4.2.23 on 2025-08-24 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kodama', '0002_category_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='site',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='category_set', to='kodama.site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='site',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tag_set', to='kodama.site'),
            preserve_default=False,
        ),
    ]
