# Generated by Django 4.2.23 on 2025-08-24 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kodama', '0004_categorylink_menu_categorylink_menu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorylink',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_links', to='kodama.menu'),
        ),
    ]
