# Generated by Django 4.2.23 on 2025-08-24 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kodama', '0006_menu_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='category_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kodama.category'),
        ),
    ]
