# Generated by Django 4.2.23 on 2025-08-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodama', '0007_menu_category_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='foot_slogan',
            field=models.CharField(default='Engineered with electrons', max_length=150),
        ),
        migrations.AddField(
            model_name='site',
            name='footer_about',
            field=models.TextField(blank=True, default='Kodama is a digital sanctuary for slow thought, cultural clarity, and independent voices.'),
        ),
        migrations.AddField(
            model_name='site',
            name='head_slogan',
            field=models.CharField(default='Peaceful Power', max_length=150),
        ),
    ]
