# Generated by Django 4.2.23 on 2025-08-24 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kodama', '0008_site_foot_slogan_site_footer_about_site_head_slogan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('import_url', models.URLField()),
                ('fallback', models.CharField(default='sans-serif', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('light_bg_top', models.CharField(default='#ffffff', max_length=7)),
                ('light_bg_bottom', models.CharField(default='#ffffff', max_length=7)),
                ('light_text_main', models.CharField(default='#000000', max_length=7)),
                ('light_text_muted', models.CharField(default='#666666', max_length=7)),
                ('light_accent', models.CharField(default='#0077ff', max_length=7)),
                ('light_border', models.CharField(default='#00f0ff', max_length=7)),
                ('light_card_bg', models.CharField(default='#f4f4f4', max_length=7)),
                ('light_footer_bg', models.CharField(default='#f4f4f4', max_length=7)),
                ('light_nav_bg_start', models.CharField(default='#d0eaff', max_length=7)),
                ('light_nav_bg_end', models.CharField(default='#e0f7fa', max_length=7)),
                ('light_nav_text', models.CharField(default='#0077ff', max_length=7)),
                ('light_nav_shadow', models.CharField(default='rgba(0, 119, 255, 0.25)', max_length=30)),
                ('dark_bg_top', models.CharField(default='#0a0a0a', max_length=7)),
                ('dark_bg_bottom', models.CharField(default='#1a1a1a', max_length=7)),
                ('dark_text_main', models.CharField(default='#ffffff', max_length=7)),
                ('dark_text_muted', models.CharField(default='#cccccc', max_length=7)),
                ('dark_accent', models.CharField(default='#00ff99', max_length=7)),
                ('dark_border', models.CharField(default='#0077ff', max_length=7)),
                ('dark_card_bg', models.CharField(default='#1a1a1a', max_length=7)),
                ('dark_footer_bg', models.CharField(default='#1a1a1a', max_length=7)),
                ('dark_nav_bg_start', models.CharField(default='#003344', max_length=7)),
                ('dark_nav_bg_end', models.CharField(default='#001a33', max_length=7)),
                ('dark_nav_text', models.CharField(default='#00ff99', max_length=7)),
                ('dark_nav_shadow', models.CharField(default='rgba(0, 255, 153, 0.25)', max_length=30)),
                ('body_font', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='body_themes', to='kodama.font')),
                ('heading_font', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heading_themes', to='kodama.font')),
            ],
        ),
    ]
