# Generated by Django 4.2.23 on 2025-08-24 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kodama', '0009_font_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='kodama.theme'),
        ),
    ]
