# Generated by Django 4.2.23 on 2025-08-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodama', '0010_site_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Upload a banner image for the site header', null=True, upload_to='site_banners/'),
        ),
    ]
