# Generated by Django 4.2.23 on 2025-08-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodama', '0011_site_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='dark_banner_overlay',
            field=models.CharField(default='rgba(0, 255, 153, 0.25)', max_length=30),
        ),
        migrations.AddField(
            model_name='theme',
            name='light_banner_overlay',
            field=models.CharField(default='rgba(0, 119, 255, 0.25)', max_length=30),
        ),
    ]
