# Generated by Django 4.2.23 on 2026-10-01 05:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BentoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('neo4j_label', models.CharField(blank=True, help_text="Neo4j node label for nodes of this category, e.g. 'Idea'.", max_length=120)),
                ('property_schema', models.JSONField(blank=True, default=list, help_text='List of {name, type, required, label, help} field definitions.')),
                ('searchable_properties', models.JSONField(blank=True, default=list, help_text='Property names (declared in property_schema) whose values identify a node in free text — used by the Ingestor to detect existing nodes of this category. Empty falls back to name/title/label by convention.')),
                ('alias_property', models.CharField(blank=True, default='', help_text='Optional property holding alternate surface forms for a node (a JSON list or a comma-separated string). Also fed to detection.', max_length=120)),
                ('internal', models.BooleanField(default=False, help_text="Hide this category from the Ingestor's LLM category set (e.g. SQL-sync infrastructure types). Does not affect manual editing.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'node category template',
                'verbose_name_plural': 'node category templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BentoEdgeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('rel_type', models.CharField(blank=True, help_text="Neo4j relationship type, e.g. 'SUPPORTS' (UPPER_SNAKE_CASE).", max_length=120)),
                ('property_schema', models.JSONField(blank=True, default=list)),
                ('directed', models.BooleanField(default=True)),
                ('trigger_lemmas', models.JSONField(blank=True, default=list, help_text="Optional lemma triggers (e.g. ['support', 'back']). When one appears in a sentence between two endpoints whose categories match this edge, the Ingestor proposes this relationship and raises its confidence.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_sources', models.ManyToManyField(blank=True, help_text='Categories whose nodes may be the source of this edge. Empty means any.', related_name='outgoing_edge_types', to='bento.bentocategory')),
                ('allowed_targets', models.ManyToManyField(blank=True, help_text='Categories whose nodes may be the target of this edge. Empty means any.', related_name='incoming_edge_types', to='bento.bentocategory')),
            ],
            options={
                'verbose_name': 'edge type template',
                'verbose_name_plural': 'edge type templates',
                'ordering': ['name'],
            },
        ),
    ]
