# Generated by Django 4.2.23 on 2026-06-06 13:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('bento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('object_id', models.CharField(max_length=255)),
                ('label', models.CharField(blank=True, help_text='Optional relationship label, e.g. references, about, located at.', max_length=80)),
                ('properties', models.JSONField(blank=True, default=dict, help_text='Flexible metadata for the reference.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='bento.ideabox')),
                ('content_type', models.ForeignKey(help_text='Which external model the reference points at.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='bento_subje_content_eeb986_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='subjectreference',
            constraint=models.UniqueConstraint(fields=('box', 'content_type', 'object_id', 'label'), name='unique_subject_reference'),
        ),
    ]
