# Generated by Django 4.2.23 on 2026-06-09 00:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bento', '0003_delete_subjectreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='BentoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('neo4j_label', models.CharField(blank=True, help_text="Neo4j node label for nodes of this category, e.g. 'Idea'.", max_length=120)),
                ('property_schema', models.JSONField(blank=True, default=list, help_text='List of {name, type, required, label, help} field definitions.')),
                ('color', models.CharField(blank=True, default='#2563eb', max_length=20)),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'node category template',
                'verbose_name_plural': 'node category templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BentoEdgeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('rel_type', models.CharField(blank=True, help_text="Neo4j relationship type, e.g. 'SUPPORTS' (UPPER_SNAKE_CASE).", max_length=120)),
                ('property_schema', models.JSONField(blank=True, default=list)),
                ('directed', models.BooleanField(default=True)),
                ('color', models.CharField(blank=True, default='#64748b', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_sources', models.ManyToManyField(blank=True, help_text='Categories whose nodes may be the source of this edge. Empty means any.', related_name='outgoing_edge_types', to='bento.bentocategory')),
                ('allowed_targets', models.ManyToManyField(blank=True, help_text='Categories whose nodes may be the target of this edge. Empty means any.', related_name='incoming_edge_types', to='bento.bentocategory')),
            ],
            options={
                'verbose_name': 'edge type template',
                'verbose_name_plural': 'edge type templates',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='ideabox',
            name='category',
        ),
        migrations.AlterUniqueTogether(
            name='idealink',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='idealink',
            name='from_box',
        ),
        migrations.RemoveField(
            model_name='idealink',
            name='to_box',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='IdeaBox',
        ),
        migrations.DeleteModel(
            name='IdeaLink',
        ),
    ]
