# Generated by Django 4.2.23 on 2026-06-25 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bento', '0006_ingestor_detection_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='bentocategory',
            name='internal',
            field=models.BooleanField(default=False, help_text="Hide this category from the Ingestor's LLM category set (e.g. SQL-sync infrastructure types). Does not affect manual editing."),
        ),
    ]
