# Generated by Django 4.2.23 on 2026-05-14 15:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_make_apiconnector_abstract'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemotePlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('base_url', models.URLField(help_text='Base URL of the remote project. Can be HTTPS or .onion.')),
                ('enabled', models.BooleanField(default=True)),
                ('outgoing_secret_key', models.CharField(blank=True, help_text='Secret used when this instance calls the remote API.', max_length=255)),
                ('incoming_secret_key', models.CharField(blank=True, help_text='Optional secret expected from this remote when it calls us.', max_length=255)),
                ('uplink_backend', models.CharField(default='default', help_text='Transport backend used for up sync. Choices come from NOOSPHERE_TRANSPORTS.', max_length=120)),
                ('downlink_backend', models.CharField(default='default', help_text='Transport backend used for down sync. Choices come from NOOSPHERE_TRANSPORTS.', max_length=120)),
                ('timeout_seconds', models.PositiveIntegerField(default=60)),
                ('notes', models.TextField(blank=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_platform', models.ForeignKey(help_text='The local platform configuration this remote belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='remote_platforms', to='core.platform')),
            ],
            options={
                'verbose_name': 'remote platform',
                'verbose_name_plural': 'remote platforms',
                'ordering': ['local_platform', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SyncRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('model_label', models.CharField(help_text='Example: core.Theme, accounts.Profile, projects.Project', max_length=150)),
                ('enabled', models.BooleanField(default=True)),
                ('direction', models.CharField(choices=[('up', 'Up'), ('down', 'Down')], max_length=10)),
                ('fields', models.JSONField(blank=True, default=list, help_text='List of field names to sync. Empty means all fields allowed by the adapter.')),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Example: {"active": true, "changed_since_last_sync": true}')),
                ('sync_creates', models.BooleanField(default=True)),
                ('sync_updates', models.BooleanField(default=True)),
                ('sync_deletes', models.BooleanField(default=False)),
                ('conflict_policy', models.CharField(choices=[('source_wins', 'Source wins'), ('target_wins', 'Target wins'), ('newest_wins', 'Newest wins'), ('skip', 'Skip conflicts')], default='source_wins', max_length=30)),
                ('include_dependencies', models.BooleanField(default=False, help_text='Include referenced uid-enabled dependency models where supported.')),
                ('last_pushed_at', models.DateTimeField(blank=True, null=True)),
                ('last_pulled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noosphere_sync_rules', to='core.platform')),
                ('remote_platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_rules', to='noosphere.remoteplatform')),
            ],
            options={
                'verbose_name': 'sync rule',
                'verbose_name_plural': 'sync rules',
                'ordering': ['local_platform', 'remote_platform', 'model_label', 'direction', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('up', 'Up'), ('down', 'Down')], max_length=10)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('exported_count', models.PositiveIntegerField(default=0)),
                ('imported_count', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('deleted_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('package_hash', models.CharField(blank=True, help_text='SHA-256 hash of the sync package, when available.', max_length=64)),
                ('remote_status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('remote_response', models.JSONField(blank=True, default=dict)),
                ('message', models.TextField(blank=True)),
                ('local_platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noosphere_sync_runs', to='core.platform')),
                ('remote_platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_runs', to='noosphere.remoteplatform')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='noosphere.syncrule')),
            ],
            options={
                'verbose_name': 'sync run',
                'verbose_name_plural': 'sync runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncObjectRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(max_length=150)),
                ('uid', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('export', 'Export'), ('import', 'Import'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('skip', 'Skip'), ('error', 'Error')], max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('skipped', 'Skipped'), ('failed', 'Failed')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_runs', to='noosphere.syncrun')),
            ],
            options={
                'verbose_name': 'sync object run',
                'verbose_name_plural': 'sync object runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='syncrule',
            constraint=models.UniqueConstraint(fields=('local_platform', 'remote_platform', 'model_label', 'direction'), name='unique_noosphere_rule_per_local_remote_model_direction'),
        ),
        migrations.AddIndex(
            model_name='syncobjectrun',
            index=models.Index(fields=['model_label', 'uid'], name='noosphere_s_model_l_a0bffc_idx'),
        ),
        migrations.AddIndex(
            model_name='syncobjectrun',
            index=models.Index(fields=['action', 'status'], name='noosphere_s_action_91f039_idx'),
        ),
        migrations.AddConstraint(
            model_name='remoteplatform',
            constraint=models.UniqueConstraint(fields=('local_platform', 'name'), name='unique_remote_platform_name_per_local_platform'),
        ),
        migrations.AddConstraint(
            model_name='remoteplatform',
            constraint=models.UniqueConstraint(fields=('local_platform', 'base_url'), name='unique_remote_platform_url_per_local_platform'),
        ),
    ]
