# Generated by Django 4.2.23 on 2026-05-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noosphere', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syncrule',
            name='last_pushed_at',
        ),
        migrations.AlterField(
            model_name='syncrule',
            name='direction',
            field=models.CharField(choices=[('down', 'Down')], max_length=10),
        ),
        migrations.AlterField(
            model_name='syncrun',
            name='direction',
            field=models.CharField(choices=[('down', 'Down')], max_length=10),
        ),
    ]
