# Generated by Django 4.2.23 on 2026-10-01 05:49

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxArrearsCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('warned', 'Warned'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=16)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('warned_at', models.DateTimeField(blank=True, null=True)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_reason', models.CharField(blank=True, max_length=32)),
                ('warning_event_uid', models.UUIDField(blank=True, null=True)),
                ('warning_channel', models.CharField(blank=True, max_length=16)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('failed_days', models.PositiveIntegerField(default=0)),
                ('last_shortfall_display', models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True)),
                ('last_shortfall_asset', models.CharField(blank=True, max_length=32)),
                ('last_stored_raw', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxQuotaPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('metric_code', models.CharField(db_index=True, max_length=100)),
                ('limit', models.DecimalField(decimal_places=10, max_digits=30)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime')], default='daily', max_length=20)),
                ('mode', models.CharField(choices=[('track', 'Track only'), ('warn', 'Warn'), ('block', 'Block')], default='block', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tax quota policy',
                'verbose_name_plural': 'Tax quota policies',
                'ordering': ['metric_code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_code', models.CharField(help_text='The registered quota metric this levy bills through.', max_length=100, unique=True)),
                ('unit_label', models.CharField(blank=True, help_text="How the billing unit is written for people, e.g. 'GB'.", max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('clamp_to_balance', models.BooleanField(default=False, help_text='Charge what the payer can afford and never open an arrears case. For levies priced in a regenerating mana pool.')),
                ('concentration_k', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Anti-concentration dial. Adds k × share² billing units to what each holder owes, where share is their holdings ÷ what all users hold between them. Quadratic so it is negligible for ordinary members and acute at real concentration, and continuous so there is no threshold to sit just under: at k=100 a 1% holder pays +0.01, a 10% holder +1, a 50% holder +25. 0 switches it off entirely, which is the default and costs the nightly run nothing.', max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['metric_code'],
            },
        ),
        migrations.CreateModel(
            name='TimeGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100)),
                ('scope_id', models.BigIntegerField(blank=True, null=True)),
                ('seconds', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['key', 'scope_id'],
            },
        ),
        migrations.CreateModel(
            name='TaxUsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_code', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=30)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('source_type', models.CharField(blank=True, max_length=100)),
                ('source_id', models.CharField(blank=True, max_length=255)),
                ('source_label', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('recorded', 'Recorded'), ('voided', 'Voided')], default='recorded', max_length=20)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tax usage event',
                'verbose_name_plural': 'Tax usage events',
                'ordering': ['-occurred_at'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='taxquotapolicy',
            constraint=models.UniqueConstraint(fields=('metric_code',), name='tax_taxquotapolicy_one_per_metric'),
        ),
        migrations.AddField(
            model_name='taxarrearscase',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrears_cases', to='tax.taxrule'),
        ),
        migrations.AddField(
            model_name='taxarrearscase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_arrears_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='timegrant',
            index=models.Index(fields=['user', 'key'], name='tax_timegra_user_id_86e0fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='timegrant',
            constraint=models.UniqueConstraint(condition=models.Q(('scope_id__isnull', True)), fields=('user', 'key'), name='tax_timegrant_one_per_user'),
        ),
        migrations.AddConstraint(
            model_name='timegrant',
            constraint=models.UniqueConstraint(condition=models.Q(('scope_id__isnull', False)), fields=('key', 'scope_id'), name='tax_timegrant_one_per_scope'),
        ),
        migrations.AddIndex(
            model_name='taxusageevent',
            index=models.Index(fields=['metric_code', 'occurred_at'], name='taxusageevent_mtime'),
        ),
        migrations.AddIndex(
            model_name='taxusageevent',
            index=models.Index(fields=['user', 'metric_code'], name='taxusageevent_umetric'),
        ),
        migrations.AddConstraint(
            model_name='taxusageevent',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('idempotency_key',), name='tax_taxusageevent_idem'),
        ),
        migrations.AddIndex(
            model_name='taxarrearscase',
            index=models.Index(fields=['status', 'deadline_at'], name='tax_taxarre_status_352911_idx'),
        ),
        migrations.AddConstraint(
            model_name='taxarrearscase',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['open', 'warned'])), fields=('user', 'rule'), name='tax_one_active_case_per_user_rule'),
        ),
    ]
