# Generated by Django 4.2.23 on 2026-08-11 19:02

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxArrearsCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('warned', 'Warned'), ('resolved', 'Resolved'), ('enforced', 'Enforced')], db_index=True, default='open', max_length=16)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('warned_at', models.DateTimeField(blank=True, null=True)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('enforced_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_reason', models.CharField(blank=True, max_length=32)),
                ('warning_event_uid', models.UUIDField(blank=True, null=True)),
                ('warning_channel', models.CharField(blank=True, max_length=16)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('failed_days', models.PositiveIntegerField(default=0)),
                ('last_shortfall_display', models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True)),
                ('last_shortfall_asset', models.CharField(blank=True, max_length=32)),
                ('last_stored_raw', models.PositiveBigIntegerField(default=0)),
                ('allowance_raw_at_open', models.PositiveBigIntegerField(default=0)),
                ('reached_target', models.BooleanField(blank=True, null=True)),
                ('enforcement_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_code', models.CharField(help_text='The registered quota metric this levy bills through.', max_length=100, unique=True)),
                ('allowance', models.DecimalField(decimal_places=10, default=Decimal('0'), help_text='Held for free, in billing units (e.g. GB). Only the excess is levied.', max_digits=30)),
                ('unit_label', models.CharField(blank=True, help_text="How the allowance unit is written for people, e.g. 'GB'.", max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['metric_code'],
            },
        ),
        migrations.CreateModel(
            name='TaxUsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_code', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=30)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('source_type', models.CharField(blank=True, max_length=100)),
                ('source_id', models.CharField(blank=True, max_length=255)),
                ('source_label', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('recorded', 'Recorded'), ('voided', 'Voided')], default='recorded', max_length=20)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tax usage event',
                'verbose_name_plural': 'Tax usage events',
                'ordering': ['-occurred_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaxQuotaPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('metric_code', models.CharField(db_index=True, max_length=100)),
                ('limit', models.DecimalField(decimal_places=10, max_digits=30)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime')], default='daily', max_length=20)),
                ('mode', models.CharField(choices=[('track', 'Track only'), ('warn', 'Warn'), ('block', 'Block')], default='block', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='Leave empty for the default policy that applies to everyone.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tax quota policy',
                'verbose_name_plural': 'Tax quota policies',
                'ordering': ['metric_code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaxEnforcementAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('deleted', 'Deleted'), ('skipped_protected', 'Skipped (protected)')], max_length=24)),
                ('item_pk', models.BigIntegerField()),
                ('item_label', models.CharField(blank=True, max_length=255)),
                ('item_key', models.CharField(blank=True, max_length=255)),
                ('container', models.CharField(blank=True, max_length=120)),
                ('size_raw', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='tax.taxarrearscase')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='taxarrearscase',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrears_cases', to='tax.taxrule'),
        ),
        migrations.AddField(
            model_name='taxarrearscase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_arrears_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SurplusPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_display', models.DecimalField(decimal_places=18, help_text='Held for free, in asset units. Only the excess is taxed.', max_digits=30)),
                ('threshold_base_units', models.PositiveBigIntegerField(blank=True, default=0)),
                ('rate', models.DecimalField(decimal_places=6, help_text='Fraction of the surplus per period, e.g. 0.02 = 2%.', max_digits=7)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='assets.asset')),
            ],
            options={
                'verbose_name_plural': 'Surplus policies',
            },
        ),
        migrations.CreateModel(
            name='SurplusCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_label', models.CharField(max_length=32)),
                ('total_base', models.PositiveBigIntegerField()),
                ('threshold_base', models.PositiveBigIntegerField()),
                ('fee_base', models.PositiveBigIntegerField()),
                ('rate', models.DecimalField(decimal_places=6, max_digits=7)),
                ('allocation', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('collected', 'Collected'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=10)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='tax.surpluspolicy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surplus_charges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100)),
                ('scope_id', models.BigIntegerField(blank=True, null=True)),
                ('seconds', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['key', 'scope_id'],
                'indexes': [models.Index(fields=['user', 'key'], name='tax_timegra_user_id_86e0fa_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='timegrant',
            constraint=models.UniqueConstraint(condition=models.Q(('scope_id__isnull', True)), fields=('user', 'key'), name='tax_timegrant_one_per_user'),
        ),
        migrations.AddConstraint(
            model_name='timegrant',
            constraint=models.UniqueConstraint(condition=models.Q(('scope_id__isnull', False)), fields=('key', 'scope_id'), name='tax_timegrant_one_per_scope'),
        ),
        migrations.AddIndex(
            model_name='taxusageevent',
            index=models.Index(fields=['metric_code', 'occurred_at'], name='taxusageevent_mtime'),
        ),
        migrations.AddIndex(
            model_name='taxusageevent',
            index=models.Index(fields=['user', 'metric_code'], name='taxusageevent_umetric'),
        ),
        migrations.AddConstraint(
            model_name='taxusageevent',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('idempotency_key',), name='tax_taxusageevent_idem'),
        ),
        migrations.AddConstraint(
            model_name='taxquotapolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('metric_code',), name='tax_taxquotapolicy_one_default'),
        ),
        migrations.AddConstraint(
            model_name='taxquotapolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('metric_code', 'user'), name='tax_taxquotapolicy_one_per_user'),
        ),
        migrations.AddIndex(
            model_name='taxarrearscase',
            index=models.Index(fields=['status', 'deadline_at'], name='tax_taxarre_status_352911_idx'),
        ),
        migrations.AddConstraint(
            model_name='taxarrearscase',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['open', 'warned'])), fields=('user', 'rule'), name='tax_one_active_case_per_user_rule'),
        ),
        migrations.AddIndex(
            model_name='surpluscharge',
            index=models.Index(fields=['policy', 'status'], name='tax_surplus_policy__5eed68_idx'),
        ),
        migrations.AddConstraint(
            model_name='surpluscharge',
            constraint=models.UniqueConstraint(fields=('policy', 'user', 'period_label'), name='tax_one_surplus_charge_per_period'),
        ),
    ]
