# Generated by Django 4.2.23 on 2026-08-07 23:08

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxArrearsCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('warned', 'Warned'), ('resolved', 'Resolved'), ('enforced', 'Enforced')], db_index=True, default='open', max_length=16)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('warned_at', models.DateTimeField(blank=True, null=True)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('enforced_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_reason', models.CharField(blank=True, max_length=32)),
                ('warning_event_uid', models.UUIDField(blank=True, null=True)),
                ('warning_channel', models.CharField(blank=True, max_length=16)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('failed_days', models.PositiveIntegerField(default=0)),
                ('last_shortfall_display', models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True)),
                ('last_shortfall_asset', models.CharField(blank=True, max_length=32)),
                ('last_stored_raw', models.PositiveBigIntegerField(default=0)),
                ('allowance_raw_at_open', models.PositiveBigIntegerField(default=0)),
                ('reached_target', models.BooleanField(blank=True, null=True)),
                ('enforcement_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_code', models.CharField(help_text='The registered quota metric this levy bills through.', max_length=100, unique=True)),
                ('allowance', models.DecimalField(decimal_places=10, default=Decimal('0'), help_text='Held for free, in billing units (e.g. GB). Only the excess is levied.', max_digits=30)),
                ('unit_label', models.CharField(blank=True, help_text="How the allowance unit is written for people, e.g. 'GB'.", max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['metric_code'],
            },
        ),
        migrations.CreateModel(
            name='TaxEnforcementAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('deleted', 'Deleted'), ('skipped_protected', 'Skipped (protected)')], max_length=24)),
                ('item_pk', models.BigIntegerField()),
                ('item_label', models.CharField(blank=True, max_length=255)),
                ('item_key', models.CharField(blank=True, max_length=255)),
                ('container', models.CharField(blank=True, max_length=120)),
                ('size_raw', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='tax.taxarrearscase')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='taxarrearscase',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrears_cases', to='tax.taxrule'),
        ),
        migrations.AddField(
            model_name='taxarrearscase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_arrears_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='taxarrearscase',
            index=models.Index(fields=['status', 'deadline_at'], name='tax_taxarre_status_352911_idx'),
        ),
        migrations.AddConstraint(
            model_name='taxarrearscase',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['open', 'warned'])), fields=('user', 'rule'), name='tax_one_active_case_per_user_rule'),
        ),
    ]
