# Generated by Django 4.2.23 on 2026-08-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surpluspolicy',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='taxenforcementaction',
            name='case',
        ),
        migrations.RemoveField(
            model_name='taxarrearscase',
            name='allowance_raw_at_open',
        ),
        migrations.RemoveField(
            model_name='taxarrearscase',
            name='enforced_at',
        ),
        migrations.RemoveField(
            model_name='taxarrearscase',
            name='enforcement_summary',
        ),
        migrations.RemoveField(
            model_name='taxarrearscase',
            name='reached_target',
        ),
        migrations.RemoveField(
            model_name='taxrule',
            name='allowance',
        ),
        migrations.AlterField(
            model_name='taxarrearscase',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('warned', 'Warned'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=16),
        ),
        migrations.AlterField(
            model_name='taxrule',
            name='unit_label',
            field=models.CharField(blank=True, help_text="How the billing unit is written for people, e.g. 'GB'.", max_length=32),
        ),
        migrations.DeleteModel(
            name='SurplusCharge',
        ),
        migrations.DeleteModel(
            name='SurplusPolicy',
        ),
        migrations.DeleteModel(
            name='TaxEnforcementAction',
        ),
    ]
