# Generated by Django 4.2.23 on 2026-08-12 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_rename_total_supply_base_units_asset_max_supply_base_units'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialhub', '0005_socialhubquotapolicy_socialhubusageevent_and_more'),
        ('tax', '0002_remove_surpluspolicy_asset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StipendPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_label', models.CharField(help_text="Calendar-aligned, e.g. 'weekly:2026-08-10'. One payment per period.", max_length=32)),
                ('amount_base_units', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stipend_payments', to='assets.asset')),
                ('holder', models.ForeignKey(help_text='Who held the office when this period was materialised.', on_delete=django.db.models.deletion.CASCADE, related_name='stipend_payments', to=settings.AUTH_USER_MODEL)),
                ('ledger_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assets.ledgertransaction')),
                ('payee_account', models.ForeignKey(help_text="The holder's billing account — where their next charge is taken from.", on_delete=django.db.models.deletion.PROTECT, related_name='stipends_received', to='assets.ledgeraccount')),
                ('payer_account', models.ForeignKey(help_text='The federal treasury. Every station is paid from here.', on_delete=django.db.models.deletion.PROTECT, related_name='stipends_paid', to='assets.ledgeraccount')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='socialhub.station')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'period_label'], name='tax_stipend_status_957d73_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='stipendpayment',
            constraint=models.UniqueConstraint(fields=('station', 'period_label'), name='tax_one_stipend_per_station_period'),
        ),
    ]
