# Generated by Django 4.2.23 on 2026-08-12 23:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0003_stipendpayment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxrule',
            name='concentration_k',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Anti-concentration dial. Adds k × share² billing units to what each holder owes, where share is their holdings ÷ what all users hold between them. Quadratic so it is negligible for ordinary members and acute at real concentration, and continuous so there is no threshold to sit just under: at k=100 a 1% holder pays +0.01, a 10% holder +1, a 50% holder +25. 0 switches it off entirely, which is the default and costs the nightly run nothing.', max_digits=12),
        ),
    ]
