# Generated by Django 4.2.23 on 2026-08-12 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0004_taxrule_concentration_k'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='taxquotapolicy',
            name='tax_taxquotapolicy_one_default',
        ),
        migrations.RemoveConstraint(
            model_name='taxquotapolicy',
            name='tax_taxquotapolicy_one_per_user',
        ),
        migrations.RemoveField(
            model_name='taxquotapolicy',
            name='user',
        ),
        migrations.AddConstraint(
            model_name='taxquotapolicy',
            constraint=models.UniqueConstraint(fields=('metric_code',), name='tax_taxquotapolicy_one_per_metric'),
        ),
    ]
