# Generated by Django 4.2.23 on 2026-08-26 10:56

from django.db import migrations


class Migration(migrations.Migration):
    """Drop the payroll's ledger: the treasury has no offices left to pay.

    A StipendPayment was one office's pay for one period, and an office was a
    ``socialhub.Station``. Stations were removed in 8/2026, so every row here
    points at something that no longer exists. IRREVERSIBLE and deliberately
    so — this is not a rename or a move, and nothing recreates these rows.

    Runs BEFORE socialhub drops Station, because this table holds the CASCADE
    foreign key to it — declared as `run_before` rather than as a dependency on
    the socialhub side. `socialhub` is a CORE app that every host installs and
    `toto.tax` ships in the optional economy package, so socialhub naming tax
    would raise NodeNotFoundError on any host without it. Naming socialhub from
    here is always safe: tax is only ever installed where socialhub already is.
    """

    run_before = [('socialhub', '0012_delete_station')]

    dependencies = [
        ('tax', '0006_alter_stipendpayment_payer_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StipendPayment',
        ),
    ]
