# Generated by Django 4.2.23 on 2026-08-26 10:56

from django.db import migrations


class Migration(migrations.Migration):
    """Drop the payroll's ledger: the treasury has no offices left to pay.

    A StipendPayment was one office's pay for one period, and an office was a
    ``socialhub.Station``. Stations were removed in 8/2026, so every row here
    points at something that no longer exists. IRREVERSIBLE and deliberately
    so — this is not a rename or a move, and nothing recreates these rows.

    Runs BEFORE socialhub drops Station, because this table holds the CASCADE
    foreign key to it. The reverse order would work in Postgres and mislead
    anybody reading it.
    """

    dependencies = [
        ('tax', '0006_alter_stipendpayment_payer_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StipendPayment',
        ),
    ]
