# Generated by Django 4.2.23 on 2026-09-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0007_delete_stipendpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxrule',
            name='clamp_to_balance',
            field=models.BooleanField(default=False, help_text='Charge what the payer can afford and never open an arrears case. For levies priced in a regenerating mana pool.'),
        ),
    ]
