# Generated by Django 4.2.23 on 2026-05-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objecttype',
            name='category',
            field=models.CharField(blank=True, choices=[('commodity', 'Commodity'), ('equipment', 'Equipment'), ('vehicle', 'Vehicle'), ('real_estate', 'Real Estate'), ('infrastructure', 'Infrastructure'), ('other', 'Other')], db_index=True, max_length=30),
        ),
        migrations.AddField(
            model_name='objecttype',
            name='is_mobile',
            field=models.BooleanField(default=False, help_text='Objects of this type move (vehicles, portable equipment). Used for fleet map filtering.'),
        ),
    ]
