# Generated by Django 4.2.23 on 2026-06-08 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ravioli', '0003_graphsyncschedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GraphChangeEvent',
        ),
        migrations.DeleteModel(
            name='GraphProjectionPlan',
        ),
        migrations.DeleteModel(
            name='GraphSyncSchedule',
        ),
        migrations.DeleteModel(
            name='GraphSync',
        ),
    ]
