# Generated by Django 4.2.23 on 2025-12-26 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, db_comment='owned_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('urgency', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2)),
                ('impact', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('campaign', models.ForeignKey(db_comment='belongs_to_campaign', on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='kanban.campaign')),
                ('owner', models.ForeignKey(blank=True, db_comment='owned_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('collaborators', models.ManyToManyField(related_name='collaborating_projects', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(db_comment='owned_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('project', models.ForeignKey(db_comment='belongs_to', on_delete=django.db.models.deletion.CASCADE, to='kanban.project')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('weight', models.PositiveIntegerField(default=1)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, db_comment='assigned_to', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('column', models.ForeignKey(db_comment='has_status', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='kanban.column')),
                ('mission', models.ForeignKey(db_comment='belongs_to', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='kanban.mission')),
                ('sprint', models.ForeignKey(blank=True, db_comment='belongs_to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='kanban.sprint')),
            ],
        ),
        migrations.AddField(
            model_name='column',
            name='project',
            field=models.ForeignKey(db_column='belongs_to_project', db_comment='belongs_to', on_delete=django.db.models.deletion.CASCADE, to='kanban.project'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='project',
            field=models.ForeignKey(db_comment='belongs_to_project', on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='kanban.project'),
        ),
    ]
