# Generated by Django 4.2.23 on 2025-12-23 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='owner',
            field=models.ForeignKey(blank=True, db_comment='owned_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='project',
            field=models.ForeignKey(db_comment='belongs_to_project', on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='kanban.project'),
        ),
        migrations.AlterField(
            model_name='column',
            name='project',
            field=models.ForeignKey(db_column='belongs_to_project', db_comment='belongs_to', on_delete=django.db.models.deletion.CASCADE, to='kanban.project'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='campaign',
            field=models.ForeignKey(db_comment='belongs_to_campaign', on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='kanban.campaign'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='owner',
            field=models.ForeignKey(blank=True, db_comment='owned_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(db_comment='owned_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='project',
            field=models.ForeignKey(db_comment='belongs_to', on_delete=django.db.models.deletion.CASCADE, to='kanban.project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(blank=True, db_comment='assigned_to', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='column',
            field=models.ForeignKey(db_comment='has_status', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='kanban.column'),
        ),
        migrations.AlterField(
            model_name='task',
            name='mission',
            field=models.ForeignKey(db_comment='belongs_to', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='kanban.mission'),
        ),
        migrations.AlterField(
            model_name='task',
            name='sprint',
            field=models.ForeignKey(blank=True, db_comment='belongs_to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='kanban.sprint'),
        ),
    ]
