# Generated by Django 4.2.23 on 2025-11-11 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_fundinground_venture'),
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='venture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kanban_projects', to='portfolio.company'),
        ),
    ]
