# Generated by Django 4.2.23 on 2025-11-11 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='venture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kanban_projects', to='portfolio.company'),
        ),
        migrations.AddField(
            model_name='column',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban.project'),
        ),
    ]
