# Generated by Django 4.2.23 on 2025-10-05 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='color_mix',
        ),
        migrations.DeleteModel(
            name='ColorMix',
        ),
    ]
