# Generated by Django 4.2.23 on 2025-10-28 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_remove_column_color_mix_delete_colormix'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
