# Generated by Django 4.2.23 on 2025-08-28 18:39

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_column_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='color',
        ),
        migrations.AddField(
            model_name='column',
            name='bg_color',
            field=colorfield.fields.ColorField(default='#F3F4F6', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='column',
            name='text_color',
            field=colorfield.fields.ColorField(default='#111827', image_field=None, max_length=25, samples=None),
        ),
    ]
