# Generated by Django 4.2.23 on 2025-12-27 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        ('kanban', '0002_alter_task_assignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='owner',
            field=models.ForeignKey(blank=True, db_comment='owned_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.communitymember'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='owner',
            field=models.ForeignKey(blank=True, db_comment='owned_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.communitymember'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(db_comment='owned_by', on_delete=django.db.models.deletion.CASCADE, to='community.communitymember'),
        ),
    ]
