# Generated by Django 4.2.23 on 2025-10-28 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_venture_company'),
        ('kanban', '0002_alter_task_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='venture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kanban_projects', to='portfolio.venture'),
        ),
    ]
