# Generated by Django 4.2.23 on 2025-10-28 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_delete_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sprint',
            old_name='end',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='sprint',
            old_name='start',
            new_name='start_time',
        ),
    ]
