# Generated by Django 4.2.23 on 2025-12-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0004_alter_task_impact_alter_task_urgency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='impact',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2, max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='urgency',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2, max_length=20),
        ),
    ]
