# Generated by Django 4.2.23 on 2025-12-13 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0008_alter_campaign_metadata_alter_mission_metadata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='campaign',
        ),
        migrations.AddField(
            model_name='task',
            name='mission',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='kanban.mission'),
            preserve_default=False,
        ),
    ]
