# Generated by Django 4.2.23 on 2025-12-13 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0009_remove_task_campaign_task_mission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='project',
        ),
        migrations.AddField(
            model_name='campaign',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='kanban.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mission',
            name='campaign',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='kanban.campaign'),
            preserve_default=False,
        ),
    ]
