# Generated by Django 4.2.23 on 2026-05-18 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='backing_document',
            field=models.TextField(blank=True, help_text='What this asset is backed by (e.g. 1:1 PLN reserve held by …)'),
        ),
        migrations.AddField(
            model_name='asset',
            name='is_currency',
            field=models.BooleanField(default=False, help_text='Accepted as a payment currency in the bazaar'),
        ),
        migrations.AddField(
            model_name='asset',
            name='minting_authority',
            field=models.CharField(blank=True, help_text='Entity authorised to mint this asset', max_length=255),
        ),
        migrations.CreateModel(
            name='Obligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('order_reference', models.CharField(blank=True, max_length=255)),
                ('amount_base_units', models.BigIntegerField()),
                ('due_at', models.DateTimeField()),
                ('collateral_amount_base_units', models.BigIntegerField(default=0)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('overdue', 'Overdue'), ('fulfilled', 'Fulfilled'), ('defaulted', 'Defaulted')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligations', to='assets.asset')),
                ('collateral_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collateral_obligations', to='assets.ledgeraccount')),
                ('collateral_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collateral_obligations', to='assets.asset')),
                ('creditor_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creditor_obligations', to='assets.ledgeraccount')),
                ('debtor_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debtor_obligations', to='assets.ledgeraccount')),
            ],
            options={
                'ordering': ['due_at'],
            },
        ),
    ]
