# Generated by Django 4.2.23 on 2026-05-19 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_realworldobject_object_type'),
        ('people', '0002_initial'),
        ('assets', '0003_obligation_iscurrency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tokenization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tokenizations', to='assets.asset')),
                ('real_world_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tokenizations', to='inventory.realworldobject')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_tokenizations', to='people.person')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['real_world_object'], name='assets_toke_real_wo_c5363f_idx'), models.Index(fields=['asset'], name='assets_toke_asset_i_aa432e_idx'), models.Index(fields=['supervisor'], name='assets_toke_supervi_da896c_idx'), models.Index(fields=['created_at'], name='assets_toke_created_690b8c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='tokenization',
            constraint=models.UniqueConstraint(fields=('real_world_object', 'asset'), name='unique_tokenization_object_asset'),
        ),
    ]
