# Generated by Django 4.2.23 on 2026-05-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_tokenization_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tokenization',
            name='unique_tokenization_object_asset',
        ),
        migrations.AddConstraint(
            model_name='tokenization',
            constraint=models.UniqueConstraint(fields=('real_world_object',), name='unique_tokenization_object'),
        ),
        migrations.AddConstraint(
            model_name='tokenization',
            constraint=models.UniqueConstraint(fields=('asset',), name='unique_tokenization_asset'),
        ),
    ]
