# Generated by Django 4.2.23 on 2026-05-19 14:30

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0005_remove_tokenization_unique_tokenization_object_asset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=12, help_text='Fixed amount of to_asset received for 1 unit of from_asset.', max_digits=24)),
                ('commission_percent', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Commission charged in the payment asset on top of the converted amount.', max_digits=7)),
                ('active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_rates_from', to='assets.asset')),
                ('to_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_rates_to', to='assets.asset')),
            ],
            options={
                'ordering': ['from_asset__unit_name', 'to_asset__unit_name'],
            },
        ),
        migrations.CreateModel(
            name='AssetExchangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_amount_base_units', models.BigIntegerField()),
                ('request_amount_base_units', models.BigIntegerField()),
                ('commission_amount_base_units', models.BigIntegerField(default=0)),
                ('exchange_rate', models.DecimalField(decimal_places=12, max_digits=24)),
                ('commission_percent', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('offer_tx_reference', models.CharField(blank=True, max_length=255)),
                ('request_tx_reference', models.CharField(blank=True, max_length=255)),
                ('commission_tx_reference', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('response_note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_exchange_requests_received', to=settings.AUTH_USER_MODEL)),
                ('counterparty_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exchange_requests_received', to='assets.ledgeraccount')),
                ('offer_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_requests_offered', to='assets.asset')),
                ('request_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_requests_requested', to='assets.asset')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_exchange_requests_made', to=settings.AUTH_USER_MODEL)),
                ('requester_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_requests_made', to='assets.ledgeraccount')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['requester', 'status'], name='assets_asse_request_a228da_idx'), models.Index(fields=['counterparty', 'status'], name='assets_asse_counter_eaf679_idx'), models.Index(fields=['offer_asset', 'request_asset'], name='assets_asse_offer_a_5e3837_idx'), models.Index(fields=['created_at'], name='assets_asse_created_a55a97_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssetExchangeRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=12, max_digits=24)),
                ('commission_percent', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('exchange_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='assets.assetexchangerate')),
                ('from_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_rate_history_from', to='assets.asset')),
                ('to_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_rate_history_to', to='assets.asset')),
            ],
            options={
                'verbose_name_plural': 'asset exchange rate history',
                'ordering': ['recorded_at'],
                'indexes': [models.Index(fields=['from_asset', 'to_asset', 'recorded_at'], name='assets_asse_from_as_f57d52_idx'), models.Index(fields=['exchange_rate', 'recorded_at'], name='assets_asse_exchang_0c523f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='assetexchangerate',
            index=models.Index(fields=['from_asset', 'to_asset'], name='assets_asse_from_as_5e8f7a_idx'),
        ),
        migrations.AddIndex(
            model_name='assetexchangerate',
            index=models.Index(fields=['active'], name='assets_asse_active_c87505_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetexchangerate',
            constraint=models.UniqueConstraint(fields=('from_asset', 'to_asset'), name='unique_asset_exchange_rate_pair'),
        ),
        migrations.AddConstraint(
            model_name='assetexchangerate',
            constraint=models.CheckConstraint(check=models.Q(('from_asset', models.F('to_asset')), _negated=True), name='exchange_rate_distinct_assets'),
        ),
    ]
