# Generated by Django 4.2.23 on 2026-05-26 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_ledger_signing'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='reserve_account',
            field=models.ForeignKey(blank=True, help_text='Admin-controlled account that holds unminted supply and fulfils purchases.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserve_assets', to='assets.ledgeraccount'),
        ),
        migrations.AlterField(
            model_name='ledgertransaction',
            name='transaction_type',
            field=models.CharField(choices=[('asset_create', 'Asset Create'), ('asset_mint', 'Asset Mint'), ('asset_transfer', 'Asset Transfer'), ('reversal', 'Reversal'), ('adjustment', 'Adjustment')], max_length=30),
        ),
    ]
