# Generated by Django 4.2.23 on 2026-05-24 15:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_tokenization_default_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.TextField(blank=True, help_text='Lapis smart-contract YAML.')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements_as_source', to='assets.ledgeraccount')),
                ('target_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements_as_target', to='assets.ledgeraccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
