# Generated by Django 4.2.23 on 2026-05-24 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_agreement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.TextField(blank=True, help_text='Jinja2 template that renders to a Lapis smart-contract YAML. Use {{ param_name }} placeholders filled by Agreement.params at runtime.')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='code',
        ),
        migrations.AddField(
            model_name='agreement',
            name='params',
            field=models.JSONField(blank=True, default=dict, help_text='Parameters passed to the contract template when rendering the Lapis YAML.'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Lapis contract template governing this agreement.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='assets.contracttemplate'),
        ),
    ]
