# Generated by Django 4.2.23 on 2026-05-24 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_contract_template_and_agreement_params'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.TextField(blank=True, help_text='Lapis smart-contract YAML.')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='params',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='template',
        ),
        migrations.DeleteModel(
            name='ContractTemplate',
        ),
        migrations.AddField(
            model_name='agreement',
            name='contract',
            field=models.ForeignKey(blank=True, help_text='Lapis contract governing this agreement.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='assets.contract'),
        ),
    ]
