# Generated by Django 4.2.23 on 2026-05-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_contract_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='global_state',
            field=models.JSONField(blank=True, default=dict, help_text='Runtime Lapis VM state (status, counters, etc.).'),
        ),
    ]
