# Generated by Django 4.2.23 on 2026-05-26 17:07

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detections', '0002_initial'),
        ('socialhub', '0001_initial'),
        ('people', '0002_initial'),
        ('assets', '0007_remove_asset_mint_transaction_type'),
        ('kanban', '0002_initial'),
        ('inventory', '0002_initial'),
        ('locations', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingDock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180)),
                ('power_kw', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('slot_count', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['community', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChargingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('start_battery_percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('end_battery_percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('energy_kwh', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ComponentReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('metric', models.CharField(max_length=80)),
                ('value', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='FirmwareInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('log', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='FirmwareRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=80)),
                ('release_notes', models.TextField(blank=True)),
                ('artifact_url', models.URLField(blank=True)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('is_required', models.BooleanField(default=False)),
                ('released_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['model', '-released_at'],
            },
        ),
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['community', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FleetMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'ordering': ['fleet', 'robot'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('parts_used', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('triaged', 'Triaged'), ('in_progress', 'In Progress'), ('waiting_parts', 'Waiting for Parts'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', max_length=32)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='warning', max_length=16)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('cost_base_units', models.BigIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='MissionWaypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, max_length=160)),
                ('instruction', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('altitude_m', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('hold_seconds', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['mission', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('callsign', models.SlugField(max_length=80)),
                ('serial_number', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('provisioning', 'Provisioning'), ('idle', 'Idle'), ('active', 'Active'), ('returning', 'Returning'), ('charging', 'Charging'), ('maintenance', 'Maintenance'), ('offline', 'Offline'), ('faulted', 'Faulted'), ('retired', 'Retired')], db_index=True, default='provisioning', max_length=32)),
                ('firmware_version', models.CharField(blank=True, max_length=80)),
                ('hardware_revision', models.CharField(blank=True, max_length=80)),
                ('battery_percent', models.PositiveSmallIntegerField(default=0)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('commissioned_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('is_autonomous', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['community', 'callsign'],
            },
        ),
        migrations.CreateModel(
            name='RobotAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('accepted', 'Accepted'), ('running', 'Running'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='queued', max_length=32)),
                ('role', models.CharField(blank=True, max_length=80)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('telemetry_summary', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['mission', 'robot'],
            },
        ),
        migrations.CreateModel(
            name='RobotCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'robot capabilities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RobotCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.CharField(max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField(blank=True, null=True)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=120)),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='RobotComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('component_type', models.CharField(max_length=80)),
                ('serial_number', models.CharField(blank=True, max_length=160)),
                ('installed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('expected_lifetime_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('runtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['robot', 'component_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RobotEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, default='info', max_length=16)),
                ('event_type', models.CharField(db_index=True, max_length=80)),
                ('message', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='RobotMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('dispatched', 'Dispatched'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='draft', max_length=32)),
                ('scheduled_start_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=5)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('constraints', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('dispatch_robot_mission', 'Can dispatch robot missions'), ('issue_robot_command', 'Can issue robot commands'), ('view_robot_telemetry', 'Can view robot telemetry'), ('manage_robot_maintenance', 'Can manage robot maintenance'), ('install_robot_firmware', 'Can install robot firmware')],
            },
        ),
        migrations.CreateModel(
            name='RobotModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('manufacturer', models.CharField(max_length=160)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('kind', models.CharField(choices=[('ground', 'Ground Robot'), ('aerial', 'Aerial Drone'), ('marine', 'Marine Robot'), ('underwater', 'Underwater Robot'), ('humanoid', 'Humanoid'), ('arm', 'Robotic Arm'), ('sensor', 'Sensor Platform'), ('other', 'Other')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('payload_capacity_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('max_speed_mps', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('battery_capacity_wh', models.PositiveIntegerField(blank=True, null=True)),
                ('nominal_runtime_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('supported_capabilities', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['manufacturer', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RobotTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('altitude_m', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('speed_mps', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('heading_degrees', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('battery_percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('battery_voltage', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('signal_strength', models.IntegerField(blank=True, null=True)),
                ('cpu_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('memory_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telemetry', to='robots.robotmission')),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='robots.robot')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='robotmodel',
            constraint=models.UniqueConstraint(fields=('manufacturer', 'name'), name='robots_unique_manufacturer_model'),
        ),
        migrations.AddField(
            model_name='robotmission',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robot_missions', to='socialhub.community'),
        ),
        migrations.AddField(
            model_name='robotmission',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='robot_mission_destinations', to='locations.address'),
        ),
        migrations.AddField(
            model_name='robotmission',
            name='detection',
            field=models.ForeignKey(blank=True, help_text='Optional incident/threat this mission mitigates.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='robot_missions', to='detections.detection'),
        ),
        migrations.AddField(
            model_name='robotmission',
            name='fleet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='robots.fleet'),
        ),
        migrations.AddField(
            model_name='robotmission',
            name='kanban_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='robot_missions', to='kanban.task'),
        ),
        migrations.AddField(
            model_name='robotmission',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='robot_mission_origins', to='locations.address'),
        ),
        migrations.AddField(
            model_name='robotmission',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_robot_missions', to='people.person'),
        ),
        migrations.AddField(
            model_name='robotmission',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='robot_missions', to='locations.route'),
        ),
        migrations.AddField(
            model_name='robotmission',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_robot_missions', to='people.person'),
        ),
        migrations.AddField(
            model_name='robotevent',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_robot_events', to='people.person'),
        ),
        migrations.AddField(
            model_name='robotevent',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='robot_events', to='locations.address'),
        ),
        migrations.AddField(
            model_name='robotevent',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='robots.robotmission'),
        ),
        migrations.AddField(
            model_name='robotevent',
            name='robot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='robots.robot'),
        ),
        migrations.AddField(
            model_name='robotcomponent',
            name='robot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='robots.robot'),
        ),
        migrations.AddField(
            model_name='robotcommand',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_robot_commands', to='people.person'),
        ),
        migrations.AddField(
            model_name='robotcommand',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commands', to='robots.robotmission'),
        ),
        migrations.AddField(
            model_name='robotcommand',
            name='robot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='robots.robot'),
        ),
        migrations.AddField(
            model_name='robotassignment',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='robots.robotmission'),
        ),
        migrations.AddField(
            model_name='robotassignment',
            name='robot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='robots.robot'),
        ),
        migrations.AddField(
            model_name='robot',
            name='capabilities',
            field=models.ManyToManyField(blank=True, related_name='robots', to='robots.robotcapability'),
        ),
        migrations.AddField(
            model_name='robot',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robots', to='socialhub.community'),
        ),
        migrations.AddField(
            model_name='robot',
            name='current_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='robots_currently_here', to='locations.address'),
        ),
        migrations.AddField(
            model_name='robot',
            name='home_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='based_robots', to='locations.address'),
        ),
        migrations.AddField(
            model_name='robot',
            name='inventory_object',
            field=models.OneToOneField(blank=True, help_text='Optional physical asset registry link.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='robot', to='inventory.realworldobject'),
        ),
        migrations.AddField(
            model_name='robot',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='robots', to='robots.robotmodel'),
        ),
        migrations.AddField(
            model_name='robot',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_robots', to='people.person'),
        ),
        migrations.AddField(
            model_name='missionwaypoint',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='robot_waypoints', to='locations.address'),
        ),
        migrations.AddField(
            model_name='missionwaypoint',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='robots.robotmission'),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_robot_maintenance_tickets', to='people.person'),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_tickets', to='robots.robotcomponent'),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='cost_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='robot_maintenance_costs', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_robot_maintenance_tickets', to='people.person'),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='robot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_tickets', to='robots.robot'),
        ),
        migrations.AddField(
            model_name='maintenanceaction',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='robot_maintenance_actions', to='people.person'),
        ),
        migrations.AddField(
            model_name='maintenanceaction',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='robots.maintenanceticket'),
        ),
        migrations.AddField(
            model_name='fleetmembership',
            name='fleet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.fleet'),
        ),
        migrations.AddField(
            model_name='fleetmembership',
            name='robot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.robot'),
        ),
        migrations.AddField(
            model_name='fleet',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robot_fleets', to='socialhub.community'),
        ),
        migrations.AddField(
            model_name='fleet',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_robot_fleets', to='people.person'),
        ),
        migrations.AddField(
            model_name='fleet',
            name='robots',
            field=models.ManyToManyField(blank=True, related_name='fleets', through='robots.FleetMembership', to='robots.robot'),
        ),
        migrations.AddField(
            model_name='firmwarerelease',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firmware_releases', to='robots.robotmodel'),
        ),
        migrations.AddField(
            model_name='firmwareinstallation',
            name='installed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='robot_firmware_installations', to='people.person'),
        ),
        migrations.AddField(
            model_name='firmwareinstallation',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installations', to='robots.firmwarerelease'),
        ),
        migrations.AddField(
            model_name='firmwareinstallation',
            name='robot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firmware_installations', to='robots.robot'),
        ),
        migrations.AddField(
            model_name='componentreading',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='robots.robotcomponent'),
        ),
        migrations.AddField(
            model_name='chargingsession',
            name='dock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charging_sessions', to='robots.chargingdock'),
        ),
        migrations.AddField(
            model_name='chargingsession',
            name='robot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charging_sessions', to='robots.robot'),
        ),
        migrations.AddField(
            model_name='chargingdock',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charging_docks', to='socialhub.community'),
        ),
        migrations.AddField(
            model_name='chargingdock',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charging_docks', to='locations.address'),
        ),
        migrations.AddField(
            model_name='chargingdock',
            name='supported_models',
            field=models.ManyToManyField(blank=True, related_name='charging_docks', to='robots.robotmodel'),
        ),
        migrations.AddIndex(
            model_name='robottelemetry',
            index=models.Index(fields=['robot', '-recorded_at'], name='robots_robo_robot_i_3bd860_idx'),
        ),
        migrations.AddIndex(
            model_name='robottelemetry',
            index=models.Index(fields=['mission', '-recorded_at'], name='robots_robo_mission_e6f85d_idx'),
        ),
        migrations.AddIndex(
            model_name='robotmission',
            index=models.Index(fields=['community', 'status'], name='robots_robo_communi_6675fa_idx'),
        ),
        migrations.AddIndex(
            model_name='robotmission',
            index=models.Index(fields=['scheduled_start_at'], name='robots_robo_schedul_40c08e_idx'),
        ),
        migrations.AddIndex(
            model_name='robotevent',
            index=models.Index(fields=['robot', 'severity', '-occurred_at'], name='robots_robo_robot_i_7190a3_idx'),
        ),
        migrations.AddIndex(
            model_name='robotevent',
            index=models.Index(fields=['event_type'], name='robots_robo_event_t_cea9c9_idx'),
        ),
        migrations.AddConstraint(
            model_name='robotcomponent',
            constraint=models.UniqueConstraint(condition=models.Q(('serial_number', ''), _negated=True), fields=('robot', 'serial_number'), name='robots_unique_component_serial_per_robot'),
        ),
        migrations.AddIndex(
            model_name='robotcommand',
            index=models.Index(fields=['robot', '-issued_at'], name='robots_robo_robot_i_dc3c36_idx'),
        ),
        migrations.AddIndex(
            model_name='robotcommand',
            index=models.Index(fields=['command_type'], name='robots_robo_command_10f63f_idx'),
        ),
        migrations.AddIndex(
            model_name='robotcommand',
            index=models.Index(fields=['idempotency_key'], name='robots_robo_idempot_289d03_idx'),
        ),
        migrations.AddIndex(
            model_name='robotassignment',
            index=models.Index(fields=['robot', 'status'], name='robots_robo_robot_i_127129_idx'),
        ),
        migrations.AddIndex(
            model_name='robotassignment',
            index=models.Index(fields=['mission', 'status'], name='robots_robo_mission_bce2b8_idx'),
        ),
        migrations.AddConstraint(
            model_name='robotassignment',
            constraint=models.UniqueConstraint(fields=('mission', 'robot'), name='robots_unique_robot_assignment_per_mission'),
        ),
        migrations.AddIndex(
            model_name='robot',
            index=models.Index(fields=['community', 'status'], name='robots_robo_communi_136704_idx'),
        ),
        migrations.AddIndex(
            model_name='robot',
            index=models.Index(fields=['last_seen_at'], name='robots_robo_last_se_3a4d5d_idx'),
        ),
        migrations.AddConstraint(
            model_name='robot',
            constraint=models.UniqueConstraint(fields=('community', 'callsign'), name='robots_unique_community_callsign'),
        ),
        migrations.AddConstraint(
            model_name='robot',
            constraint=models.UniqueConstraint(condition=models.Q(('serial_number', ''), _negated=True), fields=('community', 'serial_number'), name='robots_unique_nonempty_serial_per_community'),
        ),
        migrations.AddConstraint(
            model_name='missionwaypoint',
            constraint=models.UniqueConstraint(fields=('mission', 'order'), name='robots_unique_waypoint_order_per_mission'),
        ),
        migrations.AddIndex(
            model_name='maintenanceticket',
            index=models.Index(fields=['robot', 'status'], name='robots_main_robot_i_d05f32_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceticket',
            index=models.Index(fields=['severity', 'status'], name='robots_main_severit_d080fb_idx'),
        ),
        migrations.AddConstraint(
            model_name='fleetmembership',
            constraint=models.UniqueConstraint(fields=('fleet', 'robot'), name='robots_unique_robot_fleet_membership'),
        ),
        migrations.AddConstraint(
            model_name='fleet',
            constraint=models.UniqueConstraint(fields=('community', 'slug'), name='robots_unique_fleet_slug_per_community'),
        ),
        migrations.AddConstraint(
            model_name='firmwarerelease',
            constraint=models.UniqueConstraint(fields=('model', 'version'), name='robots_unique_firmware_release_per_model'),
        ),
        migrations.AddConstraint(
            model_name='firmwareinstallation',
            constraint=models.UniqueConstraint(fields=('robot', 'release'), name='robots_unique_firmware_installation'),
        ),
        migrations.AddIndex(
            model_name='componentreading',
            index=models.Index(fields=['component', 'metric', '-recorded_at'], name='robots_comp_compone_cf805a_idx'),
        ),
        migrations.AddIndex(
            model_name='chargingsession',
            index=models.Index(fields=['robot', '-started_at'], name='robots_char_robot_i_46b364_idx'),
        ),
        migrations.AddIndex(
            model_name='chargingsession',
            index=models.Index(fields=['dock', '-started_at'], name='robots_char_dock_id_647ac5_idx'),
        ),
        migrations.AddConstraint(
            model_name='chargingdock',
            constraint=models.UniqueConstraint(fields=('community', 'slug'), name='robots_unique_dock_slug_per_community'),
        ),
    ]
