# Generated by Django 4.2.23 on 2026-01-13 09:49

from django.db import migrations, models
import django.db.models.deletion
import django_jsonform.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Asset Type',
                'verbose_name_plural': 'Asset Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IdentityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(choices=[('individual', 'Individual'), ('organization', 'Organization')], default='individual', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('registration_number', models.CharField(blank=True, help_text='National ID or registration number', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', django_jsonform.models.fields.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.address')),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identity_profiles', to='community.community')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identity_profiles', to='community.communitymember')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_identity_profiles', to='community.communitymember')),
            ],
            options={
                'verbose_name': 'Identity Profile',
                'verbose_name_plural': 'Identity Profiles',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Optional amount associated with this asset', max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', django_jsonform.models.fields.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset_type', models.ForeignKey(db_comment='is_type_of', on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='assets.assettype')),
                ('assigned_to', models.ForeignKey(blank=True, db_comment='assigned_to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.communitymember')),
                ('location', models.ForeignKey(blank=True, db_comment='located_at', null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.address')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FractionalOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Ownership percentage (e.g., 12.50)', max_digits=5)),
                ('metadata', django_jsonform.models.fields.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fractional_owners', to='assets.asset')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='assets.identityprofile')),
            ],
            options={
                'ordering': ['asset', 'owner'],
                'unique_together': {('asset', 'owner')},
            },
        ),
    ]
