# Generated by Django 4.2.23 on 2026-01-13 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fractionalownership',
            name='metadata',
        ),
    ]
