# Generated by Django 4.2.23 on 2025-12-26 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='assigned_to',
            field=models.ForeignKey(blank=True, db_comment='assigned_to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.communitymember'),
        ),
    ]
