# Generated by Django 4.2.23 on 2025-12-13 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='assettype',
            name='updated_at',
        ),
    ]
