# Generated by Django 4.2.23 on 2026-01-17 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('locations', '0001_initial'),
        ('community', '0001_initial'),
        ('federal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fractionalownership',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='federal.identityprofile'),
        ),
        migrations.AddField(
            model_name='assetimage',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.ForeignKey(db_comment='is_type_of', on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='assets.assettype'),
        ),
        migrations.AddField(
            model_name='asset',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.communitymember'),
        ),
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.address'),
        ),
        migrations.AlterUniqueTogether(
            name='fractionalownership',
            unique_together={('asset', 'owner')},
        ),
    ]
