# Generated by Django 4.2.23 on 2026-01-13 09:53

from django.db import migrations
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_remove_fractionalownership_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityprofile',
            name='metadata',
            field=django_jsonform.models.fields.JSONField(default={}),
        ),
    ]
