# Generated by Django 4.2.23 on 2025-12-13 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_address_location'),
        ('assets', '0002_remove_asset_updated_at_remove_assettype_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.address'),
        ),
    ]
