# Generated by Django 4.2.23 on 2026-01-13 09:56

from django.db import migrations
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_identityprofile_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityprofile',
            name='metadata',
            field=django_jsonform.models.fields.JSONField(default={'content': [], 'type': 'doc'}),
        ),
    ]
