# Generated by Django 4.2.23 on 2025-12-13 18:02

from django.db import migrations
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_asset_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='metadata',
            field=django_jsonform.models.fields.JSONField(blank=True, null=True),
        ),
    ]
