# Generated by Django 4.2.23 on 2026-01-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_identityprofile_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='metadata',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='identityprofile',
            name='metadata',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
