# Generated by Django 4.2.23 on 2026-01-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_alter_asset_metadata_alter_identityprofile_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityprofile',
            name='registration_type',
            field=models.CharField(blank=True, help_text='Type of registration number (e.g., National ID, Passport, Tax ID, etc.)', max_length=100, null=True),
        ),
    ]
