# Generated by Django 4.2.23 on 2026-01-14 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0002_identityprofile'),
        ('assets', '0007_alter_asset_amount_alter_asset_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fractionalownership',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='federal.identityprofile'),
        ),
        migrations.DeleteModel(
            name='IdentityProfile',
        ),
    ]
