# Generated by Django 4.2.23 on 2026-05-25 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial'),
        ('mobilization', '0001_initial'),
        ('socialhub', '0001_initial'),
        ('locations', '0002_initial'),
        ('people', '0002_initial'),
        ('detections', '0002_initial'),
        ('kanban', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('deployment_type', models.CharField(choices=[('evacuation', 'Evacuation'), ('flood_response', 'Flood Response'), ('fire_support', 'Fire Support'), ('shelter_support', 'Shelter Support'), ('logistics', 'Logistics'), ('medical', 'Medical'), ('welfare_check', 'Welfare Check'), ('reconnaissance', 'Reconnaissance'), ('mixed', 'Mixed'), ('other', 'Other')], max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='planned', max_length=20)),
                ('objective', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_hybrid', models.BooleanField(default=False, help_text='Partial deployment — responders split time with other duties')),
                ('hybrid_time_percent', models.PositiveSmallIntegerField(blank=True, help_text='Percentage of time allocated to this deployment (0–100)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='socialhub.community')),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_deployments', to='people.person')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='mobilization.mobilizationevent')),
                ('kanban_mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobilization_deployments', to='kanban.mission')),
            ],
        ),
        migrations.CreateModel(
            name='InterventionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='fa-solid fa-hand-holding-medical', max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EvacuationRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('route_type', models.CharField(choices=[('evacuation', 'Evacuation'), ('supply', 'Supply'), ('medical', 'Medical'), ('patrol', 'Patrol'), ('other', 'Other')], default='evacuation', max_length=20)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('blocked', 'Blocked'), ('cleared', 'Cleared')], default='planned', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evac_routes', to='mobilization.mobilizationevent')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobilization_evac_routes', to='locations.route')),
            ],
            options={
                'ordering': ['route_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DeploymentRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_type', models.CharField(choices=[('primary', 'Primary'), ('alternate', 'Alternate'), ('supply', 'Supply'), ('retreat', 'Retreat'), ('other', 'Other')], default='primary', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='response.deployment')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployment_routes', to='locations.route')),
            ],
            options={
                'ordering': ['route_type'],
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('done', 'Done'), ('cancelled', 'Cancelled')], db_index=True, default='todo', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('outcome_notes', models.TextField(blank=True)),
                ('effect_description', models.TextField(blank=True, help_text='Observed effects / impact of this intervention')),
                ('is_required', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to='mobilization.responder')),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='response.deployment')),
                ('detection', models.ForeignKey(blank=True, help_text='Detection this intervention is intended to mitigate', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobilization_interventions', to='detections.detection')),
                ('intervention_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to='response.interventiontype')),
                ('kanban_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobilization_interventions', to='kanban.task')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_interventions', to='people.person')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_interventions', to='people.person')),
            ],
            options={
                'indexes': [models.Index(fields=['deployment', 'status'], name='response_in_deploym_e15060_idx'), models.Index(fields=['deployment', 'is_required', 'status'], name='response_in_deploym_c07c47_idx'), models.Index(fields=['assigned_to', 'status'], name='response_in_assigne_2fdbb5_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeploymentEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='response.deployment')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployment_equipment', to='inventory.realworldobject')),
            ],
            options={
                'ordering': ['item__name'],
                'unique_together': {('deployment', 'item')},
            },
        ),
        migrations.CreateModel(
            name='DeploymentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('lead', 'Lead'), ('deputy', 'Deputy'), ('driver', 'Driver'), ('medic', 'Medic'), ('logistics', 'Logistics'), ('communicator', 'Communicator'), ('responder', 'Responder'), ('volunteer', 'Volunteer')], default='responder', max_length=20)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('confirmed', 'Confirmed'), ('active', 'Active'), ('released', 'Released'), ('completed', 'Completed'), ('no_show', 'No Show')], db_index=True, default='assigned', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_deployment_assignments', to='people.person')),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='response.deployment')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployment_assignments', to='mobilization.responder')),
            ],
            options={
                'indexes': [models.Index(fields=['deployment', 'status'], name='response_de_deploym_163db0_idx'), models.Index(fields=['responder', 'status'], name='response_de_respond_755ef8_idx')],
                'unique_together': {('deployment', 'responder')},
            },
        ),
        migrations.AddIndex(
            model_name='deployment',
            index=models.Index(fields=['event', 'status'], name='response_de_event_i_6596a9_idx'),
        ),
        migrations.AddIndex(
            model_name='deployment',
            index=models.Index(fields=['community', 'status'], name='response_de_communi_04dee5_idx'),
        ),
        migrations.AddIndex(
            model_name='deployment',
            index=models.Index(fields=['status', 'priority'], name='response_de_status_40990e_idx'),
        ),
    ]
