# Generated by Django 4.2.23 on 2026-05-23 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='forecastpoint',
            new_name='weather_for_session_175f92_idx',
            old_name='weather_for_session_fd3c6c_idx',
        ),
    ]
