# Generated by Django 4.2.23 on 2026-05-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaultfile',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('html', 'HTML'), ('text', 'Text File'), ('json', 'JSON'), ('svg', 'SVG File'), ('audio', 'Audio'), ('video', 'Video')], max_length=10),
        ),
    ]
