# Generated by Django 4.2.23 on 2026-05-24 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_vaultdirectory'),
    ]

    operations = [
        migrations.AddField(
            model_name='filegateway',
            name='directory',
            field=models.ForeignKey(blank=True, help_text='Files uploaded through this gateway are placed in this directory. Leave blank for bucket root.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gateways', to='vault.vaultdirectory'),
        ),
    ]
