# Generated by Django 4.2.23 on 2026-05-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0005_vaultfile_file_size_bytes'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='file_quota',
            field=models.PositiveIntegerField(blank=True, help_text='Max files per user in this bucket. Leave blank for unlimited.', null=True),
        ),
        migrations.AlterField(
            model_name='filegateway',
            name='max_file_size',
            field=models.PositiveIntegerField(default=10240, help_text='Maximum allowed file size in KB.'),
        ),
    ]
