# Generated by Django 4.2.23 on 2026-05-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0006_bucket_file_quota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucket',
            name='file_quota',
        ),
        migrations.AddField(
            model_name='bucket',
            name='storage_quota_mb',
            field=models.PositiveIntegerField(blank=True, help_text='Storage quota per user in MB. Leave blank for unlimited.', null=True),
        ),
    ]
