# Generated by Django 4.2.23 on 2026-05-26 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0009_storage_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storageaccount',
            name='pin_hash',
        ),
    ]
