# Generated by Django 4.2.23 on 2026-05-26 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_wallet_authorization'),
        ('vault', '0010_remove_storageaccount_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageaccount',
            name='authorization',
            field=models.ForeignKey(blank=True, help_text='If set, vault transactions are auto-authorized. Otherwise the user must confirm manually.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_accounts', to='assets.walletauthorization'),
        ),
    ]
