# Generated by Django 4.2.23 on 2026-05-26 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0013_remove_billing_add_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultinvoice',
            name='bucket',
            field=models.ForeignKey(blank=True, help_text='Bucket this invoice was generated for (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='vault.bucket'),
        ),
        migrations.AddField(
            model_name='vaultinvoice',
            name='obligation_reference',
            field=models.CharField(blank=True, help_text='Reference of the assets Obligation created when the invoice was accepted.', max_length=255),
        ),
    ]
