# Generated by Django 4.2.23 on 2026-05-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0020_remove_bucket_tariff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='storage_config',
            field=models.JSONField(blank=True, default=dict, help_text='Non-secret backend config. S3: bucket_name, region_name, prefix, use_ssl, addressing_style, aws_profile. remote_toto: server_url, bucket_slug, api_token_env. Credentials must come from environment variables, not this field.'),
        ),
    ]
