# Generated by Django 4.2.23 on 2026-08-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manta', '0003_filejob_finished_at_filejob_started_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mantaquotapolicy',
            name='manta_mantaquotapolicy_one_default',
        ),
        migrations.RemoveConstraint(
            model_name='mantaquotapolicy',
            name='manta_mantaquotapolicy_one_per_user',
        ),
        migrations.RemoveField(
            model_name='mantaquotapolicy',
            name='user',
        ),
        migrations.AddConstraint(
            model_name='mantaquotapolicy',
            constraint=models.UniqueConstraint(fields=('metric_code',), name='manta_mantaquotapolicy_one_per_metric'),
        ),
    ]
