# Generated by Django 4.2.23 on 2026-08-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manta', '0004_remove_mantaquotapolicy_manta_mantaquotapolicy_one_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filejob',
            name='gear_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
