# Generated by Django 4.2.23 on 2026-08-26 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manta', '0005_filejob_gear_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='GearPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gear_uuid', models.UUIDField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manta_gear_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'gear preference',
            },
        ),
    ]
