# Generated by Django 4.2.23 on 2025-10-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memocard',
            name='mermaid_code',
        ),
        migrations.AddField(
            model_name='memocard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='card_images/'),
        ),
    ]
