# Generated by Django 4.2.23 on 2026-01-11 05:35

from django.db import migrations, models
import django.db.models.deletion
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('latex', models.TextField(help_text='LaTeX expression for the formula')),
                ('metadata', django_jsonform.models.fields.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='memocard',
            name='formula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='memo.memoformula'),
        ),
    ]
