# Generated by Django 4.2.23 on 2026-01-11 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0002_memoformula_memocard_formula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memoformula',
            name='metadata',
        ),
    ]
