# Generated by Django 4.2.23 on 2025-12-21 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0002_mermaidchart_memodeck_chart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memodeck',
            name='chart',
        ),
        migrations.AddField(
            model_name='memocard',
            name='chart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='memo.mermaidchart'),
        ),
    ]
