# Generated by Django 4.2.23 on 2025-12-13 19:51

from django.db import migrations
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mandragora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lambdanode',
            name='test_context',
            field=django_jsonform.models.fields.JSONField(blank=True, default=dict, help_text='Optional JSON context for testing this node'),
        ),
    ]
