# Generated by Django 4.2.23 on 2025-12-30 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mandragora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LambdaUnitTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('input_context', models.JSONField(default=dict)),
                ('expected_output', models.JSONField(default=dict)),
                ('actual_output', models.JSONField(blank=True, default=dict)),
                ('passed', models.BooleanField(default=False)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='lambdanode',
            name='is_final',
        ),
        migrations.RemoveField(
            model_name='lambdanode',
            name='is_initial',
        ),
        migrations.RemoveField(
            model_name='lambdanode',
            name='test_context',
        ),
        migrations.RemoveField(
            model_name='lambdanode',
            name='workflow',
        ),
        migrations.DeleteModel(
            name='Edge',
        ),
        migrations.DeleteModel(
            name='Workflow',
        ),
        migrations.AddField(
            model_name='lambdaunittest',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_tests', to='mandragora.lambdanode'),
        ),
        migrations.AlterUniqueTogether(
            name='lambdaunittest',
            unique_together={('node', 'name')},
        ),
    ]
