# Generated by Django 4.2.23 on 2025-12-14 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mandragora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LambdaLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('use_opencv', models.BooleanField(default=False)),
                ('use_kanban_client', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='lambdanode',
            name='layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='mandragora.lambdalayer'),
        ),
    ]
