# Generated by Django 4.2.23 on 2025-12-19 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandragora', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lambdalayer',
            name='use_kanban_client',
        ),
    ]
