# Generated by Django 4.2.23 on 2025-12-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandragora', '0002_lambdaunittest_remove_lambdanode_is_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lambdalayer',
            name='use_io',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lambdalayer',
            name='use_json',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lambdalayer',
            name='use_networkx',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lambdalayer',
            name='use_numpy',
            field=models.BooleanField(default=False),
        ),
    ]
