# Generated by Django 4.2.23 on 2025-12-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandragora', '0002_lambdalayer_lambdanode_layer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lambdanode',
            name='test_context',
            field=models.JSONField(blank=True, default=dict, help_text='Optional JSON context for testing this node'),
        ),
    ]
