# Generated by Django 4.2.23 on 2025-09-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandragora', '0002_algonode_algorithm_node_countdown_node_max_retries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noderun',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='noderun',
            name='terminated',
            field=models.BooleanField(default=False),
        ),
    ]
