# Generated by Django 4.2.23 on 2026-01-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandragora', '0003_lambdalayer_use_io_lambdalayer_use_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lambdalayer',
            name='use_random',
            field=models.BooleanField(default=False),
        ),
    ]
