# Generated by Django 4.2.23 on 2025-12-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandragora', '0004_alter_lambdanode_test_context'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lambdanode',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='lambdanode',
            name='test_context',
            field=models.JSONField(blank=True, help_text='Optional JSON context for testing', null=True),
        ),
    ]
