# Generated by Django 4.2.23 on 2026-05-18 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso_client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oidcproviderconfig',
            name='app_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='oidcproviderconfig',
            name='redirect_uris',
            field=models.TextField(blank=True, help_text='One redirect URI per line.'),
        ),
        migrations.AddField(
            model_name='oidcproviderconfig',
            name='trusted',
            field=models.BooleanField(default=False),
        ),
    ]
