# Generated by Django 4.2.23 on 2026-06-14 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gervazy', '0002_initial'),
        ('telegraph', '0002_data_mesh_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegraphchannel',
            name='dek',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegraph_channels', to='gervazy.wrappeddatakey'),
        ),
        migrations.AddField(
            model_name='telegraphchannel',
            name='message_ttl_seconds',
            field=models.PositiveIntegerField(default=86400),
        ),
        migrations.AddField(
            model_name='telegraphchannel',
            name='pin_key_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.CreateModel(
            name='TelegraphPin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pin_key_id', models.CharField(max_length=64)),
                ('iv', models.BinaryField()),
                ('ciphertext', models.BinaryField()),
                ('original_sender', models.CharField(blank=True, max_length=150)),
                ('original_timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='telegraph.telegraphchannel')),
                ('pinned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegraphMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_name', models.CharField(blank=True, max_length=150)),
                ('sender_avatar_url', models.CharField(blank=True, max_length=500)),
                ('msg_type', models.CharField(choices=[('chat_message', 'chat_message'), ('image_message', 'image_message'), ('voice_message', 'voice_message')], default='chat_message', max_length=32)),
                ('ciphertext', models.BinaryField()),
                ('nonce', models.BinaryField()),
                ('aad', models.BinaryField(default=bytes)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='telegraph.telegraphchannel')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['channel', 'created_at'], name='telegraph_t_channel_8c3464_idx')],
            },
        ),
    ]
