# Generated by Django 4.2.23 on 2026-06-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegraph', '0003_telegraphchannel_dek_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegraphmessage',
            name='encryption',
            field=models.CharField(choices=[('at_rest', 'at_rest'), ('e2e', 'e2e')], default='at_rest', max_length=16),
        ),
        migrations.AddField(
            model_name='telegraphmessage',
            name='iv',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegraphmessage',
            name='pin_key_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
