# Generated by Django 4.2.23 on 2026-05-21 11:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import toto.workflows.models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0005_workflowconnector_events_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=20)),
                ('definition', models.JSONField(default=toto.workflows.models.default_report_definition, help_text='Snapshot of the report template definition used to generate this report.', validators=[toto.workflows.models.validate_report_definition])),
                ('data', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_node_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='workflows.workflownoderun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('definition', models.JSONField(blank=True, default=toto.workflows.models.default_report_definition, help_text="JSON report syntax. Root: {version, pages:[{key,title,blocks:[]}]}. Block types: card, table, chart, text. Values can use {'path': 'metrics.total'}.", validators=[toto.workflows.models.validate_report_definition])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='workflownode',
            name='node_type',
            field=models.CharField(choices=[('lambda', 'Lambda'), ('human', 'Human'), ('split', 'Split'), ('join', 'Join'), ('connector', 'Connector'), ('report', 'Report')], max_length=20),
        ),
        migrations.CreateModel(
            name='ReportPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=120)),
                ('title', models.CharField(max_length=180)),
                ('order', models.PositiveIntegerField(default=0)),
                ('blocks', models.JSONField(blank=True, default=list)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='workflows.report')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='workflows.reporttemplate'),
        ),
        migrations.AddField(
            model_name='report',
            name='workflow_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='workflows.workflowrun'),
        ),
        migrations.AddField(
            model_name='workflownode',
            name='report_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_nodes', to='workflows.reporttemplate'),
        ),
        migrations.AddConstraint(
            model_name='reportpage',
            constraint=models.UniqueConstraint(fields=('report', 'key'), name='unique_report_page_key'),
        ),
    ]
