# Generated by Django 4.2.23 on 2026-05-21 12:46

from django.db import migrations, models
import toto.workflows.models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0006_report_reporttemplate_alter_workflownode_node_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('card', 'Card'), ('chart', 'Chart'), ('table', 'Table'), ('text', 'Text')], default='table', max_length=20),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='report_type',
            field=models.CharField(choices=[('card', 'Card'), ('chart', 'Chart'), ('table', 'Table'), ('text', 'Text')], default='table', max_length=20),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='definition',
            field=models.JSONField(blank=True, default=toto.workflows.models.default_report_definition, help_text="JSON report syntax for one visualization. Use {type:'chart', data:{path:'series'}, x:'label', y:'value'} or {type:'table', data:{path:'rows'}, columns:[...]}. Values can use {'path': 'metrics.total'}.", validators=[toto.workflows.models.validate_report_definition]),
        ),
    ]
