# Generated by Django 4.2.23 on 2026-05-21 19:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0007_report_report_type_reporttemplate_report_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflownode',
            name='node_type',
            field=models.CharField(choices=[('trigger', 'Trigger'), ('lambda', 'Lambda'), ('human', 'Human'), ('split', 'Split'), ('join', 'Join'), ('connector', 'Connector'), ('report', 'Report')], max_length=20),
        ),
        migrations.CreateModel(
            name='WorkflowTriggerInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=120)),
                ('label', models.CharField(max_length=180)),
                ('input_type', models.CharField(choices=[('int', 'Integer'), ('float', 'Float'), ('text', 'Text'), ('file', 'File'), ('datetime', 'Datetime')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('help_text', models.TextField(blank=True)),
                ('allow_multiple_files', models.BooleanField(default=False)),
                ('accepted_file_types', models.CharField(blank=True, help_text='Comma-separated MIME types or extensions, e.g. application/pdf,.txt,image/*.', max_length=255)),
                ('max_file_count', models.PositiveIntegerField(blank=True, null=True)),
                ('max_file_size', models.PositiveIntegerField(blank=True, help_text='Maximum size per file in bytes.', null=True)),
                ('trigger_node', models.ForeignKey(limit_choices_to={'node_type': 'trigger'}, on_delete=django.db.models.deletion.CASCADE, related_name='trigger_inputs', to='workflows.workflownode')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRunFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_key', models.CharField(max_length=120)),
                ('file', models.FileField(upload_to='workflow-runs/%Y/%m/%d/')),
                ('original_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('trigger_input', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_files', to='workflows.workflowtriggerinput')),
                ('workflow_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='workflows.workflowrun')),
            ],
            options={
                'ordering': ['input_key', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='workflowtriggerinput',
            constraint=models.UniqueConstraint(fields=('trigger_node', 'key'), name='unique_workflow_trigger_input_key'),
        ),
    ]
