# Generated by Django 4.2.23 on 2026-06-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraphSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Graph Sync',
                'verbose_name_plural': 'Graph Sync',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GraphProjectionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('applying', 'Applying…'), ('applied', 'Applied'), ('failed', 'Failed')], db_index=True, default='ready', max_length=16)),
                ('scope', models.JSONField(blank=True, default=dict)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('diff', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Graph Projection Plan',
                'verbose_name_plural': 'Graph Projection Plans',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GraphSyncSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('interval_minutes', models.PositiveIntegerField(default=30, help_text='How often to run the full graph sync (minutes).')),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='idle', max_length=16)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Graph Sync Schedule',
                'verbose_name_plural': 'Graph Sync Schedule',
            },
        ),
        migrations.CreateModel(
            name='GraphChangeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('upsert_node', 'Upsert node'), ('delete_node', 'Delete node'), ('resync_links', 'Resync outgoing links'), ('resync_link_source', 'Resync one link source'), ('resync_link_full', 'Resync full link'), ('upsert_junction', 'Upsert junction relationship'), ('delete_junction', 'Delete junction relationship')], max_length=32)),
                ('graph_label', models.CharField(blank=True, max_length=128)),
                ('model_path', models.CharField(blank=True, max_length=255)),
                ('object_uuid', models.CharField(blank=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Graph Change Event',
                'verbose_name_plural': 'Graph Change Events',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='sql_neo4j_s_status_14b16b_idx'), models.Index(fields=['graph_label', 'object_uuid'], name='sql_neo4j_s_graph_l_021907_idx')],
            },
        ),
    ]
