# Generated by Django 4.2.23 on 2026-05-15 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatexWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latex_workspaces', to='vault.bucket')),
            ],
            options={
                'unique_together': {('bucket', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='LatexFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('tex', 'TeX source'), ('sty', 'Style file'), ('bib', 'BibTeX database'), ('pdf', 'Compiled PDF'), ('other', 'Other text')], default='tex', max_length=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('vault_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texlab_entries', to='vault.vaultfile')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='texlab.latexworkspace')),
            ],
            options={
                'unique_together': {('workspace', 'vault_file')},
            },
        ),
    ]
