# Generated by Django 4.2.23 on 2026-05-25 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vault', '0001_initial'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatexWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latex_workspaces', to='vault.bucket')),
            ],
            options={
                'unique_together': {('bucket', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='LatexFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('tex', 'TeX source'), ('sty', 'Style file'), ('bib', 'BibTeX database'), ('pdf', 'Compiled PDF'), ('other', 'Other text')], default='tex', max_length=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('vault_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texlab_entries', to='vault.vaultfile')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='texlab.latexworkspace')),
            ],
            options={
                'unique_together': {('workspace', 'vault_file')},
            },
        ),
        migrations.CreateModel(
            name='CompileRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('log', models.TextField(blank=True)),
                ('pdf_url', models.CharField(blank=True, max_length=500)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('latex_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compile_runs', to='texlab.latexfile')),
                ('workflow_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compile_runs', to='workflows.workflowrun')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compile_runs', to='texlab.latexworkspace')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
