# Generated by Django 4.2.23 on 2026-05-23 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0012_backfill_workflownode_task_name'),
        ('texlab', '0002_compilerun'),
    ]

    operations = [
        migrations.AddField(
            model_name='compilerun',
            name='workflow_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compile_runs', to='workflows.workflowrun'),
        ),
    ]
