"""The packet layer under Smokescreen: what a Capsule can reach at all.

TWO LAYERS, AND NEITHER IS THE OTHER'S BACKUP. Smokescreen decides
DESTINATIONS — it resolves a CONNECT and refuses a host that is not on the
allowlist. This module decides PACKETS — from the egress network, the proxy's
address and port are the only thing routable, so a process that declines to use
the proxy and opens its own socket reaches nothing. Either alone is weak in a
different direction:

* a proxy with no packet filter is advisory. Nothing compels a workload to
  honour ``HTTPS_PROXY``, and a script that opens ``socket(AF_INET)`` is on the
  internet;
* a packet filter with no proxy cannot tell ``pypi.org`` from an exfiltration
  endpoint that answers on 443. Addresses are not identities.

WHY OUR OWN TABLE. Docker writes its rules into ``filter``/``nat`` through the
iptables-nft shim and rewrites them whenever a network or container changes. A
rule added to Docker's chains is a rule Docker may remove. ``inet anastasia`` is
a separate table at an earlier hook priority: Docker does not know it exists and
will not touch it, and it is evaluated before Docker's ``FORWARD`` rules get
their say.

**POLICY IS ACCEPT AND THAT IS DELIBERATE.** A ``policy drop`` on a forward hook
drops every forwarded packet on the host — every other container, every other
stack — the moment this table loads. What is wanted is narrow: packets FROM the
egress subnet are dropped unless they are going to the proxy. Everything not
from that subnet is none of this table's business, and a default that had an
opinion about it would be a host-wide outage waiting for a typo.

FAIL CLOSED means something specific here, and it is not "drop everything". The
executor cannot make the kernel filter packets if ``nft`` is missing or the
table will not load; what it can do is REFUSE TO MOUNT a Capsule that asked for
egress. That is the closed direction — no capsule gets a NIC it cannot have
filtered — and it is what `verify` is for.
"""

from __future__ import annotations

import logging
import shutil
import subprocess

log = logging.getLogger("toto.anastasia.executor.netfilter")

#: The table this module owns, in full. Nothing else writes to it, and
#: `ensure` replaces it wholesale rather than appending — an append-only
#: ruleset accumulates a second copy of every rule on each restart, and the
#: duplicates are invisible until somebody reads the counters.
TABLE = "anastasia"


class NetfilterError(Exception):
    """The ruleset could not be established or could not be proven."""


def _nft(*args: str, check: bool = True) -> subprocess.CompletedProcess:
    binary = shutil.which("nft")
    if not binary:
        raise NetfilterError(
            "nft is not installed, so egress cannot be filtered and no Capsule "
            "may be given a network. Install nftables, or turn egress off.")
    proc = subprocess.run([binary, *args], capture_output=True, text=True,
                          check=False)
    if check and proc.returncode != 0:
        raise NetfilterError(
            f"nft {' '.join(args)} failed: {proc.stderr.strip()[-400:]}")
    return proc


def ruleset(subnet: str, proxy_ip: str, proxy_port: int) -> str:
    """The whole table, as one atomic `nft -f` document.

    Written as text and applied in one shot because nftables applies a file as
    a TRANSACTION: either the whole table is replaced or nothing changes. A
    sequence of `nft add rule` calls has a window in the middle where the
    accept rule exists and the drop does not, and that window is an open
    Capsule.
    """
    return f"""\
# Generated by toto.anastasia.executor.netfilter — do not edit by hand.
# Replaced wholesale every time the executor starts.
table inet {TABLE} {{
    chain forward {{
        # priority -10: before Docker's FORWARD rules (filter, 0), so a drop
        # here is final. policy accept: this table judges the egress subnet
        # and nothing else — see the module docstring.
        type filter hook forward priority -10; policy accept;

        # Return traffic for flows the proxy itself opened. Without this the
        # proxy's own answers are dropped on the way back in.
        ct state established,related accept

        # THE ONE THING A CAPSULE MAY REACH. Not the subnet, not the port
        # range — one address, one port, TCP only.
        ip saddr {subnet} ip daddr {proxy_ip} tcp dport {proxy_port} accept

        # Everything else that starts in the egress subnet. This is the rule
        # that makes the proxy compulsory rather than advisory: DNS to the
        # world, the cloud metadata address, another stack's postgres, and a
        # socket opened directly to an IP all land here.
        ip saddr {subnet} drop
        ip6 saddr ::/0 iif "br-*" drop
    }}
}}

# CAPSULE-TO-CAPSULE is a separate table because it is a separate problem.
# Two containers on one bridge in one subnet talk at layer 2: the frames are
# BRIDGED, never routed, so they do not pass the forward hook above and the
# drop there never sees them. Docker's own `enable_icc=false` would stop it
# and cannot be used — the proxy is a container on that bridge too, so
# disabling inter-container traffic would disable the proxy.
table bridge {TABLE} {{
    chain forward {{
        type filter hook forward priority -200; policy accept;

        # To or from the proxy: allowed, this is the whole point of the bridge.
        meta protocol ip ip daddr {proxy_ip} accept
        meta protocol ip ip saddr {proxy_ip} accept

        # Capsule to capsule on the same bridge: refused. Nothing in a Capsule
        # has any business reaching another one, and they share a subnet only
        # because they share a route to the proxy.
        meta protocol ip ip saddr {subnet} ip daddr {subnet} drop
    }}
}}
"""


def ensure(subnet: str, proxy_ip: str, proxy_port: int) -> None:
    """Install the ruleset, replacing any earlier copy of it.

    Both tables are deleted first and ignored if absent: `nft -f` with a
    `table` block ADDS to an existing table rather than replacing it, so
    without the delete every executor restart appends a second identical
    chain.
    """
    for family in ("inet", "bridge"):
        _nft("delete", "table", family, TABLE, check=False)
    document = ruleset(subnet, proxy_ip, proxy_port)
    binary = shutil.which("nft")
    if not binary:
        raise NetfilterError(
            "nft is not installed, so egress cannot be filtered and no Capsule "
            "may be given a network. Install nftables, or turn egress off.")
    proc = subprocess.run([binary, "-f", "-"], input=document,
                          capture_output=True, text=True, check=False)
    if proc.returncode != 0:
        raise NetfilterError(
            f"the egress ruleset would not load: {proc.stderr.strip()[-400:]}")
    log.info("anastasia: egress filtered — %s may reach %s:%s and nothing else",
             subnet, proxy_ip, proxy_port)


def verify(subnet: str, proxy_ip: str, proxy_port: int) -> None:
    """Prove the rules are actually in the kernel. Raises if they are not.

    READ BACK FROM THE KERNEL, never remembered from `ensure`. The failure this
    guards is not "we forgot to call ensure" — it is the ruleset being flushed
    afterwards by something else on the host, which is exactly what a
    `systemctl restart nftables` or an operator's `nft flush ruleset` does. A
    Capsule with a NIC and no filter is the one state this whole module exists
    to prevent, so the check is against the live table.
    """
    listed = _nft("list", "table", "inet", TABLE).stdout
    wanted = (
        f"ip saddr {subnet} ip daddr {proxy_ip} tcp dport {proxy_port} accept",
        f"ip saddr {subnet} drop",
    )
    for rule in wanted:
        # Whitespace-normalised: nft echoes its own formatting, which is not
        # byte-identical to what was written.
        if " ".join(rule.split()) not in " ".join(listed.split()):
            raise NetfilterError(
                "the egress ruleset is not in the kernel as written "
                f"(missing: {rule}). Refusing to give a Capsule a network it "
                "cannot have filtered.")
    bridged = _nft("list", "table", "bridge", TABLE).stdout
    if f"ip saddr {subnet} ip daddr {subnet} drop" not in " ".join(bridged.split()):
        raise NetfilterError(
            "capsule-to-capsule traffic is not being dropped. Refusing to give "
            "a Capsule a network on a bridge it could reach a neighbour over.")


def available() -> bool:
    """Whether this host could filter at all. For preflight, not for gating."""
    return shutil.which("nft") is not None
