# Generated by Django 4.2.23 on 2026-05-11 21:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('country_name', models.CharField(blank=True, max_length=2, verbose_name='Country')),
                ('state_or_province_name', models.CharField(blank=True, max_length=128, verbose_name='State/Province')),
                ('locality_name', models.CharField(blank=True, max_length=128, verbose_name='Locality')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='Street')),
                ('building', models.CharField(blank=True, max_length=64, verbose_name='Building Number')),
                ('apartment', models.CharField(blank=True, max_length=64, null=True, verbose_name='Apartment Number')),
                ('geometry', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MapLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, help_text='Examples: °C, %, mm, ppm, people/km²', max_length=32)),
                ('min_value', models.FloatField(blank=True, help_text='Optional display minimum for color scaling.', null=True)),
                ('max_value', models.FloatField(blank=True, help_text='Optional display maximum for color scaling.', null=True)),
                ('style', models.JSONField(blank=True, default=dict, help_text='Frontend style config: color scale, opacity, legend, etc.')),
                ('inverted_importance', models.BooleanField(default=False, help_text='Invert value importance before color scaling.')),
                ('half_range', models.BooleanField(default=False, help_text='Use only the low-to-mid half of the color scale.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MapLayerPolygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(help_text='Must be one continuous polygon.', srid=4326)),
                ('center', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Stored center point used for layer labels and markers.', null=True, srid=4326)),
                ('value', models.FloatField()),
                ('properties', models.JSONField(blank=True, default=dict, help_text='Optional metadata for frontend/domain use.')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('geometry', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('sequence', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RouteChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('info', models.TextField(blank=True, help_text='Additional information about the travel')),
                ('score', models.PositiveSmallIntegerField(blank=True, help_text='Travel score from 1 to 5', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When this travel was reviewed or scored', null=True)),
                ('starts_at', models.DateTimeField(help_text='Travel start date and time')),
                ('ends_at', models.DateTimeField(help_text='Travel end date and time')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('territory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='locations.territory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('visited_at', models.DateTimeField(blank=True, help_text='When the visit happened', null=True)),
                ('score', models.PositiveSmallIntegerField(blank=True, help_text='Score from 1 to 5', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When this visit review was submitted', null=True)),
                ('review', models.TextField(blank=True, help_text='Optional review text', null=True)),
                ('location', models.ForeignKey(blank=True, help_text='Location that was visited', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='locations.address')),
            ],
        ),
    ]
