# Generated by Django 4.2.23 on 2026-05-15 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('socialhub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplayer',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Person who owns or manages this map layer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_map_layers', to='socialhub.person'),
        ),
        migrations.AddIndex(
            model_name='maplayerpolygon',
            index=models.Index(fields=['layer'], name='locations_m_layer_i_ecb370_idx'),
        ),
    ]
