# Generated by Django 4.2.23 on 2026-05-09 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_maplayer_maplayerpolygon'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='maplayerpolygon',
            new_name='locations_m_layer_i_ecb370_idx',
            old_name='locations_m_layer__7c60f5_idx',
        ),
    ]
