# Generated by Django 4.2.23 on 2026-05-09 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialhub', '0005_alter_person_communities'),
        ('locations', '0009_visit_travel_visit_visit_score_between_1_and_5'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplayer',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Person who owns or manages this map layer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_map_layers', to='socialhub.person'),
        ),
    ]
