# Generated by Django 4.2.23 on 2026-05-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_maplayer_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When this travel was reviewed or scored', null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Travel score from 1 to 5', null=True),
        ),
        migrations.AddConstraint(
            model_name='travel',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('score__gte', 1), ('score__lte', 5)), ('score__isnull', True), _connector='OR'), name='travel_score_between_1_and_5'),
        ),
    ]
