# Generated by Django 4.2.23 on 2026-05-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0011_travel_reviewed_at_travel_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When this visit review was submitted', null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='visited_at',
            field=models.DateTimeField(blank=True, help_text='When the visit happened', null=True),
        ),
    ]
