# Generated by Django 4.2.23 on 2026-05-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0012_visit_reviewed_at_visit_visited_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='building',
            field=models.CharField(blank=True, max_length=64, verbose_name='Building Number'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country_name',
            field=models.CharField(blank=True, max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='locality_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Locality'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state_or_province_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='State/Province'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=255, verbose_name='Street'),
        ),
    ]
