# Generated by Django 4.2.23 on 2026-03-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appname', models.CharField(max_length=100, unique=True)),
                ('filepath', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
