# Generated by Django 4.2.23 on 2026-09-23 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0008_faucetrun'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManaPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('security', 'Security'), ('compute', 'Compute'), ('storage', 'Storage')], max_length=16, unique=True)),
                ('regen_per_hour', models.DecimalField(decimal_places=18, max_digits=30)),
                ('max_pool', models.DecimalField(decimal_places=18, max_digits=30)),
                ('chosen_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='assets.asset')),
                ('chosen_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mana pool',
                'ordering': ('role',),
            },
        ),
        migrations.CreateModel(
            name='ManaGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('security', 'Security'), ('compute', 'Compute'), ('storage', 'Storage')], max_length=16)),
                ('key', models.CharField(max_length=64)),
                ('amount_base_units', models.BigIntegerField(default=0)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mana_grants', to='assets.ledgertransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mana_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['role', 'key'], name='mana_managr_role_dec813_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='managrant',
            constraint=models.UniqueConstraint(fields=('user', 'role', 'key'), name='mana_one_grant_per_user_role_key'),
        ),
    ]
