# Generated by Django 4.2.23 on 2025-11-11 21:12

import community.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=2, verbose_name='Country')),
                ('state_or_province_name', models.CharField(max_length=128, verbose_name='State/Province')),
                ('locality_name', models.CharField(max_length=128, verbose_name='Locality')),
                ('street', models.CharField(max_length=255, verbose_name='Street')),
                ('building', models.CharField(max_length=64, verbose_name='Building Number')),
                ('apartment', models.CharField(blank=True, max_length=64, null=True, verbose_name='Apartment Number')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('code', models.CharField(default=community.models.generate_code, max_length=10, unique=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('endorsed', 'Endorsed'), ('invited', 'Invited'), ('rejected', 'Rejected')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
