# Generated by Django 4.2.23 on 2025-09-27 11:24

import community.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=2, verbose_name='Country')),
                ('state_or_province_name', models.CharField(max_length=128, verbose_name='State/Province')),
                ('locality_name', models.CharField(max_length=128, verbose_name='Locality')),
                ('street', models.CharField(max_length=255, verbose_name='Street')),
                ('building', models.CharField(max_length=64, verbose_name='Building Number')),
                ('apartment', models.CharField(blank=True, max_length=64, null=True, verbose_name='Apartment Number')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the branch', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, help_text='Branch address', null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.address')),
            ],
            options={
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='CommunityMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=150)),
                ('bio', models.TextField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('joined_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier for the member', unique=True)),
                ('membership', models.ManyToManyField(help_text='Branches this member belongs to', related_name='members', to='community.branch')),
                ('patron', models.ForeignKey(blank=True, help_text='Another member who acts as a patron or mentor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentees', to='community.communitymember')),
                ('user', models.OneToOneField(help_text='Linked Django user account', on_delete=django.db.models.deletion.CASCADE, related_name='community_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('code', models.CharField(default=community.models.generate_code, help_text='Unique application code', max_length=10, unique=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('endorsed', 'Endorsed'), ('invited', 'Invited'), ('rejected', 'Rejected')], default='pending', help_text='Current status of the application', max_length=20)),
                ('branch', models.ForeignKey(help_text='Branch this application is targeting', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='community.branch')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text='Optional message from the referrer about the applicant')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', help_text='Status of the referral', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(help_text='Membership application this reference request is linked to', on_delete=django.db.models.deletion.CASCADE, related_name='reference_requests', to='community.membershipapplication')),
                ('referrer', models.ForeignKey(help_text='Community member who is endorsing the applicant', on_delete=django.db.models.deletion.CASCADE, related_name='sent_references', to='community.communitymember')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Main text content of the post')),
                ('image', models.ImageField(blank=True, help_text='Optional image attachment', null=True, upload_to='posts/')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('members', 'Members Only'), ('branch', 'Branch Only')], default='members', help_text='Who can see this post', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(help_text='Community member who created the post', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='community.communitymember')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Legal or brand name of the company', max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier for the company', unique=True)),
                ('established_year', models.IntegerField(blank=True, help_text='Year the company was founded', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.address')),
                ('head', models.ForeignKey(blank=True, help_text='Community member who leads the company', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_companies', to='community.communitymember')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(help_text='Main company this branch belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='community.company'),
        ),
        migrations.AddField(
            model_name='branch',
            name='head',
            field=models.ForeignKey(blank=True, help_text='Community member who leads this branch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_branches', to='community.communitymember'),
        ),
    ]
