# Generated by Django 4.2.23 on 2025-12-13 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oya', '0012_address'),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oya.address'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
