# Generated by Django 4.2.23 on 2025-11-11 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ravioli', '0001_initial'),
        ('federal', '0003_federatedidentity_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialEntity',
            fields=[
                ('subject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ravioli.subject')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('ravioli.subject',),
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('socialentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='community.socialentity')),
                ('name', models.CharField(help_text='Name of the community or organization', max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier', unique=True)),
                ('established_year', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('federation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communities', to='federal.federation')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('community.socialentity',),
        ),
        migrations.CreateModel(
            name='CommunityMember',
            fields=[
                ('socialentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='community.socialentity')),
                ('display_name', models.CharField(max_length=150)),
                ('bio', models.TextField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('joined_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('communities', models.ManyToManyField(related_name='members', to='community.community')),
                ('patron', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentees', to='community.communitymember')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='community_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('community.socialentity',),
        ),
        migrations.AddField(
            model_name='referencerequest',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_requests', to='community.membershipapplication'),
        ),
        migrations.AddField(
            model_name='referencerequest',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_references', to='community.communitymember'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='community.community'),
        ),
        migrations.AddField(
            model_name='community',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_communities', to='community.communitymember'),
        ),
        migrations.AddField(
            model_name='community',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.address'),
        ),
    ]
