# Generated by Django 4.2.23 on 2025-12-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymember',
            name='communities',
            field=models.ManyToManyField(db_comment='member_of', related_name='members', to='community.community'),
        ),
    ]
