# Generated by Django 4.2.23 on 2025-12-27 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='communitymember',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'base_manager_name': 'objects'},
        ),
    ]
