# Generated by Django 4.2.23 on 2025-09-09 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='branch',
        ),
    ]
