# Generated by Django 4.2.23 on 2026-01-17 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('community', '0001_initial'),
        ('federal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='federation',
            field=models.ForeignKey(blank=True, db_comment='part_of_federation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communities', to='federal.federation'),
        ),
        migrations.AddField(
            model_name='community',
            name='head',
            field=models.ForeignKey(blank=True, db_comment='headed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_communities', to='community.communitymember'),
        ),
        migrations.AddField(
            model_name='community',
            name='location',
            field=models.ForeignKey(blank=True, db_comment='located_at', null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.address'),
        ),
    ]
