# Generated by Django 4.2.23 on 2025-12-23 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0001_initial'),
        ('locations', '0001_initial'),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='federation',
            field=models.ForeignKey(blank=True, db_comment='part_of_federation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communities', to='federal.federation'),
        ),
        migrations.AlterField(
            model_name='community',
            name='head',
            field=models.ForeignKey(blank=True, db_comment='headed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_communities', to='community.communitymember'),
        ),
        migrations.AlterField(
            model_name='community',
            name='location',
            field=models.ForeignKey(blank=True, db_comment='located_at', null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.address'),
        ),
        migrations.AlterField(
            model_name='communitymember',
            name='address',
            field=models.ForeignKey(blank=True, db_comment='resides_at', help_text='Optional address for this community member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='locations.address'),
        ),
        migrations.AlterField(
            model_name='communitymember',
            name='patron',
            field=models.ForeignKey(blank=True, db_comment='mentored_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentees', to='community.communitymember'),
        ),
    ]
