# Generated by Django 4.2.23 on 2025-09-01 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='head',
            field=models.ForeignKey(blank=True, help_text='Community member who leads this branch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_branches', to='community.communitymember'),
        ),
        migrations.AddField(
            model_name='communitymember',
            name='patron',
            field=models.ForeignKey(blank=True, help_text='Another member who acts as a patron or mentor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentees', to='community.communitymember'),
        ),
        migrations.AddField(
            model_name='company',
            name='head',
            field=models.ForeignKey(blank=True, help_text='Community member who leads the company', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_companies', to='community.communitymember'),
        ),
    ]
