# Generated by Django 4.2.23 on 2025-11-07 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_delete_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Community',
        ),
    ]
