# Generated by Django 4.2.23 on 2025-12-13 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_address_alter_pathfeature_id_alter_pointfeature_id_and_more'),
        ('community', '0002_alter_community_location_delete_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.address'),
        ),
    ]
