# Generated by Django 4.2.23 on 2025-09-09 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_remove_post_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymember',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier for the member', unique=True),
        ),
    ]
