# Generated by Django 4.2.23 on 2026-01-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_communitymember_date_of_birth_communitymember_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='org_type',
            field=models.CharField(choices=[('guild', 'Guild'), ('company', 'Company'), ('non_profit', 'Non-Profit'), ('family', 'Family'), ('other', 'Other')], default='other', help_text='Type of organization', max_length=20),
        ),
    ]
