# Generated by Django 4.2.23 on 2025-11-11 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0002_initial'),
        ('community', '0002_community_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='federation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communities', to='federal.federation'),
        ),
    ]
