# Generated by Django 4.2.23 on 2025-11-07 21:29

import community.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0003_rename_company_community'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitymember',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='membershipapplication',
            name='branch',
        ),
        migrations.AddField(
            model_name='communitymember',
            name='communities',
            field=models.ManyToManyField(related_name='members', to='community.community'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='community',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='community.community'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='community',
            name='established_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_communities', to='community.communitymember'),
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(help_text='Name of the community or organization', max_length=255),
        ),
        migrations.AlterField(
            model_name='community',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier', unique=True),
        ),
        migrations.AlterField(
            model_name='communitymember',
            name='patron',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentees', to='community.communitymember'),
        ),
        migrations.AlterField(
            model_name='communitymember',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='communitymember',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='community_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='code',
            field=models.CharField(default=community.models.generate_code, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('endorsed', 'Endorsed'), ('invited', 'Invited'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='referencerequest',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_requests', to='community.membershipapplication'),
        ),
        migrations.AlterField(
            model_name='referencerequest',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='referencerequest',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_references', to='community.communitymember'),
        ),
        migrations.AlterField(
            model_name='referencerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
