# Generated by Django 4.2.23 on 2025-11-11 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_community_federation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialentity',
            name='polymorphic_ctype',
        ),
    ]
