# Generated by Django 4.2.23 on 2026-01-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_community_org_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='is_autonomous',
            field=models.BooleanField(default=False, help_text='Marks this community as self-governing, with its own internal leadership and rules.'),
        ),
    ]
