# Generated by Django 4.2.23 on 2025-12-13 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_address_location'),
        ('community', '0003_alter_community_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymember',
            name='address',
            field=models.ForeignKey(blank=True, help_text='Optional address for this community member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='locations.address'),
        ),
    ]
