# Generated by Django 4.2.23 on 2026-10-01 05:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vault', '0001_initial'),
        ('people', '0002_initial'),
        ('locations', '0003_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ('claimed_at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsensusPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('required_reviews', models.PositiveSmallIntegerField(default=1, help_text="How many reviews resolve a submission (the M in 'N of M').")),
                ('required_accepts', models.PositiveSmallIntegerField(default=1, help_text="Accepts needed to resolve as accepted (the N in 'N of M').")),
                ('reject_threshold', models.PositiveSmallIntegerField(default=1, help_text='Rejects that resolve it as rejected.')),
                ('changes_threshold', models.PositiveSmallIntegerField(blank=True, help_text='Change requests that resolve it. Falls back to reject_threshold.', null=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'consensus policies',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('urgency', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2)),
                ('impact', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2)),
                ('visibility', models.CharField(choices=[('project', 'Project'), ('private', 'Private')], db_index=True, default='project', max_length=10)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('calendar_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kanban_missions', to='events.scheduledevent')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='kanban.campaign')),
                ('consensus_policy', models.ForeignKey(blank=True, help_text="Overrides the campaign's review rule. Blank means no review gate.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='kanban.consensuspolicy')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='locations.address')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.person')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='locations.route')),
                ('visible_to', models.ManyToManyField(blank=True, help_text='People who can always see this mission when it is private.', related_name='visible_missions', to='people.person')),
                ('zone', models.ForeignKey(blank=True, help_text="Overrides the campaign's zone; must lie inside it.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='locations.zone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Practitioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('role', models.CharField(choices=[('contributor', 'Contributor'), ('reviewer', 'Reviewer'), ('auditor', 'Auditor'), ('manager', 'Manager'), ('observer', 'Observer')], default='contributor', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('work_description', models.TextField(blank=True, help_text="Free-text description of this practitioner's role or services in the project.")),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practitioner_profiles', to='people.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('auditors', models.ManyToManyField(blank=True, help_text='Practitioners who may move tasks between states.', related_name='audited_projects', to='kanban.practitioner')),
                ('project_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('verdict', models.CharField(choices=[('accept', 'Accept'), ('reject', 'Reject'), ('request_changes', 'Request changes')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_reviews', to='people.person')),
            ],
            options={
                'ordering': ('created_at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('withdrawn', 'Withdrawn')], db_index=True, default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('changes_requested', 'Changes requested')], db_index=True, default='pending', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_submissions', to='people.person')),
                ('supersedes', models.ForeignKey(blank=True, help_text='The submission this one corrects. Never edit in place.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='kanban.submission')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('todo', 'To do'), ('in_progress', 'In progress'), ('done', 'Done')], db_index=True, default='todo', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('weight', models.IntegerField(choices=[(1, 'Tiny'), (2, 'Small'), (3, 'Medium'), (5, 'Big'), (8, 'Large')], default=1)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='kanban.practitioner')),
                ('calendar_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kanban_tasks', to='events.scheduledevent')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kanban_tasks', to='locations.address')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='kanban.mission')),
                ('reviewer', models.ForeignKey(blank=True, help_text='Optional reviewer who signs off the task before it is completed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_tasks', to='kanban.practitioner')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='kanban.sprint')),
            ],
        ),
        migrations.CreateModel(
            name='TaskReviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_reviewable_tasks', to='people.person')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligible_reviewers', to='kanban.task')),
            ],
            options={
                'ordering': ('created_at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='TaskRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('relation_type', models.CharField(choices=[('blocks', 'blocks'), ('precedes', 'precedes'), ('relates', 'relates to'), ('duplicates', 'duplicates'), ('tests', 'tests'), ('implements', 'implements')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='kanban.practitioner')),
                ('from_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='kanban.task')),
                ('to_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='kanban.task')),
            ],
            options={
                'ordering': ('relation_type', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='kanban.submission')),
                ('vault_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_submission_files', to='vault.vaultfile')),
            ],
            options={
                'ordering': ('created_at', 'pk'),
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='kanban.task'),
        ),
        migrations.CreateModel(
            name='RewardPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('trigger', models.CharField(choices=[('submission_accepted', 'Submission accepted'), ('review_resolved', 'Review resolved'), ('accuracy_bonus', 'Accuracy bonus')], db_index=True, max_length=32)),
                ('asset_code', models.CharField(help_text="The asset's symbol, e.g. GEM. A SYMBOL, never a foreign key.", max_length=32)),
                ('amount_base_units', models.BigIntegerField(help_text="Amount in the asset's smallest unit. Integers; no floats, ever.")),
                ('funding_account_code', models.CharField(blank=True, help_text='Opaque account identifier the reward backend resolves.', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reward_policies', to='kanban.campaign')),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reward_policies', to='kanban.mission')),
            ],
            options={
                'verbose_name_plural': 'reward policies',
                'ordering': ('trigger', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='RewardGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('asset_code', models.CharField(max_length=32)),
                ('amount_base_units', models.BigIntegerField()),
                ('funding_account_code', models.CharField(blank=True, max_length=100)),
                ('reference', models.CharField(max_length=200, unique=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('settled', 'Settled'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=16)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='kanban.rewardpolicy')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_reward_grants', to='people.person')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reward_grants', to='kanban.review')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reward_grants', to='kanban.submission')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.AddField(
            model_name='review',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='kanban.submission'),
        ),
        migrations.CreateModel(
            name='ProjectCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_per_day', models.DecimalField(decimal_places=2, help_text='Number of hours per day committed to this project.', max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='kanban.practitioner')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='kanban.project')),
            ],
        ),
        migrations.CreateModel(
            name='MissionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('label', models.CharField(blank=True, help_text="Display name override; falls back to the file's title.", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='people.person')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='kanban.mission')),
                ('vault_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_attachments', to='vault.vaultfile')),
            ],
            options={
                'ordering': ('created_at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='DocumentationPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_manual', models.BooleanField(default=False, help_text='If true, this page is an instruction / how-to manual.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('mission', models.ForeignKey(blank=True, help_text='Optional: the mission this page is about.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wiki_pages', to='kanban.mission')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='kanban.documentationpage')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wiki_pages', to='kanban.project')),
                ('vault_file', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kanban_wiki_pages', to='vault.vaultfile')),
            ],
            options={
                'verbose_name': 'Documentation Page',
                'verbose_name_plural': 'Documentation Pages',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddConstraint(
            model_name='consensuspolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='kanban_one_default_consensus_policy'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='consensus_policy',
            field=models.ForeignKey(blank=True, help_text="Default review rule for this campaign's missions.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='kanban.consensuspolicy'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.person'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='kanban.project'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='locations.zone'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_assignments', to='people.person'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='kanban.task'),
        ),
        migrations.AddConstraint(
            model_name='taskreviewer',
            constraint=models.UniqueConstraint(fields=('task', 'person'), name='kanban_unique_task_reviewer'),
        ),
        migrations.AddIndex(
            model_name='taskrelation',
            index=models.Index(fields=['to_task', 'relation_type'], name='taskrel_to_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskrelation',
            constraint=models.UniqueConstraint(fields=('from_task', 'to_task', 'relation_type'), name='unique_task_relation'),
        ),
        migrations.AddConstraint(
            model_name='taskrelation',
            constraint=models.CheckConstraint(check=models.Q(('from_task', models.F('to_task')), _negated=True), name='task_relation_not_self'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['mission', 'status'], name='kanban_task_mission_status'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('completed_at__isnull', False), ('status', 'done')), models.Q(models.Q(('status', 'done'), _negated=True), ('completed_at__isnull', True)), _connector='OR'), name='kanban_task_completed_at_matches_status'),
        ),
        migrations.AddConstraint(
            model_name='submissionfile',
            constraint=models.UniqueConstraint(fields=('submission', 'vault_file'), name='kanban_unique_submission_file'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['task', 'state'], name='kanban_sub_task_state'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('state', 'draft'), ('submitted_at__isnull', True)), models.Q(('state', 'submitted'), ('submitted_at__isnull', False)), ('state', 'withdrawn'), _connector='OR'), name='kanban_submission_state_matches_submitted_at'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('resolution', 'pending'), ('resolved_at__isnull', True)), models.Q(models.Q(('resolution', 'pending'), _negated=True), ('resolved_at__isnull', False)), _connector='OR'), name='kanban_submission_resolution_matches_resolved_at'),
        ),
        migrations.AddConstraint(
            model_name='rewardpolicy',
            constraint=models.CheckConstraint(check=models.Q(('mission__isnull', False), ('campaign__isnull', False), _connector='OR'), name='kanban_reward_policy_has_a_scope'),
        ),
        migrations.AddConstraint(
            model_name='rewardpolicy',
            constraint=models.CheckConstraint(check=models.Q(('amount_base_units__gt', 0)), name='kanban_reward_policy_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('submission', 'reviewer'), name='kanban_one_review_per_reviewer'),
        ),
        migrations.AddConstraint(
            model_name='projectcommitment',
            constraint=models.UniqueConstraint(fields=('practitioner', 'project'), name='unique_commitment_per_project'),
        ),
        migrations.AddConstraint(
            model_name='missionattachment',
            constraint=models.UniqueConstraint(fields=('mission', 'vault_file'), name='unique_mission_attachment'),
        ),
        migrations.AddConstraint(
            model_name='documentationpage',
            constraint=models.UniqueConstraint(fields=('project', 'slug'), name='kanban_docpage_slug_per_project'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(condition=models.Q(('released_at__isnull', True)), fields=('task', 'person'), name='kanban_one_live_assignment_per_person'),
        ),
    ]
