# Generated by Django 4.2.23 on 2026-06-04 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kanban', '0001_initial'),
        ('people', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.person'),
        ),
        migrations.AddField(
            model_name='practitioner',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practitioner_profiles', to='people.person'),
        ),
        migrations.AddField(
            model_name='mission',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='kanban.campaign'),
        ),
        migrations.AddField(
            model_name='mission',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='locations.address'),
        ),
        migrations.AddField(
            model_name='mission',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.person'),
        ),
        migrations.AddField(
            model_name='mission',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='locations.route'),
        ),
        migrations.AddField(
            model_name='documentationsection',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='people.person'),
        ),
        migrations.AddField(
            model_name='documentationsection',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='kanban.documentationpage'),
        ),
        migrations.AddField(
            model_name='documentationpage',
            name='mission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documentation_page', to='kanban.mission'),
        ),
        migrations.AddField(
            model_name='column',
            name='auditors',
            field=models.ManyToManyField(blank=True, help_text='Practitioners who can move tasks into this column.', related_name='audited_columns', to='kanban.practitioner'),
        ),
        migrations.AddField(
            model_name='column',
            name='project',
            field=models.ForeignKey(db_column='belongs_to_project', on_delete=django.db.models.deletion.CASCADE, to='kanban.project'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.person'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='kanban.project'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='locations.zone'),
        ),
        migrations.AddConstraint(
            model_name='projectcommitment',
            constraint=models.UniqueConstraint(fields=('practitioner', 'project'), name='unique_commitment_per_project'),
        ),
    ]
