# Generated by Django 4.2.23 on 2026-08-22 15:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_deprecate_is_federal_agent'),
        ('vault', '0022_sealed_credentials'),
        ('kanban', '0007_remove_mission_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ('claimed_at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='ConsensusPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('required_reviews', models.PositiveSmallIntegerField(default=1, help_text="How many reviews resolve a submission (the M in 'N of M').")),
                ('required_accepts', models.PositiveSmallIntegerField(default=1, help_text="Accepts needed to resolve as accepted (the N in 'N of M').")),
                ('reject_threshold', models.PositiveSmallIntegerField(default=1, help_text='Rejects that resolve it as rejected.')),
                ('changes_threshold', models.PositiveSmallIntegerField(blank=True, help_text='Change requests that resolve it. Falls back to reject_threshold.', null=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'consensus policies',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('withdrawn', 'Withdrawn')], db_index=True, default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('changes_requested', 'Changes requested')], db_index=True, default='pending', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_submissions', to='people.person')),
                ('supersedes', models.ForeignKey(blank=True, help_text='The submission this one corrects. Never edit in place.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='kanban.submission')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='kanban.task')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='TaskReviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_reviewable_tasks', to='people.person')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligible_reviewers', to='kanban.task')),
            ],
            options={
                'ordering': ('created_at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='kanban.submission')),
                ('vault_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_submission_files', to='vault.vaultfile')),
            ],
            options={
                'ordering': ('created_at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('verdict', models.CharField(choices=[('accept', 'Accept'), ('reject', 'Reject'), ('request_changes', 'Request changes')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_reviews', to='people.person')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='kanban.submission')),
            ],
            options={
                'ordering': ('created_at', 'pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='consensuspolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='kanban_one_default_consensus_policy'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_assignments', to='people.person'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='kanban.task'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='consensus_policy',
            field=models.ForeignKey(blank=True, help_text="Default review rule for this campaign's missions.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='kanban.consensuspolicy'),
        ),
        migrations.AddField(
            model_name='mission',
            name='consensus_policy',
            field=models.ForeignKey(blank=True, help_text="Overrides the campaign's review rule. Blank means no review gate.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='kanban.consensuspolicy'),
        ),
        migrations.AddConstraint(
            model_name='taskreviewer',
            constraint=models.UniqueConstraint(fields=('task', 'person'), name='kanban_unique_task_reviewer'),
        ),
        migrations.AddConstraint(
            model_name='submissionfile',
            constraint=models.UniqueConstraint(fields=('submission', 'vault_file'), name='kanban_unique_submission_file'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['task', 'state'], name='kanban_sub_task_state'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('state', 'draft'), ('submitted_at__isnull', True)), models.Q(('state', 'submitted'), ('submitted_at__isnull', False)), ('state', 'withdrawn'), _connector='OR'), name='kanban_submission_state_matches_submitted_at'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('resolution', 'pending'), ('resolved_at__isnull', True)), models.Q(models.Q(('resolution', 'pending'), _negated=True), ('resolved_at__isnull', False)), _connector='OR'), name='kanban_submission_resolution_matches_resolved_at'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('submission', 'reviewer'), name='kanban_one_review_per_reviewer'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(condition=models.Q(('released_at__isnull', True)), fields=('task', 'person'), name='kanban_one_live_assignment_per_person'),
        ),
    ]
