# Generated by Django 4.2.23 on 2025-08-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renso', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memocard',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='memocard',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
