# Generated by Django 4.2.23 on 2026-06-17 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0006_alter_vaultfile_file_type'),
        ('notarius', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractPdfJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('log', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_vault_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_pdf_source_jobs', to='vault.vaultfile')),
                ('vault_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_pdf_jobs', to='vault.vaultfile')),
            ],
            options={
                'verbose_name': 'Contract PDF job',
                'verbose_name_plural': 'Contract PDF jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
