# Generated by Django 4.2.23 on 2026-10-01 05:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import toto.forum.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vault', '0001_initial'),
        ('people', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gervazy', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access', models.CharField(choices=[('open', 'Open'), ('password', 'Password')], default='open', max_length=8)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('password_salt', models.BinaryField(blank=True, null=True)),
                ('password_verifier', models.BinaryField(blank=True, null=True)),
                ('kdf_memory_cost', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('kdf_iterations', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('kdf_lanes', models.PositiveIntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ForumCleanupRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(blank=True, help_text="The room's name as it was, kept for when the row is gone.", max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Finished'), ('partial', 'Stopped part-way'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('triggered_by', models.CharField(choices=[('beat', 'On schedule'), ('manual', 'Started by a person'), ('expiry', 'A temporary room expired')], default='beat', max_length=8)),
                ('boundary', models.DateTimeField()),
                ('retention_days', models.PositiveIntegerField()),
                ('messages_deleted', models.PositiveIntegerField(default=0)),
                ('attachments_deleted', models.PositiveIntegerField(default=0)),
                ('bytes_freed', models.PositiveBigIntegerField(default=0)),
                ('blobs_missing', models.PositiveIntegerField(default=0)),
                ('replies_orphaned', models.PositiveIntegerField(default=0)),
                ('polls_deleted', models.PositiveIntegerField(default=0)),
                ('ballots_deleted', models.PositiveIntegerField(default=0)),
                ('channels_touched', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['person__display_name'],
            },
        ),
        migrations.CreateModel(
            name='ForumMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_name', models.CharField(blank=True, max_length=150)),
                ('sender_avatar_url', models.CharField(blank=True, max_length=500)),
                ('msg_type', models.CharField(choices=[('chat_message', 'chat_message'), ('image_message', 'image_message'), ('voice_message', 'voice_message')], default='chat_message', max_length=32)),
                ('body', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, storage=toto.forum.models.forum_attachment_storage, upload_to=toto.forum.models.message_attachment_upload_to)),
                ('attachment_name', models.CharField(blank=True, max_length=255)),
                ('attachment_mime', models.CharField(blank=True, max_length=100)),
                ('attachment_size', models.PositiveIntegerField(blank=True, null=True)),
                ('body_sealed', models.BinaryField(blank=True, null=True)),
                ('attachment_sealed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumQuotaPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('metric_code', models.CharField(db_index=True, max_length=100)),
                ('limit', models.DecimalField(decimal_places=10, max_digits=30)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime')], default='daily', max_length=20)),
                ('mode', models.CharField(choices=[('track', 'Track only'), ('warn', 'Warn'), ('block', 'Block')], default='block', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Forum quota policy',
                'verbose_name_plural': 'Forum quota policies',
                'ordering': ['metric_code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoomPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('question_text', models.CharField(blank=True, max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=170)),
                ('opens_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closes_at', models.DateTimeField(blank=True, help_text='Leave empty to stay open until somebody closes it.', null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=10)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('revisability', models.CharField(choices=[('open', 'Answers may be changed'), ('final', 'One answer, final')], default='open', max_length=8)),
                ('visibility', models.CharField(choices=[('live', 'Everyone sees the count as it grows'), ('on_close', 'The count appears when the poll closes')], default='live', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='forum.forumchannel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('text', models.CharField(blank=True, max_length=300)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='forum.roompoll')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PollBallot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast_at', models.DateTimeField(auto_now_add=True)),
                ('revised_at', models.DateTimeField(blank=True, null=True)),
                ('revisions', models.PositiveSmallIntegerField(default=0)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='forum.pollchoice')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='forum.roompoll')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['cast_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumUsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_code', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=30)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('source_type', models.CharField(blank=True, max_length=100)),
                ('source_id', models.CharField(blank=True, max_length=255)),
                ('source_label', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('recorded', 'Recorded'), ('voided', 'Voided')], default='recorded', max_length=20)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Forum usage event',
                'verbose_name_plural': 'Forum usage events',
                'ordering': ['-occurred_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ForumRoomKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_wrapped', models.BinaryField()),
                ('platform_nonce', models.BinaryField()),
                ('password_wrapped', models.BinaryField(blank=True, null=True)),
                ('password_nonce', models.BinaryField(blank=True, null=True)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room_key', to='forum.forumchannel')),
                ('platform_wrapped_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gervazy.wrappeddatakey')),
            ],
        ),
        migrations.CreateModel(
            name='ForumRetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('retention_days', models.PositiveIntegerField(default=365, help_text='Messages older than this are permanently removed.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3650)])),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Finished'), ('partial', 'Stopped part-way'), ('failed', 'Failed')], max_length=10)),
                ('last_error', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(blank=True, help_text='The room this covers. Empty means every room that has no policy of its own.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retention_policies', to='forum.forumchannel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'forum retention policy',
                'verbose_name_plural': 'forum retention policies',
            },
        ),
        migrations.AddConstraint(
            model_name='forumquotapolicy',
            constraint=models.UniqueConstraint(fields=('metric_code',), name='forum_forumquotapolicy_one_per_metric'),
        ),
        migrations.AddField(
            model_name='forummessage',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='forum.forumchannel'),
        ),
        migrations.AddField(
            model_name='forummessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='forum.forummessage'),
        ),
        migrations.AddField(
            model_name='forummessage',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forummember',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_members', to='forum.forumchannel'),
        ),
        migrations.AddField(
            model_name='forummember',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_memberships', to='people.person'),
        ),
        migrations.AddField(
            model_name='forumcleanuprun',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleanup_runs', to='forum.forumchannel'),
        ),
        migrations.AddField(
            model_name='forumcleanuprun',
            name='triggered_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumchannel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumchannel',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='forum_channels', through='forum.ForumMember', to='people.person'),
        ),
        migrations.AddField(
            model_name='forumchannel',
            name='vault_directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vault.vaultdirectory'),
        ),
        migrations.AddIndex(
            model_name='roompoll',
            index=models.Index(fields=['channel', '-created_at'], name='forum_roomp_channel_5529ed_idx'),
        ),
        migrations.AddIndex(
            model_name='roompoll',
            index=models.Index(fields=['closes_at'], name='forum_roomp_closes__ab3138_idx'),
        ),
        migrations.AddConstraint(
            model_name='roompoll',
            constraint=models.UniqueConstraint(fields=('channel', 'slug'), name='uniq_room_poll_slug_per_channel'),
        ),
        migrations.AddConstraint(
            model_name='pollchoice',
            constraint=models.UniqueConstraint(fields=('poll', 'label'), name='uniq_poll_choice_label'),
        ),
        migrations.AddIndex(
            model_name='pollballot',
            index=models.Index(fields=['poll', 'choice'], name='forum_pollb_poll_id_959afa_idx'),
        ),
        migrations.AddConstraint(
            model_name='pollballot',
            constraint=models.UniqueConstraint(fields=('poll', 'voter'), name='uniq_poll_ballot_per_voter'),
        ),
        migrations.AddIndex(
            model_name='forumusageevent',
            index=models.Index(fields=['metric_code', 'occurred_at'], name='forumusageevent_mtime'),
        ),
        migrations.AddIndex(
            model_name='forumusageevent',
            index=models.Index(fields=['user', 'metric_code'], name='forumusageevent_umetric'),
        ),
        migrations.AddConstraint(
            model_name='forumusageevent',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('idempotency_key',), name='forum_forumusageevent_idem'),
        ),
        migrations.AddConstraint(
            model_name='forumretentionpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('channel__isnull', False)), fields=('channel',), name='forum_one_retention_policy_per_channel'),
        ),
        migrations.AddIndex(
            model_name='forummessage',
            index=models.Index(fields=['channel', 'created_at'], name='forum_forum_channel_107b66_idx'),
        ),
        migrations.AddIndex(
            model_name='forummessage',
            index=models.Index(fields=['channel', '-created_at'], name='forum_forum_channel_81ac6c_idx'),
        ),
        migrations.AddConstraint(
            model_name='forummember',
            constraint=models.UniqueConstraint(condition=models.Q(('person__isnull', False)), fields=('channel', 'person'), name='unique_forum_channel_member'),
        ),
        migrations.AddConstraint(
            model_name='forummember',
            constraint=models.CheckConstraint(check=models.Q(('person__isnull', False)), name='forum_member_must_have_person'),
        ),
        migrations.AddIndex(
            model_name='forumcleanuprun',
            index=models.Index(fields=['status', 'started_at'], name='forum_forum_status_5d5a37_idx'),
        ),
    ]
