# Generated by Django 5.2.17 on 2026-10-07 00:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gervazy', '0002_initial'),
        ('socialhub', '0002_initial'),
        ('vault', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seq', models.PositiveBigIntegerField(default=0)),
                ('purged_before', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bucket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vault.bucket')),
                ('community', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forum_channel', to='socialhub.community')),
            ],
            options={
                'ordering': ['community__name'],
            },
        ),
        migrations.CreateModel(
            name='ChannelPoll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveBigIntegerField()),
                ('seq', models.PositiveBigIntegerField(db_index=True)),
                ('title_sealed', models.BinaryField(blank=True, null=True)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('revisability', models.CharField(choices=[('open', 'Answers may be changed'), ('final', 'One answer, final')], default='open', max_length=8)),
                ('visibility', models.CharField(choices=[('live', 'Everyone sees the count as it grows'), ('on_close', 'The count appears when the poll closes')], default='live', max_length=20)),
                ('opener_name', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='forum.forumchannel')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ForumChannelKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_wrapped', models.BinaryField()),
                ('platform_nonce', models.BinaryField()),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='channel_key', to='forum.forumchannel')),
                ('platform_wrapped_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gervazy.wrappeddatakey')),
            ],
        ),
        migrations.CreateModel(
            name='ForumCleanupRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Finished'), ('partial', 'Stopped part-way'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('triggered_by', models.CharField(choices=[('beat', 'On schedule'), ('manual', 'Started by a person')], default='beat', max_length=8)),
                ('boundary', models.DateTimeField()),
                ('retention_days', models.PositiveIntegerField()),
                ('messages_deleted', models.PositiveIntegerField(default=0)),
                ('attachments_deleted', models.PositiveIntegerField(default=0)),
                ('bytes_freed', models.PositiveBigIntegerField(default=0)),
                ('blobs_missing', models.PositiveIntegerField(default=0)),
                ('polls_deleted', models.PositiveIntegerField(default=0)),
                ('ballots_deleted', models.PositiveIntegerField(default=0)),
                ('channels_touched', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('workflow_run_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleanup_runs', to='forum.forumchannel')),
                ('triggered_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveBigIntegerField()),
                ('seq', models.PositiveBigIntegerField(db_index=True)),
                ('sender_name', models.CharField(blank=True, max_length=150)),
                ('kind', models.CharField(choices=[('text', 'text'), ('image', 'image')], default='text', max_length=8)),
                ('body_sealed', models.BinaryField(blank=True, null=True)),
                ('text_bytes', models.PositiveIntegerField(default=0)),
                ('attachment_mime', models.CharField(blank=True, max_length=32)),
                ('attachment_size', models.PositiveIntegerField(blank=True, null=True)),
                ('op_key', models.CharField(blank=True, editable=False, max_length=36)),
                ('op_digest', models.CharField(blank=True, editable=False, max_length=64)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vault.vaultfile')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='forum.forumchannel')),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ForumQuotaPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('metric_code', models.CharField(db_index=True, max_length=100)),
                ('limit', models.DecimalField(decimal_places=10, max_digits=30)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime')], default='daily', max_length=20)),
                ('mode', models.CharField(choices=[('track', 'Track only'), ('warn', 'Warn'), ('block', 'Block')], default='block', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Forum quota policy',
                'verbose_name_plural': 'Forum quota policies',
                'ordering': ['metric_code'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('metric_code',), name='forum_forumquotapolicy_one_per_metric')],
            },
        ),
        migrations.CreateModel(
            name='ForumSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retention_enabled', models.BooleanField(default=False)),
                ('retention_days', models.PositiveIntegerField(default=365, help_text='Messages and polls older than this are permanently removed.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3650)])),
                ('refresh_seconds', models.PositiveSmallIntegerField(default=5, help_text='How often an open channel asks for new messages, in seconds.', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(120)])),
                ('free_below_kb', models.PositiveIntegerField(default=300, help_text='A message whose text and picture together are smaller than this costs nothing. 0 charges every message.', validators=[django.core.validators.MaxValueValidator(102400)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'forum settings',
                'verbose_name_plural': 'forum settings',
            },
        ),
        migrations.CreateModel(
            name='ForumUsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_code', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=30)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('source_type', models.CharField(blank=True, max_length=100)),
                ('source_id', models.CharField(blank=True, max_length=255)),
                ('source_label', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('recorded', 'Recorded'), ('voided', 'Voided')], default='recorded', max_length=20)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Forum usage event',
                'verbose_name_plural': 'Forum usage events',
                'ordering': ['-occurred_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PollChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('sealed', models.BinaryField()),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='forum.channelpoll')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PollBallot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast_at', models.DateTimeField(auto_now_add=True)),
                ('revised_at', models.DateTimeField(blank=True, null=True)),
                ('revisions', models.PositiveSmallIntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='forum.channelpoll')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='forum.pollchoice')),
            ],
            options={
                'ordering': ['cast_at'],
            },
        ),
        migrations.AddIndex(
            model_name='channelpoll',
            index=models.Index(fields=['channel', 'seq'], name='forum_chann_channel_a95455_idx'),
        ),
        migrations.AddConstraint(
            model_name='channelpoll',
            constraint=models.UniqueConstraint(fields=('channel', 'number'), name='forum_poll_number_per_channel'),
        ),
        migrations.AddIndex(
            model_name='forumcleanuprun',
            index=models.Index(fields=['status', 'started_at'], name='forum_forum_status_5d5a37_idx'),
        ),
        migrations.AddIndex(
            model_name='forummessage',
            index=models.Index(fields=['channel', 'seq'], name='forum_forum_channel_b54c42_idx'),
        ),
        migrations.AddConstraint(
            model_name='forummessage',
            constraint=models.UniqueConstraint(fields=('channel', 'number'), name='forum_message_number_per_channel'),
        ),
        migrations.AddConstraint(
            model_name='forummessage',
            constraint=models.UniqueConstraint(condition=models.Q(('op_key', ''), _negated=True), fields=('sender', 'op_key'), name='forum_message_sender_op'),
        ),
        migrations.AddIndex(
            model_name='forumusageevent',
            index=models.Index(fields=['metric_code', 'occurred_at'], name='forumusageevent_mtime'),
        ),
        migrations.AddIndex(
            model_name='forumusageevent',
            index=models.Index(fields=['user', 'metric_code'], name='forumusageevent_umetric'),
        ),
        migrations.AddConstraint(
            model_name='forumusageevent',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('idempotency_key',), name='forum_forumusageevent_idem'),
        ),
        migrations.AddConstraint(
            model_name='pollchoice',
            constraint=models.UniqueConstraint(fields=('poll', 'position'), name='forum_poll_choice_position'),
        ),
        migrations.AddIndex(
            model_name='pollballot',
            index=models.Index(fields=['poll', 'choice'], name='forum_pollb_poll_id_959afa_idx'),
        ),
        migrations.AddConstraint(
            model_name='pollballot',
            constraint=models.UniqueConstraint(fields=('poll', 'voter'), name='forum_poll_ballot_per_voter'),
        ),
    ]
