# Generated by Django 4.2.23 on 2026-07-22 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import toto.forum.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ForumMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_members', to='forum.forumchannel')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_memberships', to='people.person')),
            ],
            options={
                'ordering': ['person__display_name'],
            },
        ),
        migrations.AddField(
            model_name='forumchannel',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='forum_channels', through='forum.ForumMember', to='people.person'),
        ),
        migrations.CreateModel(
            name='ForumMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_name', models.CharField(blank=True, max_length=150)),
                ('sender_avatar_url', models.CharField(blank=True, max_length=500)),
                ('msg_type', models.CharField(choices=[('chat_message', 'chat_message'), ('image_message', 'image_message'), ('voice_message', 'voice_message')], default='chat_message', max_length=32)),
                ('body', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, storage=toto.forum.models.forum_attachment_storage, upload_to=toto.forum.models.message_attachment_upload_to)),
                ('attachment_name', models.CharField(blank=True, max_length=255)),
                ('attachment_mime', models.CharField(blank=True, max_length=100)),
                ('attachment_size', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='forum.forumchannel')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='forum.forummessage')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['channel', 'created_at'], name='forum_forum_channel_107b66_idx'), models.Index(fields=['channel', '-created_at'], name='forum_forum_channel_81ac6c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='forummember',
            constraint=models.UniqueConstraint(condition=models.Q(('person__isnull', False)), fields=('channel', 'person'), name='unique_forum_channel_member'),
        ),
        migrations.AddConstraint(
            model_name='forummember',
            constraint=models.CheckConstraint(check=models.Q(('person__isnull', False)), name='forum_member_must_have_person'),
        ),
    ]
