# Generated by Django 4.2.23 on 2026-08-14 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0016_alter_vaultfile_file'),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumchannel',
            name='vault_directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vault.vaultdirectory'),
        ),
    ]
