# Generated by Django 4.2.23 on 2026-08-28 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0002_channel_library'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('question_text', models.CharField(blank=True, max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=170)),
                ('opens_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closes_at', models.DateTimeField(blank=True, help_text='Leave empty to stay open until somebody closes it.', null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=10)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('revisability', models.CharField(choices=[('open', 'Answers may be changed'), ('final', 'One answer, final')], default='open', max_length=8)),
                ('visibility', models.CharField(choices=[('live', 'Everyone sees the count as it grows'), ('on_close', 'The count appears when the poll closes')], default='live', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='forum.forumchannel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('text', models.CharField(blank=True, max_length=300)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='forum.roompoll')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PollBallot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast_at', models.DateTimeField(auto_now_add=True)),
                ('revised_at', models.DateTimeField(blank=True, null=True)),
                ('revisions', models.PositiveSmallIntegerField(default=0)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='forum.pollchoice')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='forum.roompoll')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['cast_at'],
            },
        ),
        migrations.AddIndex(
            model_name='roompoll',
            index=models.Index(fields=['channel', '-created_at'], name='forum_roomp_channel_5529ed_idx'),
        ),
        migrations.AddIndex(
            model_name='roompoll',
            index=models.Index(fields=['closes_at'], name='forum_roomp_closes__ab3138_idx'),
        ),
        migrations.AddConstraint(
            model_name='roompoll',
            constraint=models.UniqueConstraint(fields=('channel', 'slug'), name='uniq_room_poll_slug_per_channel'),
        ),
        migrations.AddConstraint(
            model_name='pollchoice',
            constraint=models.UniqueConstraint(fields=('poll', 'label'), name='uniq_poll_choice_label'),
        ),
        migrations.AddIndex(
            model_name='pollballot',
            index=models.Index(fields=['poll', 'choice'], name='forum_pollb_poll_id_959afa_idx'),
        ),
        migrations.AddConstraint(
            model_name='pollballot',
            constraint=models.UniqueConstraint(fields=('poll', 'voter'), name='uniq_poll_ballot_per_voter'),
        ),
    ]
