# Generated by Django 4.2.23 on 2026-08-28 18:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0003_roompoll_pollchoice_pollballot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumRetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('retention_days', models.PositiveIntegerField(default=365, help_text='Messages older than this are permanently removed.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3650)])),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Finished'), ('partial', 'Stopped part-way'), ('failed', 'Failed')], max_length=10)),
                ('last_error', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'forum retention policy',
                'verbose_name_plural': 'forum retention policy',
            },
        ),
        migrations.CreateModel(
            name='ForumCleanupRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Finished'), ('partial', 'Stopped part-way'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('triggered_by', models.CharField(choices=[('beat', 'On schedule'), ('manual', 'Started by a person')], default='beat', max_length=8)),
                ('boundary', models.DateTimeField()),
                ('retention_days', models.PositiveIntegerField()),
                ('messages_deleted', models.PositiveIntegerField(default=0)),
                ('attachments_deleted', models.PositiveIntegerField(default=0)),
                ('bytes_freed', models.PositiveBigIntegerField(default=0)),
                ('blobs_missing', models.PositiveIntegerField(default=0)),
                ('replies_orphaned', models.PositiveIntegerField(default=0)),
                ('channels_touched', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['status', 'started_at'], name='forum_forum_status_5d5a37_idx')],
            },
        ),
    ]
