"""Forum hygiene becomes per-channel.

A retention policy gains a nullable `channel`: NULL is the platform default
(pk=1, the row that already exists), and a row naming a channel is that room's
own setting. The partial unique constraint is what keeps "one override per
room" true — a plain unique on a nullable column would permit any number of
NULLs and therefore any number of platform defaults, which is the bug this
shape exists to prevent.

Runs gain the channel they swept, plus `channel_name` kept as text so a run
survives the deletion of its room, and the two poll counters — the sweep
deletes polls and their ballots now, and a number nothing counted reads as
zero.

Nothing is backfilled and nothing needs to be: every existing row is a
forum-wide policy or a forum-wide run, and NULL is exactly what those are.
"""

# Generated by Django 4.2.23 on 2026-08-29 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_cleanup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumretentionpolicy',
            options={'verbose_name': 'forum retention policy', 'verbose_name_plural': 'forum retention policies'},
        ),
        migrations.AddField(
            model_name='forumcleanuprun',
            name='ballots_deleted',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forumcleanuprun',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleanup_runs', to='forum.forumchannel'),
        ),
        migrations.AddField(
            model_name='forumcleanuprun',
            name='channel_name',
            field=models.CharField(blank=True, help_text="The room's name as it was, kept for when the row is gone.", max_length=100),
        ),
        migrations.AddField(
            model_name='forumcleanuprun',
            name='polls_deleted',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forumretentionpolicy',
            name='channel',
            field=models.ForeignKey(blank=True, help_text='The room this covers. Empty means every room that has no policy of its own.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retention_policies', to='forum.forumchannel'),
        ),
        migrations.AddConstraint(
            model_name='forumretentionpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('channel__isnull', False)), fields=('channel',), name='forum_one_retention_policy_per_channel'),
        ),
    ]
