# Generated by Django 4.2.23 on 2026-05-25 16:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='fa-solid fa-medal', max_length=100)),
                ('category', models.CharField(choices=[('service', 'Service'), ('rescue', 'Rescue'), ('leadership', 'Leadership'), ('training', 'Training'), ('special', 'Special')], default='service', max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyEquipmentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hybrid', models.BooleanField(default=True, help_text='Item shared under emergency — owner retains nominal ownership')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('authorized_at', models.DateTimeField(auto_now_add=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['item__name'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('watch', 'Watch'), ('warning', 'Warning'), ('emergency', 'Emergency'), ('critical_emergency', 'Critical Emergency')], default='warning', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('lifted', 'Lifted'), ('expired', 'Expired')], db_index=True, default='active', max_length=20)),
                ('declared_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lifted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('allows_inventory_access', models.BooleanField(default=True, help_text='Inventory items at community/zone sites become available as hybrid equipment')),
                ('allows_route_commandeering', models.BooleanField(default=False, help_text='Emergency vehicles may commandeer routes within this zone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Emergency statuses',
            },
        ),
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='fa-solid fa-triangle-exclamation', max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MobilizationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('standby', 'Standby'), ('active', 'Active'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], db_index=True, default='standby', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_hybrid', models.BooleanField(default=False, help_text='Hybrid event — some deployments are partial/shared duty')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MobilizationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('enacted', 'Enacted'), ('rejected', 'Rejected'), ('closed', 'Closed')], db_index=True, default='draft', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('justification', models.TextField(blank=True)),
                ('decision_notes', models.TextField(blank=True)),
                ('enacted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MobilizationReportEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_role', models.CharField(choices=[('primary', 'Primary'), ('supporting', 'Supporting'), ('context', 'Context'), ('contradictory', 'Contradictory')], default='supporting', max_length=20)),
                ('weight', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-awarded_at'],
            },
        ),
        migrations.CreateModel(
            name='Responder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_trained', models.BooleanField(default=False)),
                ('is_background_checked', models.BooleanField(default=False)),
                ('current_status', models.CharField(choices=[('off_duty', 'Off Duty'), ('available', 'Available'), ('standby', 'Standby'), ('responding', 'Responding'), ('unavailable', 'Unavailable')], db_index=True, default='off_duty', max_length=20)),
                ('last_status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResponderSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('basic', 'Basic'), ('trained', 'Trained'), ('certified', 'Certified'), ('professional', 'Professional')], default='basic', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='mobilization.responder')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobilization_responder_skills', to='competence.skillbadge')),
            ],
        ),
    ]
