# Generated by Django 4.2.23 on 2026-05-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilization', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencystatus',
            name='allows_asset_requisition',
            field=models.BooleanField(default=False, help_text='Community/zone assets may be requisitioned for deployment use'),
        ),
        migrations.AddField(
            model_name='emergencystatus',
            name='emergency_tax_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Levy applied to transactions during the emergency (e.g. 0.0250 = 2.5%)', max_digits=6, null=True),
        ),
    ]
