# Generated by Django 4.2.23 on 2026-10-01 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import toto.vault.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vault', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbrosiaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_workspaces_per_user', models.PositiveIntegerField(default=5, help_text='How many workspaces one person may hold at a time, across every lab. Destroying a workspace frees its slot immediately. 0 means no limit.', verbose_name='Maximum workspaces per user')),
            ],
            options={
                'verbose_name': 'Ambrosia Settings',
                'verbose_name_plural': 'Ambrosia Settings',
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('kind', models.CharField(choices=[('python', 'Python'), ('latex', 'LaTeX')], default='python', max_length=16)),
                ('execution', models.CharField(choices=[('kernel', 'Interactive kernel'), ('celery', 'Batch (Celery)')], default='kernel', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_opened_at', models.DateTimeField(blank=True, null=True)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambrosia_workspaces', to='vault.bucket')),
                ('main_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vault.vaultfile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambrosia_workspaces', to=settings.AUTH_USER_MODEL)),
                ('root_directory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ambrosia_workspace', to='vault.vaultdirectory')),
            ],
            options={
                'ordering': ['-last_opened_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceHibernation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hibernated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('rehydrated_at', models.DateTimeField(blank=True, null=True)),
                ('manifest', models.JSONField(blank=True, default=dict)),
                ('home', models.FileField(blank=True, null=True, storage=toto.vault.storage.private_storage, upload_to='ambrosia/hibernation/')),
                ('home_digest', models.CharField(blank=True, default='', max_length=64)),
                ('home_bytes', models.PositiveBigIntegerField(default=0)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hibernation', to='ambrosia.workspace')),
            ],
            options={
                'verbose_name': 'Workspace hibernation',
                'verbose_name_plural': 'Workspace hibernations',
            },
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['owner', '-last_opened_at'], name='ambrosia_wo_owner_i_b30531_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['kind'], name='ambrosia_wo_kind_e45c10_idx'),
        ),
    ]
