# Generated by Django 4.2.23 on 2026-08-22 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambrosia', '0002_workspace_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbrosiaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_workspaces_per_user', models.PositiveIntegerField(default=5, help_text='How many workspaces one person may hold at a time, across every lab. Destroying a workspace frees its slot immediately. 0 means no limit.', verbose_name='Maximum workspaces per user')),
            ],
            options={
                'verbose_name': 'Ambrosia Settings',
                'verbose_name_plural': 'Ambrosia Settings',
            },
        ),
    ]
