# Generated by Django 4.2.23 on 2026-08-25 20:08

from django.db import migrations, models
import django.db.models.deletion
import toto.vault.storage


class Migration(migrations.Migration):

    dependencies = [
        ('ambrosia', '0003_ambrosiasettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceHibernation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hibernated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('rehydrated_at', models.DateTimeField(blank=True, null=True)),
                ('manifest', models.JSONField(blank=True, default=dict)),
                ('home', models.FileField(blank=True, null=True, storage=toto.vault.storage.private_storage, upload_to='ambrosia/hibernation/')),
                ('home_digest', models.CharField(blank=True, default='', max_length=64)),
                ('home_bytes', models.PositiveBigIntegerField(default=0)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hibernation', to='ambrosia.workspace')),
            ],
            options={
                'verbose_name': 'Workspace hibernation',
                'verbose_name_plural': 'Workspace hibernations',
            },
        ),
    ]
