# Generated by Django 4.2.23 on 2026-05-11 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_alter_vaultfile_file_type'),
        ('verbena', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='vault_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_references', to='vault.vaultfile'),
        ),
        migrations.AddField(
            model_name='audio',
            name='vault_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_references', to='vault.vaultfile'),
        ),
        migrations.AddField(
            model_name='book',
            name='vault_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_references', to='vault.vaultfile'),
        ),
        migrations.AddField(
            model_name='video',
            name='vault_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_references', to='vault.vaultfile'),
        ),
    ]
