# Generated by Django 4.2.23 on 2026-05-13 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verbena', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='references',
        ),
        migrations.DeleteModel(
            name='Reference',
        ),
    ]
