# Generated by Django 4.2.23 on 2026-05-04 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verbena', '0002_remove_page_author_remove_section_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_covers', to='verbena.image')),
                ('tags', models.ManyToManyField(blank=True, related_name='books', to='verbena.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='verbena.book')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='verbena.page')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('book', 'page')},
            },
        ),
    ]
