# Generated by Django 4.2.23 on 2026-05-04 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verbena', '0003_book_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='verbena.page'),
        ),
    ]
