# Generated by Django 4.2.23 on 2026-05-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verbena', '0004_alter_chapter_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='sections', to='verbena.tag'),
        ),
    ]
