# Generated by Django 4.2.23 on 2026-05-04 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('locations', '0001_initial'),
        ('socialhub', '0001_initial'),
        ('verbena', '0005_section_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsection',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsection_events', to='events.event'),
        ),
        migrations.AddField(
            model_name='subsection',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsection_locations', to='locations.address'),
        ),
        migrations.AddField(
            model_name='subsection',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsection_people', to='socialhub.person'),
        ),
    ]
