# Generated by Django 4.2.23 on 2026-05-04 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialhub', '0001_initial'),
        ('events', '0001_initial'),
        ('locations', '0001_initial'),
        ('core', '0001_initial'),
        ('verbena', '0006_subsection_event_subsection_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsection',
            name='event',
        ),
        migrations.RemoveField(
            model_name='subsection',
            name='location',
        ),
        migrations.RemoveField(
            model_name='subsection',
            name='person',
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='locations.address')),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='socialhub.community')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='events.event')),
                ('federation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='core.federation')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='socialhub.person')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='locations.route')),
                ('territory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='locations.territory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='section',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='sections', to='verbena.topic'),
        ),
        migrations.AddField(
            model_name='subsection',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='subsections', to='verbena.topic'),
        ),
    ]
