# Generated by Django 4.2.23 on 2026-05-04 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialhub', '0001_initial'),
        ('verbena', '0008_book_uid_chapter_uid_page_uid_section_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verbena_sections', to='socialhub.person'),
        ),
    ]
