# Generated by Django 4.2.23 on 2026-05-11 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verbena', '0009_alter_section_author'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='book',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='page',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
    ]
