# Generated by Django 4.2.23 on 2026-05-11 20:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('socialhub', '0005_alter_person_communities'),
        ('verbena', '0010_alter_chapter_unique_together_remove_chapter_book_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('doi', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True)),
                ('abstract', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('director', models.CharField(blank=True, max_length=255)),
                ('producer', models.CharField(blank=True, max_length=255)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='library_video/')),
                ('authors', models.ManyToManyField(blank=True, related_name='%(class)s_references', to='socialhub.person')),
                ('tags', models.ManyToManyField(blank=True, related_name='%(class)s_references', to='verbena.tag')),
            ],
            options={
                'ordering': ['-year', 'title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('doi', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True)),
                ('abstract', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('edition', models.CharField(blank=True, max_length=50)),
                ('isbn', models.CharField(blank=True, max_length=20)),
                ('authors', models.ManyToManyField(blank=True, related_name='%(class)s_references', to='socialhub.person')),
                ('tags', models.ManyToManyField(blank=True, related_name='%(class)s_references', to='verbena.tag')),
            ],
            options={
                'ordering': ['-year', 'title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('doi', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True)),
                ('abstract', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.CharField(blank=True, max_length=255)),
                ('album', models.CharField(blank=True, max_length=255)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='library_audio/')),
                ('authors', models.ManyToManyField(blank=True, related_name='%(class)s_references', to='socialhub.person')),
                ('tags', models.ManyToManyField(blank=True, related_name='%(class)s_references', to='verbena.tag')),
            ],
            options={
                'ordering': ['-year', 'title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('doi', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True)),
                ('abstract', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal', models.CharField(blank=True, max_length=255)),
                ('volume', models.CharField(blank=True, max_length=20)),
                ('issue', models.CharField(blank=True, max_length=20)),
                ('pages', models.CharField(blank=True, max_length=50)),
                ('authors', models.ManyToManyField(blank=True, related_name='%(class)s_references', to='socialhub.person')),
                ('tags', models.ManyToManyField(blank=True, related_name='%(class)s_references', to='verbena.tag')),
            ],
            options={
                'ordering': ['-year', 'title'],
                'abstract': False,
            },
        ),
    ]
