# Generated by Django 4.2.23 on 2026-05-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verbena', '0011_video_book_audio_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='articles_refs',
            field=models.ManyToManyField(blank=True, related_name='pages_refs', to='verbena.article'),
        ),
        migrations.AddField(
            model_name='page',
            name='audios_refs',
            field=models.ManyToManyField(blank=True, related_name='pages_refs', to='verbena.audio'),
        ),
        migrations.AddField(
            model_name='page',
            name='books_refs',
            field=models.ManyToManyField(blank=True, related_name='pages_refs', to='verbena.book'),
        ),
        migrations.AddField(
            model_name='page',
            name='videos_refs',
            field=models.ManyToManyField(blank=True, related_name='pages_refs', to='verbena.video'),
        ),
    ]
