# Generated by Django 4.2.23 on 2026-05-11 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kanban', '0001_initial'),
        ('socialhub', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(blank=True, db_comment='assigned_to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='socialhub.person'),
        ),
        migrations.AddField(
            model_name='task',
            name='column',
            field=models.ForeignKey(db_comment='has_status', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='kanban.column'),
        ),
        migrations.AddField(
            model_name='task',
            name='mission',
            field=models.ForeignKey(db_comment='belongs_to', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='kanban.mission'),
        ),
        migrations.AddField(
            model_name='task',
            name='sprint',
            field=models.ForeignKey(blank=True, db_comment='belongs_to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='kanban.sprint'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='project',
            field=models.ForeignKey(db_comment='belongs_to', on_delete=django.db.models.deletion.CASCADE, to='kanban.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='collaborators',
            field=models.ManyToManyField(related_name='collaborating_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(db_comment='owned_by', on_delete=django.db.models.deletion.CASCADE, to='socialhub.person'),
        ),
        migrations.AddField(
            model_name='mission',
            name='campaign',
            field=models.ForeignKey(db_comment='belongs_to_campaign', on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='kanban.campaign'),
        ),
        migrations.AddField(
            model_name='mission',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Specific mission location, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='locations.address'),
        ),
        migrations.AddField(
            model_name='mission',
            name='owner',
            field=models.ForeignKey(blank=True, db_comment='owned_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='socialhub.person'),
        ),
        migrations.AddField(
            model_name='mission',
            name='route',
            field=models.ForeignKey(blank=True, help_text='Route connected to this mission, if movement is involved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='locations.route'),
        ),
        migrations.AddField(
            model_name='column',
            name='auditors',
            field=models.ManyToManyField(blank=True, help_text='Users who can move tasks into this column', related_name='audited_columns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='column',
            name='project',
            field=models.ForeignKey(db_column='belongs_to_project', db_comment='belongs_to', on_delete=django.db.models.deletion.CASCADE, to='kanban.project'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='owner',
            field=models.ForeignKey(blank=True, db_comment='owned_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='socialhub.person'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='project',
            field=models.ForeignKey(db_comment='belongs_to_project', on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='kanban.project'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='zone',
            field=models.ForeignKey(blank=True, help_text='Operational zone for this campaign, if it is geographically scoped.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='locations.zone'),
        ),
    ]
