# Generated by Django 4.2.23 on 2026-05-13 17:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentationPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_manual', models.BooleanField(default=False, help_text='If true, this page was written manually rather than generated.')),
                ('mission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documentation_page', to='kanban.mission')),
            ],
            options={
                'verbose_name': 'Documentation Page',
                'verbose_name_plural': 'Documentation Pages',
            },
        ),
    ]
