# Generated by Django 4.2.23 on 2026-05-16 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('kanban', '0002_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='campaign',
                    name='owner',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.person'),
                ),
                migrations.AlterField(
                    model_name='documentationsection',
                    name='author',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='people.person'),
                ),
                migrations.AlterField(
                    model_name='mission',
                    name='owner',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.person'),
                ),
                migrations.AlterField(
                    model_name='project',
                    name='owner',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.person'),
                ),
                migrations.AlterField(
                    model_name='task',
                    name='assignee',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.person'),
                ),
            ],
            database_operations=[],
        ),
    ]
