# Generated by Django 4.2.23 on 2026-05-11 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_maplayer_owner'),
        ('kanban', '0002_campaign_uid_column_uid_mission_uid_project_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='zone',
            field=models.ForeignKey(blank=True, help_text='Operational zone for this campaign, if it is geographically scoped.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='locations.zone'),
        ),
        migrations.AddField(
            model_name='mission',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Specific mission location, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='locations.address'),
        ),
        migrations.AddField(
            model_name='mission',
            name='route',
            field=models.ForeignKey(blank=True, help_text='Route connected to this mission, if movement is involved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='locations.route'),
        ),
    ]
