# Generated by Django 4.2.23 on 2026-05-23 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_tokenization_default_state'),
        ('locations', '0002_initial'),
        ('kanban', '0004_practitioner_refactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='locations.zone'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='locations.address'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='locations.route'),
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='practitionerallowance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='practitionerallowance',
            name='recipient_account',
            field=models.ForeignKey(blank=True, help_text='Account that receives the allowance. Resolved from practitioner if blank.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kanban_allowances_to_receive', to='assets.ledgeraccount'),
        ),
    ]
