# Generated by Django 4.2.23 on 2026-05-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0004_documentationsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentationpage',
            name='is_manual',
            field=models.BooleanField(default=False, help_text='If true, this page is an instruction / how-to manual for the mission.'),
        ),
    ]
