# Generated by Django 4.2.23 on 2026-08-12 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0003_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='memoquotapolicy',
            name='memo_memoquotapolicy_one_default',
        ),
        migrations.RemoveConstraint(
            model_name='memoquotapolicy',
            name='memo_memoquotapolicy_one_per_user',
        ),
        migrations.RemoveField(
            model_name='memoquotapolicy',
            name='user',
        ),
        migrations.AddConstraint(
            model_name='memoquotapolicy',
            constraint=models.UniqueConstraint(fields=('metric_code',), name='memo_memoquotapolicy_one_per_metric'),
        ),
    ]
