# Generated by Django 4.2.23 on 2026-06-04 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0001_initial'),
        ('gervazy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personsigningkey',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signing_keys', to='people.person'),
        ),
        migrations.AddField(
            model_name='encryptedsecret',
            name='strongbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to='gervazy.userstrongbox'),
        ),
        migrations.AddField(
            model_name='encryptedsecret',
            name='wrapped_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secrets', to='gervazy.wrappeddatakey'),
        ),
        migrations.AddField(
            model_name='encryptedprivatekey',
            name='strongbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_keys', to='gervazy.userstrongbox'),
        ),
        migrations.AddField(
            model_name='encryptedprivatekey',
            name='wrapped_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='private_keys', to='gervazy.wrappeddatakey'),
        ),
        migrations.AddField(
            model_name='encryptedfilechunk',
            name='encrypted_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='gervazy.encryptedfile'),
        ),
        migrations.AddField(
            model_name='encryptedfile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encrypted_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='encryptedfile',
            name='strongbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encrypted_files', to='gervazy.userstrongbox'),
        ),
        migrations.AddField(
            model_name='encryptedfile',
            name='wrapped_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='gervazy.wrappeddatakey'),
        ),
        migrations.AddField(
            model_name='cryptoauditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crypto_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cryptoauditlog',
            name='strongbox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='gervazy.userstrongbox'),
        ),
        migrations.AddConstraint(
            model_name='wrappeddatakey',
            constraint=models.UniqueConstraint(fields=('strongbox', 'version'), name='unique_dek_version_per_strongbox'),
        ),
        migrations.AddConstraint(
            model_name='wrappeddatakey',
            constraint=models.UniqueConstraint(fields=('vmk', 'nonce'), name='unique_dek_nonce_per_vmk'),
        ),
        migrations.AddConstraint(
            model_name='vaultmasterkey',
            constraint=models.UniqueConstraint(fields=('strongbox', 'version'), name='unique_vmk_version_per_strongbox'),
        ),
        migrations.AddConstraint(
            model_name='vaultmasterkey',
            constraint=models.UniqueConstraint(fields=('strongbox', 'nonce'), name='unique_vmk_nonce_per_strongbox'),
        ),
        migrations.AddConstraint(
            model_name='userstrongbox',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_strongbox_name_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='encryptedsecret',
            constraint=models.UniqueConstraint(fields=('strongbox', 'name'), name='unique_secret_name_per_strongbox'),
        ),
        migrations.AddConstraint(
            model_name='encryptedsecret',
            constraint=models.UniqueConstraint(fields=('wrapped_key', 'nonce'), name='unique_secret_nonce_per_wrapped_key'),
        ),
        migrations.AddConstraint(
            model_name='encryptedprivatekey',
            constraint=models.UniqueConstraint(fields=('wrapped_key', 'nonce'), name='unique_private_key_nonce_per_wrapped_key'),
        ),
        migrations.AddConstraint(
            model_name='encryptedfilechunk',
            constraint=models.UniqueConstraint(fields=('encrypted_file', 'index'), name='unique_chunk_index_per_file'),
        ),
        migrations.AddConstraint(
            model_name='encryptedfilechunk',
            constraint=models.UniqueConstraint(fields=('encrypted_file', 'nonce'), name='unique_chunk_nonce_per_file'),
        ),
        migrations.AddConstraint(
            model_name='encryptedfile',
            constraint=models.UniqueConstraint(fields=('wrapped_key', 'original_name_nonce'), name='unique_file_name_nonce_per_wrapped_key'),
        ),
    ]
