# Generated by Django 4.2.23 on 2026-05-23 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magistrate', '0004_role_education_relations_logistics'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='magistrate',
            new_name='magistrate__communi_31fa7c_idx',
            old_name='magistrate__communi_idx',
        ),
        migrations.RenameIndex(
            model_name='magistrate',
            new_name='magistrate__role_id_6411c9_idx',
            old_name='magistrate__role_idx',
        ),
        migrations.RenameIndex(
            model_name='magistratedecision',
            new_name='magistrate__communi_c4927b_idx',
            old_name='magistrate__dec_comm_idx',
        ),
        migrations.AddField(
            model_name='magistraterole',
            name='overseeing_interior',
            field=models.BooleanField(default=False, help_text='Holder oversees internal travel, location access, and movement of persons within community territory.'),
        ),
        migrations.AddField(
            model_name='magistraterole',
            name='overseeing_productivity',
            field=models.BooleanField(default=False, help_text='Holder oversees community productivity, work assignments, and labour standards.'),
        ),
        migrations.AlterField(
            model_name='magistratedecision',
            name='decision_type',
            field=models.CharField(choices=[('mobilization_call', 'Mobilization Call'), ('emergency_declare', 'Emergency Declaration'), ('tribunal_order', 'Tribunal Order'), ('trade_order', 'Trade Order'), ('finance_directive', 'Finance Directive'), ('public_order_directive', 'Public Order Directive'), ('legislation_fast_track', 'Legislation Fast-Track'), ('trade_reversal', 'Trade Reversal Order'), ('merchandise_fine', 'Merchandise Quality Fine'), ('education_directive', 'Education Directive'), ('relations_directive', 'Relations Directive'), ('logistics_order', 'Logistics Order'), ('interior_directive', 'Interior Directive'), ('productivity_directive', 'Productivity Directive'), ('general', 'General Directive')], db_index=True, max_length=30),
        ),
    ]
