# Generated by Django 4.2.23 on 2026-05-25 16:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Human-readable description of what this contract represents.')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContractNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Stable node id inside this contract, e.g. monthly_fee.', max_length=120)),
                ('node_type', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_manual', models.BooleanField(default=False, help_text='True when this node is manually authored and not backed by a claims/assets/instruments object.')),
                ('object_app', models.CharField(blank=True, max_length=80)),
                ('object_model', models.CharField(blank=True, max_length=80)),
                ('object_id', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('position_x', models.FloatField(blank=True, null=True)),
                ('position_y', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='contracts.contract')),
            ],
            options={
                'ordering': ['contract', 'key'],
            },
        ),
        migrations.CreateModel(
            name='ContractEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_type', models.CharField(max_length=40)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='contracts.contract')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='contracts.contractnode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='contracts.contractnode')),
            ],
            options={
                'ordering': ['contract', 'source__key', 'target__key'],
            },
        ),
        migrations.AddIndex(
            model_name='contractnode',
            index=models.Index(fields=['contract', 'node_type'], name='contracts_c_contrac_684106_idx'),
        ),
        migrations.AddIndex(
            model_name='contractnode',
            index=models.Index(fields=['contract', 'is_manual'], name='contracts_c_contrac_f8bb84_idx'),
        ),
        migrations.AddIndex(
            model_name='contractnode',
            index=models.Index(fields=['object_app', 'object_model', 'object_id'], name='contracts_c_object__d78490_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contractnode',
            unique_together={('contract', 'key')},
        ),
    ]
