# Generated by Django 4.2.23 on 2026-05-28 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gervazy', '0002_add_person_signing_key'),
        ('contracts', '0002_add_signing'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractsignatory',
            name='cryptographic_signature',
            field=models.TextField(blank=True, help_text='Base64-encoded Ed25519 signature over signing_payload.'),
        ),
        migrations.AddField(
            model_name='contractsignatory',
            name='signing_key',
            field=models.ForeignKey(blank=True, help_text='The EncryptedPrivateKey used to produce the cryptographic signature.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_signatures', to='gervazy.encryptedprivatekey'),
        ),
        migrations.AddField(
            model_name='contractsignatory',
            name='signing_payload',
            field=models.TextField(blank=True, help_text='Canonical UTF-8 payload that was signed.'),
        ),
        migrations.AlterField(
            model_name='contractsignatory',
            name='signature_data',
            field=models.TextField(blank=True, help_text='Base64-encoded PNG — decorative handwritten signature image.'),
        ),
    ]
