# Generated by Django 4.2.23 on 2026-05-19 12:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0002_initial'),
        ('people', '0002_initial'),
        ('assets', '0003_obligation_iscurrency'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('site_type', models.CharField(blank=True, help_text='warehouse, vault, office, vehicle, partner, custodian, virtual, etc.', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('location_type', models.CharField(blank=True, help_text='room, aisle, rack, shelf, bin, safe, freezer, virtual, etc.', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_locations', to='inventory.inventorysite')),
            ],
            options={
                'ordering': ['site', 'code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RealWorldObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('valuation_date', models.DateField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('custodian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custodied_inventory_objects', to='people.person')),
                ('estimated_value_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='valued_inventory_objects', to='assets.currency')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_objects', to='locations.address')),
                ('object_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objects', to='inventory.objecttype')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_inventory_objects', to='people.person')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_inventory_objects', to='people.person')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='objecttype',
            index=models.Index(fields=['slug'], name='inventory_o_slug_470f24_idx'),
        ),
        migrations.AddField(
            model_name='inventorysite',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_sites', to='locations.address'),
        ),
        migrations.AddField(
            model_name='inventorysite',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_inventory_sites', to='people.person'),
        ),
        migrations.AddIndex(
            model_name='storagelocation',
            index=models.Index(fields=['site', 'code'], name='inventory_s_site_id_e0e78f_idx'),
        ),
        migrations.AddIndex(
            model_name='storagelocation',
            index=models.Index(fields=['location_type'], name='inventory_s_locatio_1d379a_idx'),
        ),
        migrations.AddIndex(
            model_name='storagelocation',
            index=models.Index(fields=['is_active'], name='inventory_s_is_acti_2076ca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storagelocation',
            unique_together={('site', 'code')},
        ),
        migrations.AddIndex(
            model_name='realworldobject',
            index=models.Index(fields=['object_type'], name='inventory_r_object__294df6_idx'),
        ),
        migrations.AddIndex(
            model_name='realworldobject',
            index=models.Index(fields=['owner'], name='inventory_r_owner_i_0483f4_idx'),
        ),
        migrations.AddIndex(
            model_name='realworldobject',
            index=models.Index(fields=['custodian'], name='inventory_r_custodi_a3b1f8_idx'),
        ),
        migrations.AddIndex(
            model_name='realworldobject',
            index=models.Index(fields=['verified_by'], name='inventory_r_verifie_16d783_idx'),
        ),
        migrations.AddIndex(
            model_name='realworldobject',
            index=models.Index(fields=['verified_at'], name='inventory_r_verifie_c11cea_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorysite',
            index=models.Index(fields=['slug'], name='inventory_i_slug_15764e_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorysite',
            index=models.Index(fields=['site_type'], name='inventory_i_site_ty_617f9b_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorysite',
            index=models.Index(fields=['operator'], name='inventory_i_operato_9923cc_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorysite',
            index=models.Index(fields=['is_active'], name='inventory_i_is_acti_df299b_idx'),
        ),
    ]
