# Generated by Django 4.2.23 on 2025-11-09 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGateway',
        ),
    ]
