# Generated by Django 4.2.23 on 2026-10-01 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiteaForgeSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampled_at', models.DateTimeField()),
                ('total_bytes', models.BigIntegerField(default=0)),
                ('unattributed_bytes', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GiteaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('token_encrypted', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('storage_bytes', models.BigIntegerField(default=0)),
                ('storage_sampled_at', models.DateTimeField(blank=True, null=True)),
                ('storage_cap_gb', models.PositiveIntegerField(blank=True, null=True)),
                ('repo_creation_blocked', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gitea_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
