# Generated by Django 4.2.23 on 2026-05-22 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socialhub', '0003_community_is_federal_tribe'),
        ('competence', '0002_initial'),
        ('kanban', '0003_task_reviewer'),
        ('people', '0003_person_is_federal_agent'),
        ('detections', '0004_remove_bounties'),
        ('events', '0007_remove_scheduledevent_organizer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('deployment_type', models.CharField(choices=[('evacuation', 'Evacuation'), ('flood_response', 'Flood Response'), ('fire_support', 'Fire Support'), ('shelter_support', 'Shelter Support'), ('logistics', 'Logistics'), ('medical', 'Medical'), ('welfare_check', 'Welfare Check'), ('reconnaissance', 'Reconnaissance'), ('mixed', 'Mixed'), ('other', 'Other')], max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='planned', max_length=20)),
                ('objective', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='socialhub.community')),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_deployments', to='people.person')),
            ],
        ),
        migrations.CreateModel(
            name='MobilizationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('flood', 'Flood'), ('fire', 'Fire'), ('storm', 'Storm'), ('evacuation', 'Evacuation'), ('shelter', 'Shelter'), ('medical', 'Medical'), ('logistics', 'Logistics'), ('welfare_check', 'Welfare Check'), ('other', 'Other')], max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('enacted', 'Enacted'), ('rejected', 'Rejected'), ('closed', 'Closed')], db_index=True, default='draft', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('justification', models.TextField(blank=True)),
                ('decision_notes', models.TextField(blank=True)),
                ('enacted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobilization_reports', to='socialhub.community')),
                ('enacted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enacted_mobilization_reports', to='people.person')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_mobilization_reports', to='people.person')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_mobilization_reports', to='people.person')),
            ],
        ),
        migrations.CreateModel(
            name='Responder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_trained', models.BooleanField(default=False)),
                ('is_background_checked', models.BooleanField(default=False)),
                ('current_status', models.CharField(choices=[('off_duty', 'Off Duty'), ('available', 'Available'), ('standby', 'Standby'), ('responding', 'Responding'), ('unavailable', 'Unavailable')], db_index=True, default='off_duty', max_length=20)),
                ('last_status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('communities', models.ManyToManyField(blank=True, related_name='responders', to='socialhub.community')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responder_profile', to='people.person')),
            ],
        ),
        migrations.CreateModel(
            name='MobilizationReportEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_role', models.CharField(choices=[('primary', 'Primary'), ('supporting', 'Supporting'), ('context', 'Context'), ('contradictory', 'Contradictory')], default='supporting', max_length=20)),
                ('weight', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_mobilization_evidence', to='people.person')),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobilization_evidence', to='detections.detection')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='mobilization.mobilizationreport')),
            ],
        ),
        migrations.CreateModel(
            name='MobilizationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('incident_type', models.CharField(choices=[('flood', 'Flood'), ('fire', 'Fire'), ('storm', 'Storm'), ('evacuation', 'Evacuation'), ('shelter', 'Shelter'), ('medical', 'Medical'), ('logistics', 'Logistics'), ('welfare_check', 'Welfare Check'), ('other', 'Other')], max_length=30)),
                ('status', models.CharField(choices=[('standby', 'Standby'), ('active', 'Active'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], db_index=True, default='standby', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobilization_events', to='socialhub.community')),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_mobilization_events', to='people.person')),
                ('scheduled_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobilization_events', to='events.scheduledevent')),
                ('source_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobilization_events', to='mobilization.mobilizationreport')),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('intervention_type', models.CharField(choices=[('evacuation_pickup', 'Evacuation Pickup'), ('welfare_check', 'Welfare Check'), ('first_aid', 'First Aid'), ('transport', 'Transport'), ('supply_delivery', 'Supply Delivery'), ('damage_report', 'Damage Report'), ('road_closure', 'Road Closure'), ('sandbagging', 'Sandbagging'), ('other', 'Other')], max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('done', 'Done'), ('cancelled', 'Cancelled')], db_index=True, default='todo', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('outcome_notes', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to='mobilization.responder')),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='mobilization.deployment')),
                ('kanban_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobilization_interventions', to='kanban.task')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_interventions', to='people.person')),
            ],
        ),
        migrations.CreateModel(
            name='DeploymentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('lead', 'Lead'), ('deputy', 'Deputy'), ('driver', 'Driver'), ('medic', 'Medic'), ('logistics', 'Logistics'), ('communicator', 'Communicator'), ('responder', 'Responder'), ('volunteer', 'Volunteer')], default='responder', max_length=20)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('confirmed', 'Confirmed'), ('active', 'Active'), ('released', 'Released'), ('completed', 'Completed'), ('no_show', 'No Show')], db_index=True, default='assigned', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_deployment_assignments', to='people.person')),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='mobilization.deployment')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployment_assignments', to='mobilization.responder')),
            ],
        ),
        migrations.AddField(
            model_name='deployment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='mobilization.mobilizationevent'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='kanban_mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobilization_deployments', to='kanban.mission'),
        ),
        migrations.CreateModel(
            name='ResponderSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('basic', 'Basic'), ('trained', 'Trained'), ('certified', 'Certified'), ('professional', 'Professional')], default='basic', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='mobilization.responder')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobilization_responder_skills', to='competence.skillbadge')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_responder_skills', to='people.person')),
            ],
            options={
                'indexes': [models.Index(fields=['responder', 'level'], name='mobilizatio_respond_dfbd9c_idx')],
                'unique_together': {('responder', 'skill')},
            },
        ),
        migrations.AddIndex(
            model_name='responder',
            index=models.Index(fields=['current_status'], name='mobilizatio_current_07c348_idx'),
        ),
        migrations.AddIndex(
            model_name='responder',
            index=models.Index(fields=['is_active', 'current_status'], name='mobilizatio_is_acti_afa640_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilizationreportevidence',
            index=models.Index(fields=['report', 'evidence_role'], name='mobilizatio_report__72e59e_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilizationreportevidence',
            index=models.Index(fields=['report', 'weight'], name='mobilizatio_report__377fe3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mobilizationreportevidence',
            unique_together={('report', 'detection')},
        ),
        migrations.AddIndex(
            model_name='mobilizationreport',
            index=models.Index(fields=['community', 'status'], name='mobilizatio_communi_c8f4ad_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilizationreport',
            index=models.Index(fields=['status', 'severity'], name='mobilizatio_status_2a0823_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilizationreport',
            index=models.Index(fields=['report_type', 'status'], name='mobilizatio_report__b221f5_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilizationevent',
            index=models.Index(fields=['community', 'status'], name='mobilizatio_communi_d09326_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilizationevent',
            index=models.Index(fields=['status', 'incident_type'], name='mobilizatio_status_697c34_idx'),
        ),
        migrations.AddIndex(
            model_name='intervention',
            index=models.Index(fields=['deployment', 'status'], name='mobilizatio_deploym_3d731e_idx'),
        ),
        migrations.AddIndex(
            model_name='intervention',
            index=models.Index(fields=['deployment', 'is_required', 'status'], name='mobilizatio_deploym_76193c_idx'),
        ),
        migrations.AddIndex(
            model_name='intervention',
            index=models.Index(fields=['assigned_to', 'status'], name='mobilizatio_assigne_79a4cd_idx'),
        ),
        migrations.AddIndex(
            model_name='deploymentassignment',
            index=models.Index(fields=['deployment', 'status'], name='mobilizatio_deploym_35a25a_idx'),
        ),
        migrations.AddIndex(
            model_name='deploymentassignment',
            index=models.Index(fields=['responder', 'status'], name='mobilizatio_respond_868630_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deploymentassignment',
            unique_together={('deployment', 'responder')},
        ),
        migrations.AddIndex(
            model_name='deployment',
            index=models.Index(fields=['event', 'status'], name='mobilizatio_event_i_b35820_idx'),
        ),
        migrations.AddIndex(
            model_name='deployment',
            index=models.Index(fields=['community', 'status'], name='mobilizatio_communi_42458e_idx'),
        ),
        migrations.AddIndex(
            model_name='deployment',
            index=models.Index(fields=['status', 'priority'], name='mobilizatio_status_49037c_idx'),
        ),
    ]
