# Generated by Django 4.2.23 on 2026-05-25 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0003_initial'),
        ('assembly', '0002_initial'),
        ('inventory', '0002_initial'),
        ('mobilization', '0001_initial'),
        ('socialhub', '0001_initial'),
        ('people', '0002_initial'),
        ('locations', '0002_initial'),
        ('response', '0001_initial'),
        ('detections', '0002_initial'),
        ('kanban', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='responderskill',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_responder_skills', to='people.person'),
        ),
        migrations.AddField(
            model_name='responder',
            name='communities',
            field=models.ManyToManyField(blank=True, related_name='responders', to='socialhub.community'),
        ),
        migrations.AddField(
            model_name='responder',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responder_profile', to='people.person'),
        ),
        migrations.AddField(
            model_name='personachievement',
            name='awarded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_achievements', to='people.person'),
        ),
        migrations.AddField(
            model_name='personachievement',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_to', to='mobilization.achievementbadge'),
        ),
        migrations.AddField(
            model_name='personachievement',
            name='deployment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievement_awards', to='response.deployment'),
        ),
        migrations.AddField(
            model_name='personachievement',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobilization_achievements', to='people.person'),
        ),
        migrations.AddField(
            model_name='mobilizationreportevidence',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_mobilization_evidence', to='people.person'),
        ),
        migrations.AddField(
            model_name='mobilizationreportevidence',
            name='detection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobilization_evidence', to='detections.detection'),
        ),
        migrations.AddField(
            model_name='mobilizationreportevidence',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='mobilization.mobilizationreport'),
        ),
        migrations.AddField(
            model_name='mobilizationreport',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobilization_reports', to='socialhub.community'),
        ),
        migrations.AddField(
            model_name='mobilizationreport',
            name='enacted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enacted_mobilization_reports', to='people.person'),
        ),
        migrations.AddField(
            model_name='mobilizationreport',
            name='incident_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='mobilization.incidenttype'),
        ),
        migrations.AddField(
            model_name='mobilizationreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_mobilization_reports', to='people.person'),
        ),
        migrations.AddField(
            model_name='mobilizationreport',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_mobilization_reports', to='people.person'),
        ),
        migrations.AddField(
            model_name='mobilizationevent',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobilization_events', to='socialhub.community'),
        ),
        migrations.AddField(
            model_name='mobilizationevent',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_mobilization_events', to='people.person'),
        ),
        migrations.AddField(
            model_name='mobilizationevent',
            name='incident_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='mobilization.incidenttype'),
        ),
        migrations.AddField(
            model_name='mobilizationevent',
            name='kanban_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobilization_events', to='kanban.campaign'),
        ),
        migrations.AddField(
            model_name='mobilizationevent',
            name='scheduled_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobilization_events', to='events.scheduledevent'),
        ),
        migrations.AddField(
            model_name='mobilizationevent',
            name='source_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobilization_events', to='mobilization.mobilizationreport'),
        ),
        migrations.AddField(
            model_name='emergencystatus',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_statuses', to='socialhub.community'),
        ),
        migrations.AddField(
            model_name='emergencystatus',
            name='declared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declared_emergency_statuses', to='people.person'),
        ),
        migrations.AddField(
            model_name='emergencystatus',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_statuses', to='mobilization.mobilizationevent'),
        ),
        migrations.AddField(
            model_name='emergencystatus',
            name='source_proposal',
            field=models.ForeignKey(blank=True, help_text='Assembly proposal that voted to authorize this emergency status', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_declarations', to='assembly.assemblyproposal'),
        ),
        migrations.AddField(
            model_name='emergencystatus',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_statuses', to='locations.zone'),
        ),
        migrations.AddField(
            model_name='emergencyequipmentaccess',
            name='authorized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_emergency_equipment', to='people.person'),
        ),
        migrations.AddField(
            model_name='emergencyequipmentaccess',
            name='deployment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_equipment', to='response.deployment'),
        ),
        migrations.AddField(
            model_name='emergencyequipmentaccess',
            name='emergency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_accesses', to='mobilization.emergencystatus'),
        ),
        migrations.AddField(
            model_name='emergencyequipmentaccess',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_accesses', to='inventory.realworldobject'),
        ),
        migrations.AddIndex(
            model_name='responderskill',
            index=models.Index(fields=['responder', 'level'], name='mobilizatio_respond_dfbd9c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='responderskill',
            unique_together={('responder', 'skill')},
        ),
        migrations.AddIndex(
            model_name='responder',
            index=models.Index(fields=['current_status'], name='mobilizatio_current_07c348_idx'),
        ),
        migrations.AddIndex(
            model_name='responder',
            index=models.Index(fields=['is_active', 'current_status'], name='mobilizatio_is_acti_afa640_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='personachievement',
            unique_together={('person', 'badge')},
        ),
        migrations.AddIndex(
            model_name='mobilizationreportevidence',
            index=models.Index(fields=['report', 'evidence_role'], name='mobilizatio_report__72e59e_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilizationreportevidence',
            index=models.Index(fields=['report', 'weight'], name='mobilizatio_report__377fe3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mobilizationreportevidence',
            unique_together={('report', 'detection')},
        ),
        migrations.AddIndex(
            model_name='mobilizationreport',
            index=models.Index(fields=['community', 'status'], name='mobilizatio_communi_c8f4ad_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilizationreport',
            index=models.Index(fields=['status', 'severity'], name='mobilizatio_status_2a0823_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilizationevent',
            index=models.Index(fields=['community', 'status'], name='mobilizatio_communi_d09326_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencystatus',
            index=models.Index(fields=['event', 'status'], name='mobilizatio_event_i_fce0e7_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencystatus',
            index=models.Index(fields=['community', 'status'], name='mobilizatio_communi_d39171_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencystatus',
            index=models.Index(fields=['zone', 'status'], name='mobilizatio_zone_id_157010_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emergencyequipmentaccess',
            unique_together={('emergency', 'item')},
        ),
    ]
