# Generated by Django 4.2.23 on 2026-05-22 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_task_reviewer'),
        ('mobilization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilizationevent',
            name='kanban_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobilization_events', to='kanban.campaign'),
        ),
    ]
