# Generated by Django 4.2.23 on 2026-05-22 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobilization', '0002_mobilizationevent_kanban_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='fa-solid fa-triangle-exclamation', max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='mobilizationevent',
            name='mobilizatio_status_697c34_idx',
        ),
        migrations.RemoveIndex(
            model_name='mobilizationreport',
            name='mobilizatio_report__b221f5_idx',
        ),
        migrations.RemoveField(
            model_name='mobilizationreport',
            name='report_type',
        ),
        migrations.AddField(
            model_name='mobilizationreport',
            name='incident_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='mobilization.incidenttype'),
        ),
        migrations.AlterField(
            model_name='mobilizationevent',
            name='incident_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='mobilization.incidenttype'),
        ),
    ]
