# Generated by Django 4.2.23 on 2026-05-22 17:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_person_is_federal_agent'),
        ('inventory', '0002_alter_realworldobject_object_type'),
        ('assets', '0011_tokenization_default_state'),
        ('locations', '0002_initial'),
        ('socialhub', '0003_community_is_federal_tribe'),
        ('mobilization', '0004_new_models_and_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('watch', 'Watch'), ('warning', 'Warning'), ('emergency', 'Emergency'), ('critical_emergency', 'Critical Emergency')], default='warning', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('lifted', 'Lifted'), ('expired', 'Expired')], db_index=True, default='active', max_length=20)),
                ('declared_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lifted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('allows_asset_requisition', models.BooleanField(default=True, help_text='Community/zone assets can be requisitioned for deployment use')),
                ('allows_inventory_access', models.BooleanField(default=True, help_text='Inventory items at community/zone sites become available as hybrid equipment')),
                ('allows_route_commandeering', models.BooleanField(default=False, help_text='Emergency vehicles may commandeer routes within this zone')),
                ('emergency_tax_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Tax rate applied during emergency (e.g. 0.0250 = 2.5%)', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_statuses', to='socialhub.community')),
                ('declared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declared_emergency_statuses', to='people.person')),
                ('emergency_tax_account', models.ForeignKey(blank=True, help_text='Ledger account where emergency tax revenue is collected', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_tax_statuses', to='assets.ledgeraccount')),
                ('emergency_tax_asset', models.ForeignKey(blank=True, help_text='Asset/currency in which the emergency tax is denominated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_tax_statuses', to='assets.asset')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_statuses', to='mobilization.mobilizationevent')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_statuses', to='locations.zone')),
            ],
            options={
                'verbose_name_plural': 'Emergency statuses',
            },
        ),
        migrations.CreateModel(
            name='EmergencyEquipmentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hybrid', models.BooleanField(default=True, help_text='Item shared under emergency — owner retains nominal ownership')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('authorized_at', models.DateTimeField(auto_now_add=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_emergency_equipment', to='people.person')),
                ('deployment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_equipment', to='mobilization.deployment')),
                ('emergency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_accesses', to='mobilization.emergencystatus')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_accesses', to='inventory.realworldobject')),
            ],
            options={
                'ordering': ['item__name'],
            },
        ),
        migrations.AddIndex(
            model_name='emergencystatus',
            index=models.Index(fields=['event', 'status'], name='mobilizatio_event_i_fce0e7_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencystatus',
            index=models.Index(fields=['community', 'status'], name='mobilizatio_communi_d39171_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencystatus',
            index=models.Index(fields=['zone', 'status'], name='mobilizatio_zone_id_157010_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emergencyequipmentaccess',
            unique_together={('emergency', 'item')},
        ),
    ]
