# Generated by Django 4.2.23 on 2026-05-22 18:08

from django.db import migrations, models
import django.db.models.deletion

DEFAULT_INTERVENTION_TYPES = [
    ("evacuation-pickup",  "Evacuation Pickup",  "fa-solid fa-person-walking-arrow-right", 1),
    ("welfare-check",      "Welfare Check",       "fa-solid fa-heart-pulse",                2),
    ("first-aid",          "First Aid",           "fa-solid fa-kit-medical",                3),
    ("transport",          "Transport",           "fa-solid fa-van-shuttle",                4),
    ("supply-delivery",    "Supply Delivery",     "fa-solid fa-boxes-stacked",              5),
    ("damage-report",      "Damage Report",       "fa-solid fa-clipboard-list",             6),
    ("road-closure",       "Road Closure",        "fa-solid fa-road-barrier",               7),
    ("sandbagging",        "Sandbagging",         "fa-solid fa-fill-drip",                  8),
    ("search-rescue",      "Search & Rescue",     "fa-solid fa-magnifying-glass-location",  9),
    ("decontamination",    "Decontamination",     "fa-solid fa-biohazard",                 10),
    ("shelter-setup",      "Shelter Setup",       "fa-solid fa-house-chimney",             11),
    ("communications",     "Communications",      "fa-solid fa-walkie-talkie",             12),
    ("other",              "Other",               "fa-solid fa-ellipsis",                  99),
]

# Old CharField slug → new model slug mapping
LEGACY_SLUG_MAP = {
    "evacuation_pickup": "evacuation-pickup",
    "welfare_check":     "welfare-check",
    "first_aid":         "first-aid",
    "transport":         "transport",
    "supply_delivery":   "supply-delivery",
    "damage_report":     "damage-report",
    "road_closure":      "road-closure",
    "sandbagging":       "sandbagging",
    "other":             "other",
}


def seed_intervention_types(apps, schema_editor):
    InterventionType = apps.get_model("mobilization", "InterventionType")
    for slug, name, icon, order in DEFAULT_INTERVENTION_TYPES:
        InterventionType.objects.get_or_create(
            slug=slug,
            defaults={"name": name, "icon": icon, "order": order},
        )


def map_legacy_to_fk(apps, schema_editor):
    Intervention = apps.get_model("mobilization", "Intervention")
    InterventionType = apps.get_model("mobilization", "InterventionType")
    type_cache = {it.slug: it for it in InterventionType.objects.all()}
    for iv in Intervention.objects.exclude(intervention_type_legacy=""):
        new_slug = LEGACY_SLUG_MAP.get(iv.intervention_type_legacy)
        if new_slug and new_slug in type_cache:
            iv.intervention_type = type_cache[new_slug]
            iv.save(update_fields=["intervention_type"])


class Migration(migrations.Migration):

    dependencies = [
        ('mobilization', '0005_emergency_status'),
    ]

    operations = [
        # 1. Create the InterventionType model
        migrations.CreateModel(
            name='InterventionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='fa-solid fa-hand-holding-medical', max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        # 2. Seed default types before touching Intervention
        migrations.RunPython(seed_intervention_types, migrations.RunPython.noop),
        # 3. Rename old CharField so FK column can take the same name
        migrations.RenameField(
            model_name='intervention',
            old_name='intervention_type',
            new_name='intervention_type_legacy',
        ),
        # 4. Add new nullable FK column
        migrations.AddField(
            model_name='intervention',
            name='intervention_type',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='interventions',
                to='mobilization.interventiontype',
            ),
        ),
        # 5. Migrate existing string values → FK rows
        migrations.RunPython(map_legacy_to_fk, migrations.RunPython.noop),
        # 6. Drop the old legacy column
        migrations.RemoveField(
            model_name='intervention',
            name='intervention_type_legacy',
        ),
    ]
