# Generated by Django 4.2.23 on 2026-05-22 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_person_is_federal_agent'),
        ('detections', '0004_remove_bounties'),
        ('mobilization', '0007_achievement_badges'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='personachievement',
            name='unique_person_achievement',
        ),
        migrations.AddField(
            model_name='intervention',
            name='detection',
            field=models.ForeignKey(blank=True, help_text='Detection this intervention is intended to mitigate', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobilization_interventions', to='detections.detection'),
        ),
        migrations.AlterUniqueTogether(
            name='personachievement',
            unique_together={('person', 'badge')},
        ),
    ]
