# Generated by Django 4.2.23 on 2026-05-22 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0003_emergency_status_source_proposal'),
        ('mobilization', '0008_intervention_detection_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencystatus',
            name='source_proposal',
            field=models.ForeignKey(blank=True, help_text='Assembly proposal that voted to authorize this emergency status', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_declarations', to='assembly.assemblyproposal'),
        ),
    ]
