# Generated by Django 4.2.23 on 2026-05-25 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobilization', '0011_move_models_to_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencystatus',
            name='allows_asset_requisition',
        ),
        migrations.RemoveField(
            model_name='emergencystatus',
            name='emergency_tax_account',
        ),
        migrations.RemoveField(
            model_name='emergencystatus',
            name='emergency_tax_asset',
        ),
        migrations.RemoveField(
            model_name='emergencystatus',
            name='emergency_tax_rate',
        ),
    ]
