# Generated by Django 4.2.23 on 2026-05-25 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('competence', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academy', '0001_initial'),
        ('quizzes', '0001_initial'),
        ('memo', '0001_initial'),
        ('palimpsest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academy_teacher', to='people.person'),
        ),
        migrations.AddField(
            model_name='studentbadge',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_by_students', to='competence.skillbadge'),
        ),
        migrations.AddField(
            model_name='studentbadge',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to='academy.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='badges',
            field=models.ManyToManyField(blank=True, related_name='students', through='academy.StudentBadge', to='competence.skillbadge'),
        ),
        migrations.AddField(
            model_name='student',
            name='enrolled_courses',
            field=models.ManyToManyField(blank=True, related_name='students', through='academy.CourseEnrollment', to='academy.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academy_student', to='people.person'),
        ),
        migrations.AddField(
            model_name='scriptsection',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='people.person'),
        ),
        migrations.AddField(
            model_name='scriptsection',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academy.script'),
        ),
        migrations.AddField(
            model_name='script',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academy_scripts', to='people.person'),
        ),
        migrations.AddField(
            model_name='script',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='academy.coursemodule'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='attached_quizzes',
            field=models.ManyToManyField(blank=True, help_text='Standalone quizzes attached to this academy lesson.', related_name='academy_lessons', to='quizzes.quiz'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academy_lessons', to='memo.memodeck'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='academy.coursemodule'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_lessons', to='academy.teacher'),
        ),
        migrations.AddField(
            model_name='learningpathbadge',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_steps', to='competence.skillbadge'),
        ),
        migrations.AddField(
            model_name='learningpathbadge',
            name='learning_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_steps', to='academy.learningpath'),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='badges',
            field=models.ManyToManyField(blank=True, related_name='learning_paths', through='academy.LearningPathBadge', to='competence.skillbadge'),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='attached_quizzes',
            field=models.ManyToManyField(blank=True, help_text='Standalone quizzes attached to this academy module.', related_name='academy_modules', to='quizzes.quiz'),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='academy.course'),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='exam',
            field=models.ForeignKey(blank=True, help_text='Official quiz used as the exam for this module.', limit_choices_to={'is_official': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_modules', to='quizzes.quiz'),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_modules', to='academy.teacher'),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='unlocks_badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unlocking_modules', to='competence.skillbadge'),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='verbena_page',
            field=models.ForeignKey(blank=True, help_text='Optional notes, article, or handout page for this module.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academy_modules', to='palimpsest.page'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='academy.course'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='academy.student'),
        ),
        migrations.AddField(
            model_name='course',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academy_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_courses', to='academy.teacher'),
        ),
        migrations.AddField(
            model_name='cohortmembership',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='academy.cohort'),
        ),
        migrations.AddField(
            model_name='cohortmembership',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_memberships', to='academy.student'),
        ),
        migrations.AddField(
            model_name='cohort',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='academy.course'),
        ),
        migrations.AddField(
            model_name='cohort',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cohorts', to='academy.teacher'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='academy.course'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='exam',
            field=models.ForeignKey(blank=True, help_text='Official exam quiz this certificate was awarded for.', limit_choices_to={'is_official': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='quizzes.quiz'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academy_certificates', to='people.person'),
        ),
        migrations.AddConstraint(
            model_name='studentbadge',
            constraint=models.UniqueConstraint(fields=('student', 'badge'), name='unique_student_badge'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('module', 'slug'), name='unique_lesson_slug_per_module'),
        ),
        migrations.AddConstraint(
            model_name='learningpathbadge',
            constraint=models.UniqueConstraint(fields=('learning_path', 'badge'), name='unique_badge_per_path'),
        ),
        migrations.AddConstraint(
            model_name='coursemodule',
            constraint=models.UniqueConstraint(fields=('course', 'slug'), name='unique_module_slug_per_course'),
        ),
        migrations.AddConstraint(
            model_name='coursemodule',
            constraint=models.UniqueConstraint(fields=('course', 'unlocks_badge'), name='unique_badge_unlock_per_course'),
        ),
        migrations.AddConstraint(
            model_name='courseenrollment',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='unique_student_course_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='cohortmembership',
            constraint=models.UniqueConstraint(fields=('cohort', 'student'), name='unique_student_cohort_membership'),
        ),
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.UniqueConstraint(fields=('course', 'slug'), name='unique_cohort_slug_per_course'),
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', False)), fields=('person', 'course'), name='unique_course_certificate_per_person'),
        ),
    ]
