# Generated by Django 4.2.23 on 2026-05-30 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0018_alter_vaultfile_file_type'),
        ('academy', '0003_certificate_signing'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.ForeignKey(blank=True, help_text='Optional video for this lesson (from Vault).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academy_lessons', to='vault.vaultfile'),
        ),
    ]
