# Generated by Django 4.2.23 on 2026-10-01 05:49

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gervazy', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Steven', help_text="What it calls itself. Shown on the panel, and told to the model — so 'who are you' gets this answer rather than the provider's.", max_length=60)),
                ('icon', models.CharField(default='fa-solid fa-wand-magic-sparkles', help_text='A Font Awesome class.', max_length=80)),
                ('tagline', models.CharField(blank=True, help_text='One line, under the name. Not sent to the model.', max_length=160)),
                ('description', models.TextField(blank=True, help_text="What this assistant is for, in the user's words. Shown on the console. Not sent to the model.")),
                ('persona', models.TextField(blank=True, help_text='One or two sentences telling the model what it is. Sent on EVERY call, so length here is a bill, not a detail.')),
                ('language', models.CharField(blank=True, help_text='Leave blank to answer in the language of the text — the right default when people write in several. A value here overrides that.', max_length=60)),
                ('house_rules', models.TextField(blank=True, help_text='Rules that apply to every action: what never to invent, how blunt to be, what to do when unsure.')),
                ('kind_notes', models.JSONField(blank=True, default=dict, help_text='kind → an extra note for surfaces of that kind only (prose, code, latex, sheet, cells). Tuning LaTeX answers must not change prose ones.')),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI agent',
                'verbose_name_plural': 'AI agents',
                'ordering': ['-active', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AiPersonalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, help_text='Sent with every question you ask, so it counts toward what each question costs. Keep it short.', max_length=2000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI personalization',
                'verbose_name_plural': 'AI personalizations',
            },
        ),
        migrations.CreateModel(
            name='AiProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="What an operator calls this row. 'OpenAI production', 'staging key'.", max_length=120)),
                ('base_url', models.URLField(default='https://api.openai.com/v1', help_text='The OpenAI-compatible API root. Any provider speaking that wire format works here without a code change.')),
                ('model', models.CharField(default='gpt-4.1-mini', max_length=120)),
                ('temperature', models.DecimalField(decimal_places=2, default=Decimal('0.20'), max_digits=3)),
                ('max_output_tokens', models.PositiveIntegerField(default=1024, help_text='The ceiling per answer. Also the WORST CASE this platform checks a wallet against before running anything — see services.affordable.')),
                ('timeout', models.PositiveIntegerField(default=60, help_text='Seconds.')),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI provider',
                'verbose_name_plural': 'AI providers',
                'ordering': ['-active', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AiRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface', models.CharField(blank=True, max_length=64)),
                ('action', models.CharField(blank=True, max_length=64)),
                ('source_text', models.TextField(blank=True)),
                ('instruction', models.TextField(blank=True, help_text='Free-text extra instruction, when the action takes one.')),
                ('result', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Done'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error', models.TextField(blank=True)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('model_used', models.CharField(blank=True, max_length=120)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('agent_label', models.CharField(blank=True, max_length=60)),
                ('provider_label', models.CharField(blank=True, max_length=120)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('workflow_run_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'AI run',
                'verbose_name_plural': 'AI runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StevenQuotaPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('metric_code', models.CharField(db_index=True, max_length=100)),
                ('limit', models.DecimalField(decimal_places=10, max_digits=30)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime')], default='daily', max_length=20)),
                ('mode', models.CharField(choices=[('track', 'Track only'), ('warn', 'Warn'), ('block', 'Block')], default='block', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Steven quota policy',
                'verbose_name_plural': 'Steven quota policies',
                'ordering': ['metric_code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StevenUsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_code', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=30)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('source_type', models.CharField(blank=True, max_length=100)),
                ('source_id', models.CharField(blank=True, max_length=255)),
                ('source_label', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('recorded', 'Recorded'), ('voided', 'Voided')], default='recorded', max_length=20)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Steven usage event',
                'verbose_name_plural': 'Steven usage events',
                'ordering': ['-occurred_at'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='stevenquotapolicy',
            constraint=models.UniqueConstraint(fields=('metric_code',), name='steven_stevenquotapolicy_one_per_metric'),
        ),
        migrations.AddField(
            model_name='airun',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiprovider',
            name='secret',
            field=models.ForeignKey(blank=True, help_text='Gervazy EncryptedSecret holding the API key.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='steven_providers', to='gervazy.encryptedsecret'),
        ),
        migrations.AddField(
            model_name='aipersonalization',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_personalization', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='stevenusageevent',
            index=models.Index(fields=['metric_code', 'occurred_at'], name='stevenusageevent_mtime'),
        ),
        migrations.AddIndex(
            model_name='stevenusageevent',
            index=models.Index(fields=['user', 'metric_code'], name='stevenusageevent_umetric'),
        ),
        migrations.AddConstraint(
            model_name='stevenusageevent',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('idempotency_key',), name='steven_stevenusageevent_idem'),
        ),
        migrations.AddIndex(
            model_name='airun',
            index=models.Index(fields=['owner', '-created_at'], name='steven_airu_owner_i_da2a36_idx'),
        ),
        migrations.AddIndex(
            model_name='airun',
            index=models.Index(fields=['status'], name='steven_airu_status_4b3373_idx'),
        ),
    ]
