# Generated by Django 4.2.23 on 2026-08-14 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('steven', '0002_aiagent'),
    ]

    operations = [
        migrations.AddField(
            model_name='airun',
            name='duration_ms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airun',
            name='agent_label',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='airun',
            name='provider_label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='AiPersonalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, help_text='Sent with every question you ask, so it counts toward what each question costs. Keep it short.', max_length=2000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_personalization', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI personalization',
                'verbose_name_plural': 'AI personalizations',
            },
        ),
    ]
