# Generated by Django 4.2.23 on 2026-02-13 23:21

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import django_jsonform.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gervazy', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorMix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the color mix', max_length=64, unique=True)),
                ('primary_bg_light', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
                ('header_bg_light', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
                ('appbar_bg_light', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
                ('appbar_text_light', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None)),
                ('footer_bg_light', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
                ('footer_text_light', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None)),
                ('bubble_bg_light', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
                ('text_main_light', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None)),
                ('accent_light', colorfield.fields.ColorField(default='#FF4081', image_field=None, max_length=25, samples=None)),
                ('warn_light', colorfield.fields.ColorField(default='#FFC107', image_field=None, max_length=25, samples=None)),
                ('primary_bg_dark', colorfield.fields.ColorField(default='#121212', image_field=None, max_length=25, samples=None)),
                ('header_bg_dark', colorfield.fields.ColorField(default='#1F1F1F', image_field=None, max_length=25, samples=None)),
                ('appbar_bg_dark', colorfield.fields.ColorField(default='#1F1F1F', image_field=None, max_length=25, samples=None)),
                ('appbar_text_dark', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
                ('footer_bg_dark', colorfield.fields.ColorField(default='#1F1F1F', image_field=None, max_length=25, samples=None)),
                ('footer_text_dark', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
                ('bubble_bg_dark', colorfield.fields.ColorField(default='#2C2C2C', image_field=None, max_length=25, samples=None)),
                ('text_main_dark', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
                ('accent_dark', colorfield.fields.ColorField(default='#FF4081', image_field=None, max_length=25, samples=None)),
                ('warn_dark', colorfield.fields.ColorField(default='#FF5722', image_field=None, max_length=25, samples=None)),
                ('accent_1', colorfield.fields.ColorField(default='#03A9F4', image_field=None, max_length=25, samples=None)),
                ('accent_2', colorfield.fields.ColorField(default='#4CAF50', image_field=None, max_length=25, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='DashboardBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=50)),
                ('link', models.CharField(blank=True, max_length=64, null=True)),
                ('public', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name of the font (e.g. 'Playfair Display')", max_length=64, unique=True)),
                ('cdn_link', models.URLField(help_text='CDN or stylesheet URL for importing the font (e.g. Google Fonts)')),
                ('style_family', models.CharField(choices=[('serif', 'Serif'), ('sans-serif', 'Sans-serif'), ('monospace', 'Monospace'), ('display', 'Display / Decorative')], default='sans-serif', help_text='Font style family classification', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the theme', max_length=64, unique=True)),
                ('header', django_jsonform.models.fields.JSONField(default=dict, help_text='Tailwind classes for header element (light/dark mode)')),
                ('footer', django_jsonform.models.fields.JSONField(default=dict, help_text='Tailwind classes for footer element (light/dark mode)')),
                ('color_mix', models.ForeignKey(help_text='Color palette used for this theme', on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='core.colormix')),
                ('font', models.ForeignKey(blank=True, help_text='Font applied to this theme', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='themes', to='core.font')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('site_name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publication_year', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('rate_limit_window', models.IntegerField(default=60, help_text='Rate limit window in seconds')),
                ('rate_limit_max_requests', models.IntegerField(default=20, help_text='Max requests allowed per window')),
                ('logo', models.ImageField(blank=True, help_text='Optional logo for this federation', null=True, upload_to='federation_logos/')),
                ('secret', models.OneToOneField(help_text='SecretKey used for signing tokens', on_delete=django.db.models.deletion.CASCADE, related_name='platform', to='gervazy.secretkey')),
                ('theme', models.ForeignKey(blank=True, help_text='Theme applied to this platform', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_themes', to='core.theme')),
            ],
        ),
    ]
