# Generated by Django 4.2.23 on 2026-04-11 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DashboardBlock',
        ),
    ]
