# Generated by Django 4.2.23 on 2026-04-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='api_url',
            field=models.URLField(blank=True, help_text='Base API endpoint for this platform (e.g. https://example.com/api/)', null=True),
        ),
    ]
