# Generated by Django 4.2.23 on 2026-05-13 21:22

from django.db import migrations, models
import django.db.models.deletion
import django_jsonform.models.fields
import toto.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('gervazy', '0004_remove_encryptedfilechunk_unique_chunk_index_and_more'),
        ('core', '0002_update_platform_add_apiconnector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiconnector',
            name='api_secret',
            field=models.ForeignKey(blank=True, help_text='Encrypted API key/token stored in Gervazy.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='api_connectors', to='gervazy.encryptedsecret'),
        ),
        migrations.AlterField(
            model_name='apiconnector',
            name='extra',
            field=django_jsonform.models.fields.JSONField(blank=True, default=dict, help_text='Non-secret provider-specific configuration.', validators=[toto.core.models._reject_secret_like_json]),
        ),
        migrations.AlterField(
            model_name='apiconnector',
            name='signing_key',
            field=models.ForeignKey(blank=True, help_text='Encrypted private key for signed API requests.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='api_connectors', to='gervazy.encryptedprivatekey'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='api_signing_key_out',
            field=models.ForeignKey(blank=True, help_text='Encrypted private key used when this platform sends signed sync requests.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_outbound_signing', to='gervazy.encryptedprivatekey'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='logo',
            field=models.ImageField(blank=True, help_text='Optional logo for this platform', null=True, upload_to='federation_logos/'),
        ),
    ]
