# Generated by Django 4.2.23 on 2026-04-27 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gervazy', '0001_initial'),
        ('core', '0002_platform_api_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='api_secret',
            field=models.OneToOneField(blank=True, help_text='Encrypted API key for remote sync', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platform_api_key', to='gervazy.secretkey'),
        ),
    ]
