# Generated by Django 4.2.23 on 2026-04-27 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_platform_api_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='api_owner',
            field=models.ForeignKey(blank=True, help_text='User account used for API authentication', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_api_accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
