# Generated by Django 4.2.23 on 2026-04-27 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gervazy', '0001_initial'),
        ('core', '0004_platform_api_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='api_secret',
        ),
        migrations.AddField(
            model_name='platform',
            name='api_keypair',
            field=models.OneToOneField(blank=True, help_text='RSA keypair used for signing sync requests', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platform_api_keypair', to='gervazy.rsakeypair'),
        ),
    ]
