# Generated by Django 4.2.23 on 2026-04-28 22:19

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_platform_api_keypair_platform_api_keypair_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colormix',
            name='link_dark',
            field=colorfield.fields.ColorField(default='#64B5F6', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='colormix',
            name='link_light',
            field=colorfield.fields.ColorField(default='#1E88E5', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='colormix',
            name='success_dark',
            field=colorfield.fields.ColorField(default='#66BB6A', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='colormix',
            name='success_light',
            field=colorfield.fields.ColorField(default='#4CAF50', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='colormix',
            name='sunken_dark',
            field=colorfield.fields.ColorField(default='#1A1A1A', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='colormix',
            name='sunken_light',
            field=colorfield.fields.ColorField(default='#F5F5F5', image_field=None, max_length=25, samples=None),
        ),
    ]
