# Generated by Django 4.2.23 on 2025-09-23 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HTMLFile',
        ),
    ]
