# Generated by Django 4.2.23 on 2025-09-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='section',
            name='metadata',
        ),
        migrations.AlterField(
            model_name='section',
            name='content',
            field=models.TextField(help_text='Plain text content of the section'),
        ),
    ]
