# Generated by Django 4.2.23 on 2025-09-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(blank=True, help_text='Plain text content of the section'),
        ),
    ]
