# Generated by Django 4.2.23 on 2025-09-13 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='deep',
        ),
        migrations.RemoveField(
            model_name='section',
            name='deep',
        ),
    ]
