# Generated by Django 4.2.23 on 2025-10-04 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PDFFile',
        ),
    ]
