# Generated by Django 4.2.23 on 2025-09-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='latexsubsection',
            name='use_light_mode',
            field=models.BooleanField(default=False),
        ),
    ]
