# Generated by Django 4.2.23 on 2025-09-21 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='htmlfile',
            name='file',
        ),
    ]
