# Generated by Django 4.2.23 on 2025-08-23 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document_type',
            new_name='type',
        ),
    ]
