# Generated by Django 4.2.23 on 2025-09-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_section_created_at_remove_section_metadata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='content',
        ),
        migrations.RemoveField(
            model_name='document',
            name='metadata',
        ),
        migrations.AddField(
            model_name='document',
            name='summary',
            field=models.TextField(blank=True, help_text='Brief summary of the document'),
        ),
    ]
