# Generated by Django 4.2.23 on 2025-09-20 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documenteditor_editorsection_editorsubsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='summary',
        ),
    ]
