# Generated by Django 4.2.23 on 2025-10-04 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_delete_pdffile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='documents/images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='documentsubsection',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsections', to='documents.image'),
        ),
    ]
