# Generated by Django 4.2.23 on 2025-09-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(blank=True, help_text='Plain text content of the document', null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='content',
            field=models.TextField(blank=True, help_text='Plain text content of the section', null=True),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='content',
            field=models.TextField(blank=True, help_text='Plain text content of the subsection', null=True),
        ),
    ]
