# Generated by Django 4.2.23 on 2025-09-22 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_htmlfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmlfile',
            name='summary',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
