# Generated by Django 4.2.23 on 2025-09-13 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0003_latexscratchpad'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatexDocumentFactory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latex_factories', to='documents.department')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latex_factories', to=settings.AUTH_USER_MODEL)),
                ('preset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latex_factories', to='documents.latexpreset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='latexscratchpad',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scratchpads', to='documents.latexdocumentfactory'),
        ),
    ]
