# Generated by Django 4.2.23 on 2025-09-13 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_content_alter_section_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='htmlpreset',
            name='script_includes',
        ),
    ]
