# Generated by Django 4.2.23 on 2025-09-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_scratchpad'),
    ]

    operations = [
        migrations.AddField(
            model_name='scratchpad',
            name='use_light_mode',
            field=models.BooleanField(default=False),
        ),
    ]
