# Generated by Django 4.2.23 on 2025-08-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_image_subsection_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('code', models.TextField(help_text='Paste valid Mermaid.js syntax here.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
