# Generated by Django 4.2.23 on 2025-09-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_department_alter_document_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='summary',
            new_name='html_summary',
        ),
        migrations.AddField(
            model_name='document',
            name='latex_summary',
            field=models.TextField(blank=True),
        ),
    ]
