# Generated by Django 4.2.23 on 2025-09-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_remove_document_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenteditor',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
