# Generated by Django 4.2.23 on 2025-10-18 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_bucket_vaultfile_bucket'),
        ('documents', '0003_image_documentsubsection_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='bucket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='vault.bucket'),
        ),
    ]
