# Generated by Django 4.2.23 on 2025-09-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_remove_htmlpreset_script_includes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preset',
            name='depth',
        ),
        migrations.AddField(
            model_name='document',
            name='deep',
            field=models.BooleanField(default=False, help_text='Enable structured sections/subsections'),
        ),
        migrations.AddField(
            model_name='section',
            name='deep',
            field=models.BooleanField(default=False, help_text='Enable structured subsections'),
        ),
    ]
