# Generated by Django 4.2.23 on 2025-09-13 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_latexdocumentfactory_latexscratchpad_factory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='compiled_pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_file', to='documents.latexdocument')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='latexscratchpad',
            name='author',
        ),
        migrations.RemoveField(
            model_name='latexscratchpad',
            name='factory',
        ),
        migrations.DeleteModel(
            name='LatexDocumentFactory',
        ),
        migrations.DeleteModel(
            name='LatexScratchpad',
        ),
    ]
