# Generated by Django 4.2.23 on 2025-08-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_diagram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('latex_code', models.TextField(help_text='Enter valid LaTeX code here.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
