# Generated by Django 4.2.23 on 2025-09-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_remove_preset_depth_document_deep_section_deep'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='copyright_holder',
            field=models.CharField(default='SpectrumAi.pl', help_text='Name of the entity holding copyright for documents issued by this department', max_length=255),
        ),
        migrations.AddField(
            model_name='department',
            name='copyright_notice',
            field=models.TextField(default='This document is confidential and intended solely for the use of the individual or entity to whom it is addressed. Unauthorized distribution, reproduction, or disclosure is strictly prohibited.', help_text='Legal notice to be included in generated documents'),
        ),
    ]
