# Generated by Django 4.2.23 on 2025-09-13 07:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_subsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content',
            field=models.TextField(default='', help_text='Plain text content of the section'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preset',
            name='depth',
            field=models.PositiveSmallIntegerField(default=1, help_text='Depth level from 1 (shallow) to 3 (deep)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
