# Generated by Django 4.2.23 on 2025-09-20 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('documents', '0005_alter_pdffile_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='HtmlDocumentEditor',
            fields=[
                ('documenteditor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.documenteditor')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('documents.documenteditor',),
        ),
        migrations.CreateModel(
            name='LatexDocumentEditor',
            fields=[
                ('documenteditor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.documenteditor')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('documents.documenteditor',),
        ),
        migrations.AlterModelOptions(
            name='documenteditor',
            options={'base_manager_name': 'objects'},
        ),
        migrations.RemoveField(
            model_name='documenteditor',
            name='document',
        ),
        migrations.AddField(
            model_name='documenteditor',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
    ]
