# Generated by Django 4.2.23 on 2025-09-13 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_pdffile_remove_latexscratchpad_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTMLPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preview', to='documents.htmldocument')),
            ],
        ),
    ]
