# Generated by Django 4.2.23 on 2025-09-20 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_htmldocumenteditor_latexdocumenteditor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenteditor',
            name='document',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='editors', to='documents.document'),
            preserve_default=False,
        ),
    ]
