# Generated by Django 4.2.23 on 2025-09-13 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_htmlpreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='htmlpreview',
            name='html_document',
        ),
        migrations.AddField(
            model_name='htmlpreview',
            name='latex_document',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='html_preview', to='documents.latexdocument'),
            preserve_default=False,
        ),
    ]
