# Generated by Django 4.2.23 on 2025-09-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_remove_htmlpreview_html_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='htmlsection',
            name='document',
        ),
        migrations.RemoveField(
            model_name='htmlsubsection',
            name='section',
        ),
        migrations.AddField(
            model_name='htmlpreview',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='HTMLDocument',
        ),
        migrations.DeleteModel(
            name='HTMLSection',
        ),
        migrations.DeleteModel(
            name='HTMLSubSection',
        ),
    ]
