# Generated by Django 4.2.23 on 2025-09-20 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_documenteditor_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenteditor',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editors', to='documents.document'),
        ),
    ]
