# Generated by Django 4.2.23 on 2025-09-20 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_alter_documenteditor_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latexdocument',
            name='preset',
        ),
        migrations.AddField(
            model_name='latexdocumenteditor',
            name='preset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.latexpreset'),
        ),
    ]
