# Generated by Django 4.2.23 on 2025-09-13 21:56

from django.db import migrations, models
import django.db.models.deletion
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_remove_htmlsection_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='htmlpreset',
            name='template_name',
        ),
        migrations.AddField(
            model_name='htmlpreset',
            name='style_mapping',
            field=django_jsonform.models.fields.JSONField(default={'div.summary': 'text-sm italic text-gray-600 dark:text-gray-400 mb-6', 'h1': 'text-4xl font-bold mt-8 mb-4', 'h2': 'text-3xl font-semibold mt-6 mb-3', 'h3': 'text-2xl font-medium mt-4 mb-2', 'p': 'mb-4 leading-relaxed'}),
        ),
        migrations.AddField(
            model_name='htmlpreview',
            name='preset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='html_previews', to='documents.htmlpreset'),
        ),
    ]
