# Generated by Django 4.2.23 on 2025-09-20 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_remove_latexdocument_preset_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenteditor',
            name='document',
        ),
        migrations.AddField(
            model_name='htmldocumenteditor',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editors', to='documents.htmldocument'),
        ),
        migrations.AddField(
            model_name='latexdocumenteditor',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editors', to='documents.latexdocument'),
        ),
    ]
