# Generated by Django 4.2.23 on 2025-09-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_remove_htmlpreset_template_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='latexdocument',
            name='flat',
            field=models.BooleanField(default=False),
        ),
    ]
