# Generated by Django 4.2.23 on 2025-09-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_latexdocument_flat'),
    ]

    operations = [
        migrations.AddField(
            model_name='latexdocument',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
