# Generated by Django 4.2.23 on 2026-07-30 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import secrets
import toto.datalink.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatalinkPeer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peer_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('label', models.CharField(max_length=180)),
                ('base_url', models.URLField(help_text="The peer's root, e.g. https://aurelian.example.org")),
                ('grant_uid', models.UUIDField()),
                ('magic_token', models.CharField(max_length=128)),
                ('api_key', models.CharField(max_length=255)),
                ('scopes', models.JSONField(blank=True, default=list, help_text='What the peer said it granted. Advisory — the peer enforces it.')),
                ('is_active', models.BooleanField(default=True)),
                ('probe_error', models.TextField(blank=True, help_text='Why the last handshake failed. Set at pairing time so a wrong key, an expired grant or a version mismatch surfaces immediately rather than during a run.')),
                ('peer_site_name', models.CharField(blank=True, max_length=180)),
                ('peer_schema_version', models.PositiveIntegerField(default=0)),
                ('peer_registry_digest', models.CharField(blank=True, max_length=64)),
                ('peer_auth_posture', models.JSONField(blank=True, default=dict)),
                ('paired_at', models.DateTimeField(auto_now_add=True)),
                ('last_pull_at', models.DateTimeField(blank=True, null=True)),
                ('pull_count', models.PositiveIntegerField(default=0)),
                ('paired_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datalink_peers_paired', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'data link peer',
                'ordering': ['-paired_at'],
            },
        ),
        migrations.CreateModel(
            name='DatalinkRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('awaiting_operator', 'Awaiting operator'), ('awaiting_conflicts', 'Awaiting conflict decisions'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=24)),
                ('manifest', models.JSONField(blank=True, default=dict)),
                ('peer_schema_version', models.PositiveIntegerField(default=0)),
                ('peer_registry_digest', models.CharField(blank=True, max_length=64)),
                ('local_registry_digest', models.CharField(blank=True, max_length=64)),
                ('peer_auth_posture', models.JSONField(blank=True, default=dict)),
                ('clock_skew_seconds', models.IntegerField(blank=True, help_text='Peer clock minus ours at preflight. A timestamp tiebreak under unknown skew is a coin flip, so a later forensic must be able to see it was.', null=True)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='datalink.datalinkpeer')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datalink_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'data link run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DatalinkMergeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(db_index=True, max_length=100)),
                ('identity_hash', models.CharField(max_length=64)),
                ('identity', models.JSONField(default=dict, help_text='The readable identity, for forensics and display.')),
                ('peer_checksum', models.CharField(help_text="What the peer's payload hashed to when accepted.", max_length=64)),
                ('local_checksum', models.CharField(help_text='What the local row hashed to, projected through the same policy, right after it was written. Differs from peer_checksum whenever save() transformed the row — which is why both are stored.', max_length=64)),
                ('peer_changed_at', models.DateTimeField(blank=True, null=True)),
                ('local_pk', models.CharField(blank=True, max_length=64)),
                ('accepted_at', models.DateTimeField(auto_now=True)),
                ('last_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='datalink.datalinkrun')),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_bases', to='datalink.datalinkpeer')),
            ],
            options={
                'verbose_name': 'data link merge base',
            },
        ),
        migrations.CreateModel(
            name='DatalinkIdentityMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(db_index=True, max_length=100)),
                ('peer_identity', models.JSONField(default=dict)),
                ('peer_identity_hash', models.CharField(max_length=64)),
                ('local_identity', models.JSONField(default=dict)),
                ('local_pk', models.CharField(max_length=64)),
                ('note', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datalink_aliases_approved', to=settings.AUTH_USER_MODEL)),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_map', to='datalink.datalinkpeer')),
            ],
            options={
                'verbose_name': 'data link identity alias',
            },
        ),
        migrations.CreateModel(
            name='DatalinkGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('label', models.CharField(help_text="The peer this grant is for, e.g. 'aurelian'. Shown to operators only.", max_length=180)),
                ('magic_token', models.CharField(default=secrets.token_urlsafe, help_text='High-entropy URL segment, checked before the api key. Its purpose is to make the expensive key verification unreachable by guessing.', max_length=128, unique=True)),
                ('api_key_hash', models.CharField(blank=True, max_length=255)),
                ('api_key_hint', models.CharField(blank=True, help_text='Last characters of the key, so an operator can tell which one is live.', max_length=16)),
                ('scopes', models.JSONField(blank=True, default=list, help_text='Stage keys this peer may read, from the datalink registry. An empty list grants nothing.')),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, default=toto.datalink.models._default_expiry, null=True)),
                ('key_rotated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('read_count', models.PositiveIntegerField(default=0)),
                ('last_peer_ip', models.GenericIPAddressField(blank=True, help_text='Where the last read came from, so a human notices a new source.', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datalink_grants_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'data link grant',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DatalinkConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_key', models.CharField(db_index=True, max_length=32)),
                ('model_label', models.CharField(db_index=True, max_length=100)),
                ('identity', models.JSONField(default=dict)),
                ('identity_hash', models.CharField(db_index=True, max_length=64)),
                ('kind', models.CharField(choices=[('both_changed', 'Both sides changed'), ('no_base_divergence', 'Differs, and never synced before'), ('deleted_locally', 'Deleted here since the last sync'), ('unresolved_reference', 'Points at something that did not arrive'), ('unique_guard_collision', 'Collides with a different local row'), ('unclaimed_person', 'Profile with no account attached'), ('cycle', 'Circular parent reference'), ('write_error', 'Could not be written')], db_index=True, max_length=32)),
                ('severity', models.CharField(choices=[('blocking', 'Blocking'), ('warning', 'Warning'), ('info', 'Informational')], default='blocking', max_length=12)),
                ('label', models.CharField(blank=True, help_text="A human name for the row, taken from the PEER's data. Peer-supplied, so it is escaped everywhere it renders and never marked safe.", max_length=255)),
                ('field_diff', models.JSONField(blank=True, default=dict, help_text='{"field": {"local": ..., "peer": ...}}')),
                ('payload', models.JSONField(blank=True, default=dict, help_text="The peer's row, so a decision needs no refetch.")),
                ('detail', models.TextField(blank=True)),
                ('resolution', models.CharField(choices=[('pending', 'Undecided'), ('take_peer', "Take the peer's"), ('keep_local', 'Keep local'), ('skip', 'Skip this row'), ('acknowledged', 'Acknowledged')], db_index=True, default='pending', max_length=16)),
                ('resolution_reason', models.CharField(blank=True, help_text="How it was decided: 'operator', 'bulk', or 'timestamp'. A timestamp tiebreak writes a row here even though it resolved itself, so an auto-resolution is always visible rather than silent.", max_length=64)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datalink_conflicts_resolved', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='datalink.datalinkrun')),
            ],
            options={
                'verbose_name': 'data link conflict',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DatalinkStageRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_key', models.CharField(max_length=32)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=12)),
                ('total_rows', models.PositiveIntegerField(blank=True, help_text="From the peer's manifest. Null means the bar is indeterminate.", null=True)),
                ('rows_read', models.PositiveIntegerField(default=0)),
                ('rows_created', models.PositiveIntegerField(default=0)),
                ('rows_updated', models.PositiveIntegerField(default=0)),
                ('rows_skipped', models.PositiveIntegerField(default=0)),
                ('rows_conflicted', models.PositiveIntegerField(default=0)),
                ('pages_read', models.PositiveIntegerField(default=0)),
                ('cursors', models.JSONField(blank=True, default=dict)),
                ('deferred', models.JSONField(blank=True, default=list)),
                ('skips', models.JSONField(blank=True, default=list)),
                ('counts', models.JSONField(blank=True, default=dict, help_text='Tallies by reason, including every `omitted` reason the peer sent.')),
                ('stderr', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='datalink.datalinkrun')),
            ],
            options={
                'verbose_name': 'data link stage',
                'ordering': ['order', 'pk'],
                'unique_together': {('run', 'stage_key')},
            },
        ),
        migrations.AddConstraint(
            model_name='datalinkpeer',
            constraint=models.UniqueConstraint(fields=('base_url', 'grant_uid'), name='datalink_one_peer_per_grant'),
        ),
        migrations.AddIndex(
            model_name='datalinkmergebase',
            index=models.Index(fields=['peer', 'model_label'], name='datalink_da_peer_id_d44231_idx'),
        ),
        migrations.AddIndex(
            model_name='datalinkmergebase',
            index=models.Index(fields=['peer', 'model_label', 'identity_hash'], name='datalink_da_peer_id_a32c9c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='datalinkmergebase',
            unique_together={('peer', 'model_label', 'identity_hash')},
        ),
        migrations.AlterUniqueTogether(
            name='datalinkidentitymap',
            unique_together={('peer', 'model_label', 'peer_identity_hash')},
        ),
        migrations.AddIndex(
            model_name='datalinkconflict',
            index=models.Index(fields=['run', 'stage_key', 'severity'], name='datalink_da_run_id_dcb65d_idx'),
        ),
        migrations.AddIndex(
            model_name='datalinkconflict',
            index=models.Index(fields=['run', 'resolution'], name='datalink_da_run_id_e792d3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='datalinkconflict',
            unique_together={('run', 'model_label', 'identity_hash', 'kind')},
        ),
    ]
