# Generated by Django 4.2.23 on 2026-08-01 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sso_master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssoclient',
            name='paired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ssoclient',
            name='pairing_managed',
            field=models.BooleanField(default=False, help_text='Registered by federation pairing rather than by host configuration.'),
        ),
        migrations.AddField(
            model_name='ssoclient',
            name='previous_secret_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ssoclient',
            name='previous_secret_hash',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ssoclient',
            name='previous_secret_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ssoclient',
            name='secret_proven_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ssoclient',
            name='secret_rotated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SSOFederationInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secret_sha256', models.CharField(db_index=True, max_length=64, unique=True)),
                ('ticket_prefix', models.CharField(blank=True, max_length=12)),
                ('deployment_mac', models.CharField(blank=True, max_length=64)),
                ('expected_host', models.CharField(help_text='The hostname of the platform you are inviting, e.g. studio.example.com', max_length=255)),
                ('granted_scopes', models.CharField(default='openid email profile', max_length=255)),
                ('granted_trusted', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('redeemed_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('redeemed_callback_uri', models.CharField(blank=True, max_length=1000)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minted_federation_invites', to=settings.AUTH_USER_MODEL)),
                ('relying_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='federation_invites', to='sso_master.ssoclient')),
            ],
            options={
                'verbose_name': 'SSO federation invite',
                'verbose_name_plural': 'SSO federation invites',
                'ordering': ['-created_at'],
            },
        ),
    ]
