# Generated by Django 4.2.23 on 2026-05-16 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('academy', '0002_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='certificate',
                    name='person',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academy_certificates', to='people.person'),
                ),
                migrations.AlterField(
                    model_name='script',
                    name='author',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academy_scripts', to='people.person'),
                ),
                migrations.AlterField(
                    model_name='scriptsection',
                    name='author',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='people.person'),
                ),
                migrations.AlterField(
                    model_name='student',
                    name='person',
                    field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academy_student', to='people.person'),
                ),
                migrations.AlterField(
                    model_name='teacher',
                    name='person',
                    field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academy_teacher', to='people.person'),
                ),
            ],
            database_operations=[],
        ),
    ]
