# Generated by Django 4.2.23 on 2026-05-28 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gervazy', '0002_add_person_signing_key'),
        ('academy', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='cryptographic_signature',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='signed_by',
            field=models.ForeignKey(blank=True, help_text='Teacher who cryptographically signed this certificate.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_certificates', to='academy.teacher'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='signing_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_signatures', to='gervazy.encryptedprivatekey'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='signing_payload',
            field=models.TextField(blank=True),
        ),
    ]
