# Generated by Django 4.2.23 on 2026-05-13 19:02

from django.db import migrations, models
import django.db.models.deletion
import trix_editor.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('socialhub', '0001_initial'),
        ('academy', '0003_instruction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academy_scripts', to='socialhub.person')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='academy.coursemodule')),
            ],
            options={
                'verbose_name': 'Script',
                'verbose_name_plural': 'Scripts',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ScriptSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', trix_editor.fields.TrixEditorField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='socialhub.person')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academy.script')),
            ],
            options={
                'verbose_name': 'Script Section',
                'verbose_name_plural': 'Script Sections',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='Instruction',
        ),
    ]
