# Generated by Django 4.2.23 on 2026-05-31 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_lesson_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodule',
            name='lecture_video_url',
            field=models.URLField(blank=True, help_text='Optional VOD link for the lecture video (YouTube, Vimeo, etc.).'),
        ),
    ]
