# Generated by Django 4.2.23 on 2026-05-13 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialhub', '0001_initial'),
        ('academy', '0005_quiz_and_traits'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_quizzes', to='socialhub.person'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='max_time',
            field=models.PositiveIntegerField(blank=True, help_text='Optional time limit for this question in minutes.', null=True),
        ),
    ]
