# Generated by Django 4.2.23 on 2026-05-13 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_quiz_owner_question_maxtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodule',
            name='exam',
            field=models.ForeignKey(blank=True, help_text='Official quiz used as the exam for this module.', limit_choices_to={'is_official': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_modules', to='academy.quiz'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_official',
            field=models.BooleanField(default=False, help_text='Official quizzes can be set as the exam for a course module.'),
        ),
    ]
