# Generated by Django 4.2.23 on 2026-05-13 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_quiz_is_official_module_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='exam',
            field=models.ForeignKey(blank=True, help_text='Official exam quiz this certificate was awarded for.', limit_choices_to={'is_official': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='academy.quiz'),
        ),
    ]
