# Generated by Django 4.2.23 on 2026-10-01 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(default='placidia-activity', max_length=80, unique=True)),
                ('name', models.CharField(default='Placidia activity audit', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveBigIntegerField()),
                ('previous_hash', models.CharField(blank=True, max_length=64)),
                ('record_hash', models.CharField(editable=False, max_length=64)),
                ('algorithm', models.CharField(default='sha256-json-chain-1', max_length=32)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor_username', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('app_label', models.CharField(db_index=True, max_length=100)),
                ('object_type', models.CharField(blank=True, db_index=True, max_length=150)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('object_description', models.CharField(blank=True, max_length=500)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('request_source', models.JSONField(blank=True, default=dict)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('source', models.CharField(default='system', max_length=80)),
                ('success', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='placidia_audit_records', to=settings.AUTH_USER_MODEL)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='audit.auditchain')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ('-timestamp', '-sequence'),
                'indexes': [models.Index(fields=['object_type', 'object_id', '-timestamp'], name='placidia_audit_object_idx'), models.Index(fields=['app_label', 'action', '-timestamp'], name='placidia_audit_action_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='auditrecord',
            constraint=models.UniqueConstraint(fields=('chain', 'sequence'), name='placidia_audit_sequence_per_chain'),
        ),
    ]
