"""An audit record keeps its actor's id when the account goes (2026-09-29).

The digest covers `actor_user_id`; SET_NULL rewrote it on every account
delete and the chain stopped verifying. DO_NOTHING, no database constraint:
the id stays as written. No data changes.
"""

# Generated by Django 4.2.23 on 2026-09-29 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditrecord',
            name='actor_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='placidia_audit_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
