# Generated by Django 4.2.23 on 2026-05-25 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_initial'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenization',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_tokenizations', to='people.person'),
        ),
        migrations.AddField(
            model_name='obligation',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligations', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='obligation',
            name='collateral_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collateral_obligations', to='assets.ledgeraccount'),
        ),
        migrations.AddField(
            model_name='obligation',
            name='collateral_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collateral_obligations', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='obligation',
            name='creditor_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creditor_obligations', to='assets.ledgeraccount'),
        ),
        migrations.AddField(
            model_name='obligation',
            name='debtor_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debtor_obligations', to='assets.ledgeraccount'),
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='reversed_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_set', to='assets.ledgertransaction'),
        ),
        migrations.AddField(
            model_name='ledgerhash',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='hash_record', to='assets.ledgertransaction'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='assets.ledgeraccount'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='assets.ledgertransaction'),
        ),
        migrations.AddField(
            model_name='ledgeraccount',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='currency',
            name='asset',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='currency_peg', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetholding',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='assets.ledgeraccount'),
        ),
        migrations.AddField(
            model_name='assetholding',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='contract',
            field=models.ForeignKey(blank=True, help_text='Lapis contract governing this agreement.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='assets.contract'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='source_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements_as_source', to='assets.ledgeraccount'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='target_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements_as_target', to='assets.ledgeraccount'),
        ),
        migrations.AddIndex(
            model_name='tokenization',
            index=models.Index(fields=['real_world_object'], name='assets_toke_real_wo_c5363f_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenization',
            index=models.Index(fields=['asset'], name='assets_toke_asset_i_aa432e_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenization',
            index=models.Index(fields=['status'], name='assets_toke_status_4058ae_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenization',
            index=models.Index(fields=['supervisor'], name='assets_toke_supervi_da896c_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenization',
            index=models.Index(fields=['created_at'], name='assets_toke_created_690b8c_idx'),
        ),
        migrations.AddConstraint(
            model_name='tokenization',
            constraint=models.UniqueConstraint(fields=('real_world_object',), name='unique_tokenization_object'),
        ),
        migrations.AddConstraint(
            model_name='tokenization',
            constraint=models.UniqueConstraint(fields=('asset',), name='unique_tokenization_asset'),
        ),
        migrations.AlterUniqueTogether(
            name='assetholding',
            unique_together={('asset', 'account')},
        ),
    ]
