# Generated by Django 4.2.23 on 2026-05-26 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('public_key', models.TextField(help_text='Public key (PEM or hex).')),
                ('private_key_encrypted', models.TextField(blank=True, help_text='Private key encrypted with the server master secret. Do not expose.')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ledger_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_authorizations', to='assets.ledgeraccount')),
            ],
            options={
                'verbose_name': 'Wallet Authorization',
                'verbose_name_plural': 'Wallet Authorizations',
                'ordering': ['name'],
            },
        ),
    ]
