# Generated by Django 4.2.23 on 2026-05-26 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gervazy', '0001_initial'),
        ('assets', '0004_wallet_authorization'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerAccountKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.CharField(max_length=100, unique=True)),
                ('public_key_pem', models.TextField(help_text='Plaintext snapshot of the public key PEM. Must match gervazy.EncryptedPrivateKey.public_key_pem.')),
                ('algorithm', models.CharField(default='Ed25519', max_length=32)),
                ('state', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('retired', 'Retired'), ('compromised', 'Compromised'), ('destroyed', 'Destroyed')], default='active', max_length=20)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encrypted_private_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_account_keys', to='gervazy.encryptedprivatekey')),
                ('ledger_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signing_keys', to='assets.ledgeraccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='nonce',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='payload_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='signature',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LedgerAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scopes', models.JSONField(default=list, help_text='List of allowed scope strings, e.g. ["transfer", "sign"].')),
                ('max_amount_base_units', models.BigIntegerField(blank=True, help_text='Per-operation ceiling. None = unlimited.', null=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('signed_grant_payload', models.JSONField(default=dict)),
                ('grant_signature', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, help_text='If set, delegation is restricted to this asset only.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authorizations', to='assets.asset')),
                ('delegate_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delegated_authorizations', to='gervazy.encryptedprivatekey')),
                ('delegate_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_authorizations', to=settings.AUTH_USER_MODEL)),
                ('ledger_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorizations', to='assets.ledgeraccount')),
                ('signed_by_account_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signed_authorizations', to='assets.ledgeraccountkey')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='authorization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_transactions', to='assets.ledgerauthorization'),
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='signed_by_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_transactions', to='assets.ledgeraccountkey'),
        ),
        migrations.AddIndex(
            model_name='ledgeraccountkey',
            index=models.Index(fields=['ledger_account', 'state'], name='assets_ledg_ledger__cbee6f_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgeraccountkey',
            index=models.Index(fields=['key_id'], name='assets_ledg_key_id_8f3036_idx'),
        ),
    ]
