# Generated by Django 4.2.23 on 2026-06-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('key', models.SlugField(help_text="Contract type key — matched against the contract's <documentType>.", max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('latex_source', models.TextField(help_text='LaTeX template rendered with the Django template engine. Context: `contract` (parsed .contract), `signature_images` (list of {party_name, typed_name, filename}), `content_pdf_filename` (the embedded original PDF, or empty). Load `{% load notarius_latex %}` and pipe text through `|latexescape`.')),
                ('is_default', models.BooleanField(default=False, help_text="Used when no template matches the contract's type. Keep exactly one.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contract PDF template',
                'verbose_name_plural': 'Contract PDF templates',
                'ordering': ['name'],
            },
        ),
    ]
