# Generated by Django 4.2.23 on 2026-05-27 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vault', '0018_alter_vaultfile_file_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('access_mode', models.CharField(choices=[('public', 'Public'), ('private', 'Private — readers list only')], default='private', max_length=24)),
                ('allow_downloads', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('bucket', models.ForeignKey(blank=True, help_text='Vault bucket used for source media and generated transcript files.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcript_collections', to='vault.bucket')),
                ('cover_file', models.ForeignKey(blank=True, help_text='Optional VaultFile image used as collection cover.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcript_collection_covers', to='vault.vaultfile')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcript_collections', to=settings.AUTH_USER_MODEL)),
                ('readers', models.ManyToManyField(blank=True, related_name='transcript_readable_collections', to=settings.AUTH_USER_MODEL)),
                ('writers', models.ManyToManyField(blank=True, related_name='transcript_writable_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=24)),
                ('engine', models.CharField(choices=[('default', 'Default backend'), ('openai_whisper', 'openai-whisper'), ('faster_whisper', 'faster-whisper'), ('command', 'Command backend'), ('custom', 'Custom callable')], default='default', max_length=40)),
                ('language', models.CharField(blank=True, max_length=16)),
                ('detect_speakers', models.BooleanField(default=False)),
                ('translate_to', models.CharField(blank=True, max_length=16)),
                ('prompt', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptSpeaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('label', models.CharField(max_length=80)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='transcription.transcriptionjob')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcript_speaker_roles', to='people.person')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('title', models.CharField(max_length=240)),
                ('slug', models.SlugField(max_length=260)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('processing', 'Processing'), ('transcribed', 'Transcribed'), ('failed', 'Failed'), ('archived', 'Archived')], default='draft', max_length=24)),
                ('language', models.CharField(blank=True, help_text='Optional BCP-47 language code, e.g. en, pl.', max_length=16)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('transcript_text', models.TextField(blank=True)),
                ('segments_count', models.PositiveIntegerField(default=0)),
                ('transcribed_at', models.DateTimeField(blank=True, null=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='transcription.transcriptcollection')),
                ('source_file', models.ForeignKey(help_text='Original unencrypted VaultFile audio or video.', on_delete=django.db.models.deletion.PROTECT, related_name='transcript_source_files', to='vault.vaultfile')),
            ],
            options={
                'ordering': ['collection', 'position', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('index', models.PositiveIntegerField(default=0)),
                ('start_ms', models.PositiveIntegerField(default=0)),
                ('end_ms', models.PositiveIntegerField(default=0)),
                ('text', models.TextField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='transcription.transcriptionjob')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='transcription.transcriptsource')),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segments', to='transcription.transcriptspeaker')),
            ],
            options={
                'ordering': ['source', 'start_ms', 'index'],
            },
        ),
        migrations.AddField(
            model_name='transcriptionjob',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='transcription.transcriptsource'),
        ),
        migrations.CreateModel(
            name='TranscriptEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event', models.CharField(choices=[('impression', 'Impression'), ('play', 'Play'), ('transcribe', 'Transcribe'), ('export', 'Export'), ('download', 'Download')], default='impression', max_length=24)),
                ('seconds_played', models.PositiveIntegerField(default=0)),
                ('session_key', models.CharField(blank=True, max_length=80)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='transcription.transcriptsource')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcript_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('txt', 'Plain text'), ('json', 'JSON'), ('srt', 'SRT subtitles'), ('vtt', 'WebVTT subtitles'), ('summary', 'Summary')], max_length=24)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcript_artifacts', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='transcription.transcriptionjob')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='transcription.transcriptsource')),
                ('vault_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transcript_artifacts', to='vault.vaultfile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='transcriptspeaker',
            constraint=models.UniqueConstraint(fields=('job', 'label'), name='uniq_transcript_speaker_label_per_job'),
        ),
        migrations.AddIndex(
            model_name='transcriptsource',
            index=models.Index(fields=['collection', 'status'], name='transcripti_collect_3aa8c3_idx'),
        ),
        migrations.AddIndex(
            model_name='transcriptsource',
            index=models.Index(fields=['status', 'transcribed_at'], name='transcripti_status_28d320_idx'),
        ),
        migrations.AddIndex(
            model_name='transcriptsource',
            index=models.Index(fields=['slug'], name='transcripti_slug_7db9b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='transcriptsource',
            constraint=models.UniqueConstraint(fields=('collection', 'slug'), name='uniq_transcript_source_slug_per_collection'),
        ),
        migrations.AddIndex(
            model_name='transcriptsegment',
            index=models.Index(fields=['source', 'start_ms'], name='transcripti_source__6dec98_idx'),
        ),
        migrations.AddIndex(
            model_name='transcriptsegment',
            index=models.Index(fields=['job', 'index'], name='transcripti_job_id_231390_idx'),
        ),
        migrations.AddIndex(
            model_name='transcriptionjob',
            index=models.Index(fields=['source', 'status'], name='transcripti_source__a8b725_idx'),
        ),
        migrations.AddIndex(
            model_name='transcriptionjob',
            index=models.Index(fields=['status', 'created_at'], name='transcripti_status_93d188_idx'),
        ),
        migrations.AddIndex(
            model_name='transcriptevent',
            index=models.Index(fields=['source', 'event', 'created_at'], name='transcripti_source__3c7a4b_idx'),
        ),
        migrations.AddIndex(
            model_name='transcriptevent',
            index=models.Index(fields=['event', 'created_at'], name='transcripti_event_1411a7_idx'),
        ),
        migrations.AddIndex(
            model_name='transcriptcollection',
            index=models.Index(fields=['access_mode', 'position'], name='transcripti_access__0c3370_idx'),
        ),
        migrations.AddIndex(
            model_name='transcriptcollection',
            index=models.Index(fields=['slug'], name='transcripti_slug_731190_idx'),
        ),
        migrations.AddIndex(
            model_name='transcriptartifact',
            index=models.Index(fields=['source', 'kind'], name='transcripti_source__ef64ab_idx'),
        ),
    ]
