# Generated by Django 4.2.23 on 2026-05-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptionjob',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='Celery task ID for async jobs — used for revocation.', max_length=255),
        ),
    ]
