# Generated by Django 4.2.23 on 2026-05-28 09:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0003_add_whisper_model_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('backend', models.CharField(choices=[('faster_whisper', 'Audio Interpreter Fast'), ('openai_whisper', 'Audio Interpreter AI')], default='faster_whisper', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False, help_text='Use this model for jobs targeting its backend.')),
                ('weights_file', models.FileField(blank=True, help_text='Model weights file. faster-whisper: .zip of the CTranslate2 model directory. openai-whisper: .pt weights file. Can be populated via the Download action instead of a manual upload.', null=True, upload_to='speech_models/')),
                ('model_size', models.CharField(blank=True, help_text='Fallback identifier when no weights_file is available: tiny / base / small / medium / large-v3', max_length=32)),
                ('device', models.CharField(choices=[('cpu', 'CPU'), ('cuda', 'GPU (CUDA)')], default='cpu', max_length=16)),
                ('compute_type', models.CharField(blank=True, default='int8', help_text='faster-whisper only: int8, float16, float32, auto', max_length=16)),
                ('beam_size', models.PositiveSmallIntegerField(default=5)),
                ('language', models.CharField(blank=True, help_text='Default language code (e.g. en, pl). Blank = auto-detect per job.', max_length=8)),
                ('download_source', models.CharField(blank=True, help_text='HuggingFace repo ID (e.g. Systran/faster-whisper-small) or direct HTTPS URL to a .pt file. Simple size names (small, base, tiny…) are also accepted and resolved automatically.', max_length=512)),
                ('download_status', models.CharField(choices=[('idle', 'Idle'), ('downloading', 'Downloading…'), ('done', 'Done'), ('failed', 'Failed')], default='idle', max_length=16)),
                ('download_progress', models.PositiveSmallIntegerField(default=0)),
                ('download_error', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['backend', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='transcriptionjob',
            name='engine',
            field=models.CharField(choices=[('default', 'Default backend'), ('openai_whisper', 'Audio Interpreter AI'), ('faster_whisper', 'Audio Interpreter Fast'), ('command', 'Command backend'), ('custom', 'Custom callable')], default='default', max_length=40),
        ),
        migrations.DeleteModel(
            name='WhisperModelConfig',
        ),
    ]
