# Generated by Django 4.2.23 on 2026-10-01 05:49

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('country_name', models.CharField(blank=True, max_length=2, verbose_name='Country')),
                ('state_or_province_name', models.CharField(blank=True, max_length=128, verbose_name='State/Province')),
                ('locality_name', models.CharField(blank=True, max_length=128, verbose_name='Locality')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='Street')),
                ('building', models.CharField(blank=True, max_length=64, verbose_name='Building Number')),
                ('apartment', models.CharField(blank=True, max_length=64, null=True, verbose_name='Apartment Number')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Free-form JSON metadata for this location.')),
                ('note', models.TextField(blank=True, help_text='Free-text note about this address.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AddressInDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LocationsQuotaPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('metric_code', models.CharField(db_index=True, max_length=100)),
                ('limit', models.DecimalField(decimal_places=10, max_digits=30)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime')], default='daily', max_length=20)),
                ('mode', models.CharField(choices=[('track', 'Track only'), ('warn', 'Warn'), ('block', 'Block')], default='block', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Locations quota policy',
                'verbose_name_plural': 'Locations quota policies',
                'ordering': ['metric_code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocationsUsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_code', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=30)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('source_type', models.CharField(blank=True, max_length=100)),
                ('source_id', models.CharField(blank=True, max_length=255)),
                ('source_label', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('recorded', 'Recorded'), ('voided', 'Voided')], default='recorded', max_length=20)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Locations usage event',
                'verbose_name_plural': 'Locations usage events',
                'ordering': ['-occurred_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MapDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MapDomainClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MapLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, help_text='Examples: °C, %, mm, ppm, people/km²', max_length=32)),
                ('min_value', models.FloatField(blank=True, help_text='Optional display minimum for color scaling.', null=True)),
                ('max_value', models.FloatField(blank=True, help_text='Optional display maximum for color scaling.', null=True)),
                ('style', models.JSONField(blank=True, default=dict, help_text='Frontend style config: color scale, opacity, legend, etc.')),
                ('inverted_importance', models.BooleanField(default=False, help_text='Invert value importance before color scaling.')),
                ('half_range', models.BooleanField(default=False, help_text='Use only the low-to-mid half of the color scale.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('geometry', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Free-form JSON metadata for this location.')),
                ('notes', models.TextField(blank=True, help_text='Free-text notes about this route.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('end_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_ends', to='locations.address')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RouteChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Free-form JSON metadata for this location.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Free-form JSON metadata for this location.')),
                ('capital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='territory_capitals', to='locations.address')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Free-form JSON metadata for this location.')),
                ('territory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='locations.territory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZoneInDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_rows', to='locations.mapdomain')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_rows', to='locations.zone')),
            ],
        ),
        migrations.CreateModel(
            name='TerritoryInDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='territory_rows', to='locations.mapdomain')),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_rows', to='locations.territory')),
            ],
        ),
        migrations.CreateModel(
            name='RouteInDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_rows', to='locations.mapdomain')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_rows', to='locations.route')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='route_chain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='locations.routechain'),
        ),
        migrations.AddField(
            model_name='route',
            name='start_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_starts', to='locations.address'),
        ),
        migrations.CreateModel(
            name='MapLayerPolygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(help_text='Must be one continuous polygon.', srid=4326)),
                ('center', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Stored center point used for layer labels and markers.', null=True, srid=4326)),
                ('value', models.FloatField()),
                ('properties', models.JSONField(blank=True, default=dict, help_text='Optional metadata for frontend/domain use.')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polygons', to='locations.maplayer')),
            ],
        ),
        migrations.CreateModel(
            name='MapLayerInDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_layer_rows', to='locations.mapdomain')),
                ('map_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_rows', to='locations.maplayer')),
            ],
        ),
    ]
