# Generated by Django 4.2.23 on 2026-10-01 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socialhub', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapdomainclearance',
            name='clearance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='map_domain_rows', to='socialhub.clearance'),
        ),
        migrations.AddField(
            model_name='mapdomainclearance',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearance_rows', to='locations.mapdomain'),
        ),
        migrations.AddField(
            model_name='locationsusageevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='locationsquotapolicy',
            constraint=models.UniqueConstraint(fields=('metric_code',), name='locations_locationsquotapolicy_one_per_metric'),
        ),
        migrations.AddField(
            model_name='addressindomain',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_rows', to='locations.address'),
        ),
        migrations.AddField(
            model_name='addressindomain',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_rows', to='locations.mapdomain'),
        ),
        migrations.AddField(
            model_name='address',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='zoneindomain',
            constraint=models.UniqueConstraint(fields=('domain', 'zone'), name='locations_zone_in_domain_once'),
        ),
        migrations.AddConstraint(
            model_name='territoryindomain',
            constraint=models.UniqueConstraint(fields=('domain', 'territory'), name='locations_territory_in_domain_once'),
        ),
        migrations.AddConstraint(
            model_name='routeindomain',
            constraint=models.UniqueConstraint(fields=('domain', 'route'), name='locations_route_in_domain_once'),
        ),
        migrations.AddIndex(
            model_name='maplayerpolygon',
            index=models.Index(fields=['layer'], name='locations_m_layer_i_ecb370_idx'),
        ),
        migrations.AddConstraint(
            model_name='maplayerindomain',
            constraint=models.UniqueConstraint(fields=('domain', 'map_layer'), name='locations_layer_in_domain_once'),
        ),
        migrations.AddConstraint(
            model_name='mapdomainclearance',
            constraint=models.UniqueConstraint(fields=('domain', 'clearance'), name='locations_domain_clearance_once'),
        ),
        migrations.AddIndex(
            model_name='locationsusageevent',
            index=models.Index(fields=['metric_code', 'occurred_at'], name='locationsusageevent_mtime'),
        ),
        migrations.AddIndex(
            model_name='locationsusageevent',
            index=models.Index(fields=['user', 'metric_code'], name='locationsusageevent_umetric'),
        ),
        migrations.AddConstraint(
            model_name='locationsusageevent',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('idempotency_key',), name='locations_locationsusageevent_idem'),
        ),
        migrations.AddConstraint(
            model_name='addressindomain',
            constraint=models.UniqueConstraint(fields=('domain', 'address'), name='locations_address_in_domain_once'),
        ),
    ]
