# Generated for toto.subscriptions
import uuid
from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("assets", "0001_initial"),
        ("people", "0001_initial"),
        ("socialhub", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("name", models.CharField(max_length=160)),
                ("slug", models.SlugField(max_length=180)),
                ("code", models.SlugField(max_length=80)),
                ("kind", models.CharField(choices=[("ai", "AI"), ("storage", "Storage"), ("academy", "Academy"), ("community", "Community"), ("support", "Support"), ("bundle", "Bundle"), ("custom", "Custom")], default="custom", max_length=32)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("active", "Active"), ("paused", "Paused"), ("archived", "Archived")], default="draft", max_length=24)),
                ("description", models.TextField(blank=True)),
                ("is_public", models.BooleanField(default=True)),
                ("trial_days", models.PositiveIntegerField(default=0)),
                ("max_subscribers", models.PositiveIntegerField(blank=True, null=True)),
                ("community", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subscription_plans", to="socialhub.community")),
                ("owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="owned_subscription_plans", to="people.person")),
            ],
            options={"ordering": ["community", "name"]},
        ),
        migrations.CreateModel(
            name="SubscriptionCustomer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(choices=[("active", "Active"), ("blocked", "Blocked"), ("archived", "Archived")], default="active", max_length=24)),
                ("label", models.CharField(blank=True, max_length=160)),
                ("billing_account", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="subscription_customer_profiles", to="assets.ledgeraccount")),
                ("community", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subscription_customers", to="socialhub.community")),
                ("default_asset", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="subscription_customers", to="assets.asset")),
                ("person", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subscription_customers", to="people.person")),
            ],
            options={"ordering": ["community", "person"]},
        ),
        migrations.CreateModel(
            name="SubscriptionPrice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("name", models.CharField(default="Default", max_length=120)),
                ("code", models.SlugField(max_length=80)),
                ("amount_base_units", models.BigIntegerField(default=0)),
                ("interval", models.CharField(choices=[("once", "Once"), ("daily", "Daily"), ("weekly", "Weekly"), ("monthly", "Monthly"), ("quarterly", "Quarterly"), ("yearly", "Yearly"), ("custom", "Custom")], default="monthly", max_length=24)),
                ("interval_count", models.PositiveIntegerField(default=1)),
                ("setup_fee_base_units", models.BigIntegerField(default=0)),
                ("payer_must_prepay", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("asset", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="subscription_prices", to="assets.asset")),
                ("plan", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="prices", to="subscriptions.subscriptionplan")),
                ("receiving_account", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="subscription_price_receipts", to="assets.ledgeraccount")),
            ],
            options={"ordering": ["plan", "amount_base_units"]},
        ),
        migrations.CreateModel(
            name="SubscriptionFeature",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("code", models.SlugField(max_length=100)),
                ("name", models.CharField(max_length=160)),
                ("kind", models.CharField(choices=[("entitlement", "Entitlement"), ("allowance", "Allowance"), ("metered", "Metered"), ("boolean", "Boolean"), ("service_level", "Service level")], default="entitlement", max_length=32)),
                ("quantity", models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ("unit", models.CharField(blank=True, help_text="Examples: tokens, MB, uploads, seats, lessons.", max_length=32)),
                ("reset_interval", models.CharField(choices=[("once", "Once"), ("daily", "Daily"), ("weekly", "Weekly"), ("monthly", "Monthly"), ("quarterly", "Quarterly"), ("yearly", "Yearly"), ("custom", "Custom")], default="monthly", max_length=24)),
                ("hard_limit", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("plan", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="features", to="subscriptions.subscriptionplan")),
            ],
            options={"ordering": ["plan", "code"]},
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(choices=[("trialing", "Trialing"), ("active", "Active"), ("past_due", "Past due"), ("paused", "Paused"), ("cancelled", "Cancelled"), ("expired", "Expired")], default="active", max_length=24)),
                ("starts_at", models.DateTimeField()),
                ("current_period_start", models.DateTimeField()),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("trial_ends_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_at_period_end", models.BooleanField(default=False)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("source_object_id", models.CharField(blank=True, max_length=64)),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="subscriptions", to="subscriptions.subscriptioncustomer")),
                ("plan", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="subscriptions", to="subscriptions.subscriptionplan")),
                ("price", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="subscriptions", to="subscriptions.subscriptionprice")),
                ("source_content_type", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="subscription_sources", to="contenttypes.contenttype")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="SubscriptionEntitlement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(choices=[("active", "Active"), ("suspended", "Suspended"), ("expired", "Expired"), ("revoked", "Revoked")], default="active", max_length=24)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("feature", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="entitlements", to="subscriptions.subscriptionfeature")),
                ("subscription", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="entitlements", to="subscriptions.subscription")),
            ],
            options={"ordering": ["subscription", "feature"]},
        ),
        migrations.CreateModel(
            name="SubscriptionAllowance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("included_quantity", models.DecimalField(decimal_places=6, default=Decimal("0"), max_digits=24)),
                ("consumed_quantity", models.DecimalField(decimal_places=6, default=Decimal("0"), max_digits=24)),
                ("feature", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="allowances", to="subscriptions.subscriptionfeature")),
                ("subscription", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="allowances", to="subscriptions.subscription")),
            ],
            options={"ordering": ["subscription", "feature", "-period_start"]},
        ),
        migrations.CreateModel(
            name="SubscriptionUsage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=24)),
                ("unit", models.CharField(blank=True, max_length=32)),
                ("occurred_at", models.DateTimeField()),
                ("status", models.CharField(choices=[("recorded", "Recorded"), ("applied", "Applied"), ("over_limit", "Over limit"), ("void", "Void")], default="recorded", max_length=24)),
                ("note", models.TextField(blank=True)),
                ("source_object_id", models.CharField(blank=True, max_length=64)),
                ("allowance", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="usage_records", to="subscriptions.subscriptionallowance")),
                ("feature", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="usage_records", to="subscriptions.subscriptionfeature")),
                ("source_content_type", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="subscription_usage_sources", to="contenttypes.contenttype")),
                ("subscription", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="usage_records", to="subscriptions.subscription")),
            ],
            options={"ordering": ["-occurred_at"]},
        ),
        migrations.CreateModel(
            name="SubscriptionInvoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("open", "Open"), ("paid", "Paid"), ("partial", "Partial"), ("void", "Void"), ("failed", "Failed")], default="draft", max_length=24)),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("due_at", models.DateTimeField()),
                ("subtotal_base_units", models.BigIntegerField(default=0)),
                ("discount_base_units", models.BigIntegerField(default=0)),
                ("tax_base_units", models.BigIntegerField(default=0)),
                ("total_base_units", models.BigIntegerField(default=0)),
                ("paid_base_units", models.BigIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="subscription_invoices", to="subscriptions.subscriptioncustomer")),
                ("ledger_transaction", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="subscription_invoices", to="assets.ledgertransaction")),
                ("price", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="invoices", to="subscriptions.subscriptionprice")),
                ("subscription", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="invoices", to="subscriptions.subscription")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="SubscriptionInvoiceLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("kind", models.CharField(choices=[("subscription", "Subscription"), ("setup", "Setup fee"), ("overage", "Overage"), ("adjustment", "Adjustment"), ("credit", "Credit")], default="subscription", max_length=24)),
                ("description", models.CharField(max_length=240)),
                ("quantity", models.DecimalField(decimal_places=6, default=Decimal("1"), max_digits=18)),
                ("unit_amount_base_units", models.BigIntegerField(default=0)),
                ("amount_base_units", models.BigIntegerField(default=0)),
                ("invoice", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="subscriptions.subscriptioninvoice")),
            ],
            options={"ordering": ["invoice", "created_at"]},
        ),
        migrations.CreateModel(
            name="SubscriptionPayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("amount_base_units", models.BigIntegerField()),
                ("status", models.CharField(choices=[("pending", "Pending"), ("succeeded", "Succeeded"), ("failed", "Failed"), ("reversed", "Reversed")], default="pending", max_length=24)),
                ("reference", models.CharField(blank=True, max_length=180)),
                ("error_message", models.TextField(blank=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("invoice", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payments", to="subscriptions.subscriptioninvoice")),
                ("ledger_transaction", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="subscription_payments", to="assets.ledgertransaction")),
                ("payer_account", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="subscription_payments_sent", to="assets.ledgeraccount")),
                ("receiving_account", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="subscription_payments_received", to="assets.ledgeraccount")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="SubscriptionEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("kind", models.CharField(choices=[("customer_created", "Customer created"), ("plan_created", "Plan created"), ("subscription_created", "Subscription created"), ("subscription_renewed", "Subscription renewed"), ("subscription_cancelled", "Subscription cancelled"), ("usage_recorded", "Usage recorded"), ("invoice_created", "Invoice created"), ("invoice_paid", "Invoice paid"), ("payment_failed", "Payment failed"), ("entitlement_granted", "Entitlement granted")], max_length=40)),
                ("target_object_id", models.CharField(blank=True, max_length=64)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="subscription_events", to="people.person")),
                ("community", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subscription_events", to="socialhub.community")),
                ("subscription", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="events", to="subscriptions.subscription")),
                ("target_content_type", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="subscription_event_targets", to="contenttypes.contenttype")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddConstraint("SubscriptionPlan", models.UniqueConstraint(fields=("community", "slug"), name="uniq_subscription_plan_slug_per_community")),
        migrations.AddConstraint("SubscriptionPlan", models.UniqueConstraint(fields=("community", "code"), name="uniq_subscription_plan_code_per_community")),
        migrations.AddConstraint("SubscriptionCustomer", models.UniqueConstraint(fields=("community", "person"), name="uniq_subscription_customer_per_community_person")),
        migrations.AddConstraint("SubscriptionPrice", models.UniqueConstraint(fields=("plan", "code"), name="uniq_subscription_price_code_per_plan")),
        migrations.AddConstraint("SubscriptionFeature", models.UniqueConstraint(fields=("plan", "code"), name="uniq_subscription_feature_code_per_plan")),
        migrations.AddConstraint("SubscriptionEntitlement", models.UniqueConstraint(fields=("subscription", "feature"), name="uniq_entitlement_per_subscription_feature")),
        migrations.AddConstraint("SubscriptionAllowance", models.UniqueConstraint(fields=("subscription", "feature", "period_start"), name="uniq_allowance_period_per_feature")),
    ]
