# Generated by Django 4.2.23 on 2026-05-26 23:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='current_period_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='source_object_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='starts_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subscriptionentitlement',
            name='starts_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subscriptionevent',
            name='target_object_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='subscriptioninvoice',
            name='due_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subscriptionusage',
            name='occurred_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subscriptionusage',
            name='source_object_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['customer', 'status'], name='subscriptio_custome_cea13a_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['plan', 'status'], name='subscriptio_plan_id_f7cbce_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['current_period_end', 'status'], name='subscriptio_current_ae50a9_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['source_content_type', 'source_object_id'], name='subscriptio_source__79065d_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionallowance',
            index=models.Index(fields=['subscription', 'period_start', 'period_end'], name='subscriptio_subscri_96b465_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptioncustomer',
            index=models.Index(fields=['community', 'status'], name='subscriptio_communi_0cc252_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptioncustomer',
            index=models.Index(fields=['person'], name='subscriptio_person__4acda2_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionentitlement',
            index=models.Index(fields=['subscription', 'status'], name='subscriptio_subscri_0c89fa_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionentitlement',
            index=models.Index(fields=['feature', 'status'], name='subscriptio_feature_a118ff_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionevent',
            index=models.Index(fields=['community', 'kind', 'created_at'], name='subscriptio_communi_c6d026_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionevent',
            index=models.Index(fields=['subscription', 'created_at'], name='subscriptio_subscri_3f832a_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionevent',
            index=models.Index(fields=['target_content_type', 'target_object_id'], name='subscriptio_target__4f1400_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionfeature',
            index=models.Index(fields=['plan', 'kind', 'active'], name='subscriptio_plan_id_e6356a_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptioninvoice',
            index=models.Index(fields=['subscription', 'status'], name='subscriptio_subscri_57ea27_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptioninvoice',
            index=models.Index(fields=['customer', 'status'], name='subscriptio_custome_d00a5b_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptioninvoice',
            index=models.Index(fields=['due_at', 'status'], name='subscriptio_due_at_956efd_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptioninvoiceline',
            index=models.Index(fields=['invoice', 'kind'], name='subscriptio_invoice_aa1ec7_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionpayment',
            index=models.Index(fields=['invoice', 'status'], name='subscriptio_invoice_69b1af_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionpayment',
            index=models.Index(fields=['reference'], name='subscriptio_referen_d01fea_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['community', 'status', 'kind'], name='subscriptio_communi_7b7af6_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['code'], name='subscriptio_code_d07513_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionprice',
            index=models.Index(fields=['plan', 'is_active', 'interval'], name='subscriptio_plan_id_6d08cc_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionusage',
            index=models.Index(fields=['subscription', 'feature', 'occurred_at'], name='subscriptio_subscri_00d0af_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionusage',
            index=models.Index(fields=['status', 'occurred_at'], name='subscriptio_status_ceba11_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionusage',
            index=models.Index(fields=['source_content_type', 'source_object_id'], name='subscriptio_source__ded26a_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionallowance',
            constraint=models.CheckConstraint(check=models.Q(('included_quantity__gte', 0)), name='subscription_allowance_included_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionallowance',
            constraint=models.CheckConstraint(check=models.Q(('consumed_quantity__gte', 0)), name='subscription_allowance_consumed_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='subscriptioninvoice',
            constraint=models.CheckConstraint(check=models.Q(('subtotal_base_units__gte', 0)), name='subscription_invoice_subtotal_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='subscriptioninvoice',
            constraint=models.CheckConstraint(check=models.Q(('discount_base_units__gte', 0)), name='subscription_invoice_discount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='subscriptioninvoice',
            constraint=models.CheckConstraint(check=models.Q(('tax_base_units__gte', 0)), name='subscription_invoice_tax_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='subscriptioninvoice',
            constraint=models.CheckConstraint(check=models.Q(('total_base_units__gte', 0)), name='subscription_invoice_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='subscriptioninvoice',
            constraint=models.CheckConstraint(check=models.Q(('paid_base_units__gte', 0)), name='subscription_invoice_paid_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionpayment',
            constraint=models.CheckConstraint(check=models.Q(('amount_base_units__gt', 0)), name='subscription_payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionprice',
            constraint=models.CheckConstraint(check=models.Q(('amount_base_units__gte', 0)), name='subscription_price_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionprice',
            constraint=models.CheckConstraint(check=models.Q(('setup_fee_base_units__gte', 0)), name='subscription_setup_fee_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionprice',
            constraint=models.CheckConstraint(check=models.Q(('interval_count__gt', 0)), name='subscription_interval_count_positive'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionusage',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='subscription_usage_quantity_positive'),
        ),
    ]
