# Generated by Django 4.2.23 on 2026-05-28 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_add_digital_signature'),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='executed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Signatures'), ('executed', 'Executed')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='ContractSignatory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True, help_text='If True, this person must sign before the contract can be executed.')),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signature_data', models.TextField(blank=True, help_text='Base64-encoded PNG captured at signing time.')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatories', to='contracts.contract')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_signatories', to='people.person')),
            ],
            options={
                'ordering': ['added_at'],
                'unique_together': {('contract', 'person')},
            },
        ),
    ]
