# Generated by Django 4.2.23 on 2026-05-25 19:08

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('source_type', models.CharField(blank=True, max_length=100)),
                ('source_id', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TariffItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(help_text='Metric key, e.g. ai.input_tokens, storage.mb_hour', max_length=100)),
                ('price_per_unit_display', models.DecimalField(decimal_places=18, help_text='Human-readable price in asset display units', max_digits=30)),
                ('price_per_unit_base_units', models.BigIntegerField(help_text='Price in asset base units (integer)')),
                ('unit', models.CharField(choices=[('request', 'Request'), ('token', 'Token'), ('input_token', 'Input Token'), ('output_token', 'Output Token'), ('byte', 'Byte'), ('kb', 'KB'), ('mb', 'MB'), ('gb', 'GB'), ('second', 'Second'), ('minute', 'Minute'), ('hour', 'Hour'), ('mb_second', 'MB·Second'), ('mb_minute', 'MB·Minute'), ('mb_hour', 'MB·Hour'), ('gb_hour', 'GB·Hour'), ('node', 'Node'), ('relationship', 'Relationship'), ('custom', 'Custom')], max_length=20)),
                ('unit_quantity', models.DecimalField(decimal_places=6, default=Decimal('1'), help_text='Denominator: price applies per this many units, e.g. 1000 for per-1000-tokens pricing', max_digits=20)),
                ('minimum_charge_base_units', models.BigIntegerField(default=0, help_text='Minimum charge per usage event, in base units (0 = no minimum)')),
                ('rounding_mode', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('nearest', 'Nearest')], default='up', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charged_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tariff_items', to='assets.asset')),
                ('receiving_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tariff_items_receiving', to='assets.ledgeraccount')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tariffs.tariff')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('metric_code', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=30)),
                ('unit', models.CharField(choices=[('request', 'Request'), ('token', 'Token'), ('input_token', 'Input Token'), ('output_token', 'Output Token'), ('byte', 'Byte'), ('kb', 'KB'), ('mb', 'MB'), ('gb', 'GB'), ('second', 'Second'), ('minute', 'Minute'), ('hour', 'Hour'), ('mb_second', 'MB·Second'), ('mb_minute', 'MB·Minute'), ('mb_hour', 'MB·Hour'), ('gb_hour', 'GB·Hour'), ('node', 'Node'), ('relationship', 'Relationship'), ('custom', 'Custom')], max_length=20)),
                ('source_type', models.CharField(blank=True, max_length=100)),
                ('source_id', models.CharField(blank=True, max_length=255)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('rated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('rated', 'Rated'), ('posted', 'Posted'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ledger_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usage_records', to='assets.ledgertransaction')),
                ('payer_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_records_as_payer', to='assets.ledgeraccount')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_records', to='tariffs.tariff')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=30)),
                ('unit', models.CharField(choices=[('request', 'Request'), ('token', 'Token'), ('input_token', 'Input Token'), ('output_token', 'Output Token'), ('byte', 'Byte'), ('kb', 'KB'), ('mb', 'MB'), ('gb', 'GB'), ('second', 'Second'), ('minute', 'Minute'), ('hour', 'Hour'), ('mb_second', 'MB·Second'), ('mb_minute', 'MB·Minute'), ('mb_hour', 'MB·Hour'), ('gb_hour', 'GB·Hour'), ('node', 'Node'), ('relationship', 'Relationship'), ('custom', 'Custom')], max_length=20)),
                ('price_per_unit_base_units', models.BigIntegerField()),
                ('amount_base_units', models.BigIntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('charged_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_charges', to='assets.asset')),
                ('payer_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_charges_as_payer', to='assets.ledgeraccount')),
                ('receiving_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_charges_as_receiver', to='assets.ledgeraccount')),
                ('tariff_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='tariffs.tariffitem')),
                ('usage_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='tariffs.usagerecord')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tariff',
            index=models.Index(fields=['status'], name='tariffs_tar_status_e4bb02_idx'),
        ),
        migrations.AddIndex(
            model_name='tariff',
            index=models.Index(fields=['code'], name='tariffs_tar_code_c6f488_idx'),
        ),
        migrations.AddIndex(
            model_name='tariff',
            index=models.Index(fields=['source_type', 'source_id'], name='tariffs_tar_source__f29187_idx'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['tariff', 'status'], name='tariffs_usa_tariff__e6831a_idx'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['payer_account', 'status'], name='tariffs_usa_payer_a_53277a_idx'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['metric_code'], name='tariffs_usa_metric__b2cfff_idx'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['status'], name='tariffs_usa_status_1dd79a_idx'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['source_type', 'source_id'], name='tariffs_usa_source__e122fb_idx'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['occurred_at'], name='tariffs_usa_occurre_b68b97_idx'),
        ),
        migrations.AddIndex(
            model_name='tariffitem',
            index=models.Index(fields=['tariff', 'active'], name='tariffs_tar_tariff__baa8c5_idx'),
        ),
        migrations.AddIndex(
            model_name='tariffitem',
            index=models.Index(fields=['code'], name='tariffs_tar_code_73de00_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tariffitem',
            unique_together={('tariff', 'code')},
        ),
    ]
