# Generated by Django 4.2.23 on 2026-05-25 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0003_remove_billingunit'),
    ]

    operations = [
        # Wipe demo data that references TariffItem.unit (varchar that becomes FK).
        # All rows are re-seeded by ingress after migration.
        migrations.RunSQL(
            "DELETE FROM tariffs_usagecharge; DELETE FROM tariffs_usagerecord; DELETE FROM tariffs_tariffitem;",
            migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='BillingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('dimension', models.CharField(blank=True, max_length=50)),
                ('app_label', models.CharField(blank=True, max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['dimension', 'code'],
            },
        ),
        migrations.AlterField(
            model_name='tariffitem',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tariff_items', to='tariffs.billingunit'),
        ),
    ]
