# Generated by Django 4.2.23 on 2026-10-01 05:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeatEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('task', models.CharField(max_length=200)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'beat entries',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CheckState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, unique=True)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(max_length=10)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('since', models.DateTimeField(default=django.utils.timezone.now)),
                ('bad_since', models.DateTimeField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('alerted_status', models.CharField(blank=True, max_length=10)),
                ('alerted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sys_cpu_percent', models.FloatField(blank=True, null=True)),
                ('sys_load_1m', models.FloatField(blank=True, null=True)),
                ('sys_mem_used_bytes', models.BigIntegerField(blank=True, null=True)),
                ('sys_mem_limit_bytes', models.BigIntegerField(blank=True, null=True)),
                ('sys_disk_used_bytes', models.BigIntegerField(blank=True, null=True)),
                ('sys_disk_total_bytes', models.BigIntegerField(blank=True, null=True)),
                ('db_ok', models.BooleanField(blank=True, null=True)),
                ('db_latency_ms', models.FloatField(blank=True, null=True)),
                ('redis_ok', models.BooleanField(blank=True, null=True)),
                ('redis_latency_ms', models.FloatField(blank=True, null=True)),
                ('redis_used_memory_bytes', models.BigIntegerField(blank=True, null=True)),
                ('redis_connected_clients', models.IntegerField(blank=True, null=True)),
                ('celery_ok', models.BooleanField(blank=True, null=True)),
                ('celery_workers', models.IntegerField(blank=True, null=True)),
                ('tor_ctrl_ok', models.BooleanField(blank=True, null=True)),
                ('onion_enabled', models.BooleanField(blank=True, null=True)),
                ('clearnet_enabled', models.BooleanField(blank=True, null=True)),
                ('onion_published', models.BooleanField(blank=True, null=True)),
                ('aster_devices_total', models.IntegerField(blank=True, null=True)),
                ('aster_devices_fresh', models.IntegerField(blank=True, null=True)),
                ('web_ok', models.BooleanField(blank=True, null=True)),
                ('web_latency_ms', models.FloatField(blank=True, null=True)),
                ('web_process_start', models.FloatField(blank=True, null=True)),
                ('web_rss_bytes', models.BigIntegerField(blank=True, null=True)),
                ('web_cpu_seconds', models.FloatField(blank=True, null=True)),
                ('web_requests_total', models.BigIntegerField(blank=True, null=True)),
                ('web_responses_5xx', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created',),
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(default='running', max_length=20)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('error', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ('-started_at', '-pk'),
                'get_latest_by': 'started_at',
                'indexes': [models.Index(fields=['task', '-started_at'], name='monit_taskrun_task_started')],
            },
        ),
    ]
