# Generated by Django 4.2.23 on 2026-10-01 01:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, unique=True)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(max_length=10)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('since', models.DateTimeField(default=django.utils.timezone.now)),
                ('bad_since', models.DateTimeField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('alerted_status', models.CharField(blank=True, max_length=10)),
                ('alerted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('key',),
            },
        ),
    ]
