from django.utils import timezone
from django.contrib.auth.models import User
from lorem_text import lorem
from oya.ingress import IngressCommand
from documents.models import (
    Tag, Department,
    HTMLPreset, LatexPreset,
    LatexDocument, HTMLDocument,
    DocumentEditor, EditorSection, EditorSubSection
)

class Command(IngressCommand):
    help = "Seed LaTeX and HTML documents with editors, presets, departments, and tags"

    def process(self, _):
        self.create_dashboard_item(
            title="Documents",
            icon="file-text",
            description="LaTeX and HTML documents with presets, departments, tags, and structured editors.",
            link="/documents/"
        )

        self.stdout.write("🚀 Starting document ingress...")

        users = list(User.objects.all())
        if not users:
            self.stdout.write(self.style.ERROR("❌ No users found. Create at least one user before running ingress."))
            return

        # 📌 Tags
        tag_names = ['Research', 'Internal', 'Public', 'Confidential', 'Draft']
        tags = [Tag.objects.get_or_create(name=name)[0] for name in tag_names]

        # 🏢 Departments
        departments = [
            Department.objects.create(
                name=f"Department {i+1}",
                owner=users[i % len(users)],
                copyright_holder="SpectrumAi.pl",
                copyright_notice=(
                    "This document is confidential and intended solely for the use "
                    "of the individual or entity to whom it is addressed. "
                    "Unauthorized distribution, reproduction, or disclosure is strictly prohibited."
                )
            )
            for i in range(3)
        ]

        # 🎨 Presets
        html_preset = HTMLPreset.objects.create(
            name="HTML Preset",
            description="Default HTML setup",
            css_classes={},
            style_mapping={
                "h1": "text-3xl font-bold mt-8 mb-4",
                "h2": "text-2xl font-semibold mt-6 mb-3",
                "h3": "text-2xl font-medium mt-4 mb-2",
                "p": "mb-4 leading-relaxed",
                "div.summary": "text-sm italic text-gray-600 dark:text-gray-400 mb-6"
            },
            footer_html="<footer>Generated by Copilot</footer>"
        )

        latex_preset = LatexPreset.objects.create(
            name="LaTeX Preset",
            description="Default LaTeX setup",
            document_class='article',
            preamble="",
            packages=["amsmath", "geometry", "graphicx"],
            footer_note=lorem.sentence()
        )

        # 📄 Create LaTeX and HTML Documents + Editors
        for i in range(2):
            user = users[i % len(users)]
            department = departments[i % len(departments)]

            # LaTeX
            latex_doc = LatexDocument.objects.create(
                title=f"LaTeX Document {i+1}",
                content="",
                created_by=user,
                department=department,
                created_at=timezone.now(),
                preset=latex_preset
            )
            latex_doc.tags.set(tags)
            self.stdout.write(f"📄 Created: {latex_doc.title}")

            latex_editor = DocumentEditor.objects.create(
                title=f"LaTeX Editor {i+1}",
                created_by=user,
                department=department,
                document=latex_doc
            )

            for j in range(2):
                section = EditorSection.objects.create(
                    document=latex_editor,
                    order=j,
                    title=f"LaTeX Section {j+1}",
                    content=lorem.paragraph()
                )
                for k in range(2):
                    EditorSubSection.objects.create(
                        section=section,
                        order=k,
                        title=f"LaTeX Subsection {j+1}.{k+1}",
                        content=lorem.paragraph()
                    )

            # HTML
            html_doc = HTMLDocument.objects.create(
                title=f"HTML Document {i+1}",
                content="",
                created_by=user,
                department=department,
                created_at=timezone.now(),
                preset=html_preset
            )
            html_doc.tags.set(tags)
            self.stdout.write(f"🌐 Created: {html_doc.title}")

            html_editor = DocumentEditor.objects.create(
                title=f"HTML Editor {i+1}",
                created_by=user,
                department=department,
                document=html_doc
            )

            for j in range(2):
                section = EditorSection.objects.create(
                    document=html_editor,
                    order=j,
                    title=f"HTML Section {j+1}",
                    content=lorem.paragraph()
                )
                for k in range(2):
                    EditorSubSection.objects.create(
                        section=section,
                        order=k,
                        title=f"HTML Subsection {j+1}.{k+1}",
                        content=lorem.paragraph()
                    )

        self.stdout.write(self.style.SUCCESS("🎉 Ingress complete. Documents and editors seeded."))
