import itertools
from django.utils import timezone
from django.contrib.auth.models import User
from lorem_text import lorem
from oya.ingress import IngressCommand
from documents.models import (
    Tag, Department,
    LatexPreset, HTMLPreset,
    Document, Section, SubSection
)

class Command(IngressCommand):
    help = "Seed documents with all engine-depth combinations using existing users"

    def process(self, _):
        self.create_dashboard_item(
            title="Documents",
            icon="file-text",
            description="Presets, departments, and structured documents with sections and subsections.",
            link="/documents/"
        )

        self.stdout.write("🚀 Starting document ingress...")

        users = list(User.objects.all())
        if not users:
            self.stdout.write(self.style.ERROR("❌ No users found. Create at least one user before running ingress."))
            return

        # Tags
        tag_names = ['Research', 'Internal', 'Public', 'Confidential', 'Draft']
        tags = [Tag.objects.get_or_create(name=name)[0] for name in tag_names]

        # Departments
        departments = [
            Department.objects.create(name=f"Department {i+1}", owner=users[i % len(users)])
            for i in range(3)
        ]

        # Presets
        presets = []
        for engine, depth in itertools.product(['latex', 'html'], [1, 2, 3]):
            if engine == 'latex':
                preset = LatexPreset.objects.create(
                    name=f"LaTeX Preset Depth {depth}",
                    engine='latex',
                    depth=depth,
                    document_class='article',
                    preamble=lorem.paragraph(),
                    packages=["amsmath", "geometry", "graphicx"],
                    footer_note=lorem.sentence()
                )
            else:
                preset = HTMLPreset.objects.create(
                    name=f"HTML Preset Depth {depth}",
                    engine='html',
                    depth=depth,
                    template_name=f"template_depth_{depth}.html",
                    css_classes={"body": "bg-white text-black", "header": "font-bold"},
                    script_includes=["https://cdn.example.com/script.js"],
                    footer_html="<footer>Generated by Copilot</footer>"
                )
            presets.append(preset)

        # Documents
        for i, preset in enumerate(presets):
            doc = Document(
                title=f"Document for {preset.name}",
                preset=preset,
                summary=lorem.sentence(),
                created_by=users[i % len(users)],
                department=departments[i % len(departments)],
                created_at=timezone.now()
            )

            if preset.depth == 1:
                doc.content = lorem.paragraph()

            doc.save()  # Must save before assigning tags
            doc.tags.set(tags)

            if preset.depth == 2:
                for j in range(3):
                    Section.objects.create(
                        document=doc,
                        title=f"Section {j+1}",
                        order=j,
                        content=lorem.paragraph()
                    )

            elif preset.depth == 3:
                for j in range(2):
                    section = Section.objects.create(
                        document=doc,
                        title=f"Section {j+1}",
                        order=j,
                        content=""
                    )
                    for k in range(2):
                        SubSection.objects.create(
                            section=section,
                            order=k,
                            title=f"SubSection {j+1}.{k+1}",
                            content=lorem.paragraph()
                        )

        self.stdout.write(self.style.SUCCESS("✅ Ingress complete. All engine-depth combinations seeded."))
