# Generated by Django 4.2.23 on 2026-05-31 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0004_contract_body_vault_pdf'),
        ('assets', '0007_remove_asset_mint_transaction_type'),
        ('people', '0004_person_preferred_language'),
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_fee_base_units', models.BigIntegerField(default=0)),
                ('billing_period', models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('custom', 'Custom')], default='monthly', max_length=20)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('next_billing_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lease', to='contracts.contract')),
                ('leased_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='inventory.realworldobject')),
                ('lessee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases_as_lessee', to='people.person')),
                ('lessee_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leases_as_lessee', to='assets.ledgeraccount')),
                ('lessor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases_as_lessor', to='people.person')),
                ('lessor_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leases_as_lessor', to='assets.ledgeraccount')),
                ('payment_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leases_as_payment', to='assets.asset')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'next_billing_at'], name='leasing_lea_status_3e0b4a_idx'), models.Index(fields=['lessor', 'status'], name='leasing_lea_lessor__4e306b_idx'), models.Index(fields=['lessee', 'status'], name='leasing_lea_lessee__afd9eb_idx')],
            },
        ),
    ]
