# Generated by Django 4.2.23 on 2025-10-18 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Investor',
        ),
    ]
