# Generated by Django 4.2.23 on 2025-11-11 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_community_federation'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharepackage',
            name='social_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_package_ownership', to='community.socialentity'),
        ),
    ]
