# Generated by Django 4.2.23 on 2025-10-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_chamber_default_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamber',
            name='strategy',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='chamber',
            name='manifest',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
