# Generated by Django 4.2.23 on 2025-11-08 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        ('finance', '0003_delete_obligation'),
        ('portfolio', '0002_alter_chamber_id_alter_company_id_alter_currency_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='venture',
        ),
        migrations.AddField(
            model_name='company',
            name='social_entity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='community.socialentity'),
        ),
        migrations.AlterField(
            model_name='chamber',
            name='default_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chambers', to='finance.currency'),
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
