# Generated by Django 4.2.23 on 2025-10-18 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_delete_investor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamber',
            name='total_stock_emitted',
        ),
    ]
