# Generated by Django 4.2.23 on 2025-11-08 15:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_delete_obligation'),
        ('portfolio', '0003_remove_transaction_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingRound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.currency')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funding_round', to='finance.transaction')),
                ('venture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_rounds', to='portfolio.venture')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
