# Generated by Django 4.2.23 on 2025-10-18 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shareholders', '0001_initial'),
        ('portfolio', '0003_remove_chamber_total_stock_emitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='venture',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventures', to='shareholders.company'),
        ),
    ]
