# Generated by Django 4.2.23 on 2025-10-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_chamber_strategy_alter_chamber_manifest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Associate',
        ),
        migrations.RenameField(
            model_name='investor',
            old_name='balance',
            new_name='stock_owned',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='kyc_verified',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='wallet_address',
        ),
        migrations.AddField(
            model_name='chamber',
            name='total_stock_emitted',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
