# Generated by Django 4.2.23 on 2025-11-11 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_address_id_alter_community_id_and_more'),
        ('portfolio', '0004_fundinground'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareholder',
            name='user',
        ),
        migrations.AddField(
            model_name='shareholder',
            name='social_entity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shareholder', to='community.socialentity'),
        ),
    ]
