# Generated by Django 4.2.23 on 2025-11-11 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_alter_project_venture'),
        ('portfolio', '0006_alter_fundinground_venture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Venture',
        ),
    ]
