# Generated by Django 4.2.23 on 2026-01-13 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gervazy', '0001_initial'),
        ('oya', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Federation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='Unique slug identifier for this federation', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, help_text='Optional logo for this federation', null=True, upload_to='federation_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.address')),
                ('platform', models.OneToOneField(help_text='Platform associated with this federation', on_delete=django.db.models.deletion.CASCADE, related_name='federation', to='oya.platform')),
            ],
        ),
        migrations.CreateModel(
            name='FederatedIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('federation', models.ForeignKey(help_text='Federation this identity belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='federated_identities', to='federal.federation')),
                ('rsa_keypair', models.OneToOneField(blank=True, help_text='RSA keypair associated with this identity', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identity', to='gervazy.rsakeypair')),
                ('user', models.ForeignKey(blank=True, help_text='Optional link to a Django User account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='federated_identities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='federatedidentity',
            constraint=models.UniqueConstraint(fields=('id', 'federation'), name='unique_id_federation'),
        ),
    ]
