# Generated by Django 4.2.23 on 2025-11-08 17:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Federation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='Unique slug identifier for this federation', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, help_text='Optional logo for this federation', null=True, upload_to='federation_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FederatedIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('federation', models.ForeignKey(help_text='Federation this identity belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='federated_identities', to='federal.federation')),
            ],
        ),
        migrations.AddConstraint(
            model_name='federatedidentity',
            constraint=models.UniqueConstraint(fields=('id', 'federation'), name='unique_id_federation'),
        ),
    ]
