# Generated by Django 4.2.23 on 2025-11-08 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gervazy', '0002_rsakeypair'),
        ('federal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='federatedidentity',
            name='rsa_keypair',
            field=models.OneToOneField(blank=True, help_text='RSA keypair associated with this identity', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identity', to='gervazy.rsakeypair'),
        ),
    ]
