# Generated by Django 4.2.23 on 2025-10-04 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gervazy', '0003_rsakeypair'),
        ('federal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthRSAKeyPair',
            fields=[
                ('rsakeypair_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gervazy.rsakeypair')),
                ('active', models.BooleanField(default=True)),
            ],
            bases=('gervazy.rsakeypair',),
        ),
        migrations.CreateModel(
            name='ExternalIdentityProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('issuer_url', models.URLField(unique=True)),
                ('audience', models.CharField(max_length=100)),
                ('jwks_url', models.URLField()),
                ('trusted', models.BooleanField(default=True)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IdentityProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('issuer_url', models.URLField(unique=True)),
                ('audience', models.CharField(max_length=100)),
                ('trusted', models.BooleanField(default=True)),
                ('rsa_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='federal.authrsakeypair')),
            ],
        ),
        migrations.CreateModel(
            name='LocalIdentityProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('issuer_url', models.URLField(unique=True)),
                ('audience', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('metadata_url', models.URLField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token_lifetime', models.PositiveIntegerField(default=300, help_text='Token lifetime in seconds')),
                ('rsa_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='federal.authrsakeypair')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='accesstoken',
            name='user',
        ),
        migrations.RemoveField(
            model_name='identitytoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='RSAKey',
        ),
        migrations.DeleteModel(
            name='TrustedIssuer',
        ),
        migrations.AlterField(
            model_name='federatedidentity',
            name='subject',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='federatedidentity',
            unique_together={('subject', 'issuer')},
        ),
        migrations.DeleteModel(
            name='AccessToken',
        ),
        migrations.DeleteModel(
            name='IdentityToken',
        ),
    ]
