# Generated by Django 4.2.23 on 2025-11-11 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('federal', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='federatedidentity',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Optional link to a Django User account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='federated_identities', to=settings.AUTH_USER_MODEL),
        ),
    ]
