# Generated by Django 4.2.23 on 2025-11-08 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0002_federatedidentity_rsa_keypair'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.CharField(max_length=255, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('verified', models.BooleanField(default=False)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='federal.federatedidentity')),
            ],
        ),
    ]
