# Generated by Django 4.2.23 on 2026-01-14 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_communitymember_date_of_birth_communitymember_email_and_more'),
        ('federal', '0002_identityprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityprofile',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identity_profiles', to='community.community'),
        ),
        migrations.AddField(
            model_name='identityprofile',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identity_profiles', to='community.communitymember'),
        ),
        migrations.AlterField(
            model_name='identityprofile',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='identityprofile',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='identityprofile',
            name='registration_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
