# Generated by Django 4.2.23 on 2025-10-05 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0002_authrsakeypair_externalidentityprovider_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IdentityProvider',
        ),
    ]
