# Generated by Django 4.2.23 on 2026-01-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0003_identityprofile_community_identityprofile_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='federation',
            name='is_foreign',
            field=models.BooleanField(default=False, help_text='Indicates whether this federation originates outside the local jurisdiction'),
        ),
    ]
