# Generated by Django 4.2.23 on 2025-10-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0003_delete_identityprovider'),
    ]

    operations = [
        migrations.AddField(
            model_name='localidentityprovider',
            name='logo',
            field=models.ImageField(blank=True, help_text='Optional logo for this identity provider', null=True, upload_to='identity_provider_logos/'),
        ),
    ]
