# Generated by Django 4.2.23 on 2026-01-14 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gervazy', '0001_initial'),
        ('federal', '0004_federation_is_foreign'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='federatedidentity',
            name='unique_id_federation',
        ),
        migrations.RemoveField(
            model_name='federatedidentity',
            name='federation',
        ),
        migrations.AddField(
            model_name='federatedidentity',
            name='profile',
            field=models.OneToOneField(blank=True, help_text='IdentityProfile associated with this federated identity', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='federated_identity', to='federal.identityprofile'),
        ),
        migrations.AlterField(
            model_name='federatedidentity',
            name='name',
            field=models.CharField(blank=True, help_text='Human-readable label for this federated identity', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='federatedidentity',
            name='rsa_keypair',
            field=models.OneToOneField(blank=True, help_text='RSA keypair used for signing/verification', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='federated_identity', to='gervazy.rsakeypair'),
        ),
        migrations.AlterField(
            model_name='federatedidentity',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Optional link to a Django User', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='federated_identities', to=settings.AUTH_USER_MODEL),
        ),
    ]
