# Generated by Django 4.2.23 on 2025-10-05 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('federal', '0005_federation_remove_localidentityprovider_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalidentityprovider',
            name='federation',
            field=models.ForeignKey(blank=True, help_text='Federation this provider belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_identity_providers', to='federal.federation'),
        ),
        migrations.AddField(
            model_name='federatedidentity',
            name='federation',
            field=models.ForeignKey(blank=True, help_text='Federation this identity belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='federated_identities', to='federal.federation'),
        ),
        migrations.AddField(
            model_name='localidentityprovider',
            name='federation',
            field=models.ForeignKey(blank=True, help_text='Federation this provider belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_identity_providers', to='federal.federation'),
        ),
    ]
