# Generated by Django 4.2.23 on 2026-05-30 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vault', '0018_alter_vaultfile_file_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('input_files', models.JSONField(blank=True, default=list, help_text='List of VaultFile IDs for concat')),
                ('params', models.JSONField(blank=True, default=dict)),
                ('rendered_argv', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=20)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('progress_message', models.CharField(blank=True, max_length=255)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('stdout', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('output_metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('input_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_jobs_as_input', to='vault.vaultfile')),
                ('output_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_jobs_as_output', to='vault.vaultfile')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_jobs', to=settings.AUTH_USER_MODEL)),
                ('secondary_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_jobs_as_secondary', to='vault.vaultfile')),
                ('workflow_node_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_jobs', to='workflows.workflownoderun')),
                ('workflow_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_jobs', to='workflows.workflowrun')),
            ],
            options={
                'verbose_name': 'Media Job',
                'verbose_name_plural': 'Media Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProbeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('format', models.JSONField(blank=True, default=dict)),
                ('streams', models.JSONField(blank=True, default=list)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('video_codec', models.CharField(blank=True, max_length=50)),
                ('audio_codec', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='probe_results', to='videomant.mediajob')),
                ('vault_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probe_results', to='vault.vaultfile')),
            ],
            options={
                'verbose_name': 'Probe Result',
                'verbose_name_plural': 'Probe Results',
                'ordering': ['-created_at'],
            },
        ),
    ]
