# Generated by Django 4.2.23 on 2026-05-18 08:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0002_initial'),
        ('locations', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('visited_at', models.DateTimeField(blank=True, help_text='When the visit happened', null=True)),
                ('ends_at', models.DateTimeField(blank=True, help_text='When the visit ended (optional)', null=True)),
                ('score', models.PositiveSmallIntegerField(blank=True, help_text='Score from 1 to 5', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When this visit review was submitted', null=True)),
                ('review', models.TextField(blank=True, help_text='Optional review text', null=True)),
                ('location', models.ForeignKey(blank=True, help_text='Location that was visited', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='locations.address')),
                ('participant', models.ForeignKey(help_text='Person who made the visit', on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='people.person')),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('info', models.TextField(blank=True, help_text='Additional information about the travel')),
                ('score', models.PositiveSmallIntegerField(blank=True, help_text='Travel score from 1 to 5', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When this travel was reviewed or scored', null=True)),
                ('starts_at', models.DateTimeField(help_text='Travel start date and time')),
                ('ends_at', models.DateTimeField(help_text='Travel end date and time')),
                ('participants', models.ManyToManyField(help_text='People participating in this travel', related_name='travels', to='people.person')),
                ('route', models.ForeignKey(blank=True, help_text='Route used for this travel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travels', to='locations.route')),
            ],
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('score__gte', 1), ('score__lte', 5)), ('score__isnull', True), _connector='OR'), name='visit_score_between_1_and_5'),
        ),
        migrations.AddConstraint(
            model_name='travel',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('score__gte', 1), ('score__lte', 5)), ('score__isnull', True), _connector='OR'), name='travel_score_between_1_and_5'),
        ),
    ]
