# Generated by Django 4.2.23 on 2026-05-16 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='travel',
                    name='participants',
                    field=models.ManyToManyField(help_text='People participating in this travel', related_name='travels', to='people.person'),
                ),
                migrations.AlterField(
                    model_name='visit',
                    name='participant',
                    field=models.ForeignKey(help_text='Person who made the visit', on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='people.person'),
                ),
            ],
            database_operations=[],
        ),
    ]
