# Generated by Django 4.2.23 on 2026-05-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='ends_at',
            field=models.DateTimeField(blank=True, help_text='When the visit ended (optional)', null=True),
        ),
    ]
