# Generated by Django 4.2.23 on 2026-06-04 19:02

from django.db import migrations, models
import django.db.models.deletion
import toto.socialhub.models
import trix_editor.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('gervazy', '0001_initial'),
        ('people', '0001_initial'),
        ('api', '0002_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text='Name of the community or organization', max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier', unique=True)),
                ('org_type', models.CharField(choices=[('guild', 'Guild'), ('company', 'Company'), ('non_profit', 'Non-Profit'), ('family', 'Family'), ('other', 'Other')], default='other', help_text='Type of organization', max_length=20)),
                ('established_year', models.IntegerField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, help_text='Optional logo for this federation', null=True, upload_to='community_logos/')),
                ('is_autonomous', models.BooleanField(default=False, help_text='Marks this community as self-governing, with its own internal leadership and rules.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('is_foreign', models.BooleanField(default=False, help_text='Indicates whether this federation originates outside the local jurisdiction')),
                ('is_federal_tribe', models.BooleanField(default=False, help_text='Members of this community are exempt from all poll taxes (federal tax exemption).')),
                ('email_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_emails', to='api.emailservice')),
                ('federation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communities', to='core.federation')),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_communities', to='people.person')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_locations', to='locations.address')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent community in the hierarchy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='socialhub.community')),
                ('senior_members', models.ManyToManyField(blank=True, help_text='Members allowed to manage community announcements and news.', related_name='senior_communities', to='people.person')),
                ('territory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_territories', to='locations.territory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommunityNewsTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Community news topic',
                'verbose_name_plural': 'Community news topics',
            },
        ),
        migrations.CreateModel(
            name='Constitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('body', models.TextField()),
                ('version', models.CharField(blank=True, help_text='e.g. I, II, 2025-rev1', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Only the active constitution is shown on the community page.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constitutions', to='socialhub.community')),
            ],
            options={
                'verbose_name': 'Constitution',
                'verbose_name_plural': 'Constitutions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('code', models.CharField(default=toto.socialhub.models.generate_code, max_length=10, unique=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('endorsed', 'Endorsed'), ('invited', 'Invited'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='socialhub.community')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_requests', to='socialhub.membershipapplication')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_references', to='people.person')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityNewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', trix_editor.fields.TrixEditorField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('community', 'Community')], default='public', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_news_posts', to='people.person')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_posts', to='socialhub.community')),
                ('topics', models.ManyToManyField(blank=True, related_name='posts', to='socialhub.communitynewstopic')),
            ],
            options={
                'verbose_name': 'Community news post',
                'verbose_name_plural': 'Community news posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConstitutionSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signature_data', models.TextField(blank=True, help_text='Base64-encoded PNG — decorative handwritten signature image.')),
                ('signing_payload', models.TextField(blank=True, help_text='Canonical UTF-8 payload that was signed.')),
                ('cryptographic_signature', models.TextField(blank=True, help_text='Base64-encoded Ed25519 signature over signing_payload.')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('constitution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='socialhub.constitution')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constitution_signatures', to='people.person')),
                ('signing_key', models.ForeignKey(blank=True, help_text='The EncryptedPrivateKey used to produce the cryptographic signature.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='constitution_signatures', to='gervazy.encryptedprivatekey')),
            ],
            options={
                'verbose_name': 'Constitution signature',
                'verbose_name_plural': 'Constitution signatures',
                'ordering': ['added_at'],
                'unique_together': {('constitution', 'person')},
            },
        ),
    ]
