# Generated by Django 4.2.23 on 2026-10-01 05:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import toto.socialhub.models
import trix_editor.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='What it opens: internal, confidential.', max_length=120, unique=True, verbose_name='name')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('regen_security', models.DecimalField(blank=True, decimal_places=4, help_text="Blank: the pool's own rate.", max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='security mana per hour')),
                ('regen_compute', models.DecimalField(blank=True, decimal_places=4, help_text="Blank: the pool's own rate.", max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='compute mana per hour')),
                ('regen_storage', models.DecimalField(blank=True, decimal_places=4, help_text="Blank: the pool's own rate.", max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='storage mana per hour')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'clearance',
                'verbose_name_plural': 'clearances',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text='Name of the community or organization', max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier', unique=True)),
                ('org_type', models.CharField(choices=[('guild', 'Guild'), ('company', 'Company'), ('non_profit', 'Non-Profit'), ('family', 'Family'), ('other', 'Other')], default='other', help_text='Type of organization', max_length=20)),
                ('seat', models.CharField(blank=True, default='', help_text='Where the community has its seat, as text.', max_length=255)),
                ('established_year', models.IntegerField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, help_text='Optional logo for this federation', null=True, upload_to='community_logos/')),
                ('is_autonomous', models.BooleanField(default=False, help_text='Marks this community as self-governing, with its own internal leadership and rules.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('is_foreign', models.BooleanField(default=False, help_text='Indicates whether this federation originates outside the local jurisdiction')),
                ('is_federal_tribe', models.BooleanField(default=False, help_text="DEPRECATED as a live flag. It promised 'members are exempt from all poll taxes' for years; the poll tax that briefly existed (the head tax) has been removed, and what a community now does to what its members pay is a discount on a subscription plan — see toto.subscriptions.CommunityPlanDiscount. Kept because aurelian's mobilization app reads it by name for responder eligibility. Retiring it is an aurelian follow-up.")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommunityForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_slug', models.SlugField(help_text="The forum room's slug. Resolved when the page renders.", unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Community forum room',
                'verbose_name_plural': 'Community forum rooms',
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='CommunityNewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', trix_editor.fields.TrixEditorField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('community', 'Community')], default='public', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Community news post',
                'verbose_name_plural': 'Community news posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityNewsTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Community news topic',
                'verbose_name_plural': 'Community news topics',
            },
        ),
        migrations.CreateModel(
            name='CommunityPrivilege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('may_see_community_chain', models.BooleanField(default=False, help_text='Members may open the platform-wide community chain graph.')),
                ('may_administer_communities', models.BooleanField(default=False, help_text='Members may open the Administrata view of any community.')),
                ('may_manage_community_news', models.BooleanField(default=False, help_text='Members may publish news in ANY community, without being its head or a senior member.')),
                ('may_operate_mint', models.BooleanField(default=False, help_text='Members may operate the mint on a host that IS the monetary master. This does not grant minting authority: the master check asks whether the MACHINE holds an issuer private key and takes no user argument, so on a branch host this still refuses.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['community__name'],
            },
        ),
        migrations.CreateModel(
            name='DataExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Queued'), ('running', 'Being prepared'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'data export',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('code', models.CharField(default=toto.socialhub.models.generate_code, max_length=10, unique=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('endorsed', 'Endorsed'), ('invited', 'Invited'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('privacy_version', models.PositiveIntegerField(blank=True, null=True)),
                ('privacy_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='socialhub.community')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_requests', to='socialhub.membershipapplication')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_references', to='people.person')),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(unique=True)),
                ('text_pl', models.TextField()),
                ('text_en', models.TextField()),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'privacy notice',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='PrivacyAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_acceptances', to='people.person')),
            ],
            options={
                'verbose_name': 'privacy notice acceptance',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='PendingEmailChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_email', models.EmailField(max_length=254)),
                ('old_email', models.EmailField(blank=True, default='', max_length=254)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_email_change', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pending e-mail change',
            },
        ),
        migrations.CreateModel(
            name='ErasureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('open', 'Waiting for an operator'), ('done', 'Carried out'), ('declined', 'Declined')], default='open', max_length=10)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erasure_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'erasure request',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
