# Generated by Django 4.2.23 on 2026-10-01 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('socialhub', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0003_initial'),
        ('vault', '0001_initial'),
        ('people', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataexport',
            name='output',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vault.vaultfile'),
        ),
        migrations.AddField(
            model_name='dataexport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_exports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communityprivilege',
            name='community',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privilege', to='socialhub.community'),
        ),
        migrations.AddField(
            model_name='communitynewspost',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_news_posts', to='people.person'),
        ),
        migrations.AddField(
            model_name='communitynewspost',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_posts', to='socialhub.community'),
        ),
        migrations.AddField(
            model_name='communitynewspost',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='posts', to='socialhub.communitynewstopic'),
        ),
        migrations.AddField(
            model_name='communityforum',
            name='community',
            field=models.OneToOneField(help_text='The community whose room this is.', on_delete=django.db.models.deletion.CASCADE, related_name='forum', to='socialhub.community'),
        ),
        migrations.AddField(
            model_name='community',
            name='federation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communities', to='core.federation'),
        ),
        migrations.AddField(
            model_name='community',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_communities', to='people.person'),
        ),
        migrations.AddField(
            model_name='community',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_locations', to='locations.address'),
        ),
        migrations.AddField(
            model_name='community',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent community in the hierarchy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='socialhub.community'),
        ),
        migrations.AddField(
            model_name='community',
            name='senior_members',
            field=models.ManyToManyField(blank=True, help_text='Members allowed to manage community announcements and news.', related_name='senior_communities', to='people.person'),
        ),
        migrations.AddField(
            model_name='community',
            name='statute',
            field=models.ForeignKey(blank=True, help_text="The community's statute, as a PDF in the vault.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vault.vaultfile'),
        ),
        migrations.AddField(
            model_name='community',
            name='territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_territories', to='locations.territory'),
        ),
        migrations.AddConstraint(
            model_name='privacyacceptance',
            constraint=models.UniqueConstraint(fields=('person', 'version'), name='socialhub_privacy_acceptance_once'),
        ),
        migrations.AddConstraint(
            model_name='erasurerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('user',), name='socialhub_one_open_erasure_request'),
        ),
        migrations.AddConstraint(
            model_name='dataexport',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'running'])), fields=('user',), name='socialhub_one_open_data_export'),
        ),
    ]
