# Generated by Django 5.2.17 on 2026-10-06 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0002_initial'),
        ('socialhub', '0001_initial'),
        ('vault', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='statute',
            field=models.ForeignKey(blank=True, help_text="The community's statute, as a PDF in the vault.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vault.vaultfile'),
        ),
        migrations.AddField(
            model_name='communityforum',
            name='community',
            field=models.OneToOneField(help_text='The community whose room this is.', on_delete=django.db.models.deletion.CASCADE, related_name='forum', to='socialhub.community'),
        ),
        migrations.AddField(
            model_name='communitynewspost',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_news_posts', to='people.person'),
        ),
        migrations.AddField(
            model_name='communitynewspost',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_posts', to='socialhub.community'),
        ),
        migrations.AddField(
            model_name='communitynewspost',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='posts', to='socialhub.communitynewstopic'),
        ),
        migrations.AddField(
            model_name='communityprivilege',
            name='community',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privilege', to='socialhub.community'),
        ),
        migrations.AddField(
            model_name='dataexport',
            name='output',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vault.vaultfile'),
        ),
        migrations.AddField(
            model_name='dataexport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_exports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='erasurerequest',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='erasurerequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erasure_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='socialhub.community'),
        ),
        migrations.AddField(
            model_name='pendingemailchange',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_email_change', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='privacyacceptance',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_acceptances', to='people.person'),
        ),
        migrations.AddField(
            model_name='privacynotice',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referencerequest',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_requests', to='socialhub.membershipapplication'),
        ),
        migrations.AddField(
            model_name='referencerequest',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_references', to='people.person'),
        ),
        migrations.AddConstraint(
            model_name='dataexport',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'running'])), fields=('user',), name='socialhub_one_open_data_export'),
        ),
        migrations.AddConstraint(
            model_name='erasurerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('user',), name='socialhub_one_open_erasure_request'),
        ),
        migrations.AddConstraint(
            model_name='privacyacceptance',
            constraint=models.UniqueConstraint(fields=('person', 'version'), name='socialhub_privacy_acceptance_once'),
        ),
    ]
