# Generated by Django 4.2.23 on 2026-08-12 19:49

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_deprecate_is_federal_agent'),
        ('socialhub', '0002_remove_community_email_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='is_federal_tribe',
            field=models.BooleanField(default=False, help_text="DEPRECATED as a live flag. It promised 'members are exempt from all poll taxes' for years while no poll tax existed; there is one now, and what a community's members owe is its CommunityPrivilege head_weight (0 is the exemption this always meant). Kept because aurelian's mobilization app reads it by name for responder eligibility. Retiring it is an aurelian follow-up."),
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('charter', models.TextField(blank=True, help_text='What this office is responsible for. Shown on the public roster.')),
                ('since', models.DateField(blank=True, help_text='When the current holder took office.', null=True)),
                ('active', models.BooleanField(default=True)),
                ('may_see_community_chain', models.BooleanField(default=False)),
                ('may_administer_communities', models.BooleanField(default=False)),
                ('may_manage_community_news', models.BooleanField(default=False)),
                ('may_operate_mint', models.BooleanField(default=False)),
                ('limit_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Multiplies every quota limit for the holder, so an office has the headroom its work needs. HEADROOM ONLY: prices and the head tax are untouched, and a holder pays exactly what anyone else pays for the same action.', max_digits=8)),
                ('stipend', models.DecimalField(decimal_places=10, default=Decimal('0'), help_text="Paid per period by the federal treasury, in the host's billing asset. 0 is an unpaid office, which is an ordinary thing to be.", max_digits=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('holder', models.ForeignKey(blank=True, help_text='Empty means VACANT: the office keeps existing and pays nobody.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stations', to='people.person')),
                ('serves', models.ForeignKey(blank=True, help_text='Which community this office works for, if any. Attribution only — the federal treasury pays every station and a community never pays anyone.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stations', to='socialhub.community')),
            ],
            options={
                'ordering': ['serves__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CommunityPrivilege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_weight', models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='How many heads a member of this community counts as when the federal head tax is levied. 1 is ordinary; 0 exempts them entirely; 2 or 3 says this community is trusted less. Across several communities the LOWEST weight wins — belonging to a good community is what makes you cheap to tax. The tax itself is federal: this sets what a member owes, never who receives it.', max_digits=6)),
                ('may_see_community_chain', models.BooleanField(default=False, help_text='Members may open the platform-wide community chain graph.')),
                ('may_administer_communities', models.BooleanField(default=False, help_text='Members may open the Administrata view of any community.')),
                ('may_manage_community_news', models.BooleanField(default=False, help_text='Members may publish news in ANY community, without being its head or a senior member.')),
                ('may_operate_mint', models.BooleanField(default=False, help_text='Members may operate the mint on a host that IS the monetary master. This does not grant minting authority: the master check asks whether the MACHINE holds an issuer private key and takes no user argument, so on a branch host this still refuses.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privilege', to='socialhub.community')),
            ],
            options={
                'ordering': ['community__name'],
            },
        ),
    ]
