# Generated by Django 4.2.23 on 2026-10-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialhub', '0003_dataexport_replaced'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacynotice',
            name='seeded',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
