# Generated by Django 4.2.23 on 2026-08-12 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialhub', '0005_socialhubquotapolicy_socialhubusageevent_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='socialhubquotapolicy',
            name='socialhub_socialhubquotapolicy_one_default',
        ),
        migrations.RemoveConstraint(
            model_name='socialhubquotapolicy',
            name='socialhub_socialhubquotapolicy_one_per_user',
        ),
        migrations.RemoveField(
            model_name='socialhubquotapolicy',
            name='user',
        ),
        migrations.AddConstraint(
            model_name='socialhubquotapolicy',
            constraint=models.UniqueConstraint(fields=('metric_code',), name='socialhub_socialhubquotapolicy_one_per_metric'),
        ),
    ]
