# Generated by Django 4.2.23 on 2026-08-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialhub', '0006_remove_socialhubquotapolicy_socialhub_socialhubquotapolicy_one_default_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityprivilege',
            name='head_weight',
        ),
        migrations.AlterField(
            model_name='community',
            name='is_federal_tribe',
            field=models.BooleanField(default=False, help_text="DEPRECATED as a live flag. It promised 'members are exempt from all poll taxes' for years; the poll tax that briefly existed (the head tax) has been removed, and what a community now does to what its members pay is a discount on a subscription plan — see toto.subscriptions.CommunityPlanDiscount. Kept because aurelian's mobilization app reads it by name for responder eligibility. Retiring it is an aurelian follow-up."),
        ),
    ]
