# Generated by Django 4.2.23 on 2026-08-13 10:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialhub', '0007_remove_communityprivilege_head_weight_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialhubQuotaPolicy',
        ),
        migrations.AlterField(
            model_name='station',
            name='limit_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Multiplies every quota limit for the holder, so an office has the headroom its work needs. HEADROOM ONLY: prices are untouched, and a holder pays exactly what anyone else pays for the same action.', max_digits=8),
        ),
        migrations.DeleteModel(
            name='SocialhubUsageEvent',
        ),
    ]
