# Generated by Django 4.2.23 on 2026-08-15 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """The statute arrives; the constitution goes.

    A community's governing document is now a PDF in the vault (`statute`),
    for every kind of community rather than only companies. The Constitution
    model and its signatures are retired with the platform-wide "committed
    citizen" status they computed: membership is the register that says who
    belongs, and signing a PDF is what notarius does.

    The RemoveFields come BEFORE the DeleteModels on purpose — Django's own
    ordering, and the one SQLite needs to rebuild the tables cleanly.
    """


    dependencies = [
        ('vault', '0016_alter_vaultfile_file'),
        ('socialhub', '0008_delete_socialhubquotapolicy_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='constitutionsignature',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='constitutionsignature',
            name='constitution',
        ),
        migrations.RemoveField(
            model_name='constitutionsignature',
            name='person',
        ),
        migrations.RemoveField(
            model_name='constitutionsignature',
            name='signing_key',
        ),
        migrations.AddField(
            model_name='community',
            name='statute',
            field=models.ForeignKey(blank=True, help_text="The community's statute, as a PDF in the vault.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vault.vaultfile'),
        ),
        migrations.DeleteModel(
            name='Constitution',
        ),
        migrations.DeleteModel(
            name='ConstitutionSignature',
        ),
    ]
