# Generated by Django 4.2.23 on 2026-08-15 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialhub', '0009_community_statute_retire_constitution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ['serves__name', 'name'], 'verbose_name': 'Special Role', 'verbose_name_plural': 'Special Roles'},
        ),
        migrations.AlterField(
            model_name='station',
            name='serves',
            field=models.ForeignKey(blank=True, help_text='Which community this office works for, if any. Attribution only — the federal treasury pays every special role and a community never pays anyone.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stations', to='socialhub.community'),
        ),
    ]
