# Generated by Django 4.2.23 on 2026-08-18 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_deprecate_is_federal_agent'),
        ('socialhub', '0010_alter_station_options_alter_station_serves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='holder',
            field=models.ForeignKey(blank=True, help_text='Empty means VACANT: the office keeps existing and pays nobody.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='people.person'),
        ),
        migrations.AlterField(
            model_name='station',
            name='serves',
            field=models.ForeignKey(blank=True, help_text='Which community this office works for, if any. Attribution only — the federal treasury pays every special role and a community never pays anyone.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='socialhub.community'),
        ),
    ]
