# Generated by Django 4.2.23 on 2026-08-26 10:56

from django.db import migrations


class Migration(migrations.Migration):
    """Drop the Special Roles.

    A Station fused three unrelated things into one row: an office, an
    authorisation grant (four ``may_*`` booleans plus a quota multiplier) and a
    payslip. Each has a better home or no home at all — rights come from
    community membership, quota limits are flat, and recurring payment is a
    Faucet, which pays people rather than posts.

    IRREVERSIBLE. Station rows are NOT migrated or converted: an office is not a
    faucet member, and pretending otherwise would invent appointments nobody
    made. Whoever held an office is added to a faucet by staff, deliberately, or
    not at all.
    """

    # NO dependency on tax here, and that is not an oversight. `socialhub` is
    # in `registry.CORE_APPS` — every host installs it — while `toto.tax` ships
    # in the optional `toto-economy` package. A concrete dependency on an app
    # that is not in INSTALLED_APPS makes MigrationLoader raise
    # NodeNotFoundError while it builds the graph, before a single migration
    # runs, so naming tax here would break `migrate` on every host that pins
    # toto-base without the economy.
    #
    # The CASCADE ordering still matters: tax.StipendPayment holds the FK to
    # Station and must go first. That is declared from the OTHER side, as
    # `run_before` in tax/0007 — tax is only ever installed where socialhub
    # already is, so a dependency in that direction is always resolvable.
    dependencies = [
        ('socialhub', '0011_alter_station_holder_alter_station_serves'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Station',
        ),
    ]
