# Generated by Django 4.2.23 on 2026-08-26 10:56

from django.db import migrations


class Migration(migrations.Migration):
    """Drop the Special Roles.

    A Station fused three unrelated things into one row: an office, an
    authorisation grant (four ``may_*`` booleans plus a quota multiplier) and a
    payslip. Each has a better home or no home at all — rights come from
    community membership, quota limits are flat, and recurring payment is a
    Faucet, which pays people rather than posts.

    IRREVERSIBLE. Station rows are NOT migrated or converted: an office is not a
    faucet member, and pretending otherwise would invent appointments nobody
    made. Whoever held an office is added to a faucet by staff, deliberately, or
    not at all.
    """

    dependencies = [
        ('tax', '0007_delete_stipendpayment'),
        ('socialhub', '0011_alter_station_holder_alter_station_serves'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Station',
        ),
    ]
