# Generated by Django 4.2.23 on 2026-09-29 21:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialhub', '0013_communityforum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='What it opens: internal, confidential.', max_length=120, unique=True, verbose_name='name')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('regen_security', models.DecimalField(blank=True, decimal_places=4, help_text="Blank: the pool's own rate.", max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='security mana per hour')),
                ('regen_compute', models.DecimalField(blank=True, decimal_places=4, help_text="Blank: the pool's own rate.", max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='compute mana per hour')),
                ('regen_storage', models.DecimalField(blank=True, decimal_places=4, help_text="Blank: the pool's own rate.", max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='storage mana per hour')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'clearance',
                'verbose_name_plural': 'clearances',
                'ordering': ['name'],
            },
        ),
    ]
