"""Circles: a Community that decides who reads, and nothing else (2026-09-28).

One column, `is_circle`, default False, so every existing community stays
functional. Nothing is backfilled — a circle is made by a superuser. The two
`limit_choices_to` changes touch no table: a privilege and a membership
application name functional communities only, and the admin and every form
offer nothing else.
"""

# Generated by Django 4.2.23 on 2026-09-28 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialhub', '0013_communityforum'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='is_circle',
            field=models.BooleanField(db_index=True, default=False, help_text='A circle decides who may read wiki pages, and nothing else: no plan offers, no discounts, no privileges. Hidden from members; a superuser adds its members.', verbose_name='circle'),
        ),
        migrations.AlterField(
            model_name='communityprivilege',
            name='community',
            field=models.OneToOneField(limit_choices_to={'is_circle': False}, on_delete=django.db.models.deletion.CASCADE, related_name='privilege', to='socialhub.community'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='community',
            field=models.ForeignKey(limit_choices_to={'is_circle': False}, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='socialhub.community'),
        ),
    ]
