"""Circles set how fast mana refills (2026-09-28).

Three nullable columns, one per pool; blank keeps the pool's own rate, so
nothing changes until a superuser sets a speed on a circle. No backfill.
"""

# Generated by Django 4.2.23 on 2026-09-28 22:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialhub', '0014_community_is_circle'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='regen_compute',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="Blank: the pool's own rate.", max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='compute mana per hour'),
        ),
        migrations.AddField(
            model_name='community',
            name='regen_security',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="Blank: the pool's own rate.", max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='security mana per hour'),
        ),
        migrations.AddField(
            model_name='community',
            name='regen_storage',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="Blank: the pool's own rate.", max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='storage mana per hour'),
        ),
        migrations.AlterField(
            model_name='community',
            name='is_circle',
            field=models.BooleanField(db_index=True, default=False, help_text="A circle decides who may read wiki pages and how fast its members' mana refills: no plan offers, no discounts, no privileges. Hidden from members; a superuser adds its members.", verbose_name='circle'),
        ),
    ]
