# Generated by Django 4.2.23 on 2026-09-30 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialhub', '0016_pendingemailchange_old_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(unique=True)),
                ('text_pl', models.TextField()),
                ('text_en', models.TextField()),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'privacy notice',
                'ordering': ['-version'],
            },
        ),
    ]
