# Generated by Django 4.2.23 on 2026-09-30 23:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_person_timezone'),
        ('socialhub', '0017_privacy_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipapplication',
            name='privacy_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='privacy_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PrivacyAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_acceptances', to='people.person')),
            ],
            options={
                'verbose_name': 'privacy notice acceptance',
                'ordering': ['-version'],
            },
        ),
        migrations.AddConstraint(
            model_name='privacyacceptance',
            constraint=models.UniqueConstraint(fields=('person', 'version'), name='socialhub_privacy_acceptance_once'),
        ),
    ]
