# Generated by Django 4.2.23 on 2026-10-01 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0029_vault_file_trash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialhub', '0018_privacy_acceptance'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Queued'), ('running', 'Being prepared'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('output', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vault.vaultfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'data export',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='dataexport',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'running'])), fields=('user',), name='socialhub_one_open_data_export'),
        ),
    ]
