# Generated by Django 4.2.23 on 2026-10-01 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialhub', '0019_data_export'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErasureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('open', 'Waiting for an operator'), ('done', 'Carried out'), ('declined', 'Declined')], default='open', max_length=10)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erasure_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'erasure request',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='erasurerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('user',), name='socialhub_one_open_erasure_request'),
        ),
    ]
