# Generated by Django 4.2.23 on 2026-10-01 05:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gervazy', '0002_initial'),
        ('socialhub', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit_name', models.CharField(max_length=20)),
                ('code', models.CharField(help_text="Four capital letters, e.g. FLOR — the key of the asset's page.", max_length=4, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{4}$', 'Four capital letters, A–Z.')], verbose_name='short name')),
                ('symbol', models.CharField(blank=True, max_length=5)),
                ('decimals', models.PositiveSmallIntegerField()),
                ('max_supply_base_units', models.PositiveBigIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('backing_document', models.TextField(blank=True, help_text='What this asset is backed by (e.g. reserves held by …)')),
                ('minting_authority', models.CharField(blank=True, help_text='Entity authorised to mint this asset', max_length=255)),
                ('currency_hash', models.CharField(blank=True, editable=False, max_length=71, null=True, unique=True)),
                ('genesis_payload', models.JSONField(blank=True, default=dict)),
                ('genesis_signature', models.TextField(blank=True)),
                ('origin_platform', models.CharField(blank=True, max_length=200)),
                ('is_mirror', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssetHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_base_units', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-balance_base_units'],
            },
        ),
        migrations.CreateModel(
            name='AssetsQuotaPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('metric_code', models.CharField(db_index=True, max_length=100)),
                ('limit', models.DecimalField(decimal_places=10, max_digits=30)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime')], default='daily', max_length=20)),
                ('mode', models.CharField(choices=[('track', 'Track only'), ('warn', 'Warn'), ('block', 'Block')], default='block', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Assets quota policy',
                'verbose_name_plural': 'Assets quota policies',
                'ordering': ['metric_code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetsUsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_code', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=30)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('source_type', models.CharField(blank=True, max_length=100)),
                ('source_id', models.CharField(blank=True, max_length=255)),
                ('source_label', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('recorded', 'Recorded'), ('voided', 'Voided')], default='recorded', max_length=20)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Assets usage event',
                'verbose_name_plural': 'Assets usage events',
                'ordering': ['-occurred_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CurrencyContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=200)),
                ('currency_hash', models.CharField(max_length=71)),
                ('serial', models.PositiveIntegerField(default=1)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('signature', models.TextField(blank=True)),
                ('is_local', models.BooleanField(default=False)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-serial', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyIssuer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('fingerprint', models.CharField(editable=False, max_length=64, unique=True)),
                ('public_key_pem', models.TextField()),
                ('private_key_encrypted', models.BinaryField(blank=True, null=True)),
                ('is_self', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('retired', 'Retired')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Faucet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('source', models.CharField(choices=[('members', 'Named members, hourly'), ('scheduled', 'Scheduled regeneration'), ('automatic', 'Automatic grant'), ('manual', 'Manual grant')], default='members', max_length=12)),
                ('active', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, help_text='What this faucet is for. Shown to its members.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FaucetMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_per_hour', models.DecimalField(decimal_places=18, max_digits=30)),
                ('active', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['faucet__name', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='FaucetPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('members', 'Named members, hourly'), ('scheduled', 'Scheduled regeneration'), ('automatic', 'Automatic grant'), ('manual', 'Manual grant')], default='members', max_length=12)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('period_label', models.CharField(db_index=True, max_length=64)),
                ('amount_base_units', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FaucetRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_label', models.CharField(db_index=True, max_length=64)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('paid', models.PositiveIntegerField(default=0)),
                ('skipped', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('detail', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('user', 'User'), ('system', 'System'), ('reserve', 'Reserve'), ('external', 'External')], max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('user_priority', models.IntegerField(default=0, help_text="Billing priority for this user's accounts. Higher = checked first.")),
                ('allows_negative', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LedgerAccountKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.CharField(max_length=100, unique=True)),
                ('public_key_pem', models.TextField(help_text='Plaintext snapshot of the public key PEM. Must match gervazy.EncryptedPrivateKey.public_key_pem.')),
                ('algorithm', models.CharField(default='Ed25519', max_length=32)),
                ('state', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('retired', 'Retired'), ('compromised', 'Compromised'), ('destroyed', 'Destroyed')], default='active', max_length=20)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scopes', models.JSONField(default=list, help_text='List of allowed scope strings, e.g. ["transfer", "sign"].')),
                ('max_amount_base_units', models.BigIntegerField(blank=True, help_text='Per-operation ceiling. None = unlimited.', null=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('signed_grant_payload', models.JSONField(default=dict)),
                ('grant_signature', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_base_units', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'ledger entries',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.PositiveBigIntegerField(help_text='assets.LedgerEntry pk. Not an FK — see LedgerEntryTag.', unique=True)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ledger entry comment',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.PositiveBigIntegerField(db_index=True, help_text='assets.LedgerEntry pk. Not an FK — see the class docstring.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ledger entry tag',
                'ordering': ['tag__name'],
            },
        ),
        migrations.CreateModel(
            name='LedgerHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_hash', models.CharField(blank=True, max_length=64)),
                ('hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ledger hash',
                'verbose_name_plural': 'ledger hashes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LedgerTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Without the '#' — write 'invoice', not '#invoice'.", max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ledger tag',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LedgerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('origin_platform', models.CharField(blank=True, default='', max_length=100)),
                ('origin_uuid', models.UUIDField(blank=True, null=True)),
                ('transaction_type', models.CharField(choices=[('asset_create', 'Asset Create'), ('asset_transfer', 'Asset Transfer'), ('reversal', 'Reversal'), ('adjustment', 'Adjustment'), ('mint', 'Mint'), ('burn', 'Burn')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('source_type', models.CharField(blank=True, max_length=100)),
                ('source_id', models.CharField(blank=True, max_length=255)),
                ('posted', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payload_hash', models.CharField(blank=True, max_length=128)),
                ('signature', models.TextField(blank=True)),
                ('nonce', models.CharField(blank=True, max_length=128)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('fingerprint', models.CharField(editable=False, max_length=64, unique=True)),
                ('public_key_pem', models.TextField()),
                ('private_key_encrypted', models.BinaryField(blank=True, null=True)),
                ('is_self', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('secret', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_pin', to='gervazy.encryptedsecret')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_pin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('public_key', models.TextField(help_text='Public key (PEM or hex).')),
                ('private_key_encrypted', models.TextField(blank=True, help_text='Private key encrypted with the server master secret. Do not expose.')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ledger_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_authorizations', to='assets.ledgeraccount')),
            ],
            options={
                'verbose_name': 'Wallet Authorization',
                'verbose_name_plural': 'Wallet Authorizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SettlementAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('chosen_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='assets.asset')),
                ('chosen_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'settlement asset',
                'verbose_name_plural': 'settlement asset',
            },
        ),
        migrations.AddConstraint(
            model_name='platformkey',
            constraint=models.UniqueConstraint(condition=models.Q(('is_self', True)), fields=('is_self',), name='assets_one_local_platform_key'),
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='authorization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_transactions', to='assets.ledgerauthorization'),
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='reversed_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_set', to='assets.ledgertransaction'),
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='signed_by_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_transactions', to='assets.ledgeraccountkey'),
        ),
        migrations.AddField(
            model_name='ledgertag',
            name='account',
            field=models.ForeignKey(help_text='Whose vocabulary this is. Tags never cross accounts.', on_delete=django.db.models.deletion.CASCADE, related_name='ledger_tags', to='assets.ledgeraccount'),
        ),
        migrations.AddField(
            model_name='ledgerhash',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='hash_record', to='assets.ledgertransaction'),
        ),
        migrations.AddField(
            model_name='ledgerentrytag',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ledgerentrytag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_links', to='assets.ledgertag'),
        ),
        migrations.AddField(
            model_name='ledgerentrycomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='assets.ledgeraccount'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='assets.ledgertransaction'),
        ),
        migrations.AddField(
            model_name='ledgerauthorization',
            name='asset',
            field=models.ForeignKey(blank=True, help_text='If set, delegation is restricted to this asset only.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authorizations', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='ledgerauthorization',
            name='delegate_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delegated_authorizations', to='gervazy.encryptedprivatekey'),
        ),
        migrations.AddField(
            model_name='ledgerauthorization',
            name='delegate_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_authorizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ledgerauthorization',
            name='ledger_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorizations', to='assets.ledgeraccount'),
        ),
        migrations.AddField(
            model_name='ledgerauthorization',
            name='signed_by_account_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signed_authorizations', to='assets.ledgeraccountkey'),
        ),
        migrations.AddField(
            model_name='ledgeraccountkey',
            name='encrypted_private_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_account_keys', to='gervazy.encryptedprivatekey'),
        ),
        migrations.AddField(
            model_name='ledgeraccountkey',
            name='ledger_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signing_keys', to='assets.ledgeraccount'),
        ),
        migrations.AddField(
            model_name='ledgeraccount',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faucetrun',
            name='faucet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='assets.faucet'),
        ),
        migrations.AddField(
            model_name='faucetpayout',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faucet_payouts', to='socialhub.community'),
        ),
        migrations.AddField(
            model_name='faucetpayout',
            name='faucet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='assets.faucet'),
        ),
        migrations.AddField(
            model_name='faucetpayout',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faucetpayout',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='assets.faucetmember'),
        ),
        migrations.AddField(
            model_name='faucetpayout',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faucet_payouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faucetpayout',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faucet_payouts', to='assets.ledgertransaction'),
        ),
        migrations.AddField(
            model_name='faucetmember',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faucetmember',
            name='faucet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='assets.faucet'),
        ),
        migrations.AddField(
            model_name='faucetmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faucet_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faucet',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faucets', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='faucet',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faucets', to='socialhub.community'),
        ),
        migrations.AddField(
            model_name='faucet',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='currencyissuer',
            constraint=models.UniqueConstraint(condition=models.Q(('is_self', True)), fields=('is_self',), name='assets_one_local_issuer'),
        ),
        migrations.AddField(
            model_name='currencycontract',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='currencycontract',
            name='issuer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='assets.currencyissuer'),
        ),
        migrations.AddField(
            model_name='assetsusageevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='assetsquotapolicy',
            constraint=models.UniqueConstraint(fields=('metric_code',), name='assets_assetsquotapolicy_one_per_metric'),
        ),
        migrations.AddField(
            model_name='assetholding',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='assets.ledgeraccount'),
        ),
        migrations.AddField(
            model_name='assetholding',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='asset',
            name='issuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.currencyissuer'),
        ),
        migrations.AddField(
            model_name='asset',
            name='reserve_account',
            field=models.ForeignKey(blank=True, help_text='Admin-controlled account that holds unminted supply and fulfils purchases.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserve_assets', to='assets.ledgeraccount'),
        ),
        migrations.AddConstraint(
            model_name='ledgertag',
            constraint=models.UniqueConstraint(fields=('account', 'slug'), name='assets_ledgertag_slug_per_account'),
        ),
        migrations.AddConstraint(
            model_name='ledgertag',
            constraint=models.UniqueConstraint(fields=('account', 'name'), name='assets_ledgertag_name_per_account'),
        ),
        migrations.AddIndex(
            model_name='ledgerentrytag',
            index=models.Index(fields=['tag', 'entry_id'], name='assets_ledg_tag_id_062f95_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentrytag',
            constraint=models.UniqueConstraint(fields=('entry_id', 'tag'), name='assets_ledgerentrytag_once'),
        ),
        migrations.AddIndex(
            model_name='ledgeraccountkey',
            index=models.Index(fields=['ledger_account', 'state'], name='assets_ledg_ledger__cbee6f_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgeraccountkey',
            index=models.Index(fields=['key_id'], name='assets_ledg_key_id_8f3036_idx'),
        ),
        migrations.AddIndex(
            model_name='faucetrun',
            index=models.Index(fields=['period_label', '-started_at'], name='assets_fauc_period__7b2867_idx'),
        ),
        migrations.AddIndex(
            model_name='faucetpayout',
            index=models.Index(fields=['status', 'period_label'], name='assets_fauc_status_86bff2_idx'),
        ),
        migrations.AddIndex(
            model_name='faucetpayout',
            index=models.Index(fields=['faucet', '-created_at'], name='assets_fauc_faucet__faba1f_idx'),
        ),
        migrations.AddConstraint(
            model_name='faucetpayout',
            constraint=models.UniqueConstraint(fields=('faucet', 'recipient', 'period_label'), name='assets_one_payout_per_recipient_period'),
        ),
        migrations.AddConstraint(
            model_name='faucetmember',
            constraint=models.UniqueConstraint(fields=('faucet', 'user'), name='assets_one_membership_per_faucet'),
        ),
        migrations.AddConstraint(
            model_name='currencycontract',
            constraint=models.UniqueConstraint(condition=models.Q(('is_local', True), ('superseded_at__isnull', True)), fields=('is_local',), name='assets_one_active_local_contract'),
        ),
        migrations.AddConstraint(
            model_name='currencycontract',
            constraint=models.UniqueConstraint(fields=('node_id', 'serial'), name='assets_one_contract_per_node_serial'),
        ),
        migrations.AddIndex(
            model_name='assetsusageevent',
            index=models.Index(fields=['metric_code', 'occurred_at'], name='assetsusageevent_mtime'),
        ),
        migrations.AddIndex(
            model_name='assetsusageevent',
            index=models.Index(fields=['user', 'metric_code'], name='assetsusageevent_umetric'),
        ),
        migrations.AddConstraint(
            model_name='assetsusageevent',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('idempotency_key',), name='assets_assetsusageevent_idem'),
        ),
        migrations.AlterUniqueTogether(
            name='assetholding',
            unique_together={('asset', 'account')},
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('issuer', 'unit_name'), name='assets_ticker_unique_per_issuer'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('currency_hash', ''), _negated=True), ('currency_hash__isnull', False)), name='assets_asset_has_genesis_hash'),
        ),
    ]
