# Generated by Django 4.2.23 on 2026-08-11 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gervazy', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit_name', models.CharField(max_length=20)),
                ('code', models.CharField(blank=True, max_length=10)),
                ('symbol', models.CharField(blank=True, max_length=5)),
                ('decimals', models.PositiveSmallIntegerField()),
                ('total_supply_base_units', models.PositiveBigIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('backing_document', models.TextField(blank=True, help_text='What this asset is backed by (e.g. reserves held by …)')),
                ('minting_authority', models.CharField(blank=True, help_text='Entity authorised to mint this asset', max_length=255)),
                ('currency_hash', models.CharField(blank=True, editable=False, max_length=71, null=True, unique=True)),
                ('genesis_payload', models.JSONField(blank=True, default=dict)),
                ('genesis_signature', models.TextField(blank=True)),
                ('origin_platform', models.CharField(blank=True, max_length=200)),
                ('is_mirror', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssetHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_base_units', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-balance_base_units'],
            },
        ),
        migrations.CreateModel(
            name='AssetsQuotaPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('metric_code', models.CharField(db_index=True, max_length=100)),
                ('limit', models.DecimalField(decimal_places=10, max_digits=30)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime')], default='daily', max_length=20)),
                ('mode', models.CharField(choices=[('track', 'Track only'), ('warn', 'Warn'), ('block', 'Block')], default='block', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Assets quota policy',
                'verbose_name_plural': 'Assets quota policies',
                'ordering': ['metric_code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetsUsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_code', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=30)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('source_type', models.CharField(blank=True, max_length=100)),
                ('source_id', models.CharField(blank=True, max_length=255)),
                ('source_label', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('recorded', 'Recorded'), ('voided', 'Voided')], default='recorded', max_length=20)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Assets usage event',
                'verbose_name_plural': 'Assets usage events',
                'ordering': ['-occurred_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CurrencyIssuer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('fingerprint', models.CharField(editable=False, max_length=64, unique=True)),
                ('public_key_pem', models.TextField()),
                ('private_key_encrypted', models.BinaryField(blank=True, null=True)),
                ('is_self', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('retired', 'Retired')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('user', 'User'), ('system', 'System'), ('reserve', 'Reserve'), ('external', 'External')], max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('user_priority', models.IntegerField(default=0, help_text="Billing priority for this user's accounts. Higher = checked first.")),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LedgerAccountKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.CharField(max_length=100, unique=True)),
                ('public_key_pem', models.TextField(help_text='Plaintext snapshot of the public key PEM. Must match gervazy.EncryptedPrivateKey.public_key_pem.')),
                ('algorithm', models.CharField(default='Ed25519', max_length=32)),
                ('state', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('retired', 'Retired'), ('compromised', 'Compromised'), ('destroyed', 'Destroyed')], default='active', max_length=20)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encrypted_private_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_account_keys', to='gervazy.encryptedprivatekey')),
                ('ledger_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signing_keys', to='assets.ledgeraccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scopes', models.JSONField(default=list, help_text='List of allowed scope strings, e.g. ["transfer", "sign"].')),
                ('max_amount_base_units', models.BigIntegerField(blank=True, help_text='Per-operation ceiling. None = unlimited.', null=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('signed_grant_payload', models.JSONField(default=dict)),
                ('grant_signature', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, help_text='If set, delegation is restricted to this asset only.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authorizations', to='assets.asset')),
                ('delegate_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delegated_authorizations', to='gervazy.encryptedprivatekey')),
                ('delegate_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_authorizations', to=settings.AUTH_USER_MODEL)),
                ('ledger_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorizations', to='assets.ledgeraccount')),
                ('signed_by_account_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signed_authorizations', to='assets.ledgeraccountkey')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('secret', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_pin', to='gervazy.encryptedsecret')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_pin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('public_key', models.TextField(help_text='Public key (PEM or hex).')),
                ('private_key_encrypted', models.TextField(blank=True, help_text='Private key encrypted with the server master secret. Do not expose.')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ledger_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_authorizations', to='assets.ledgeraccount')),
            ],
            options={
                'verbose_name': 'Wallet Authorization',
                'verbose_name_plural': 'Wallet Authorizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LedgerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('origin_platform', models.CharField(blank=True, default='', max_length=100)),
                ('origin_uuid', models.UUIDField(blank=True, null=True)),
                ('transaction_type', models.CharField(choices=[('asset_create', 'Asset Create'), ('asset_transfer', 'Asset Transfer'), ('reversal', 'Reversal'), ('adjustment', 'Adjustment')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('source_type', models.CharField(blank=True, max_length=100)),
                ('source_id', models.CharField(blank=True, max_length=255)),
                ('posted', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payload_hash', models.CharField(blank=True, max_length=128)),
                ('signature', models.TextField(blank=True)),
                ('nonce', models.CharField(blank=True, max_length=128)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='assets.asset')),
                ('authorization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_transactions', to='assets.ledgerauthorization')),
                ('reversed_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_set', to='assets.ledgertransaction')),
                ('signed_by_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_transactions', to='assets.ledgeraccountkey')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_hash', models.CharField(blank=True, max_length=64)),
                ('hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='hash_record', to='assets.ledgertransaction')),
            ],
            options={
                'verbose_name': 'ledger hash',
                'verbose_name_plural': 'ledger hashes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_base_units', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='assets.ledgeraccount')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='assets.asset')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='assets.ledgertransaction')),
            ],
            options={
                'verbose_name_plural': 'ledger entries',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='currencyissuer',
            constraint=models.UniqueConstraint(condition=models.Q(('is_self', True)), fields=('is_self',), name='assets_one_local_issuer'),
        ),
        migrations.AddField(
            model_name='assetsusageevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetsquotapolicy',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Leave empty for the default policy that applies to everyone.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetholding',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='assets.ledgeraccount'),
        ),
        migrations.AddField(
            model_name='assetholding',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='asset',
            name='issuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.currencyissuer'),
        ),
        migrations.AddField(
            model_name='asset',
            name='reserve_account',
            field=models.ForeignKey(blank=True, help_text='Admin-controlled account that holds unminted supply and fulfils purchases.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserve_assets', to='assets.ledgeraccount'),
        ),
        migrations.AddIndex(
            model_name='ledgeraccountkey',
            index=models.Index(fields=['ledger_account', 'state'], name='assets_ledg_ledger__cbee6f_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgeraccountkey',
            index=models.Index(fields=['key_id'], name='assets_ledg_key_id_8f3036_idx'),
        ),
        migrations.AddIndex(
            model_name='assetsusageevent',
            index=models.Index(fields=['metric_code', 'occurred_at'], name='assetsusageevent_mtime'),
        ),
        migrations.AddIndex(
            model_name='assetsusageevent',
            index=models.Index(fields=['user', 'metric_code'], name='assetsusageevent_umetric'),
        ),
        migrations.AddConstraint(
            model_name='assetsusageevent',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('idempotency_key',), name='assets_assetsusageevent_idem'),
        ),
        migrations.AddConstraint(
            model_name='assetsquotapolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('metric_code',), name='assets_assetsquotapolicy_one_default'),
        ),
        migrations.AddConstraint(
            model_name='assetsquotapolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('metric_code', 'user'), name='assets_assetsquotapolicy_one_per_user'),
        ),
        migrations.AlterUniqueTogether(
            name='assetholding',
            unique_together={('asset', 'account')},
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('issuer', 'unit_name'), name='assets_ticker_unique_per_issuer'),
        ),
    ]
