# Generated by Django 4.2.23 on 2026-07-28 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gervazy', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit_name', models.CharField(max_length=20, unique=True)),
                ('decimals', models.PositiveSmallIntegerField()),
                ('total_supply_base_units', models.PositiveBigIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('is_currency', models.BooleanField(default=False, help_text='Accepted as a payment currency on the platform')),
                ('backing_document', models.TextField(blank=True, help_text='What this asset is backed by (e.g. reserves held by …)')),
                ('minting_authority', models.CharField(blank=True, help_text='Entity authorised to mint this asset', max_length=255)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.TextField(blank=True, help_text='Lapis smart-contract YAML.')),
                ('global_state', models.JSONField(blank=True, default=dict, help_text='Runtime Lapis VM state (status, counters, etc.).')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('user', 'User'), ('system', 'System'), ('reserve', 'Reserve'), ('external', 'External')], max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('user_priority', models.IntegerField(default=0, help_text="Billing priority for this user's accounts. Higher = checked first.")),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LedgerAccountKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.CharField(max_length=100, unique=True)),
                ('public_key_pem', models.TextField(help_text='Plaintext snapshot of the public key PEM. Must match gervazy.EncryptedPrivateKey.public_key_pem.')),
                ('algorithm', models.CharField(default='Ed25519', max_length=32)),
                ('state', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('retired', 'Retired'), ('compromised', 'Compromised'), ('destroyed', 'Destroyed')], default='active', max_length=20)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encrypted_private_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_account_keys', to='gervazy.encryptedprivatekey')),
                ('ledger_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signing_keys', to='assets.ledgeraccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scopes', models.JSONField(default=list, help_text='List of allowed scope strings, e.g. ["transfer", "sign"].')),
                ('max_amount_base_units', models.BigIntegerField(blank=True, help_text='Per-operation ceiling. None = unlimited.', null=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('signed_grant_payload', models.JSONField(default=dict)),
                ('grant_signature', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, help_text='If set, delegation is restricted to this asset only.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authorizations', to='assets.asset')),
                ('delegate_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delegated_authorizations', to='gervazy.encryptedprivatekey')),
                ('delegate_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_authorizations', to=settings.AUTH_USER_MODEL)),
                ('ledger_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorizations', to='assets.ledgeraccount')),
                ('signed_by_account_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signed_authorizations', to='assets.ledgeraccountkey')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('secret', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_pin', to='gervazy.encryptedsecret')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_pin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('public_key', models.TextField(help_text='Public key (PEM or hex).')),
                ('private_key_encrypted', models.TextField(blank=True, help_text='Private key encrypted with the server master secret. Do not expose.')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ledger_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_authorizations', to='assets.ledgeraccount')),
            ],
            options={
                'verbose_name': 'Wallet Authorization',
                'verbose_name_plural': 'Wallet Authorizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Obligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('order_reference', models.CharField(blank=True, max_length=255)),
                ('amount_base_units', models.BigIntegerField()),
                ('due_at', models.DateTimeField()),
                ('collateral_amount_base_units', models.BigIntegerField(default=0)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('overdue', 'Overdue'), ('fulfilled', 'Fulfilled'), ('defaulted', 'Defaulted')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligations', to='assets.asset')),
                ('collateral_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collateral_obligations', to='assets.ledgeraccount')),
                ('collateral_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collateral_obligations', to='assets.asset')),
                ('creditor_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creditor_obligations', to='assets.ledgeraccount')),
                ('debtor_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debtor_obligations', to='assets.ledgeraccount')),
            ],
            options={
                'ordering': ['due_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('transaction_type', models.CharField(choices=[('asset_create', 'Asset Create'), ('asset_transfer', 'Asset Transfer'), ('reversal', 'Reversal'), ('adjustment', 'Adjustment')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('source_type', models.CharField(blank=True, max_length=100)),
                ('source_id', models.CharField(blank=True, max_length=255)),
                ('posted', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payload_hash', models.CharField(blank=True, max_length=128)),
                ('signature', models.TextField(blank=True)),
                ('nonce', models.CharField(blank=True, max_length=128)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='assets.asset')),
                ('authorization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_transactions', to='assets.ledgerauthorization')),
                ('reversed_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_set', to='assets.ledgertransaction')),
                ('signed_by_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_transactions', to='assets.ledgeraccountkey')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_hash', models.CharField(blank=True, max_length=64)),
                ('hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='hash_record', to='assets.ledgertransaction')),
            ],
            options={
                'verbose_name': 'ledger hash',
                'verbose_name_plural': 'ledger hashes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_base_units', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='assets.ledgeraccount')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='assets.asset')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='assets.ledgertransaction')),
            ],
            options={
                'verbose_name_plural': 'ledger entries',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(blank=True, max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('asset', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='currency', to='assets.asset')),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AssetHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_base_units', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='assets.ledgeraccount')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='assets.asset')),
            ],
            options={
                'ordering': ['-balance_base_units'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='reserve_account',
            field=models.ForeignKey(blank=True, help_text='Admin-controlled account that holds unminted supply and fulfils purchases.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserve_assets', to='assets.ledgeraccount'),
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(blank=True, help_text='Lapis contract governing this agreement.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='assets.contract')),
                ('source_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements_as_source', to='assets.ledgeraccount')),
                ('target_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements_as_target', to='assets.ledgeraccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ledgeraccountkey',
            index=models.Index(fields=['ledger_account', 'state'], name='assets_ledg_ledger__cbee6f_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgeraccountkey',
            index=models.Index(fields=['key_id'], name='assets_ledg_key_id_8f3036_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assetholding',
            unique_together={('asset', 'account')},
        ),
    ]
