# Generated by Django 4.2.23 on 2026-08-11 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_ledgertransaction_transaction_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='total_supply_base_units',
            new_name='max_supply_base_units',
        ),
    ]
