# Generated by Django 4.2.23 on 2026-08-02, then hand-edited: adding a UNIQUE
# uuid in one AddField stamps every EXISTING row with the same default value,
# which cannot satisfy the constraint on a deployed ledger. The standard
# three-step recipe instead: add nullable and un-unique, backfill one uuid per
# row, then tighten to unique+indexed. Fresh databases take the same path and
# never notice.

import uuid

from django.db import migrations, models


def backfill_uuids(apps, schema_editor):
    LedgerTransaction = apps.get_model("assets", "LedgerTransaction")
    rows = []
    for tx in LedgerTransaction.objects.filter(uuid__isnull=True).only("id"):
        tx.uuid = uuid.uuid4()
        rows.append(tx)
        if len(rows) >= 500:
            LedgerTransaction.objects.bulk_update(rows, ["uuid"])
            rows = []
    if rows:
        LedgerTransaction.objects.bulk_update(rows, ["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_drop_lapis_obligation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgertransaction',
            name='origin_platform',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='origin_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='uuid',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(backfill_uuids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='ledgertransaction',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
