# Generated by Django 4.2.23 on 2026-08-12 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_rename_total_supply_base_units_asset_max_supply_base_units'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assetsquotapolicy',
            name='assets_assetsquotapolicy_one_default',
        ),
        migrations.RemoveConstraint(
            model_name='assetsquotapolicy',
            name='assets_assetsquotapolicy_one_per_user',
        ),
        migrations.RemoveField(
            model_name='assetsquotapolicy',
            name='user',
        ),
        migrations.AddConstraint(
            model_name='assetsquotapolicy',
            constraint=models.UniqueConstraint(fields=('metric_code',), name='assets_assetsquotapolicy_one_per_metric'),
        ),
    ]
