# Generated by Django 4.2.23 on 2026-08-26 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0005_ledger_decorations'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('chosen_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='assets.asset')),
                ('chosen_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'settlement asset',
                'verbose_name_plural': 'settlement asset',
            },
        ),
    ]
