# Generated by Django 4.2.23 on 2026-08-26 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0006_settlementasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faucet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, help_text='What this faucet is for. Shown to its members.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faucets', to='assets.asset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FaucetMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_per_hour', models.DecimalField(decimal_places=18, max_digits=30)),
                ('active', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('faucet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='assets.faucet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faucet_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['faucet__name', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='FaucetPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_label', models.CharField(db_index=True, max_length=40)),
                ('amount_base_units', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='assets.faucetmember')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faucet_payouts', to='assets.ledgertransaction')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'period_label'], name='assets_fauc_status_86bff2_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='faucetpayout',
            constraint=models.UniqueConstraint(fields=('member', 'period_label'), name='assets_one_payout_per_member_hour'),
        ),
        migrations.AddConstraint(
            model_name='faucetmember',
            constraint=models.UniqueConstraint(fields=('faucet', 'user'), name='assets_one_membership_per_faucet'),
        ),
    ]
