# Generated by Django 4.2.23 on 2026-08-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_faucet_faucetmember_faucetpayout_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaucetRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_label', models.CharField(db_index=True, max_length=40)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('paid', models.PositiveIntegerField(default=0)),
                ('skipped', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('detail', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
                'indexes': [models.Index(fields=['period_label', '-started_at'], name='assets_fauc_period__7b2867_idx')],
            },
        ),
    ]
