# Generated by Django 4.2.23 on 2025-12-14 00:57

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_jsonform.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vault', '0001_initial'),
        ('gervazy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppIngress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(choices=[('oya', 'oya'), ('audit', 'audit'), ('memo', 'memo'), ('gervazy', 'gervazy'), ('vault', 'vault'), ('federal', 'federal'), ('community', 'community'), ('finance', 'finance'), ('events', 'events'), ('kanban', 'kanban'), ('ravioli', 'ravioli'), ('library', 'library'), ('webfront', 'webfront'), ('locations', 'locations'), ('assets', 'assets'), ('mandragora', 'mandragora')], help_text='Target app for ingress', max_length=64)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this ingress should be executed')),
            ],
        ),
        migrations.CreateModel(
            name='ColorMix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the color mix', max_length=64, unique=True)),
                ('primary_bg_light', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
                ('header_bg_light', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
                ('appbar_bg_light', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
                ('appbar_text_light', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None)),
                ('footer_bg_light', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
                ('footer_text_light', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None)),
                ('bubble_bg_light', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
                ('text_main_light', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None)),
                ('accent_light', colorfield.fields.ColorField(default='#FF4081', image_field=None, max_length=25, samples=None)),
                ('warn_light', colorfield.fields.ColorField(default='#FFC107', image_field=None, max_length=25, samples=None)),
                ('primary_bg_dark', colorfield.fields.ColorField(default='#121212', image_field=None, max_length=25, samples=None)),
                ('header_bg_dark', colorfield.fields.ColorField(default='#1F1F1F', image_field=None, max_length=25, samples=None)),
                ('appbar_bg_dark', colorfield.fields.ColorField(default='#1F1F1F', image_field=None, max_length=25, samples=None)),
                ('appbar_text_dark', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
                ('footer_bg_dark', colorfield.fields.ColorField(default='#1F1F1F', image_field=None, max_length=25, samples=None)),
                ('footer_text_dark', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
                ('bubble_bg_dark', colorfield.fields.ColorField(default='#2C2C2C', image_field=None, max_length=25, samples=None)),
                ('text_main_dark', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
                ('accent_dark', colorfield.fields.ColorField(default='#FF4081', image_field=None, max_length=25, samples=None)),
                ('warn_dark', colorfield.fields.ColorField(default='#FF5722', image_field=None, max_length=25, samples=None)),
                ('accent_1', colorfield.fields.ColorField(default='#03A9F4', image_field=None, max_length=25, samples=None)),
                ('accent_2', colorfield.fields.ColorField(default='#4CAF50', image_field=None, max_length=25, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='DashboardBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=50)),
                ('link', models.CharField(blank=True, max_length=64, null=True)),
                ('public', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name of the font (e.g. 'Playfair Display')", max_length=64, unique=True)),
                ('cdn_link', models.URLField(help_text='CDN or stylesheet URL for importing the font (e.g. Google Fonts)')),
                ('style_family', models.CharField(choices=[('serif', 'Serif'), ('sans-serif', 'Sans-serif'), ('monospace', 'Monospace'), ('display', 'Display / Decorative')], default='sans-serif', help_text='Font style family classification', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GraphSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(choices=[('community', 'community'), ('finance', 'finance'), ('events', 'events'), ('federal', 'federal')], max_length=64)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the theme', max_length=64, unique=True)),
                ('header', django_jsonform.models.fields.JSONField(default=dict, help_text='Tailwind classes for header element (light/dark mode)')),
                ('footer', django_jsonform.models.fields.JSONField(default=dict, help_text='Tailwind classes for footer element (light/dark mode)')),
                ('color_mix', models.ForeignKey(help_text='Color palette used for this theme', on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='oya.colormix')),
                ('font', models.ForeignKey(blank=True, help_text='Font applied to this theme', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='themes', to='oya.font')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('site_name', models.CharField(max_length=255)),
                ('publication_year', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('rate_limit_window', models.IntegerField(default=60, help_text='Rate limit window in seconds')),
                ('rate_limit_max_requests', models.IntegerField(default=20, help_text='Max requests allowed per window')),
                ('secret', models.OneToOneField(help_text='SecretKey used for signing tokens', on_delete=django.db.models.deletion.CASCADE, related_name='platform', to='gervazy.secretkey')),
                ('theme', models.ForeignKey(blank=True, help_text='Theme applied to this platform', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_themes', to='oya.theme')),
            ],
        ),
        migrations.CreateModel(
            name='AppBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(choices=[('community', 'community'), ('finance', 'finance'), ('events', 'events')], help_text='Target app for backup', max_length=64)),
                ('filename', models.CharField(help_text='Base filename prefix to use for backup dumps', max_length=128)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this backup should be executed')),
                ('bucket', models.ForeignKey(help_text='Target Vault bucket for backup', on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='vault.bucket')),
            ],
        ),
    ]
