# Generated by Django 4.2.23 on 2025-08-20 22:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_jsonform.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppIngress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(choices=[('oya', 'oya'), ('netogami', 'netogami'), ('nakamori', 'nakamori'), ('renso', 'renso'), ('resume', 'resume')], help_text='Target app for ingress', max_length=64)),
                ('args', models.JSONField(blank=True, default=dict, help_text='Arguments to pass to the ingress command')),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this ingress should be executed')),
            ],
        ),
        migrations.CreateModel(
            name='DashboardBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=50)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name of the font (e.g. 'Playfair Display')", max_length=64, unique=True)),
                ('cdn_link', models.URLField(help_text='CDN or stylesheet URL for importing the font (e.g. Google Fonts)')),
                ('style_family', models.CharField(choices=[('serif', 'Serif'), ('sans-serif', 'Sans-serif'), ('monospace', 'Monospace'), ('display', 'Display / Decorative')], default='sans-serif', help_text='Font style family classification', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the theme', max_length=64, unique=True)),
                ('theme', django_jsonform.models.fields.JSONField(default={}, help_text='Tailwind classes for page-level layout elements')),
                ('header', django_jsonform.models.fields.JSONField(default=dict, help_text='Tailwind classes for header element (light/dark mode)')),
                ('font', models.ForeignKey(blank=True, help_text='Font applied to this theme', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='themes', to='oya.font')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('site_name', models.CharField(max_length=255)),
                ('publication_year', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('index_url', models.CharField(blank=True, max_length=255, null=True)),
                ('theme', models.ForeignKey(blank=True, help_text='Theme applied to this platform', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_themes', to='oya.theme')),
            ],
        ),
    ]
