# Generated by Django 4.2.23 on 2025-11-23 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oya', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appingress',
            name='args',
        ),
    ]
