# Generated by Django 4.2.23 on 2025-12-18 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oya', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppIngress',
        ),
        migrations.DeleteModel(
            name='GraphSync',
        ),
    ]
