# Generated by Django 4.2.23 on 2025-08-18 20:10

from django.db import migrations, models
import django.db.models.deletion
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('oya', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name of the font (e.g. 'Playfair Display')", max_length=64, unique=True)),
                ('cdn_link', models.URLField(help_text='CDN or stylesheet URL for importing the font (e.g. Google Fonts)')),
                ('style_family', models.CharField(choices=[('serif', 'Serif'), ('sans-serif', 'Sans-serif'), ('monospace', 'Monospace'), ('display', 'Display / Decorative')], default='sans-serif', help_text='Font style family classification', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the theme', max_length=64, unique=True)),
                ('theme', django_jsonform.models.fields.JSONField(default={}, help_text='Tailwind classes for page-level layout elements')),
                ('header_classes', django_jsonform.models.fields.JSONField(default=dict, help_text='Tailwind classes for header element (light/dark mode)')),
                ('font', models.ForeignKey(blank=True, help_text='Font applied to this theme', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='themes', to='oya.font')),
            ],
        ),
        migrations.AddField(
            model_name='platform',
            name='theme',
            field=models.ForeignKey(blank=True, help_text='Theme applied to this platform', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_themes', to='oya.theme'),
        ),
    ]
