# Generated by Django 4.2.23 on 2025-12-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oya', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='logo',
            field=models.ImageField(blank=True, help_text='Optional logo for this federation', null=True, upload_to='federation_logos/'),
        ),
    ]
