# Generated by Django 4.2.23 on 2025-09-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oya', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appingress',
            name='app_name',
            field=models.CharField(choices=[('oya', 'oya'), ('webfront', 'webfront'), ('memo', 'memo'), ('documents', 'documents'), ('kanban', 'kanban')], help_text='Target app for ingress', max_length=64),
        ),
    ]
