# Generated by Django 4.2.23 on 2025-10-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oya', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appingress',
            name='app_name',
            field=models.CharField(choices=[('oya', 'oya'), ('webfront', 'webfront'), ('memo', 'memo'), ('documents', 'documents'), ('kanban', 'kanban'), ('community', 'community'), ('mandragora', 'mandragora'), ('kodama', 'kodama'), ('federal', 'federal')], help_text='Target app for ingress', max_length=64),
        ),
    ]
