# Generated by Django 4.2.23 on 2025-11-10 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oya', '0002_delete_logentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appingress',
            name='app_name',
            field=models.CharField(choices=[('oya', 'oya'), ('audit', 'audit'), ('memo', 'memo'), ('gervazy', 'gervazy'), ('vault', 'vault'), ('community', 'community'), ('federal', 'federal'), ('finance', 'finance'), ('portfolio', 'portfolio'), ('events', 'events'), ('kanban', 'kanban')], help_text='Target app for ingress', max_length=64),
        ),
    ]
