# Generated by Django 4.2.23 on 2025-11-23 23:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
        ('oya', '0002_remove_appingress_args'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(choices=[('community', 'community')], help_text='Target app for backup', max_length=64)),
                ('filename', models.CharField(help_text='Base filename prefix to use for backup dumps', max_length=128)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this backup should be executed')),
                ('bucket', models.ForeignKey(help_text='Target Vault bucket for backup', on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='vault.bucket')),
            ],
        ),
    ]
