# Generated by Django 4.2.23 on 2025-08-18 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oya', '0002_font_theme_platform_theme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theme',
            old_name='header_classes',
            new_name='header',
        ),
    ]
