# Generated by Django 4.2.23 on 2025-10-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oya', '0002_alter_appingress_app_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appingress',
            name='app_name',
            field=models.CharField(choices=[('oya', 'oya'), ('webfront', 'webfront'), ('memo', 'memo'), ('editor', 'editor'), ('gervazy', 'gervazy'), ('gitops', 'gitops'), ('vault', 'vault'), ('portfolio', 'portfolio'), ('community', 'community'), ('shareholders', 'shareholders')], help_text='Target app for ingress', max_length=64),
        ),
    ]
