# Generated by Django 4.2.23 on 2025-11-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oya', '0003_alter_appingress_app_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='rate_limit_max_requests',
            field=models.IntegerField(default=10, help_text='Max requests allowed per window'),
        ),
        migrations.AddField(
            model_name='platform',
            name='rate_limit_window',
            field=models.IntegerField(default=60, help_text='Rate limit window in seconds'),
        ),
    ]
