# Generated by Django 4.2.23 on 2025-10-07 10:49

import colorfield.fields
from django.db import migrations
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('oya', '0003_alter_appingress_app_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='colormix',
            name='appbar_text_dark',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='colormix',
            name='appbar_text_light',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='colormix',
            name='footer_bg_dark',
            field=colorfield.fields.ColorField(default='#1F1F1F', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='colormix',
            name='footer_bg_light',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='colormix',
            name='footer_text_dark',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='colormix',
            name='footer_text_light',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='theme',
            name='footer',
            field=django_jsonform.models.fields.JSONField(default=dict, help_text='Tailwind classes for footer element (light/dark mode)'),
        ),
    ]
