# Generated by Django 4.2.23 on 2025-10-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oya', '0003_alter_appingress_app_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardblock',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
