# Generated by Django 4.2.23 on 2025-09-20 18:58
# Generated by Django 4.2.23 on 2025-08-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oya', '0003_alter_appingress_app_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appingress',
            name='app_name',
            field=models.CharField(choices=[('oya', 'oya'), ('webfront', 'webfront'), ('memo', 'memo'), ('documents', 'documents'), ('kanban', 'kanban'), ('community', 'community'), ('mandragora', 'mandragora')], help_text='Target app for ingress', max_length=64),
            field=models.CharField(choices=[('oya', 'oya'), ('webfront', 'webfront'), ('nakamori', 'nakamori'), ('memo', 'memo'), ('resume', 'resume'), ('documents', 'documents'), ('kodama', 'kodama')], help_text='Target app for ingress', max_length=64),
        ),
    ]