# Generated by Django 4.2.23 on 2025-08-18 20:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oya', '0003_rename_header_classes_theme_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppIngress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(choices=[('oya', 'oya')], help_text='Target app for ingress', max_length=100)),
                ('args', models.JSONField(default=dict, help_text='Arguments to pass to the ingress command')),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this ingress should be executed')),
            ],
        ),
    ]
