# Generated by Django 4.2.23 on 2025-11-23 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oya', '0003_appbackup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appbackup',
            name='app_name',
            field=models.CharField(choices=[('community', 'community'), ('finance', 'finance'), ('portfolio', 'portfolio'), ('events', 'events'), ('ravioli', 'ravioli')], help_text='Target app for backup', max_length=64),
        ),
    ]
