# Generated by Django 4.2.23 on 2025-10-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oya', '0004_colormix_appbar_text_dark_colormix_appbar_text_light_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appingress',
            name='app_name',
            field=models.CharField(choices=[('oya', 'oya'), ('webfront', 'webfront'), ('memo', 'memo'), ('documents', 'documents'), ('kanban', 'kanban'), ('community', 'community'), ('mandragora', 'mandragora'), ('kodama', 'kodama'), ('federal', 'federal'), ('forum', 'forum'), ('gervazy', 'gervazy')], help_text='Target app for ingress', max_length=64),
        ),
    ]
