# Generated by Django 4.2.23 on 2025-10-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oya', '0004_dashboardblock_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardblock',
            name='link',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
