# Generated by Django 4.2.23 on 2025-11-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oya', '0004_alter_appbackup_app_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appbackup',
            name='app_name',
            field=models.CharField(choices=[('community', 'community'), ('finance', 'finance'), ('portfolio', 'portfolio'), ('events', 'events'), ('notes', 'notes')], help_text='Target app for backup', max_length=64),
        ),
    ]
