# Generated by Django 4.2.23 on 2025-11-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oya', '0004_platform_rate_limit_max_requests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='rate_limit_max_requests',
            field=models.IntegerField(default=20, help_text='Max requests allowed per window'),
        ),
    ]
