# Generated by Django 4.2.23 on 2025-11-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oya', '0005_alter_appbackup_app_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appingress',
            name='app_name',
            field=models.CharField(choices=[('oya', 'oya'), ('audit', 'audit'), ('memo', 'memo'), ('gervazy', 'gervazy'), ('vault', 'vault'), ('federal', 'federal'), ('community', 'community'), ('finance', 'finance'), ('portfolio', 'portfolio'), ('events', 'events'), ('kanban', 'kanban'), ('notes', 'notes'), ('ravioli', 'ravioli'), ('library', 'library')], help_text='Target app for ingress', max_length=64),
        ),
    ]
