# Generated by Django 4.2.23 on 2025-11-10 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oya', '0005_alter_platform_rate_limit_max_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='index_url',
        ),
    ]
