# Generated by Django 4.2.23 on 2025-10-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oya', '0005_alter_dashboardblock_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appingress',
            name='app_name',
            field=models.CharField(choices=[('oya', 'oya'), ('webfront', 'webfront'), ('memo', 'memo'), ('editor', 'editor'), ('gervazy', 'gervazy'), ('gitops', 'gitops'), ('vault', 'vault'), ('community', 'community'), ('shareholders', 'shareholders'), ('portfolio', 'portfolio'), ('events', 'events')], help_text='Target app for ingress', max_length=64),
        ),
    ]
