# Generated by Django 4.2.23 on 2025-10-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oya', '0006_alter_appingress_app_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appingress',
            name='app_name',
            field=models.CharField(choices=[('oya', 'oya'), ('webfront', 'webfront'), ('memo', 'memo'), ('editor', 'editor'), ('kanban', 'kanban'), ('community', 'community'), ('mandragora', 'mandragora'), ('kodama', 'kodama'), ('federal', 'federal'), ('forum', 'forum'), ('gervazy', 'gervazy'), ('gitops', 'gitops'), ('vault', 'vault'), ('portfolio', 'portfolio')], help_text='Target app for ingress', max_length=64),
        ),
    ]
