# Generated by Django 4.2.23 on 2025-08-18 20:53

from django.db import migrations
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('oya', '0006_alter_appingress_args'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appingress',
            name='args',
            field=django_jsonform.models.fields.JSONField(help_text='Arguments to pass to the ingress command'),
        ),
    ]
