# Generated by Django 4.2.23 on 2025-08-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oya', '0008_alter_appingress_args'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appingress',
            name='args',
            field=models.JSONField(blank=True, default=dict, help_text='Arguments to pass to the ingress command'),
        ),
    ]
