# Generated by Django 4.2.23 on 2025-08-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oya', '0009_alter_appingress_args'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appingress',
            name='app_name',
            field=models.CharField(choices=[('oya', 'oya'), ('netogami', 'netogami')], help_text='Target app for ingress', max_length=64),
        ),
    ]
