# Generated by Django 4.2.23 on 2025-08-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oya', '0011_alter_appingress_app_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appingress',
            name='app_name',
            field=models.CharField(choices=[('oya', 'oya'), ('netogami', 'netogami'), ('nakamori', 'nakamori'), ('renso', 'renso')], help_text='Target app for ingress', max_length=64),
        ),
    ]
