# Generated by Django 4.2.23 on 2025-12-13 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_community_location'),
        ('oya', '0012_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
