# Generated by Django 4.2.23 on 2025-12-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oya', '0014_alter_appingress_app_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appbackup',
            name='app_name',
            field=models.CharField(choices=[('community', 'community'), ('finance', 'finance'), ('portfolio', 'portfolio'), ('events', 'events')], help_text='Target app for backup', max_length=64),
        ),
        migrations.AlterField(
            model_name='appingress',
            name='app_name',
            field=models.CharField(choices=[('oya', 'oya'), ('audit', 'audit'), ('memo', 'memo'), ('gervazy', 'gervazy'), ('vault', 'vault'), ('federal', 'federal'), ('community', 'community'), ('finance', 'finance'), ('portfolio', 'portfolio'), ('events', 'events'), ('kanban', 'kanban'), ('ravioli', 'ravioli'), ('library', 'library'), ('webfront', 'webfront'), ('locations', 'locations'), ('assets', 'assets')], help_text='Target app for ingress', max_length=64),
        ),
        migrations.AlterField(
            model_name='graphsync',
            name='app_name',
            field=models.CharField(choices=[('community', 'community'), ('finance', 'finance'), ('portfolio', 'portfolio'), ('events', 'events'), ('federal', 'federal')], max_length=64),
        ),
    ]
