# Generated by Django 4.2.23 on 2025-12-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
