# Generated by Django 4.2.23 on 2025-10-02 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VaultFile',
        ),
    ]
