# Generated by Django 4.2.23 on 2025-10-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_bucket_vaultfile_bucket'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultfile',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='vaultfile',
            name='key',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='vaultfile',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('html', 'HTML'), ('text', 'Text File')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='vaultfile',
            unique_together={('bucket', 'key')},
        ),
    ]
