# Generated by Django 4.2.23 on 2025-10-04 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vault', '0002_delete_vaultfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='vault/files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False, help_text='If true, file is visible to others')),
                ('notes', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vault File',
                'verbose_name_plural': 'Vault Files',
            },
        ),
        migrations.AlterModelOptions(
            name='vaultpdf',
            options={'verbose_name': 'Vault PDF', 'verbose_name_plural': 'Vault PDFs'},
        ),
        migrations.RemoveField(
            model_name='vaultpdf',
            name='keyring',
        ),
        migrations.AddField(
            model_name='vaultpdf',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If true, file is visible to others'),
        ),
        migrations.AlterField(
            model_name='vaultpdf',
            name='file',
            field=models.FileField(upload_to='vault/files/'),
        ),
        migrations.AlterField(
            model_name='vaultpdf',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vaultpdf',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='KeyRing',
        ),
    ]
