# Generated by Django 4.2.23 on 2025-11-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_vaultfile_content_hash_vaultfile_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaultfile',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('html', 'HTML'), ('text', 'Text File'), ('json', 'JSON')], max_length=10),
        ),
    ]
