# Generated by Django 4.2.23 on 2026-10-01 02:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_sessions'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=40, unique=True)),
                ('recipient_hash', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('retrying', 'Being retried'), ('failed', 'Failed')], max_length=10)),
                ('tries', models.PositiveSmallIntegerField(default=1)),
                ('error', models.CharField(blank=True, max_length=200)),
                ('failures', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'notice deliveries',
                'ordering': ['purpose'],
            },
        ),
    ]
