# Generated by Django 4.2.23 on 2026-08-22 16:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0004_deprecate_is_federal_agent'),
        ('locations', '0005_address_latlon'),
        ('assets', '0005_ledger_decorations'),
        ('kanban', '0010_rewards'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-accepted_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('licence', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DatasetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('number', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('manifest_hash', models.CharField(blank=True, max_length=64)),
                ('frozen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='placidia.dataset')),
                ('frozen_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placidia_frozen_versions', to='people.person')),
            ],
            options={
                'ordering': ('-number',),
            },
        ),
        migrations.CreateModel(
            name='PlacidiaCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('collection_scheme', models.JSONField(blank=True, null=True)),
                ('licence', models.CharField(blank=True, max_length=100)),
                ('attribution', models.CharField(blank=True, max_length=200)),
                ('is_open', models.BooleanField(default=True, help_text='Whether new contributions are accepted at all.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placidia', to='kanban.campaign')),
                ('gem_asset', models.ForeignKey(blank=True, help_text='The decorative asset rewards are paid in.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='placidia_campaigns', to='assets.asset')),
                ('treasury_account', models.ForeignKey(blank=True, help_text="This campaign's gem purse. Empty means rewards fail, not that work stops.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='placidia_campaigns', to='assets.ledgeraccount')),
            ],
            options={
                'verbose_name': 'Placidia campaign',
            },
        ),
        migrations.CreateModel(
            name='PlacidiaBounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('instructions', models.TextField(blank=True, help_text='What to collect, and what counts as good.')),
                ('reward_summary', models.CharField(blank=True, help_text='Display only. The actual reward is a kanban RewardPolicy.', max_length=200)),
                ('collection_settings', models.JSONField(blank=True, null=True)),
                ('max_contributions', models.PositiveIntegerField(blank=True, help_text='Blank means unlimited.', null=True)),
                ('opens_at', models.DateTimeField(blank=True, null=True)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placidia_bounty', to='kanban.mission')),
            ],
            options={
                'verbose_name_plural': 'Placidia bounties',
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='DatasetVersionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='version_memberships', to='placidia.acceptedobservation')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='placidia.datasetversion')),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='placidia.placidiacampaign'),
        ),
        migrations.AddField(
            model_name='acceptedobservation',
            name='bounty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='placidia.placidiabounty'),
        ),
        migrations.AddField(
            model_name='acceptedobservation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placidia_observations', to='locations.address'),
        ),
        migrations.AddField(
            model_name='acceptedobservation',
            name='observed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placidia_observations', to='people.person'),
        ),
        migrations.AddField(
            model_name='acceptedobservation',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='accepted_observation', to='kanban.submission'),
        ),
        migrations.AddField(
            model_name='acceptedobservation',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placidia_observations', to='locations.zone'),
        ),
        migrations.AddConstraint(
            model_name='datasetversionmember',
            constraint=models.UniqueConstraint(fields=('version', 'observation'), name='placidia_unique_version_member'),
        ),
        migrations.AddConstraint(
            model_name='datasetversion',
            constraint=models.UniqueConstraint(fields=('dataset', 'number'), name='placidia_version_number_per_dataset'),
        ),
        migrations.AddConstraint(
            model_name='dataset',
            constraint=models.UniqueConstraint(fields=('campaign', 'slug'), name='placidia_dataset_slug_per_campaign'),
        ),
    ]
