# Generated by Django 4.2.23 on 2026-10-01 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gervazy', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Display name, e.g. 'Fastmail (production)'.", max_length=120)),
                ('backend', models.CharField(choices=[('smtp', 'SMTP'), ('console', 'Console (printed, not sent)'), ('dummy', 'Dummy (discarded)'), ('locmem', 'In-memory (tests)'), ('filebased', 'Files on disk')], default='console', help_text='How to send. Console and Dummy do not deliver, and Jess reports that honestly — the reset page then serves patron-approved recovery instead of promising an email.', max_length=20)),
                ('host', models.CharField(blank=True, max_length=255)),
                ('port', models.PositiveIntegerField(default=587)),
                ('use_tls', models.BooleanField(default=True, help_text='STARTTLS on port 587.')),
                ('use_ssl', models.BooleanField(default=False, help_text='Implicit TLS on port 465.')),
                ('timeout', models.PositiveIntegerField(default=10, help_text="Seconds. Django's default is no limit, which is wrong for a worker.")),
                ('username', models.CharField(blank=True, max_length=255)),
                ('from_address', models.EmailField(blank=True, help_text='The From: address. Falls back to DEFAULT_FROM_EMAIL when empty.', max_length=254)),
                ('reply_to', models.EmailField(blank=True, max_length=254)),
                ('imap_host', models.CharField(blank=True, help_text='e.g. imap.fastmail.com. Leave blank if this account is send-only.', max_length=255)),
                ('imap_port', models.PositiveIntegerField(blank=True, default=993)),
                ('imap_use_ssl', models.BooleanField(default=True, help_text='Implicit TLS on port 993.')),
                ('mailbox', models.CharField(blank=True, default='INBOX', max_length=255)),
                ('active', models.BooleanField(default=False, help_text='Exactly one provider is active; activating this one deactivates the others.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email provider',
                'verbose_name_plural': 'Email providers',
                'ordering': ['-active', 'label'],
            },
        ),
        migrations.CreateModel(
            name='InboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address', models.CharField(blank=True, max_length=255)),
                ('to', models.JSONField(blank=True, default=list)),
                ('subject', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('html_body', models.TextField(blank=True)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('message_id', models.CharField(max_length=998, unique=True)),
                ('in_reply_to', models.CharField(blank=True, max_length=998)),
                ('references', models.JSONField(blank=True, default=list)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('date_header', models.DateTimeField(blank=True, null=True)),
                ('read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Inbound message',
                'verbose_name_plural': 'Inbound messages',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='JessQuotaPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('metric_code', models.CharField(db_index=True, max_length=100)),
                ('limit', models.DecimalField(decimal_places=10, max_digits=30)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime')], default='daily', max_length=20)),
                ('mode', models.CharField(choices=[('track', 'Track only'), ('warn', 'Warn'), ('block', 'Block')], default='block', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Jess quota policy',
                'verbose_name_plural': 'Jess quota policies',
                'ordering': ['metric_code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.JSONField(default=list)),
                ('cc', models.JSONField(blank=True, default=list)),
                ('bcc', models.JSONField(blank=True, default=list)),
                ('subject', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('html_body', models.TextField(blank=True)),
                ('from_address', models.CharField(blank=True, max_length=255)),
                ('reply_to', models.JSONField(blank=True, default=list)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('provider_label', models.CharField(blank=True, help_text="The provider's label as it was when this was sent — survives the provider being renamed or deleted.", max_length=120)),
                ('purpose', models.CharField(choices=[('test', 'Test'), ('manual', 'Sent by hand'), ('password_reset', 'Password reset'), ('socialhub_endorsement', 'Endorsement'), ('other', 'Other')], default='other', max_length=40)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('held', 'Held')], db_index=True, default='queued', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True, help_text="The provider's own error text, kept verbatim. Diagnosing SMTP is exactly when a paraphrase is useless.")),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jess_messages', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(blank=True, help_text='Left empty to use whichever provider is active at send time.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='jess.emailprovider')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jess_released', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mail message',
                'verbose_name_plural': 'Mail messages',
                'ordering': ['-queued_at'],
            },
        ),
        migrations.CreateModel(
            name='JessUsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_code', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=30)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('source_type', models.CharField(blank=True, max_length=100)),
                ('source_id', models.CharField(blank=True, max_length=255)),
                ('source_label', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('recorded', 'Recorded'), ('voided', 'Voided')], default='recorded', max_length=20)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jess usage event',
                'verbose_name_plural': 'Jess usage events',
                'ordering': ['-occurred_at'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='jessquotapolicy',
            constraint=models.UniqueConstraint(fields=('metric_code',), name='jess_jessquotapolicy_one_per_metric'),
        ),
        migrations.AddField(
            model_name='inboundmessage',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound', to='jess.emailprovider'),
        ),
        migrations.AddField(
            model_name='inboundmessage',
            name='read_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jess_read', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inboundmessage',
            name='replied_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply_to_inbound', to='jess.mailmessage'),
        ),
        migrations.AddField(
            model_name='emailprovider',
            name='secret',
            field=models.ForeignKey(blank=True, help_text='Gervazy EncryptedSecret holding the SMTP password.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jess_providers', to='gervazy.encryptedsecret'),
        ),
        migrations.AddIndex(
            model_name='mailmessage',
            index=models.Index(fields=['status', 'queued_at'], name='jess_mailme_status_2d72ad_idx'),
        ),
        migrations.AddIndex(
            model_name='jessusageevent',
            index=models.Index(fields=['metric_code', 'occurred_at'], name='jessusageevent_mtime'),
        ),
        migrations.AddIndex(
            model_name='jessusageevent',
            index=models.Index(fields=['user', 'metric_code'], name='jessusageevent_umetric'),
        ),
        migrations.AddConstraint(
            model_name='jessusageevent',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('idempotency_key',), name='jess_jessusageevent_idem'),
        ),
        migrations.AddIndex(
            model_name='inboundmessage',
            index=models.Index(fields=['read', 'received_at'], name='jess_inboun_read_dc57ff_idx'),
        ),
    ]
