# Generated by Django 4.2.23 on 2026-07-30 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gervazy', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Display name, e.g. 'Fastmail (production)'.", max_length=120)),
                ('backend', models.CharField(choices=[('smtp', 'SMTP'), ('console', 'Console (printed, not sent)'), ('dummy', 'Dummy (discarded)'), ('locmem', 'In-memory (tests)'), ('filebased', 'Files on disk')], default='console', help_text="How to send. Console and Dummy do not deliver, and Jess reports that honestly — the 'Forgot password?' link hides itself.", max_length=20)),
                ('host', models.CharField(blank=True, max_length=255)),
                ('port', models.PositiveIntegerField(default=587)),
                ('use_tls', models.BooleanField(default=True, help_text='STARTTLS on port 587.')),
                ('use_ssl', models.BooleanField(default=False, help_text='Implicit TLS on port 465.')),
                ('timeout', models.PositiveIntegerField(default=10, help_text="Seconds. Django's default is no limit, which is wrong for a worker.")),
                ('username', models.CharField(blank=True, max_length=255)),
                ('from_address', models.EmailField(blank=True, help_text='The From: address. Falls back to DEFAULT_FROM_EMAIL when empty.', max_length=254)),
                ('reply_to', models.EmailField(blank=True, max_length=254)),
                ('active', models.BooleanField(default=False, help_text='Exactly one provider is active; activating this one deactivates the others.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('secret', models.ForeignKey(blank=True, help_text='Gervazy EncryptedSecret holding the SMTP password.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jess_providers', to='gervazy.encryptedsecret')),
            ],
            options={
                'verbose_name': 'Email provider',
                'verbose_name_plural': 'Email providers',
                'ordering': ['-active', 'label'],
            },
        ),
        migrations.CreateModel(
            name='MailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.JSONField(default=list)),
                ('cc', models.JSONField(blank=True, default=list)),
                ('bcc', models.JSONField(blank=True, default=list)),
                ('subject', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('html_body', models.TextField(blank=True)),
                ('from_address', models.CharField(blank=True, max_length=255)),
                ('reply_to', models.JSONField(blank=True, default=list)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('provider_label', models.CharField(blank=True, help_text="The provider's label as it was when this was sent — survives the provider being renamed or deleted.", max_length=120)),
                ('purpose', models.CharField(choices=[('test', 'Test'), ('password_reset', 'Password reset'), ('socialhub_endorsement', 'Endorsement'), ('other', 'Other')], default='other', max_length=40)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True, help_text="The provider's own error text, kept verbatim. Diagnosing SMTP is exactly when a paraphrase is useless.")),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jess_messages', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(blank=True, help_text='Left empty to use whichever provider is active at send time.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='jess.emailprovider')),
            ],
            options={
                'verbose_name': 'Mail message',
                'verbose_name_plural': 'Mail messages',
                'ordering': ['-queued_at'],
                'indexes': [models.Index(fields=['status', 'queued_at'], name='jess_mailme_status_2d72ad_idx')],
            },
        ),
    ]
