# Generated by Django 4.2.23 on 2026-07-31 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailmessage',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jess_released', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mailmessage',
            name='purpose',
            field=models.CharField(choices=[('test', 'Test'), ('manual', 'Sent by hand'), ('password_reset', 'Password reset'), ('socialhub_endorsement', 'Endorsement'), ('other', 'Other')], default='other', max_length=40),
        ),
        migrations.AlterField(
            model_name='mailmessage',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('held', 'Held')], db_index=True, default='queued', max_length=20),
        ),
    ]
