# Generated by Django 4.2.23 on 2026-07-31 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jess', '0002_manual_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailprovider',
            name='imap_host',
            field=models.CharField(blank=True, help_text='e.g. imap.fastmail.com. Leave blank if this account is send-only.', max_length=255),
        ),
        migrations.AddField(
            model_name='emailprovider',
            name='imap_port',
            field=models.PositiveIntegerField(blank=True, default=993),
        ),
        migrations.AddField(
            model_name='emailprovider',
            name='imap_use_ssl',
            field=models.BooleanField(default=True, help_text='Implicit TLS on port 993.'),
        ),
        migrations.AddField(
            model_name='emailprovider',
            name='mailbox',
            field=models.CharField(blank=True, default='INBOX', max_length=255),
        ),
        migrations.CreateModel(
            name='InboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address', models.CharField(blank=True, max_length=255)),
                ('to', models.JSONField(blank=True, default=list)),
                ('subject', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('html_body', models.TextField(blank=True)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('message_id', models.CharField(max_length=998, unique=True)),
                ('in_reply_to', models.CharField(blank=True, max_length=998)),
                ('references', models.JSONField(blank=True, default=list)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('date_header', models.DateTimeField(blank=True, null=True)),
                ('read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound', to='jess.emailprovider')),
                ('read_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jess_read', to=settings.AUTH_USER_MODEL)),
                ('replied_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply_to_inbound', to='jess.mailmessage')),
            ],
            options={
                'verbose_name': 'Inbound message',
                'verbose_name_plural': 'Inbound messages',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['read', 'received_at'], name='jess_inboun_read_dc57ff_idx')],
            },
        ),
    ]
