# Generated by Django 4.2.23 on 2026-05-31 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='incident',
            new_name='incidents_i_status_85e429_idx',
            old_name='incidents_i_status_sev_idx',
        ),
        migrations.RenameIndex(
            model_name='incident',
            new_name='incidents_i_inciden_337dba_idx',
            old_name='incidents_i_type_idx',
        ),
    ]
