# Generated by Django 4.2.23 on 2026-05-26 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0015_remove_vaultinvoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('format', models.CharField(choices=[('html', 'HTML'), ('xml', 'XML'), ('yaml', 'YAML')], default='html', max_length=10)),
                ('template_source', models.TextField(help_text='Jinja2 template. Available context: invoice, issued_to, issued_by, bucket, tariff, billing_cycle, settlements, now.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_report_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invoice Report Template',
                'verbose_name_plural': 'Invoice Report Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rendered_output', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_invoice_reports', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='invoice.invoice')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='invoice.invoicereporttemplate')),
                ('vault_file', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_report', to='vault.vaultfile')),
            ],
            options={
                'verbose_name': 'Invoice Report',
                'verbose_name_plural': 'Invoice Reports',
                'ordering': ['-generated_at'],
            },
        ),
    ]
