# Generated by Django 4.2.23 on 2026-05-12 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Environment variable name, for example OPENAI_API_KEY.', max_length=120, unique=True)),
                ('active', models.BooleanField(default=True, help_text='When active, admin can set the value into os.environ for this process.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KeyRing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salt', models.BinaryField(help_text='Salt used for key derivation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, help_text='Optional unique name for this KeyRing. Auto-generated if omitted.', max_length=128, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyrings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RSAKeyPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.CharField(max_length=100, unique=True)),
                ('public_key_pem', models.TextField()),
                ('private_key_pem', models.TextField()),
                ('issuer', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecretKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_encrypted', models.CharField(max_length=1024)),
                ('size', models.PositiveIntegerField(choices=[(64, '64 bytes (~86 chars)'), (128, '128 bytes (~172 chars)'), (256, '256 bytes (~344 chars)')], default=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('keyring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to='gervazy.keyring')),
            ],
        ),
        migrations.CreateModel(
            name='SecretPassword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Optional name for this secret access box. Auto-generated if omitted.', max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('environment_variable', models.ForeignKey(blank=True, help_text='Environment variable that contains the passphrase for unlocking the SecretKey.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secret_passwords', to='gervazy.environmentvariable')),
                ('secret_key', models.ForeignKey(blank=True, help_text='SecretKey used to encrypt and decrypt this password.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passwords', to='gervazy.secretkey')),
            ],
        ),
    ]
