# Generated by Django 4.2.23 on 2026-05-25 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import toto.gervazy.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name_encrypted', models.BinaryField()),
                ('original_name_nonce', models.BinaryField(default=toto.gervazy.models.random_12_byte_nonce)),
                ('mime_type', models.CharField(blank=True, max_length=127)),
                ('file', models.FileField(upload_to='strongbox/encrypted/')),
                ('nonce_strategy', models.CharField(default='random_per_chunk', max_length=32)),
                ('chunk_size', models.PositiveIntegerField(default=65536)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('ciphertext_sha256', models.CharField(blank=True, max_length=64)),
                ('plaintext_size', models.BigIntegerField(default=0)),
                ('ciphertext_size', models.BigIntegerField(default=0)),
                ('algorithm', models.CharField(default='AES-256-GCM', max_length=32)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('state', models.CharField(choices=[('pre_active', 'Pre-active'), ('active', 'Active'), ('suspended', 'Suspended'), ('retired', 'Retired'), ('compromised', 'Compromised'), ('destroyed', 'Destroyed')], default='active', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encrypted_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='UserStrongbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('kdf', models.CharField(default='argon2id', max_length=32)),
                ('kdf_version', models.PositiveSmallIntegerField(default=19)),
                ('salt', models.BinaryField(default=toto.gervazy.models.random_16_byte_salt, help_text='Random 16-byte KDF salt.')),
                ('argon2_memory_cost', models.PositiveIntegerField(default=65536, help_text='Argon2id memory cost in KiB.')),
                ('argon2_iterations', models.PositiveIntegerField(default=3)),
                ('argon2_lanes', models.PositiveSmallIntegerField(default=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_strongboxes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VaultMasterKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_vmk', models.BinaryField()),
                ('nonce', models.BinaryField(default=toto.gervazy.models.random_12_byte_nonce)),
                ('algorithm', models.CharField(default='AES-256-GCM', max_length=32)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('state', models.CharField(choices=[('pre_active', 'Pre-active'), ('active', 'Active'), ('suspended', 'Suspended'), ('retired', 'Retired'), ('compromised', 'Compromised'), ('destroyed', 'Destroyed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('strongbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_keys', to='gervazy.userstrongbox')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='WrappedDataKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_dek', models.BinaryField()),
                ('nonce', models.BinaryField(default=toto.gervazy.models.random_12_byte_nonce)),
                ('algorithm', models.CharField(default='AES-256-GCM', max_length=32)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('state', models.CharField(choices=[('pre_active', 'Pre-active'), ('active', 'Active'), ('suspended', 'Suspended'), ('retired', 'Retired'), ('compromised', 'Compromised'), ('destroyed', 'Destroyed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('strongbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_keys', to='gervazy.userstrongbox')),
                ('vmk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wrapped_data_keys', to='gervazy.vaultmasterkey')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='EncryptedSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('purpose', models.CharField(blank=True, help_text='Example: smtp_password, api_token, oauth_client_secret.', max_length=255)),
                ('ciphertext', models.BinaryField()),
                ('nonce', models.BinaryField(default=toto.gervazy.models.random_12_byte_nonce, help_text='Random 12-byte AES-GCM nonce. Must be unique per wrapped_key.')),
                ('aad', models.BinaryField(blank=True, default=b'', help_text='Additional authenticated data. Bind ciphertext to context.')),
                ('algorithm', models.CharField(default='AES-256-GCM', max_length=32)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('state', models.CharField(choices=[('pre_active', 'Pre-active'), ('active', 'Active'), ('suspended', 'Suspended'), ('retired', 'Retired'), ('compromised', 'Compromised'), ('destroyed', 'Destroyed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('strongbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to='gervazy.userstrongbox')),
                ('wrapped_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secrets', to='gervazy.wrappeddatakey')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EncryptedPrivateKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.CharField(max_length=100, unique=True)),
                ('key_type', models.CharField(choices=[('Ed25519', 'Ed25519'), ('RSA-2048', 'RSA-2048'), ('RSA-4096', 'RSA-4096')], max_length=16)),
                ('public_key_pem', models.TextField()),
                ('issuer', models.URLField(blank=True)),
                ('encrypted_private_key', models.BinaryField()),
                ('nonce', models.BinaryField(default=toto.gervazy.models.random_12_byte_nonce)),
                ('aad', models.BinaryField(blank=True, default=b'')),
                ('algorithm', models.CharField(default='AES-256-GCM', max_length=32)),
                ('state', models.CharField(choices=[('pre_active', 'Pre-active'), ('active', 'Active'), ('suspended', 'Suspended'), ('retired', 'Retired'), ('compromised', 'Compromised'), ('destroyed', 'Destroyed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('strongbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_keys', to='gervazy.userstrongbox')),
                ('wrapped_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='private_keys', to='gervazy.wrappeddatakey')),
            ],
            options={
                'ordering': ['key_id'],
            },
        ),
        migrations.CreateModel(
            name='EncryptedFileChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('nonce', models.BinaryField(default=toto.gervazy.models.random_12_byte_nonce)),
                ('ciphertext_size', models.PositiveIntegerField()),
                ('ciphertext_sha256', models.CharField(blank=True, max_length=64)),
                ('encrypted_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='gervazy.encryptedfile')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.AddField(
            model_name='encryptedfile',
            name='strongbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encrypted_files', to='gervazy.userstrongbox'),
        ),
        migrations.AddField(
            model_name='encryptedfile',
            name='wrapped_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='gervazy.wrappeddatakey'),
        ),
        migrations.CreateModel(
            name='CryptoAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=64)),
                ('object_type', models.CharField(blank=True, max_length=64)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('success', models.BooleanField()),
                ('reason', models.TextField(blank=True, help_text='Do not store secret values here.')),
                ('key_version', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crypto_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('strongbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='gervazy.userstrongbox')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='wrappeddatakey',
            constraint=models.UniqueConstraint(fields=('strongbox', 'version'), name='unique_dek_version_per_strongbox'),
        ),
        migrations.AddConstraint(
            model_name='wrappeddatakey',
            constraint=models.UniqueConstraint(fields=('vmk', 'nonce'), name='unique_dek_nonce_per_vmk'),
        ),
        migrations.AddConstraint(
            model_name='vaultmasterkey',
            constraint=models.UniqueConstraint(fields=('strongbox', 'version'), name='unique_vmk_version_per_strongbox'),
        ),
        migrations.AddConstraint(
            model_name='vaultmasterkey',
            constraint=models.UniqueConstraint(fields=('strongbox', 'nonce'), name='unique_vmk_nonce_per_strongbox'),
        ),
        migrations.AddConstraint(
            model_name='userstrongbox',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_strongbox_name_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='encryptedsecret',
            constraint=models.UniqueConstraint(fields=('strongbox', 'name'), name='unique_secret_name_per_strongbox'),
        ),
        migrations.AddConstraint(
            model_name='encryptedsecret',
            constraint=models.UniqueConstraint(fields=('wrapped_key', 'nonce'), name='unique_secret_nonce_per_wrapped_key'),
        ),
        migrations.AddConstraint(
            model_name='encryptedprivatekey',
            constraint=models.UniqueConstraint(fields=('wrapped_key', 'nonce'), name='unique_private_key_nonce_per_wrapped_key'),
        ),
        migrations.AddConstraint(
            model_name='encryptedfilechunk',
            constraint=models.UniqueConstraint(fields=('encrypted_file', 'index'), name='unique_chunk_index_per_file'),
        ),
        migrations.AddConstraint(
            model_name='encryptedfilechunk',
            constraint=models.UniqueConstraint(fields=('encrypted_file', 'nonce'), name='unique_chunk_nonce_per_file'),
        ),
        migrations.AddConstraint(
            model_name='encryptedfile',
            constraint=models.UniqueConstraint(fields=('wrapped_key', 'original_name_nonce'), name='unique_file_name_nonce_per_wrapped_key'),
        ),
    ]
