# Generated by Django 4.2.23 on 2026-04-03 11:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gervazy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretPassword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('password_encrypted', models.TextField(help_text='Encrypted password material')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('keyring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passwords', to='gervazy.keyring')),
            ],
        ),
    ]
