# Generated by Django 4.2.23 on 2026-04-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gervazy', '0002_secretpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretpassword',
            name='name',
            field=models.CharField(blank=True, help_text='Optional name for this password. Auto-generated if omitted.', max_length=128, unique=True),
        ),
    ]
