# Generated by Django 4.2.23 on 2026-05-08 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gervazy', '0002_refactor_secretpassword_unlock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretpassword',
            name='name',
            field=models.CharField(blank=True, help_text='Optional name for this secret access box. Auto-generated if omitted.', max_length=128, unique=True),
        ),
    ]
