# Generated by Django 4.2.23 on 2026-05-29 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claims', '0001_initial'),
        ('contracts', '0004_contract_body_vault_pdf'),
        ('assets', '0007_remove_asset_mint_transaction_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0003_add_digital_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('owner_type', models.CharField(blank=True, max_length=100)),
                ('owner_id', models.CharField(blank=True, max_length=255)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='assets.asset')),
                ('budget_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_budgets', to='assets.ledgeraccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetStreamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('direction', models.CharField(choices=[('inflow', 'Inflow'), ('outflow', 'Outflow')], max_length=10)),
                ('namespace', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'code'],
                'indexes': [models.Index(fields=['direction', 'is_active'], name='budget_budg_directi_a60e4c_idx'), models.Index(fields=['namespace', 'code'], name='budget_budg_namespa_29e71a_idx')],
            },
        ),
        migrations.CreateModel(
            name='BudgetLedgerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('operating', 'Operating'), ('reserve', 'Reserve'), ('receivables', 'Receivables'), ('payables', 'Payables'), ('payroll', 'Payroll'), ('escrow', 'Escrow'), ('tax', 'Tax'), ('external', 'External')], default='operating', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('can_receive', models.BooleanField(default=True)),
                ('can_pay', models.BooleanField(default=True)),
                ('can_commit', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_bindings', to='budget.budget')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_account_bindings', to=settings.AUTH_USER_MODEL)),
                ('ledger_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_bindings', to='assets.ledgeraccount')),
            ],
            options={
                'ordering': ['role', 'ledger_account__code'],
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('approved', 'Approved'), ('committed', 'Committed'), ('booked', 'Booked'), ('cancelled', 'Cancelled'), ('reversed', 'Reversed')], default='planned', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('amount_base_units', models.PositiveBigIntegerField()),
                ('source_type', models.CharField(blank=True, max_length=100)),
                ('source_id', models.CharField(blank=True, max_length=255)),
                ('source_label', models.CharField(blank=True, max_length=255)),
                ('source_url', models.CharField(blank=True, max_length=500)),
                ('import_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('external_reference', models.CharField(blank=True, max_length=255)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('booked_at', models.DateTimeField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_binding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='budget.budgetledgeraccount')),
                ('allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_items', to='claims.allocation')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_items', to='assets.asset')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='budget.budget')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_items', to='contracts.contract')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_items', to='people.person')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_items', to=settings.AUTH_USER_MODEL)),
                ('ledger_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_items', to='assets.ledgertransaction')),
                ('obligation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_items', to='assets.obligation')),
                ('paired_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paired_with', to='budget.budgetitem')),
                ('stream_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='budget.budgetstreamtype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='budgetledgeraccount',
            constraint=models.UniqueConstraint(fields=('budget', 'ledger_account', 'role'), name='budget_unique_account_role'),
        ),
        migrations.AddIndex(
            model_name='budgetitem',
            index=models.Index(fields=['budget', 'status'], name='budget_budg_budget__92a09f_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetitem',
            index=models.Index(fields=['source_type', 'source_id'], name='budget_budg_source__5793a9_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetitem',
            index=models.Index(fields=['stream_type', 'status'], name='budget_budg_stream__9c3ea4_idx'),
        ),
        migrations.AddConstraint(
            model_name='budgetitem',
            constraint=models.UniqueConstraint(condition=models.Q(('import_key', ''), _negated=True), fields=('budget', 'import_key'), name='budget_item_unique_import_key'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['status'], name='budget_budg_status_a86797_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['owner_type', 'owner_id'], name='budget_budg_owner_t_383c18_idx'),
        ),
    ]
