# Generated by Django 4.2.23 on 2026-05-16 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socialhub', '0001_initial'),
        ('locations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Person',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                        ('display_name', models.CharField(max_length=150)),
                        ('bio', models.TextField(blank=True, null=True)),
                        ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                        ('joined_date', models.DateTimeField(default=django.utils.timezone.now)),
                        ('slug', models.SlugField(blank=True, unique=True)),
                        ('date_of_birth', models.DateField(blank=True, null=True)),
                        ('email', models.EmailField(blank=True, max_length=254, null=True)),
                        ('phone', models.CharField(blank=True, max_length=50, null=True)),
                        ('address', models.ForeignKey(blank=True, help_text='Optional address for this community member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='locations.address')),
                        ('communities', models.ManyToManyField(blank=True, db_table='socialhub_person_communities', related_name='members', to='socialhub.community')),
                        ('patron', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentees', to='people.person')),
                        ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_profile', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'socialhub_person',
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
