# Generated by Django 4.2.23 on 2026-05-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_federal_agent',
            field=models.BooleanField(default=False, help_text='Federal agents are exempt from community poll taxes.'),
        ),
    ]
