# Generated by Django 4.2.23 on 2026-05-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_add_digital_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('pl', 'Polski')], default='en', max_length=10),
        ),
    ]
