# Generated by Django 4.2.23 on 2026-07-05 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import toto.api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_initial'),
        ('ingestor', '0001_initial'),
        ('vault', '0007_alter_vaultfile_file_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('extractor_kind', models.CharField(default='rest_api', help_text='Extractor plugin key (see services/extract).', max_length=40)),
                ('extract_config', models.JSONField(blank=True, default=dict, help_text='Non-secret extraction config: endpoint, params, records_path, pagination.', validators=[toto.api.models._reject_secret_like_json])),
                ('mapping_spec', models.JSONField(blank=True, default=dict, help_text='Declarative record → nodes/relationships mapping (see services/mapping.py).')),
                ('trusted', models.BooleanField(default=False, help_text='Auto-apply valid elements after a run; the full proposal and apply log are still recorded for after-the-fact audit.')),
                ('is_active', models.BooleanField(default=True)),
                ('schedule_enabled', models.BooleanField(default=False)),
                ('interval_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('http_connector', models.ForeignKey(help_text='Outbound API connector supplying base URL + auth (secrets in Gervazy).', on_delete=django.db.models.deletion.PROTECT, related_name='data_connectors', to='api.connector')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_connectors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data connector',
                'verbose_name_plural': 'Data connectors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConnectorRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running…'), ('review', 'Awaiting review'), ('applied', 'Applied'), ('empty', 'Empty'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('triggered', models.CharField(choices=[('manual', 'Manual'), ('schedule', 'Schedule')], default='manual', max_length=16)),
                ('request_log', models.JSONField(blank=True, default=list)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='connectors.dataconnector')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connector_runs', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connector_runs', to='ingestor.ingestproposal')),
                ('raw_payload_file', models.ForeignKey(blank=True, help_text='Archived raw API payload (all fetched pages).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vault.vaultfile')),
            ],
            options={
                'verbose_name': 'Connector run',
                'verbose_name_plural': 'Connector runs',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['connector', 'status'], name='connectors__connect_38bbc7_idx'), models.Index(fields=['status', 'created_at'], name='connectors__status_fccad5_idx')],
            },
        ),
    ]
