# Generated by Django 4.2.23 on 2025-12-19 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mandragora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('chart_type', models.CharField(choices=[('line', 'Line'), ('bar', 'Bar'), ('pie', 'Pie'), ('doughnut', 'Doughnut')], max_length=20)),
                ('stacked', models.BooleanField(default=False)),
                ('params', models.JSONField(blank=True, default=dict, help_text='Optional JSON parameters passed to LambdaNode when computing data')),
                ('lambda_node', models.ForeignKey(blank=True, help_text='Optional LambdaNode to compute chart data', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charts', to='mandragora.lambdanode')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='HtmlTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('content', models.TextField(help_text='Raw HTML template content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('json_schema', models.JSONField(blank=True, help_text='Optional JSON Schema to validate DynamicPage data', null=True)),
                ('script', models.TextField(blank=True, help_text='Optional JavaScript to be injected into the page', null=True)),
            ],
            options={
                'verbose_name': 'HTML Template',
                'verbose_name_plural': 'HTML Templates',
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Static Page',
                'verbose_name_plural': 'Static Pages',
            },
        ),
        migrations.CreateModel(
            name='MetricsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('charts', models.ManyToManyField(blank=True, help_text='Charts included in this metrics page', related_name='metrics_pages', to='webfront.chart')),
            ],
            options={
                'verbose_name': 'Metrics Page',
                'verbose_name_plural': 'Metrics Pages',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DynamicPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('data', models.JSONField(help_text='JSON data to be injected into template')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lambda_node', models.ForeignKey(blank=True, help_text='Optional LambdaNode to process context before rendering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dynamic_pages', to='mandragora.lambdanode')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='webfront.htmltemplate')),
            ],
            options={
                'verbose_name': 'Dynamic Page',
                'verbose_name_plural': 'Dynamic Pages',
            },
        ),
    ]
