# Generated by Django 4.2.23 on 2025-08-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('image', models.ImageField(upload_to='uploads/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='dynamicpage',
            name='template_key',
            field=models.CharField(choices=[('sport', 'sport.json'), ('basilisk', 'basilisk.json'), ('spectrum', 'spectrum.json')], max_length=100),
        ),
    ]
