# Generated by Django 4.2.23 on 2025-12-13 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mandragora', '0001_initial'),
        ('webfront', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicpage',
            name='lambda_node',
            field=models.ForeignKey(blank=True, help_text='Optional LambdaNode to process context before rendering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dynamic_pages', to='mandragora.lambdanode'),
        ),
    ]
