# Generated by Django 4.2.23 on 2025-10-18 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_vaultfile_content_hash_vaultfile_key_and_more'),
        ('webfront', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('json_schema', models.JSONField(blank=True, null=True)),
                ('check_schema', models.BooleanField(default=True)),
                ('html_template_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vault.vaultfile')),
            ],
        ),
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('html_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vault.vaultfile')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webfront.language')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='dynamicpage',
            name='generator',
        ),
        migrations.RemoveField(
            model_name='dynamicpage',
            name='language',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.RemoveField(
            model_name='staticpage',
            name='language',
        ),
        migrations.RemoveField(
            model_name='pagegenerator',
            name='check_schema',
        ),
        migrations.RemoveField(
            model_name='pagegenerator',
            name='html_template_file',
        ),
        migrations.RemoveField(
            model_name='pagegenerator',
            name='json_schema',
        ),
        migrations.AddField(
            model_name='pagegenerator',
            name='config_json',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagegenerator',
            name='language',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='webfront.language'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagegenerator',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pagegenerator',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.DeleteModel(
            name='DynamicPage',
        ),
        migrations.DeleteModel(
            name='StaticPage',
        ),
        migrations.AddField(
            model_name='pagegenerator',
            name='template',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='webfront.pagetemplate'),
            preserve_default=False,
        ),
    ]
