# Generated by Django 4.2.23 on 2025-12-14 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mandragora', '0001_initial'),
        ('webfront', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('chart_type', models.CharField(choices=[('line', 'Line'), ('bar', 'Bar'), ('pie', 'Pie'), ('doughnut', 'Doughnut')], max_length=20)),
                ('stacked', models.BooleanField(default=False)),
                ('params', models.JSONField(blank=True, default=dict, help_text='Optional JSON parameters passed to LambdaNode when computing data')),
                ('lambda_node', models.ForeignKey(blank=True, help_text='Optional LambdaNode to compute chart data', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charts', to='mandragora.lambdanode')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='MetricsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('charts', models.ManyToManyField(blank=True, help_text='Charts included in this metrics page', related_name='metrics_pages', to='webfront.chart')),
            ],
            options={
                'verbose_name': 'Metrics Page',
                'verbose_name_plural': 'Metrics Pages',
                'ordering': ['order', 'title'],
            },
        ),
    ]
