# Generated by Django 4.2.23 on 2025-12-19 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='lambda_node',
        ),
    ]
