# Generated by Django 4.2.23 on 2025-12-27 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webfront', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cypherquery',
            name='code',
            field=models.TextField(blank=True, help_text='Restricted Python code snippet executed after the query or widget logic.'),
        ),
        migrations.AlterField(
            model_name='cypherquery',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cypher_queries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cypherquery',
            name='test_context',
            field=models.JSONField(blank=True, help_text='Optional JSON context for testing.', null=True),
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.TextField(blank=True, help_text='Restricted Python code snippet executed after the query or widget logic.')),
                ('test_context', models.JSONField(blank=True, help_text='Optional JSON context for testing.', null=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('line_chart', 'Line Chart'), ('pie_chart', 'Pie Chart'), ('bar_chart', 'Bar Chart'), ('list', 'List'), ('card', 'Card')], help_text='Type of widget.', max_length=50)),
                ('config', models.JSONField(blank=True, help_text='Widget-specific configuration (axes, labels, filters, etc.).', null=True)),
                ('cypher_query', models.ForeignKey(blank=True, help_text='Optional Cypher query powering this widget.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='widgets', to='webfront.cypherquery')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DynamicPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human-readable name of the query.', max_length=200, unique=True)),
                ('query', models.TextField(help_text='The query string to run (Cypher, SQL, API, etc.).')),
                ('code', models.TextField(blank=True, help_text='Restricted Python code snippet executed after the query or widget logic.')),
                ('test_context', models.JSONField(blank=True, help_text='Optional JSON context for testing.', null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dynamic_pages', to=settings.AUTH_USER_MODEL)),
                ('cypher_query', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dynamic_pages', to='webfront.cypherquery')),
                ('widgets', models.ManyToManyField(blank=True, related_name='pages', to='webfront.widget')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
