# Generated by Django 4.2.23 on 2025-12-26 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MetricsPage',
        ),
    ]
