# Generated by Django 4.2.23 on 2025-12-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0002_alter_cypherquery_code_alter_cypherquery_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicpage',
            name='cypher_query',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='cypher_query',
        ),
        migrations.AlterField(
            model_name='cypherquery',
            name='code',
            field=models.TextField(help_text='Restricted Python code snippet'),
        ),
        migrations.AlterField(
            model_name='cypherquery',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cypherquery',
            name='name',
            field=models.CharField(help_text='Human-readable name.', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='cypherquery',
            name='test_context',
            field=models.JSONField(blank=True, help_text='Optional JSON context for testing', null=True),
        ),
        migrations.AlterField(
            model_name='dynamicpage',
            name='code',
            field=models.TextField(help_text='Restricted Python code snippet'),
        ),
        migrations.AlterField(
            model_name='dynamicpage',
            name='name',
            field=models.CharField(help_text='Human-readable name.', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='dynamicpage',
            name='test_context',
            field=models.JSONField(blank=True, help_text='Optional JSON context for testing', null=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='code',
            field=models.TextField(help_text='Restricted Python code snippet'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='config',
            field=models.JSONField(blank=True, help_text='Widget-specific configuration.', null=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='test_context',
            field=models.JSONField(blank=True, help_text='Optional JSON context for testing', null=True),
        ),
    ]
