# Generated by Django 4.2.23 on 2025-12-26 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0002_alter_pagewidget_widget_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicpage',
            name='loader_code',
        ),
        migrations.RemoveField(
            model_name='dynamicpage',
            name='loader_test_context',
        ),
    ]
