# Generated by Django 4.2.23 on 2025-12-26 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0003_remove_dynamicpage_loader_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagewidget',
            name='layout',
        ),
    ]
