# Generated by Django 4.2.23 on 2025-12-27 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0003_remove_dynamicpage_cypher_query_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicpage',
            name='widgets',
        ),
        migrations.DeleteModel(
            name='Widget',
        ),
    ]
