# Generated by Django 4.2.23 on 2025-12-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0004_remove_pagewidget_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagewidget',
            name='name',
            field=models.CharField(default='', help_text='Unique widget name within this page', max_length=200),
            preserve_default=False,
        ),
    ]
