# Generated by Django 4.2.23 on 2025-12-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0004_remove_dynamicpage_widgets_delete_widget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicpage',
            name='created_at',
        ),
        migrations.AddField(
            model_name='dynamicpage',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier for this page.', max_length=200, unique=True),
        ),
    ]
