# Generated by Django 4.2.23 on 2025-12-26 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webfront', '0005_pagewidget_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagewidget',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='dynamicpage',
            name='layout',
        ),
        migrations.RemoveField(
            model_name='dynamicpage',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='dynamicpage',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dynamicpage',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagewidget',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagewidget',
            name='config',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='pagewidget',
            name='test_context',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagewidget',
            name='widget_type',
            field=models.CharField(choices=[('chart.line', 'Line Chart'), ('chart.bar', 'Bar Chart'), ('chart.pie', 'Pie Chart'), ('table.basic', 'Table'), ('card.basic', 'Card'), ('list.basic', 'List')], max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='pagewidget',
            unique_together={('page', 'name')},
        ),
    ]
