# Generated by Django 4.2.23 on 2025-12-26 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webfront', '0006_alter_pagewidget_options_remove_dynamicpage_layout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicpage',
            name='created_by',
        ),
        migrations.AddField(
            model_name='dynamicpage',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_pages', to=settings.AUTH_USER_MODEL),
        ),
    ]
