# Generated by Django 4.2.23 on 2025-12-27 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0006_remove_dynamicpage_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicpage',
            name='cypher_query',
        ),
        migrations.AddField(
            model_name='dynamicpage',
            name='code',
            field=models.TextField(default='', help_text='Restricted Python code snippet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dynamicpage',
            name='query',
            field=models.TextField(default='', help_text='The query string to run (Cypher, SQL, API, etc.).'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dynamicpage',
            name='test_context',
            field=models.JSONField(blank=True, help_text='Optional JSON context for testing', null=True),
        ),
    ]
