# Generated by Django 4.2.23 on 2025-12-28 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vault', '0002_alter_bucket_name'),
        ('webfront', '0007_remove_dynamicpage_cypher_query_dynamicpage_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileWorkflow',
            fields=[
                ('code', models.TextField(help_text='Restricted Python code snippet')),
                ('test_context', models.JSONField(blank=True, help_text='Optional JSON context for testing', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bucket', models.ForeignKey(help_text='Workflow is restricted to files inside this bucket.', on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='vault.bucket')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_workflows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier for this gateway.', max_length=200, unique=True)),
                ('workflow', models.ForeignKey(help_text='The workflow this gateway triggers.', on_delete=django.db.models.deletion.CASCADE, related_name='gateways', to='webfront.fileworkflow')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
