# Generated by Django 4.2.23 on 2025-12-30 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mandragora', '0003_lambdalayer_use_io_lambdalayer_use_json_and_more'),
        ('webfront', '0008_fileworkflow_gateway'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cypherquery',
            name='code',
        ),
        migrations.RemoveField(
            model_name='cypherquery',
            name='test_context',
        ),
        migrations.RemoveField(
            model_name='dynamicpage',
            name='code',
        ),
        migrations.RemoveField(
            model_name='dynamicpage',
            name='query',
        ),
        migrations.RemoveField(
            model_name='dynamicpage',
            name='test_context',
        ),
        migrations.RemoveField(
            model_name='fileworkflow',
            name='code',
        ),
        migrations.RemoveField(
            model_name='fileworkflow',
            name='test_context',
        ),
        migrations.AddField(
            model_name='cypherquery',
            name='lambda_node',
            field=models.ForeignKey(blank=True, help_text='Optional LambdaNode that post-processes query results.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cypher_queries', to='mandragora.lambdanode'),
        ),
        migrations.AddField(
            model_name='dynamicpage',
            name='lambda_node',
            field=models.ForeignKey(blank=True, help_text='LambdaNode that powers this page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dynamic_pages', to='mandragora.lambdanode'),
        ),
        migrations.AddField(
            model_name='fileworkflow',
            name='lambda_node',
            field=models.ForeignKey(blank=True, help_text='LambdaNode that executes this workflow.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_workflows', to='mandragora.lambdanode'),
        ),
        migrations.AddField(
            model_name='fileworkflow',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier for this workflow.', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='cypherquery',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='cypherquery',
            name='query',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Gateway',
        ),
    ]
