# Generated by Django 4.2.23 on 2025-12-30 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_alter_bucket_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mandragora', '0003_lambdalayer_use_io_lambdalayer_use_json_and_more'),
        ('webfront', '0009_remove_cypherquery_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cypherquery',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dynamicpage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fileworkflow',
            options={},
        ),
        migrations.RemoveField(
            model_name='cypherquery',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cypherquery',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='cypherquery',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='cypherquery',
            name='lambda_node',
        ),
        migrations.RemoveField(
            model_name='fileworkflow',
            name='owner',
        ),
        migrations.AddField(
            model_name='dynamicpage',
            name='cypher_query',
            field=models.ForeignKey(blank=True, help_text='Optional Cypher query powering this page.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='webfront.cypherquery'),
        ),
        migrations.AddField(
            model_name='dynamicpage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cypherquery',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cypherquery',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dynamicpage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dynamicpage',
            name='lambda_node',
            field=models.ForeignKey(blank=True, help_text='Optional lambda that renders widgets for this page.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mandragora.lambdanode'),
        ),
        migrations.AlterField(
            model_name='dynamicpage',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dynamicpage',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dynamicpage',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='fileworkflow',
            name='bucket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.bucket'),
        ),
        migrations.AlterField(
            model_name='fileworkflow',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fileworkflow',
            name='lambda_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mandragora.lambdanode'),
        ),
        migrations.AlterField(
            model_name='fileworkflow',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fileworkflow',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.CreateModel(
            name='GraphWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cypher_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graph_workflows', to='webfront.cypherquery')),
                ('lambda_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mandragora.lambdanode')),
            ],
        ),
    ]
