# Generated by Django 4.2.23 on 2025-12-30 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0010_alter_cypherquery_options_alter_dynamicpage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicpage',
            name='owner',
        ),
    ]
