# Generated by Django 4.2.23 on 2025-12-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0011_remove_dynamicpage_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicpage',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
