# Generated by Django 4.2.23 on 2026-01-11 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0013_widget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='type',
            field=models.CharField(choices=[('table', 'Table'), ('chart', 'Chart'), ('calendar', 'Calendar'), ('map', 'Map')], max_length=50),
        ),
    ]
