# Generated by Django 4.2.23 on 2026-01-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0014_alter_widget_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='type',
            field=models.CharField(choices=[('table', 'Table'), ('chart', 'Chart'), ('calendar', 'Calendar'), ('map', 'Map'), ('form', 'Form')], max_length=50),
        ),
    ]
