# Generated by Django 4.2.23 on 2026-05-25 16:30

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityMagistrateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_fine_pct', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text="Maximum infraction fine a magistrate may levy, expressed as a percentage of the target's assessed holdings (0–100).", max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
            ],
            options={
                'verbose_name': 'Community magistrate settings',
                'verbose_name_plural': 'Community magistrate settings',
            },
        ),
        migrations.CreateModel(
            name='Magistrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('impeached', 'Impeached'), ('term_ended', 'Term Ended')], db_index=True, default='active', max_length=20)),
                ('term_start', models.DateField()),
                ('term_end', models.DateField(blank=True, null=True)),
                ('elected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Magistrate',
                'verbose_name_plural': 'Magistrates',
                'ordering': ['-elected_at'],
            },
        ),
        migrations.CreateModel(
            name='MagistrateDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_type', models.CharField(choices=[('mobilization_call', 'Mobilization Call'), ('emergency_declare', 'Emergency Declaration'), ('tribunal_order', 'Tribunal Order'), ('trade_order', 'Trade Order'), ('finance_directive', 'Finance Directive'), ('public_order_directive', 'Public Order Directive'), ('legislation_fast_track', 'Legislation Fast-Track'), ('trade_reversal', 'Trade Reversal Order'), ('merchandise_fine', 'Merchandise Quality Fine'), ('education_directive', 'Education Directive'), ('relations_directive', 'Relations Directive'), ('logistics_order', 'Logistics Order'), ('interior_directive', 'Interior Directive'), ('productivity_directive', 'Productivity Directive'), ('infraction_fine', 'Infraction Fine'), ('general', 'General Directive')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('reviewed', 'Reviewed by Assembly')], db_index=True, default='active', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Magistrate decision',
                'verbose_name_plural': 'Magistrate decisions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MagistrateFine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority_domain', models.CharField(blank=True, help_text="The magistrate oversight domain under which this fine was issued (e.g. 'Finance', 'Trade').", max_length=60)),
                ('fine_pct', models.DecimalField(decimal_places=2, help_text='Percentage of assessed holdings applied as a fine.', max_digits=5)),
                ('basis_amount_display', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Assessed holding balance at the time of the fine.', max_digits=24)),
                ('fine_amount_display', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Actual fine amount (fine_pct % of basis).', max_digits=24)),
                ('infraction', models.TextField(help_text='Description of the infraction.')),
                ('status', models.CharField(choices=[('issued', 'Issued — Obligation Pending'), ('obligation_created', 'Obligation Created'), ('pending_collection', 'Pending — No Collection Account'), ('contested', 'Contested at Tribunal'), ('overturned', 'Overturned')], db_index=True, default='issued', max_length=30)),
                ('contested_at', models.DateTimeField(blank=True, null=True)),
                ('overturned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Magistrate fine',
                'verbose_name_plural': 'Magistrate fines',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MagistrateReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('reporting_period_start', models.DateField(blank=True, null=True)),
                ('reporting_period_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('acknowledged', 'Acknowledged')], db_index=True, default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Magistrate report',
                'verbose_name_plural': 'Magistrate reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MagistrateRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='fa-solid fa-scroll', max_length=100)),
                ('overseeing_mobilization', models.BooleanField(default=False, help_text='Holder may act on emergency declarations without full assembly vote.')),
                ('overseeing_tribunal', models.BooleanField(default=False, help_text='Holder oversees tribunal proceedings.')),
                ('overseeing_trade', models.BooleanField(default=False, help_text='Holder oversees trade and commerce.')),
                ('overseeing_finance', models.BooleanField(default=False, help_text='Holder oversees community finances and taxation.')),
                ('overseeing_public_order', models.BooleanField(default=False, help_text='Holder oversees public order and safety.')),
                ('overseeing_legislation', models.BooleanField(default=False, help_text='Holder may propose and fast-track legislation.')),
                ('overseeing_merchandise', models.BooleanField(default=False, help_text='Holder may inspect merchandise quality and impose fines. Fines may be contested before the tribunal.')),
                ('overseeing_education', models.BooleanField(default=False, help_text='Holder oversees community education, academies, and knowledge standards.')),
                ('overseeing_relations', models.BooleanField(default=False, help_text='Holder oversees inter-community diplomatic relations, treaties, and external liaisons.')),
                ('overseeing_logistics', models.BooleanField(default=False, help_text='Holder oversees logistics, supply chains, and transport operations.')),
                ('overseeing_interior', models.BooleanField(default=False, help_text='Holder oversees internal travel, location access, and movement of persons within community territory.')),
                ('overseeing_productivity', models.BooleanField(default=False, help_text='Holder oversees community productivity, work assignments, and labour standards.')),
                ('can_set_fines', models.BooleanField(default=False, help_text='Holder may levy infraction fines on community members within their oversight domains. Bounded by the community max-fine-pct setting.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Magistrate role',
                'verbose_name_plural': 'Magistrate roles',
                'ordering': ['order', 'name'],
            },
        ),
    ]
