# Generated by Django 5.2.17 on 2026-10-06 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0002_initial'),
        ('socialhub', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(blank=True, default='', max_length=64, verbose_name='company ID number')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_record', to='socialhub.community')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'company record',
                'verbose_name_plural': 'company records',
            },
        ),
        migrations.CreateModel(
            name='ShareHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveBigIntegerField(default=0, verbose_name='shares')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_holdings', to='socialhub.community')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_holdings', to='people.person')),
            ],
            options={
                'verbose_name': 'shareholding',
                'verbose_name_plural': 'shareholdings',
                'ordering': ['-quantity', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('community', 'person'), name='companies_one_holding_per_person'), models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='companies_holding_not_negative')],
            },
        ),
    ]
