# Generated by Django 4.2.23 on 2026-05-22 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0011_tokenization_default_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('instrument_type', models.CharField(choices=[('escrow', 'Escrow'), ('forward', 'Forward'), ('future', 'Future'), ('revenue_share', 'Revenue Share'), ('timelock', 'Timelock'), ('vesting', 'Vesting'), ('staking', 'Staking')], max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('settled', 'Settled'), ('defaulted', 'Defaulted'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('terms', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_account', models.ForeignKey(blank=True, help_text='Contract/vault/margin account used by this instrument, if applicable.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_instruments', to='assets.ledgeraccount')),
                ('issuer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_instruments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FutureContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_count', models.PositiveIntegerField(default=1)),
                ('entry_price_base_units', models.BigIntegerField()),
                ('settlement_price_base_units', models.BigIntegerField(blank=True, null=True)),
                ('settlement_at', models.DateTimeField()),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='future_contract', to='instruments.financialinstrument')),
                ('long_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='future_long_positions', to='assets.ledgeraccount')),
            ],
            options={
                'ordering': ['-settlement_at'],
            },
        ),
        migrations.CreateModel(
            name='RevenueShareContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_from', models.DateTimeField()),
                ('active_until', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='revenue_share_contract', to='instruments.financialinstrument')),
                ('revenue_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revenue_share_sources', to='assets.ledgeraccount')),
                ('revenue_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revenue_share_contracts', to='assets.asset')),
            ],
        ),
        migrations.CreateModel(
            name='VestingContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount_base_units', models.BigIntegerField()),
                ('released_amount_base_units', models.BigIntegerField(default=0)),
                ('start_at', models.DateTimeField()),
                ('cliff_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField()),
                ('release_frequency', models.CharField(default='monthly', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vesting_contracts', to='assets.asset')),
                ('beneficiary_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vesting_grants_received', to='assets.ledgeraccount')),
                ('grantor_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vesting_grants_made', to='assets.ledgeraccount')),
                ('instrument', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vesting_contract', to='instruments.financialinstrument')),
            ],
        ),
        migrations.CreateModel(
            name='TimelockContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_base_units', models.BigIntegerField()),
                ('unlock_at', models.DateTimeField()),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timelock_contracts', to='assets.asset')),
                ('beneficiary_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timelock_benefits', to='assets.ledgeraccount')),
                ('instrument', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='timelock_contract', to='instruments.financialinstrument')),
                ('owner_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timelocks', to='assets.ledgeraccount')),
            ],
        ),
        migrations.CreateModel(
            name='StakingPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staked_amount_base_units', models.BigIntegerField()),
                ('reward_rate_bps', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('unstaked_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='staking_position', to='instruments.financialinstrument')),
                ('reward_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staking_reward_positions', to='assets.asset')),
                ('staked_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staking_positions', to='assets.asset')),
                ('staker_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staking_positions', to='assets.ledgeraccount')),
                ('staking_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staking_pool_positions', to='assets.ledgeraccount')),
            ],
        ),
        migrations.CreateModel(
            name='FutureMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('contract_size_base_units', models.BigIntegerField()),
                ('settlement_type', models.CharField(choices=[('cash', 'Cash Settlement'), ('physical', 'Physical Delivery')], default='cash', max_length=20)),
                ('initial_margin_bps', models.PositiveIntegerField(default=1000)),
                ('maintenance_margin_bps', models.PositiveIntegerField(default=750)),
                ('active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('settlement_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='future_markets_as_settlement_asset', to='assets.asset')),
                ('underlying_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='future_markets_as_underlying', to='assets.asset')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FutureMarginPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_margin_base_units', models.BigIntegerField()),
                ('deposited_margin_base_units', models.BigIntegerField(default=0)),
                ('margin_call_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='future_margin_positions', to='assets.ledgeraccount')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='future_margin_positions', to='assets.asset')),
                ('future', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='margin_positions', to='instruments.futurecontract')),
                ('margin_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='future_margin_pool_positions', to='assets.ledgeraccount')),
            ],
            options={
                'ordering': ['future', 'account'],
            },
        ),
        migrations.AddField(
            model_name='futurecontract',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='instruments.futuremarket'),
        ),
        migrations.AddField(
            model_name='futurecontract',
            name='short_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='future_short_positions', to='assets.ledgeraccount'),
        ),
        migrations.CreateModel(
            name='ForwardContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_base_units', models.BigIntegerField()),
                ('payment_amount_base_units', models.BigIntegerField()),
                ('settlement_type', models.CharField(choices=[('physical', 'Physical Delivery'), ('cash', 'Cash Settlement')], default='physical', max_length=20)),
                ('settlement_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forward_contracts_as_buyer', to='assets.ledgeraccount')),
                ('instrument', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='forward_contract', to='instruments.financialinstrument')),
                ('payment_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forward_contracts_as_payment', to='assets.asset')),
                ('seller_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forward_contracts_as_seller', to='assets.ledgeraccount')),
                ('underlying_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forward_contracts_as_underlying', to='assets.asset')),
            ],
            options={
                'ordering': ['-settlement_at'],
            },
        ),
        migrations.CreateModel(
            name='EscrowContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_base_units', models.BigIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('funded', 'Funded'), ('released', 'Released'), ('refunded', 'Refunded'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('order_reference', models.CharField(blank=True, max_length=255)),
                ('release_condition', models.JSONField(blank=True, default=dict)),
                ('funded_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('disputed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escrow_contracts', to='assets.asset')),
                ('buyer_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escrows_as_buyer', to='assets.ledgeraccount')),
                ('escrow_account', models.ForeignKey(help_text='Contract account holding the escrowed asset.', on_delete=django.db.models.deletion.PROTECT, related_name='escrow_contracts', to='assets.ledgeraccount')),
                ('instrument', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='escrow_contract', to='instruments.financialinstrument')),
                ('seller_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escrows_as_seller', to='assets.ledgeraccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RevenueShareRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_bps', models.PositiveIntegerField(help_text='10000 bps = 100%')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revenue_share_entitlements', to='assets.ledgeraccount')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipients', to='instruments.revenuesharecontract')),
            ],
            options={
                'unique_together': {('contract', 'account')},
            },
        ),
        migrations.CreateModel(
            name='InstrumentObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('underlying_delivery', 'Underlying Delivery'), ('payment', 'Payment'), ('margin', 'Margin'), ('settlement', 'Settlement'), ('premium', 'Premium'), ('collateral_return', 'Collateral Return'), ('payout', 'Payout'), ('reward', 'Reward'), ('escrow_release', 'Escrow Release'), ('escrow_refund', 'Escrow Refund')], max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligation_links', to='instruments.financialinstrument')),
                ('obligation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='instrument_link', to='assets.obligation')),
            ],
            options={
                'ordering': ['instrument', 'role'],
                'indexes': [models.Index(fields=['role'], name='instruments_role_9bd228_idx')],
                'unique_together': {('instrument', 'role')},
            },
        ),
        migrations.CreateModel(
            name='InstrumentExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='instruments.financialinstrument')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instrument_executions', to='assets.ledgertransaction')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['instrument', 'action'], name='instruments_instrum_506fce_idx'), models.Index(fields=['status', 'created_at'], name='instruments_status_53080c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='futuremarket',
            index=models.Index(fields=['code'], name='instruments_code_2a2673_idx'),
        ),
        migrations.AddIndex(
            model_name='futuremarket',
            index=models.Index(fields=['underlying_asset', 'active'], name='instruments_underly_6215c2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='futuremarginposition',
            unique_together={('future', 'account')},
        ),
        migrations.AddIndex(
            model_name='futurecontract',
            index=models.Index(fields=['market', 'settlement_at'], name='instruments_market__791e19_idx'),
        ),
        migrations.AddIndex(
            model_name='futurecontract',
            index=models.Index(fields=['long_account', 'settlement_at'], name='instruments_long_ac_b17dec_idx'),
        ),
        migrations.AddIndex(
            model_name='futurecontract',
            index=models.Index(fields=['short_account', 'settlement_at'], name='instruments_short_a_4b106b_idx'),
        ),
        migrations.AddIndex(
            model_name='forwardcontract',
            index=models.Index(fields=['buyer_account', 'settlement_at'], name='instruments_buyer_a_ccdaac_idx'),
        ),
        migrations.AddIndex(
            model_name='forwardcontract',
            index=models.Index(fields=['seller_account', 'settlement_at'], name='instruments_seller__6c9d01_idx'),
        ),
        migrations.AddIndex(
            model_name='forwardcontract',
            index=models.Index(fields=['underlying_asset', 'settlement_at'], name='instruments_underly_fdc39b_idx'),
        ),
        migrations.AddIndex(
            model_name='financialinstrument',
            index=models.Index(fields=['reference'], name='instruments_referen_2d8dac_idx'),
        ),
        migrations.AddIndex(
            model_name='financialinstrument',
            index=models.Index(fields=['instrument_type', 'status'], name='instruments_instrum_6bf0d7_idx'),
        ),
        migrations.AddIndex(
            model_name='financialinstrument',
            index=models.Index(fields=['issuer', 'status'], name='instruments_issuer__a6944b_idx'),
        ),
        migrations.AddIndex(
            model_name='financialinstrument',
            index=models.Index(fields=['created_at'], name='instruments_created_ae867b_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowcontract',
            index=models.Index(fields=['buyer_account', 'status'], name='instruments_buyer_a_2b1443_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowcontract',
            index=models.Index(fields=['seller_account', 'status'], name='instruments_seller__9f893a_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowcontract',
            index=models.Index(fields=['asset', 'status'], name='instruments_asset_i_327074_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowcontract',
            index=models.Index(fields=['order_reference'], name='instruments_order_r_459273_idx'),
        ),
    ]
