# Generated by Django 4.2.23 on 2026-05-22 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_tokenization_default_state'),
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_type', models.CharField(choices=[('call', 'Call'), ('put', 'Put')], max_length=10)),
                ('style', models.CharField(choices=[('european', 'European'), ('american', 'American')], default='european', max_length=10)),
                ('quantity_base_units', models.BigIntegerField()),
                ('strike_price_base_units', models.BigIntegerField(help_text='Strike price per unit of underlying, in payment asset base units.')),
                ('premium_base_units', models.BigIntegerField(default=0, help_text='Premium paid by buyer to writer for the option.')),
                ('settlement_type', models.CharField(choices=[('physical', 'Physical Delivery'), ('cash', 'Cash Settlement')], default='cash', max_length=20)),
                ('expiry_at', models.DateTimeField()),
                ('exercised_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer_account', models.ForeignKey(help_text='Holds the right to exercise.', on_delete=django.db.models.deletion.PROTECT, related_name='option_positions_as_buyer', to='assets.ledgeraccount')),
            ],
            options={
                'ordering': ['-expiry_at'],
            },
        ),
        migrations.AlterField(
            model_name='financialinstrument',
            name='instrument_type',
            field=models.CharField(choices=[('escrow', 'Escrow'), ('forward', 'Forward'), ('future', 'Future'), ('option', 'Option'), ('revenue_share', 'Revenue Share'), ('vesting', 'Vesting'), ('staking', 'Staking')], max_length=40),
        ),
        migrations.DeleteModel(
            name='TimelockContract',
        ),
        migrations.AddField(
            model_name='optioncontract',
            name='instrument',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='option_contract', to='instruments.financialinstrument'),
        ),
        migrations.AddField(
            model_name='optioncontract',
            name='payment_asset',
            field=models.ForeignKey(help_text='Asset used to pay the strike price.', on_delete=django.db.models.deletion.PROTECT, related_name='option_contracts_as_payment', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='optioncontract',
            name='underlying_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='option_contracts_as_underlying', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='optioncontract',
            name='writer_account',
            field=models.ForeignKey(help_text='Has the obligation if exercised.', on_delete=django.db.models.deletion.PROTECT, related_name='option_positions_as_writer', to='assets.ledgeraccount'),
        ),
        migrations.AddIndex(
            model_name='optioncontract',
            index=models.Index(fields=['buyer_account', 'expiry_at'], name='instruments_buyer_a_d7ec8b_idx'),
        ),
        migrations.AddIndex(
            model_name='optioncontract',
            index=models.Index(fields=['writer_account', 'expiry_at'], name='instruments_writer__258818_idx'),
        ),
        migrations.AddIndex(
            model_name='optioncontract',
            index=models.Index(fields=['underlying_asset', 'option_type', 'expiry_at'], name='instruments_underly_f2e661_idx'),
        ),
    ]
