# Generated by Django 4.2.23 on 2026-05-31 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_remove_subscriptioncontract'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaseContract',
        ),
    ]
