# Generated by Django 4.2.23 on 2026-05-23 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_tokenization_default_state'),
        ('instruments', '0003_subscriptioncontract'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_mode', models.CharField(choices=[('fixed', 'Fixed'), ('metered', 'Metered'), ('mixed', 'Mixed')], default='fixed', max_length=20)),
                ('fixed_fee_base_units', models.BigIntegerField(default=0)),
                ('billing_period', models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('custom', 'Custom')], default='monthly', max_length=20)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('next_billing_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('defaulted', 'Defaulted')], default='draft', max_length=20)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaseMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('time', 'Time'), ('usage', 'Usage'), ('unit', 'Unit')], max_length=20)),
                ('unit', models.CharField(max_length=50)),
                ('step', models.DecimalField(decimal_places=6, default=1, max_digits=18)),
                ('allow_fractional_quantity', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AlterField(
            model_name='financialinstrument',
            name='instrument_type',
            field=models.CharField(choices=[('escrow', 'Escrow'), ('forward', 'Forward'), ('future', 'Future'), ('option', 'Option'), ('revenue_share', 'Revenue Share'), ('subscription', 'Subscription'), ('vesting', 'Vesting'), ('staking', 'Staking'), ('lease', 'Lease')], max_length=40),
        ),
        migrations.CreateModel(
            name='LeaseTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_step_base_units', models.BigIntegerField()),
                ('minimum_charge_base_units', models.BigIntegerField(default=0)),
                ('rounding_mode', models.CharField(choices=[('exact', 'Exact'), ('round_up_step', 'Round Up to Step'), ('round_down_step', 'Round Down to Step')], default='round_up_step', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tariffs', to='instruments.leasecontract')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tariffs', to='instruments.leasemetric')),
            ],
            options={
                'ordering': ['lease', 'metric'],
                'unique_together': {('lease', 'metric')},
            },
        ),
        migrations.AddField(
            model_name='leasecontract',
            name='instrument',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='lease_contract', to='instruments.financialinstrument'),
        ),
        migrations.AddField(
            model_name='leasecontract',
            name='leased_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases_as_subject', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='leasecontract',
            name='lessee_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases_as_lessee', to='assets.ledgeraccount'),
        ),
        migrations.AddField(
            model_name='leasecontract',
            name='lessor_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases_as_lessor', to='assets.ledgeraccount'),
        ),
        migrations.AddField(
            model_name='leasecontract',
            name='payment_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases_as_payment', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='leasecontract',
            name='revenue_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases_as_revenue', to='assets.ledgeraccount'),
        ),
        migrations.CreateModel(
            name='LeaseCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('billed_quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('billed_steps', models.DecimalField(decimal_places=6, max_digits=18)),
                ('amount_base_units', models.BigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('charged', 'Charged'), ('waived', 'Waived'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('source_type', models.CharField(blank=True, max_length=100)),
                ('source_id', models.CharField(blank=True, max_length=255)),
                ('charged_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='instruments.leasecontract')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='instruments.leasemetric')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='instruments.leasetariff')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lease_charges', to='assets.ledgertransaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='leasecontract',
            index=models.Index(fields=['status', 'next_billing_at'], name='instruments_status_9a764b_idx'),
        ),
        migrations.AddIndex(
            model_name='leasecontract',
            index=models.Index(fields=['lessor_account', 'status'], name='instruments_lessor__ed1145_idx'),
        ),
        migrations.AddIndex(
            model_name='leasecontract',
            index=models.Index(fields=['lessee_account', 'status'], name='instruments_lessee__33d59b_idx'),
        ),
        migrations.AddIndex(
            model_name='leasecharge',
            index=models.Index(fields=['lease', 'status'], name='instruments_lease_i_bc83b6_idx'),
        ),
        migrations.AddIndex(
            model_name='leasecharge',
            index=models.Index(fields=['status', 'created_at'], name='instruments_status_1e954a_idx'),
        ),
    ]
