# Generated by Django 4.2.23 on 2026-05-24 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_tokenization_default_state'),
        ('instruments', '0004_lease_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialinstrument',
            name='instrument_type',
            field=models.CharField(choices=[('escrow', 'Escrow'), ('forward', 'Forward'), ('future', 'Future'), ('option', 'Option'), ('revenue_share', 'Revenue Share'), ('subscription', 'Subscription'), ('vesting', 'Vesting'), ('staking', 'Staking'), ('lease', 'Lease'), ('amortization', 'Amortization')], max_length=40),
        ),
        migrations.CreateModel(
            name='AmortizationContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_amount_base_units', models.BigIntegerField()),
                ('amortized_amount_base_units', models.BigIntegerField(default=0)),
                ('basis', models.CharField(choices=[('time', 'Time'), ('usage', 'Usage'), ('schedule', 'Schedule'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('exhausted', 'Exhausted'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amortization_contracts', to='assets.asset')),
                ('destination_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amortization_destinations', to='assets.ledgeraccount')),
                ('instrument', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='amortization_contract', to='instruments.financialinstrument')),
                ('source_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amortization_sources', to='assets.ledgeraccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AmortizationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_base_units', models.BigIntegerField()),
                ('source_type', models.CharField(blank=True, max_length=100)),
                ('source_id', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='instruments.amortizationcontract')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='amortization_entries', to='assets.ledgertransaction')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['contract', 'created_at'], name='instruments_contrac_b8c6fe_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='amortizationcontract',
            index=models.Index(fields=['status', 'created_at'], name='instruments_status_3ecf67_idx'),
        ),
        migrations.AddIndex(
            model_name='amortizationcontract',
            index=models.Index(fields=['source_account', 'status'], name='instruments_source__dcef6a_idx'),
        ),
        migrations.AddIndex(
            model_name='amortizationcontract',
            index=models.Index(fields=['destination_account', 'status'], name='instruments_destina_047a84_idx'),
        ),
        migrations.AddIndex(
            model_name='amortizationcontract',
            index=models.Index(fields=['asset', 'status'], name='instruments_asset_i_de9de8_idx'),
        ),
    ]
