# Generated by Django 4.2.23 on 2026-05-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0005_alter_financialinstrument_instrument_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amortizationcontract',
            name='basis',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
