# Generated by Django 4.2.23 on 2026-05-24 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_rename_contracttemplate_to_contract'),
        ('instruments', '0006_alter_amortizationcontract_basis'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leasetariff',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='leasetariff',
            name='lease',
        ),
        migrations.RemoveField(
            model_name='leasetariff',
            name='metric',
        ),
        migrations.RemoveField(
            model_name='leasecontract',
            name='billing_mode',
        ),
        migrations.AddField(
            model_name='financialinstrument',
            name='contract',
            field=models.OneToOneField(blank=True, help_text="Lapis smart-contract generated from this instrument's parameters.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_instrument', to='assets.contract'),
        ),
        migrations.DeleteModel(
            name='LeaseCharge',
        ),
        migrations.DeleteModel(
            name='LeaseMetric',
        ),
        migrations.DeleteModel(
            name='LeaseTariff',
        ),
    ]
