# Generated by Django 4.2.23 on 2026-06-04 19:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('display_name', models.CharField(max_length=150)),
                ('bio', models.TextField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('joined_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('is_federal_agent', models.BooleanField(default=False, help_text='Federal agents are exempt from community poll taxes.')),
                ('digital_signature', models.TextField(blank=True, help_text="Base64-encoded PNG of the person's handwritten signature.")),
                ('preferred_language', models.CharField(blank=True, choices=[('en', 'English'), ('pl', 'Polski')], default='en', max_length=10)),
                ('address', models.ForeignKey(blank=True, help_text='Optional address for this community member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='locations.address')),
            ],
            options={
                'db_table': 'socialhub_person',
            },
        ),
    ]
