# Generated by Django 4.2.23 on 2026-10-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='show_email',
            field=models.BooleanField(default=False, help_text="Whether other members see this person's e-mail address. Off by default."),
        ),
        migrations.AddField(
            model_name='person',
            name='show_phone',
            field=models.BooleanField(default=False, help_text="Whether other members see this person's phone number. Off by default."),
        ),
        migrations.AddField(
            model_name='person',
            name='show_address',
            field=models.BooleanField(default=False, help_text="Whether other members see this person's postal address. Off by default."),
        ),
    ]
