# Generated by Django 4.2.23 on 2026-08-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_deprecate_is_federal_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='location_sharing',
            field=models.CharField(choices=[('off', 'Not shown to anyone'), ('approximate', 'Approximate area only'), ('exact', 'Exact address')], default='off', help_text='Whether other members may see where this person lives, and how precisely. Off by default.', max_length=12),
        ),
    ]
