# Generated by Django 4.2.23 on 2026-09-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialhub', '0014_clearances'),
        ('people', '0005_location_sharing'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='clearances',
            field=models.ManyToManyField(blank=True, related_name='members', to='socialhub.clearance'),
        ),
    ]
