# Generated by Django 4.2.23 on 2026-09-30 21:26

from django.db import migrations, models
import toto.people.models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_clearances'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='timezone',
            field=models.CharField(blank=True, default='', help_text='IANA time zone name, e.g. Europe/Warsaw. Blank: the platform default.', max_length=64, validators=[toto.people.models.validate_time_zone]),
        ),
    ]
