# Generated by Django 4.2.23 on 2026-05-31 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palimpsest', '0003_rename_verbose_names_to_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Private pages are only visible to logged-in users.'),
        ),
    ]
