# Generated by Django 4.2.23 on 2026-08-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileservices', '0002_fileservicequotapolicy_fileserviceusageevent_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fileservicequotapolicy',
            name='fileservices_fileservicequotapolicy_one_default',
        ),
        migrations.RemoveConstraint(
            model_name='fileservicequotapolicy',
            name='fileservices_fileservicequotapolicy_one_per_user',
        ),
        migrations.RemoveField(
            model_name='fileservicequotapolicy',
            name='user',
        ),
        migrations.AddConstraint(
            model_name='fileservicequotapolicy',
            constraint=models.UniqueConstraint(fields=('metric_code',), name='fileservices_fileservicequotapolicy_one_per_metric'),
        ),
    ]
