# Generated by Django 4.2.23 on 2026-10-01 05:49

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialhub', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.PositiveSmallIntegerField(default=0, help_text='0–100. Taken off the billed quantity of ANY plan, for members of this community. Across several communities the LARGEST wins.')),
            ],
            options={
                'verbose_name': 'community discount',
                'verbose_name_plural': 'community discounts',
                'ordering': ['community__name'],
            },
        ),
        migrations.CreateModel(
            name='CommunityPlanOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_key', models.SlugField(help_text='A plan_key from plans.yaml. Not a foreign key: plans are not rows.', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'community plan offer',
                'verbose_name_plural': 'community plan offers',
                'ordering': ['plan_key', 'community__name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_key', models.SlugField(max_length=64)),
                ('state', models.CharField(choices=[('active', 'Active'), ('arrears', 'In arrears'), ('lapsed', 'Lapsed'), ('cancelled', 'Cancelled')], default='active', max_length=12)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('anchor_date', models.DateField()),
                ('arrears_since', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('lapse_reason', models.CharField(blank=True, max_length=20)),
                ('forced', models.BooleanField(default=False)),
                ('for_admins', models.BooleanField(default=False, editable=False, help_text='Set from the plan: only Django superusers may hold a plan for administrators.', verbose_name='for admins')),
                ('changed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_label', models.CharField(max_length=10)),
                ('plan_key', models.SlugField(blank=True, max_length=64)),
                ('plan_name', models.CharField(blank=True, max_length=120)),
                ('units', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('discount_percent', models.PositiveSmallIntegerField(default=0)),
                ('discount_source', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('due', 'Due'), ('paid', 'Paid'), ('failed', 'Could not be paid'), ('waived', 'Waived')], default='due', max_length=10)),
                ('detail', models.CharField(blank=True, help_text='Why it failed, in the words the user was shown.', max_length=300)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'subscription charge',
                'verbose_name_plural': 'subscription charges',
                'ordering': ['-period_label'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionQuotaPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('metric_code', models.CharField(db_index=True, max_length=100)),
                ('limit', models.DecimalField(decimal_places=10, max_digits=30)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime')], default='daily', max_length=20)),
                ('mode', models.CharField(choices=[('track', 'Track only'), ('warn', 'Warn'), ('block', 'Block')], default='block', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription quota policy',
                'verbose_name_plural': 'Subscription quota policies',
                'ordering': ['metric_code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionUsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_code', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=30)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('source_type', models.CharField(blank=True, max_length=100)),
                ('source_id', models.CharField(blank=True, max_length=255)),
                ('source_label', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('recorded', 'Recorded'), ('voided', 'Voided')], default='recorded', max_length=20)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription usage event',
                'verbose_name_plural': 'Subscription usage events',
                'ordering': ['-occurred_at'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='subscriptionquotapolicy',
            constraint=models.UniqueConstraint(fields=('metric_code',), name='subscriptions_subscriptionquotapolicy_one_per_metric'),
        ),
        migrations.AddField(
            model_name='subscriptioncharge',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='subscriptions.subscription'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communityplanoffer',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_offers', to='socialhub.community'),
        ),
        migrations.AddField(
            model_name='communitydiscount',
            name='community',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_discount', to='socialhub.community'),
        ),
        migrations.AddIndex(
            model_name='subscriptionusageevent',
            index=models.Index(fields=['metric_code', 'occurred_at'], name='subscriptionusageevent_mtime'),
        ),
        migrations.AddIndex(
            model_name='subscriptionusageevent',
            index=models.Index(fields=['user', 'metric_code'], name='subscriptionusageevent_umetric'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionusageevent',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('idempotency_key',), name='subscriptions_subscriptionusageevent_idem'),
        ),
        migrations.AddIndex(
            model_name='subscriptioncharge',
            index=models.Index(fields=['status'], name='subscriptio_status_53b329_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscriptioncharge',
            constraint=models.UniqueConstraint(fields=('subscription', 'period_label'), name='uniq_subscription_charge_period'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['state'], name='subscriptio_state_5faeee_idx'),
        ),
        migrations.AddIndex(
            model_name='communityplanoffer',
            index=models.Index(fields=['plan_key'], name='subscriptio_plan_ke_9d39dd_idx'),
        ),
        migrations.AddConstraint(
            model_name='communityplanoffer',
            constraint=models.UniqueConstraint(fields=('community', 'plan_key'), name='subscriptions_one_offer_per_community_plan'),
        ),
        migrations.AddConstraint(
            model_name='communitydiscount',
            constraint=models.CheckConstraint(check=models.Q(('percent__lte', 100)), name='discount_percent_at_most_100'),
        ),
    ]
