# Generated by Django 4.2.23 on 2026-08-15 09:26

from django.db import migrations, models
import django.db.models.deletion


def carry_over_best_percent(apps, schema_editor):
    """One row per community, carrying its LARGEST per-plan percent.

    Largest, not average or latest: every member of that community was
    already entitled to it on at least one plan, and a migration must never
    quietly raise somebody's bill. Zeroes are dropped — the new table is the
    set of communities that actually give something.
    """
    Old = apps.get_model("subscriptions", "CommunityPlanDiscount")
    New = apps.get_model("subscriptions", "CommunityDiscount")
    best = {}
    for community_id, percent in Old.objects.values_list("community_id", "percent"):
        best[community_id] = max(best.get(community_id, 0), percent or 0)
    New.objects.bulk_create([
        New(community_id=community_id, percent=percent)
        for community_id, percent in best.items() if percent > 0
    ])


def unmerge_is_impossible(apps, schema_editor):
    """Reverse leaves the old table empty rather than inventing per-plan rows.

    One number cannot be split back into the several it was collapsed from,
    and guessing would be worse than an empty table an operator can see.
    """
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('socialhub', '0009_community_statute_retire_constitution'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.PositiveSmallIntegerField(default=0, help_text='0–100. Taken off the billed quantity of ANY plan, for members of this community. Across several communities the LARGEST wins.')),
                ('community', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_discount', to='socialhub.community')),
            ],
            options={
                'verbose_name': 'community discount',
                'verbose_name_plural': 'community discounts',
                'ordering': ['community__name'],
            },
        ),
        migrations.RunPython(carry_over_best_percent, unmerge_is_impossible),
        migrations.DeleteModel(
            name='CommunityPlanDiscount',
        ),
        migrations.AddConstraint(
            model_name='communitydiscount',
            constraint=models.CheckConstraint(check=models.Q(('percent__lte', 100)), name='discount_percent_at_most_100'),
        ),
    ]
