"""A plan offer and a discount name a functional community only (2026-09-28).

`limit_choices_to` and nothing else: no table changes. A circle decides who
reads, and is offered no plan and gives no discount — the models refuse one
on save as well, and every resolver skips circles.
"""

# Generated by Django 4.2.23 on 2026-09-28 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialhub', '0014_community_is_circle'),
        ('subscriptions', '0003_subscription_for_admins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitydiscount',
            name='community',
            field=models.OneToOneField(limit_choices_to={'is_circle': False}, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_discount', to='socialhub.community'),
        ),
        migrations.AlterField(
            model_name='communityplanoffer',
            name='community',
            field=models.ForeignKey(limit_choices_to={'is_circle': False}, on_delete=django.db.models.deletion.CASCADE, related_name='plan_offers', to='socialhub.community'),
        ),
    ]
