"""Plans can be offered to particular communities.

A join table and nothing else, because the rule is about ABSENCE: a plan with
no rows here is public, which is every plan that exists when this migration
runs. Nothing is backfilled and nothing changes behaviour on the day it is
applied — restriction is something an operator switches on afterwards, never a
default that arrived with a schema change.

The unique constraint is plain rather than partial: both columns are NOT NULL,
so there is no NULL-duplicates hole of the kind
`forum_one_retention_policy_per_channel` had to work around.
"""

# Generated by Django 4.2.23 on 2026-08-29 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialhub', '0012_delete_station'),
        ('subscriptions', '0003_signed_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_audiences', to='socialhub.community')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiences', to='subscriptions.subscriptionplan')),
            ],
            options={
                'verbose_name': 'plan audience',
                'verbose_name_plural': 'plan audiences',
                'ordering': ['plan__order', 'community__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='planaudience',
            constraint=models.UniqueConstraint(fields=('plan', 'community'), name='subscriptions_one_audience_per_plan_community'),
        ),
    ]
