# Generated by Django 4.2.23 on 2026-05-20 04:03

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0010_move_asset_exchange_request_to_bourse'),
        ('people', '0002_initial'),
        ('locations', '0002_initial'),
        ('bazaar', '0009_remove_bountyboard_custodian_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reward_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('max_claims', models.PositiveIntegerField(default=1)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('bounty_type', models.CharField(choices=[('task', 'Task'), ('bug_fix', 'Bug Fix'), ('research', 'Research'), ('creative', 'Creative'), ('development', 'Development'), ('testing', 'Testing'), ('content', 'Content'), ('other', 'Other')], default='task', max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('claimed', 'Claimed'), ('submitted', 'Submitted'), ('reviewing', 'Reviewing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='draft', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'bounties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BountyClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('working', 'Working'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('paid', 'Paid')], default='pending', max_length=32)),
                ('proposal', models.TextField(blank=True)),
                ('internal_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('bounty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='detections.bounty')),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bounty_claims', to='people.person')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounty_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('public', models.BooleanField(default=True, help_text='Check if this event is publicly visible.')),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('detection_type', models.CharField(choices=[('incident', 'Incident'), ('observation', 'Observation'), ('anomaly', 'Anomaly'), ('hazard', 'Hazard'), ('other', 'Other')], default='incident', max_length=24)),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('handling', 'In Handling'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='locations.address')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='DetectionHandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_handles', to='people.person')),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handles', to='detections.detection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetectionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='detections.detectioncategory')),
            ],
            options={
                'verbose_name_plural': 'detection categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='detection',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='detections.detectioncategory'),
        ),
        migrations.AddField(
            model_name='detection',
            name='involved_persons',
            field=models.ManyToManyField(blank=True, related_name='involved_detections', to='people.person'),
        ),
        migrations.AddField(
            model_name='detection',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_detections', to='people.person'),
        ),
        migrations.AddField(
            model_name='detection',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='locations.route'),
        ),
        migrations.AddField(
            model_name='detection',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='locations.zone'),
        ),
        migrations.CreateModel(
            name='BountySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('revision_requested', 'Revision Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=32)),
                ('reviewer_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='detections.bountyclaim')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='BountyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('rating', models.PositiveSmallIntegerField()),
                ('body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bounty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='detections.bounty')),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='detections.bountyclaim')),
                ('hunter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_bounty_reviews', to='people.person')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_bounty_reviews', to='people.person')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BountyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('ledger_tx_reference', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('is_settled', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounty_payments', to='assets.asset')),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='detections.bountyclaim')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounty_payments', to='assets.currency')),
                ('ledger_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounty_payments', to='assets.ledgeraccount')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounty_payments_issued', to='people.person')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='BountyBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('description', models.TextField(blank=True)),
                ('currency', models.CharField(default='PLN', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custodian', models.ForeignKey(blank=True, help_text='Custodian who must approve each submission before reward is released.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounty_boards', to='bazaar.marketcustodian')),
                ('ledger_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounty_boards', to='assets.ledgeraccount')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bounty_boards', to='bazaar.shop')),
                ('territory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounty_boards', to='locations.territory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='bounty',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bounties', to='detections.bountyboard'),
        ),
        migrations.AddField(
            model_name='bounty',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounties', to='detections.detectioncategory'),
        ),
        migrations.AddField(
            model_name='bounty',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bounties', to='people.person'),
        ),
        migrations.AddField(
            model_name='bounty',
            name='handle',
            field=models.ForeignKey(blank=True, help_text='The detection handle this bounty resolves, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounties', to='detections.detectionhandle'),
        ),
        migrations.AddField(
            model_name='bounty',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounties', to='locations.address'),
        ),
        migrations.AddField(
            model_name='bounty',
            name='product',
            field=models.OneToOneField(blank=True, help_text='The regulated-service product this bounty represents in the bazaar marketplace.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounty', to='bazaar.product'),
        ),
        migrations.AddField(
            model_name='bounty',
            name='reward_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_rewards', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='bounty',
            name='reward_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_rewards', to='assets.currency'),
        ),
        migrations.AddField(
            model_name='bounty',
            name='reward_ledger_account',
            field=models.ForeignKey(blank=True, help_text='Escrow account holding the reward.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_rewards', to='assets.ledgeraccount'),
        ),
        migrations.AddField(
            model_name='bounty',
            name='territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounties', to='locations.territory'),
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['status', 'severity'], name='detections__status_2a8e8e_idx'),
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['detection_type'], name='detections__detecti_9e4a23_idx'),
        ),
        migrations.AddConstraint(
            model_name='bountyreview',
            constraint=models.CheckConstraint(check=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='detection_bounty_review_rating_1_to_5'),
        ),
        migrations.AlterUniqueTogether(
            name='bountyclaim',
            unique_together={('bounty', 'hunter')},
        ),
        migrations.AddIndex(
            model_name='bounty',
            index=models.Index(fields=['board', 'status', 'is_public'], name='detections__board_i_41d528_idx'),
        ),
        migrations.AddIndex(
            model_name='bounty',
            index=models.Index(fields=['bounty_type'], name='detections__bounty__67f99b_idx'),
        ),
        migrations.AddIndex(
            model_name='bounty',
            index=models.Index(fields=['deadline'], name='detections__deadlin_231806_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bounty',
            unique_together={('board', 'slug')},
        ),
    ]
