# Generated by Django 4.2.23 on 2026-10-01 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jsonform.models.fields
import toto.api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gervazy', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('provider', models.CharField(choices=[('generic', 'Generic'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('github', 'GitHub'), ('custom', 'Custom'), ('rule_based', 'Rule-based (no API key)')], default='generic', max_length=40)),
                ('base_url', models.URLField(blank=True, help_text='Base API URL, e.g. https://api.openai.com/v1/')),
                ('auth_type', models.CharField(choices=[('none', 'No authentication'), ('api_key_header', 'API key header'), ('bearer_token', 'Bearer token'), ('query_param', 'Query parameter'), ('hmac', 'HMAC signature'), ('signature', 'Asymmetric request signature'), ('custom', 'Custom')], default='bearer_token', max_length=40)),
                ('auth_config', django_jsonform.models.fields.JSONField(blank=True, default=dict, help_text='Non-secret auth config such as header name or timeout.')),
                ('extra', django_jsonform.models.fields.JSONField(blank=True, default=dict, help_text='Non-secret provider-specific configuration.', validators=[toto.api.models._reject_secret_like_json])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_secret', models.ForeignKey(blank=True, help_text='Encrypted API key/token stored in Gervazy.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_api_connectors', to='gervazy.encryptedsecret')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('signing_key', models.ForeignKey(blank=True, help_text='Encrypted private key for signed API requests.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_signing_keys', to='gervazy.encryptedprivatekey')),
            ],
            options={
                'verbose_name': 'API connector',
                'verbose_name_plural': 'API connectors',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
