# Generated by Django 4.2.23 on 2026-06-04 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gervazy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailservice',
            name='smtp_secret',
            field=models.ForeignKey(blank=True, help_text='Gervazy EncryptedSecret holding the SMTP password.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_services', to='gervazy.encryptedsecret'),
        ),
        migrations.AddField(
            model_name='connector',
            name='api_secret',
            field=models.ForeignKey(blank=True, help_text='Encrypted API key/token stored in Gervazy.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_api_connectors', to='gervazy.encryptedsecret'),
        ),
        migrations.AddField(
            model_name='connector',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='connector',
            name='signing_key',
            field=models.ForeignKey(blank=True, help_text='Encrypted private key for signed API requests.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_signing_keys', to='gervazy.encryptedprivatekey'),
        ),
    ]
