# Generated by Django 4.2.23 on 2026-05-25 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervention',
            name='actual_cost',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='cost_asset',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='cost_center',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='estimated_cost',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='reward_amount',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='reward_asset',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='reward_currency',
        ),
    ]
