# Generated by Django 4.2.23 on 2025-08-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='disclaimer',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
