# Generated by Django 4.2.23 on 2026-05-25 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_initial'),
        ('assembly', '0001_initial'),
        ('people', '0001_initial'),
        ('socialhub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='senateveto',
            name='senator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senate_vetoes', to='people.person'),
        ),
        migrations.AddField(
            model_name='polltaxpayment',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_tax_payments', to='people.person'),
        ),
        migrations.AddField(
            model_name='polltaxpayment',
            name='poll_tax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='assembly.polltax'),
        ),
        migrations.AddField(
            model_name='polltax',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_taxes', to='socialhub.community'),
        ),
        migrations.AddField(
            model_name='polltax',
            name='decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enacted_poll_taxes', to='assembly.assemblydecision'),
        ),
        migrations.AddField(
            model_name='polltax',
            name='payment_asset',
            field=models.ForeignKey(help_text='Asset in which the tax is collected.', on_delete=django.db.models.deletion.PROTECT, related_name='poll_taxes_payment', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='polltax',
            name='wealth_asset',
            field=models.ForeignKey(blank=True, help_text='Asset used to measure member wealth. Null = no wealth component.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='poll_taxes_wealth', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='communitytransactionfee',
            name='asset',
            field=models.ForeignKey(blank=True, help_text='Null = blanket fee for all assets in this community.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_transaction_fees', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='communitytransactionfee',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_fees', to='socialhub.community'),
        ),
        migrations.AddField(
            model_name='communitytransactionfee',
            name='decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enacted_fees', to='assembly.assemblydecision'),
        ),
        migrations.AddField(
            model_name='communitysenate',
            name='community',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='senate', to='socialhub.community'),
        ),
        migrations.AddField(
            model_name='communitysenate',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Senators. A senator is excluded from voting in the popular assembly.', related_name='senate_memberships', to='people.person'),
        ),
        migrations.AddField(
            model_name='communityrule',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='socialhub.community'),
        ),
        migrations.AddField(
            model_name='communityrule',
            name='decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enacted_rules', to='assembly.assemblydecision'),
        ),
        migrations.AddField(
            model_name='communityassemblyconfig',
            name='community',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_config', to='socialhub.community'),
        ),
        migrations.AddField(
            model_name='assemblyvote',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='assembly.assemblyproposal'),
        ),
        migrations.AddField(
            model_name='assemblyvote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_votes', to='people.person'),
        ),
        migrations.AddField(
            model_name='assemblyproposal',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_proposals', to='socialhub.community'),
        ),
        migrations.AddField(
            model_name='assemblyproposal',
            name='opened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assembly_proposals_opened', to='people.person'),
        ),
        migrations.AddField(
            model_name='assemblydecision',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assembly_decisions', to='socialhub.community'),
        ),
        migrations.AddField(
            model_name='assemblydecision',
            name='proposal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decision', to='assembly.assemblyproposal'),
        ),
        migrations.AddIndex(
            model_name='polltaxpayment',
            index=models.Index(fields=['poll_tax', 'person'], name='assembly_po_poll_ta_acdcd1_idx'),
        ),
        migrations.AddIndex(
            model_name='polltaxpayment',
            index=models.Index(fields=['person', 'period_label'], name='assembly_po_person__f78fce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='polltaxpayment',
            unique_together={('poll_tax', 'person', 'period_label')},
        ),
        migrations.AddIndex(
            model_name='polltax',
            index=models.Index(fields=['community', 'active'], name='assembly_po_communi_05de5e_idx'),
        ),
        migrations.AddIndex(
            model_name='communitytransactionfee',
            index=models.Index(fields=['community', 'active'], name='assembly_co_communi_9be9ee_idx'),
        ),
        migrations.AddIndex(
            model_name='communitytransactionfee',
            index=models.Index(fields=['asset'], name='assembly_co_asset_i_094a81_idx'),
        ),
        migrations.AddIndex(
            model_name='communityrule',
            index=models.Index(fields=['community', 'active'], name='assembly_co_communi_e455d4_idx'),
        ),
        migrations.AddIndex(
            model_name='assemblyvote',
            index=models.Index(fields=['proposal'], name='assembly_as_proposa_dff47c_idx'),
        ),
        migrations.AddIndex(
            model_name='assemblyvote',
            index=models.Index(fields=['voter'], name='assembly_as_voter_i_689439_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assemblyvote',
            unique_together={('proposal', 'voter')},
        ),
        migrations.AddIndex(
            model_name='assemblyproposal',
            index=models.Index(fields=['community', 'status'], name='assembly_as_communi_69ceb4_idx'),
        ),
        migrations.AddIndex(
            model_name='assemblyproposal',
            index=models.Index(fields=['proposal_type'], name='assembly_as_proposa_173b7a_idx'),
        ),
        migrations.AddIndex(
            model_name='assemblyproposal',
            index=models.Index(fields=['closes_at'], name='assembly_as_closes__56cb79_idx'),
        ),
        migrations.AddIndex(
            model_name='assemblydecision',
            index=models.Index(fields=['community', 'created_at'], name='assembly_as_communi_70b8dd_idx'),
        ),
        migrations.AddIndex(
            model_name='assemblydecision',
            index=models.Index(fields=['decision_type'], name='assembly_as_decisio_962a60_idx'),
        ),
    ]
