# Generated by Django 4.2.23 on 2026-05-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_person_preferred_language'),
        ('assembly', '0004_assemblyproposaltype_add_mobilization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitysenate',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Legacy explicit senators. Senators are now derived from community.senior_members.', related_name='senate_memberships', to='people.person'),
        ),
    ]
