# Generated by Django 4.2.23 on 2025-08-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=255, verbose_name='Common Name (CN)')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('auth_url', models.URLField(default='http://localhost:8000/.well-known/acme-challenge/')),
                ('cert_dir', models.CharField(default='/home/janek/certbot', max_length=512)),
                ('debug', models.BooleanField(default=False)),
                ('success', models.BooleanField(default=False)),
                ('cert_path', models.CharField(blank=True, max_length=512)),
                ('key_path', models.CharField(blank=True, max_length=512)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TLSCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=255, verbose_name='Common Name (CN)')),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('country_name', models.CharField(max_length=2)),
                ('state_or_province_name', models.CharField(max_length=100)),
                ('locality_name', models.CharField(max_length=100)),
                ('organization_name', models.CharField(max_length=255)),
                ('private_key', models.TextField(blank=True, null=True)),
                ('certificate', models.TextField(blank=True, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
