# Generated by Django 4.2.23 on 2025-10-04 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gervazy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyRing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('salt', models.BinaryField(help_text='Salt used for key derivation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyrings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
