# Generated by Django 4.2.23 on 2025-11-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gervazy', '0003_secretkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretkey',
            name='size',
            field=models.PositiveIntegerField(choices=[(64, '64 bytes (~86 chars)'), (128, '128 bytes (~172 chars)'), (256, '256 bytes (~344 chars)')], default=64, help_text='Entropy size used when generating the secret'),
        ),
    ]
