# Generated by Django 4.2.23 on 2025-10-18 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gervazy', '0003_rsakeypair'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExternalCertificate',
        ),
        migrations.DeleteModel(
            name='RSAKeyPair',
        ),
        migrations.DeleteModel(
            name='TLSCertificate',
        ),
    ]
