# Generated by Django 4.2.23 on 2026-05-16 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_maplayer_owner'),
        ('enigma', '0002_alter_participant_person_alter_room_people'),
        ('quizzes', '0002_alter_quiz_owner_alter_quizattempt_participant'),
        ('travels', '0002_alter_travel_participants_alter_visit_participant'),
        ('verbena', '0002_alter_section_author'),
        ('competence', '0003_alter_experience_person'),
        ('library', '0003_alter_article_authors_alter_book_authors'),
        ('people', '0001_initial'),
        ('kanban', '0003_alter_campaign_owner_and_more'),
        ('events', '0003_alter_event_organizer'),
        ('academy', '0003_alter_certificate_person_alter_script_author_and_more'),
        ('socialhub', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='community',
                    name='head',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_communities', to='people.person'),
                ),
                migrations.AlterField(
                    model_name='referencerequest',
                    name='referrer',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_references', to='people.person'),
                ),
                migrations.DeleteModel(
                    name='Person',
                ),
            ],
            database_operations=[],
        ),
    ]
