# Generated by Django 4.2.23 on 2026-05-04 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_federation_uid'),
        ('socialhub', '0002_community_uid_communitymember_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='federation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communities', to='core.federation'),
        ),
    ]
