# Generated by Django 4.2.23 on 2026-05-25 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialhub', '0003_community_is_federal_tribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent community in the hierarchy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='socialhub.community'),
        ),
    ]
