# Generated by Django 4.2.23 on 2026-05-08 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gervazy', '0003_alter_secretpassword_name'),
        ('socialhub', '0003_remove_emailservice_pass_phrase_env_var'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailservice',
            name='secret_password',
            field=models.OneToOneField(help_text='SecretPassword unlock box for the SMTP password SecretKey', on_delete=django.db.models.deletion.CASCADE, related_name='email_service_for', to='gervazy.secretpassword'),
        ),
    ]
