# Generated by Django 4.2.23 on 2026-08-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitvault', '0003_gitvaultquotapolicy_gitvaultusageevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitrepo',
            name='remote_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
