# Generated by Django 4.2.23 on 2026-06-04 19:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import toto.workflows.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mandragora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LambdaFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_name', models.CharField(max_length=255, unique=True)),
                ('content', models.TextField(blank=True)),
                ('stdout', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('kernel', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lambda_function', to='mandragora.computekernel')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('report_type', models.CharField(choices=[('card', 'Card'), ('chart', 'Chart'), ('table', 'Table'), ('text', 'Text')], default='table', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=20)),
                ('definition', models.JSONField(default=toto.workflows.models.default_report_definition, help_text='Snapshot of the report template definition used to generate this report.', validators=[toto.workflows.models.validate_report_definition])),
                ('data', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('report_type', models.CharField(choices=[('card', 'Card'), ('chart', 'Chart'), ('table', 'Table'), ('text', 'Text')], default='table', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('definition', models.JSONField(blank=True, default=toto.workflows.models.default_report_definition, help_text="JSON report syntax for one visualization. Use {type:'chart', data:{path:'series'}, x:'label', y:'value'} or {type:'table', data:{path:'rows'}, columns:[...]}. Values can use {'path': 'metrics.total'}.", validators=[toto.workflows.models.validate_report_definition])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_key', models.CharField(blank=True, max_length=255)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('lambda', 'Lambda'), ('split', 'Split'), ('join', 'Join'), ('report', 'Report'), ('predefined_task', 'Predefined Task')], max_length=20)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('task_name', models.CharField(blank=True, max_length=255)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('position_x', models.FloatField(default=0.0)),
                ('position_y', models.FloatField(default=0.0)),
                ('lambda_function', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_nodes', to='workflows.lambdafunction')),
                ('report_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_nodes', to='workflows.reporttemplate')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='workflows.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('output_data', models.JSONField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='workflows.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowNodeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('input_data', models.JSONField(blank=True, null=True)),
                ('output_data', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_runs', to='workflows.workflownode')),
                ('workflow_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_runs', to='workflows.workflowrun')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowEdgeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('edge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edge_runs', to='workflows.workflowedge')),
                ('workflow_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edge_runs', to='workflows.workflowrun')),
            ],
        ),
        migrations.AddField(
            model_name='workflowedge',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='workflows.workflownode'),
        ),
        migrations.AddField(
            model_name='workflowedge',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='workflows.workflownode'),
        ),
        migrations.AddField(
            model_name='workflowedge',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='workflows.workflow'),
        ),
        migrations.CreateModel(
            name='ReportPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=120)),
                ('title', models.CharField(max_length=180)),
                ('order', models.PositiveIntegerField(default=0)),
                ('blocks', models.JSONField(blank=True, default=list)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='workflows.report')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='source_node_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='workflows.workflownoderun'),
        ),
        migrations.AddField(
            model_name='report',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='workflows.reporttemplate'),
        ),
        migrations.AddField(
            model_name='report',
            name='workflow_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='workflows.workflowrun'),
        ),
        migrations.AddConstraint(
            model_name='workflownoderun',
            constraint=models.UniqueConstraint(fields=('workflow_run', 'node'), name='unique_workflow_node_run'),
        ),
        migrations.AddConstraint(
            model_name='workflowedgerun',
            constraint=models.UniqueConstraint(fields=('workflow_run', 'edge'), name='unique_workflow_edge_run'),
        ),
        migrations.AddConstraint(
            model_name='workflowedge',
            constraint=models.UniqueConstraint(fields=('source', 'target'), name='unique_workflow_edge'),
        ),
        migrations.AddConstraint(
            model_name='reportpage',
            constraint=models.UniqueConstraint(fields=('report', 'key'), name='unique_report_page_key'),
        ),
    ]
