# Generated by Django 4.2.23 on 2026-08-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_workflow_owner_workflowrun_started_by_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workflowquotapolicy',
            name='workflows_workflowquotapolicy_one_default',
        ),
        migrations.RemoveConstraint(
            model_name='workflowquotapolicy',
            name='workflows_workflowquotapolicy_one_per_user',
        ),
        migrations.RemoveField(
            model_name='workflowquotapolicy',
            name='user',
        ),
        migrations.AddConstraint(
            model_name='workflowquotapolicy',
            constraint=models.UniqueConstraint(fields=('metric_code',), name='workflows_workflowquotapolicy_one_per_metric'),
        ),
    ]
