# Generated by Django 4.2.23 on 2025-12-13 15:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=2, verbose_name='Country')),
                ('state_or_province_name', models.CharField(max_length=128, verbose_name='State/Province')),
                ('locality_name', models.CharField(max_length=128, verbose_name='Locality')),
                ('street', models.CharField(max_length=255, verbose_name='Street')),
                ('building', models.CharField(max_length=64, verbose_name='Building Number')),
                ('apartment', models.CharField(blank=True, max_length=64, null=True, verbose_name='Apartment Number')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='pathfeature',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pointfeature',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='zonefeature',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
