"""
Django settings for toto project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import logging

logging.basicConfig(level=logging.DEBUG)


from pathlib import Path
import os
from neomodel import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--g0q3jqz@81_kbndpgay5&s3fx3t08x10@#32@0xdik!nb!699'

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = os.getenv("DJANGO_DEBUG", False) == True
#DEBUG = True
DJANGO_ENV = os.getenv("DJANGO_ENV", "dev")

if DJANGO_ENV != "PROD":
    DEBUG = True
else:
    DEBUG = False


ACME_CHALLENGE_ROOT = os.path.join(BASE_DIR, 'acme-challenges')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'django_celery_beat',
    'django_jsonform',
    'django_json_widget',
    'rest_framework',
    'nested_admin',
    'colorfield',
    'polymorphic',
    'django_ace',
    'reversion',
    "gervazy",
    "oya",
    "captcha",
    "memo",
    "editor",
    "vault",
    "portfolio",
    "latextile",
    "community",
    "events",
    "audit",
    "kanban",
    "yamabiko",
    "finance",
    "federal",
    "gate",
    "ravioli"
]


MIDDLEWARE = [
    "oya.middleware.PlatformMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.middleware.locale.LocaleMiddleware"
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend'
]

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


ROOT_URLCONF = 'toto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = 'toto.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# if DJANGO_ENV == "PROD":
#     DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.postgresql',
#             'NAME': os.getenv('DB_NAME'),
#             'USER': os.getenv('DB_USER'),
#             'PASSWORD': os.getenv('DB_PASSWORD'),
#             'HOST': os.getenv('DB_HOST'),
#             'PORT': os.getenv('DB_PORT'),
#         }
#     }
# else:
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
#STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
# If you need to serve static files in production, use this:
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DJANGO_HOST_IP = os.getenv("DJANGO_HOST_IP", "127.0.0.1")  # Default fallback

DEBUG = DJANGO_ENV != "PROD"

ALLOWED_HOSTS = [DJANGO_HOST_IP, 'localhost']

if DJANGO_ENV == "PROD":
    CSRF_TRUSTED_ORIGINS = [
        f"https://{DJANGO_HOST_IP}:443",
        f"https://{DJANGO_HOST_IP}:8443",
        "https://localhost:443",
        "https://localhost:8443"
    ]

    CSRF_ALLOWED_ORIGINS = [
        f"https://{DJANGO_HOST_IP}:443",
        f"https://{DJANGO_HOST_IP}:8443",
        "https://localhost:443",
        "https://localhost:8443"
    ]
else:
    CSRF_TRUSTED_ORIGINS = [
        f"http://{DJANGO_HOST_IP}:8000",
        f"http://{DJANGO_HOST_IP}:8080",
        "http://localhost:8000",
        "http://localhost:8080"
    ]

    CSRF_ALLOWED_ORIGINS = [
        f"http://{DJANGO_HOST_IP}:8000",
        f"http://{DJANGO_HOST_IP}:8080",
        "http://localhost:8000",
        "http://localhost:8080"
    ]



if DJANGO_ENV == "PROD":
    SECURE_SSL_REDIRECT = DJANGO_ENV == "PROD"
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = DJANGO_ENV == "PROD"
    CSRF_COOKIE_SECURE = DJANGO_ENV == "PROD"
    CSRF_COOKIE_HTTPONLY = True

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}



LOGIN_URL = '/community/login/'

REDIS_HOST = os.getenv("REDIS_HOST", "localhost") if DJANGO_ENV != "PROD" else "redis_toto"

CELERY_BROKER_URL = f'redis://{REDIS_HOST}:6379/0'
CELERY_RESULT_BACKEND = f'redis://{REDIS_HOST}:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE


FIELD_ENCRYPTION_KEY = 'GYVe39sJIvujld8u5NlnFStQXEkZnLDAXxtD6p2UfWs='

INGRESS_ALLOWED_APPS = [
    'oya',
    'audit',
    "memo",
    "gervazy",
    "vault",
    "community",
    "federal",
    "finance",
    "portfolio",
    "events",
    "kanban",
    "ravioli"
]

FULL_INGRESS = True#DEBUG

GIT_REPO_BASE_DIR = BASE_DIR / 'git_repos'

LOG_DIR = Path(BASE_DIR) / 'logs'
LOG_DIR.mkdir(exist_ok=True)

INSTALLED_LOGGERS = {}

for app in INSTALLED_APPS:
    app_label = app.split('.')[-1]
    log_file = LOG_DIR / f"{app_label}.log"

    INSTALLED_LOGGERS[app_label] = {
        'handlers': [f'{app_label}_file'],
        'level': 'INFO',
        'propagate': False,
    }

LOG_PATH = os.path.join(BASE_DIR, 'log.txt')  # assuming BASE_DIR points to your project root

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'default': {
            'format': '[%(name)s] %(asctime)s %(levelname)s %(message)s',
        },
    },
    'handlers': {
        **{
            f'{app_label}_file': {
                'class': 'logging.handlers.TimedRotatingFileHandler',
                'filename': str(LOG_DIR / f"{app_label}.log"),
                'when': 'midnight',
                'backupCount': 7,
                'formatter': 'default',
            }
            for app_label in INSTALLED_LOGGERS
        }
    },
    'loggers': INSTALLED_LOGGERS,
}

AUDITED_APPS = [
    "gervazy",
    "oya",
    "memo",
    "editor",
    "vault",
    "portfolio",
    "latextile",
    "community",
    "events",
    "finance"
]

NEO4J_HOST = os.getenv("NEO4J_HOST", "neo4j")   # container name or localhost
NEO4J_PORT = os.getenv("NEO4J_PORT", "7687")
NEO4J_USER = os.getenv("NEO4J_USER", "neo4j")
NEO4J_PASSWORD = os.getenv("NEO4J_PASSWORD", "supersecretneo4j")

config.DATABASE_URL = f"bolt://{NEO4J_USER}:{NEO4J_PASSWORD}@{NEO4J_HOST}:{NEO4J_PORT}"

NEO4J_CHECK_ALIVE = DEBUG
