# Generated by Django 4.2.23 on 2026-05-19 13:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_alter_realworldobject_object_type'),
        ('assets', '0003_obligation_iscurrency'),
        ('people', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TribunalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('case_number', models.CharField(blank=True, max_length=64, unique=True)),
                ('reason', models.CharField(blank=True, help_text='Short reason for opening the case.', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, default='open', help_text='open, under_review, awaiting_evidence, resolved, dismissed, escalated, etc.', max_length=64)),
                ('priority', models.CharField(blank=True, default='normal', help_text='low, normal, high, urgent, etc.', max_length=64)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Mediator, judge, supervisor, or responsible reviewer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tribunal_cases', to='people.person')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_tribunal_cases', to='people.person')),
                ('related_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tribunal_cases', to='inventory.realworldobject')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='TribunalParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('role', models.CharField(blank=True, help_text='claimant, respondent, witness, mediator, custodian, verifier, observer, etc.', max_length=64)),
                ('statement', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='tribunal.tribunalcase')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tribunal_participations', to='people.person')),
            ],
            options={
                'ordering': ['case', 'role', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TribunalEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('evidence_type', models.CharField(blank=True, help_text='document, photo, statement, ledger_reference, object_snapshot, external_link, file_hash, etc.', max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='tribunal/evidence/')),
                ('file_hash', models.CharField(blank=True, max_length=64)),
                ('external_reference', models.CharField(blank=True, max_length=255)),
                ('external_url', models.URLField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='tribunal.tribunalcase')),
                ('related_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tribunal_evidence', to='inventory.realworldobject')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_evidence', to='tribunal.tribunalparty')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='TribunalClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('claim_type', models.CharField(blank=True, help_text='ownership, custody, damage, missing_object, fraud, valuation, breach, verification, etc.', max_length=64)),
                ('summary', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('requested_resolution', models.TextField(blank=True, help_text='What the claimant wants: return, compensation, transfer, correction, dismissal, etc.')),
                ('amount', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='tribunal.tribunalcase')),
                ('claimant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims_made', to='tribunal.tribunalparty')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tribunal_claims', to='assets.currency')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TribunalRuling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('decision', models.TextField(help_text='The actual ruling / decision.')),
                ('reasoning', models.TextField(blank=True, help_text='Why this decision was made.')),
                ('resolution_type', models.CharField(blank=True, help_text='dismissed, upheld, partial, settlement, compensation, transfer_required, correction_required, etc.', max_length=64)),
                ('amount_awarded', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('effective_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rulings', to='tribunal.tribunalcase')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tribunal_rulings', to='assets.currency')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tribunal_rulings', to='people.person')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['case'], name='tribunal_tr_case_id_34d430_idx'), models.Index(fields=['decided_by'], name='tribunal_tr_decided_82033d_idx'), models.Index(fields=['resolution_type'], name='tribunal_tr_resolut_75bf1f_idx'), models.Index(fields=['currency'], name='tribunal_tr_currenc_d18c76_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='tribunalparty',
            index=models.Index(fields=['case'], name='tribunal_tr_case_id_1bef86_idx'),
        ),
        migrations.AddIndex(
            model_name='tribunalparty',
            index=models.Index(fields=['person'], name='tribunal_tr_person__ee9acf_idx'),
        ),
        migrations.AddIndex(
            model_name='tribunalparty',
            index=models.Index(fields=['role'], name='tribunal_tr_role_87c760_idx'),
        ),
        migrations.AddIndex(
            model_name='tribunalevidence',
            index=models.Index(fields=['case'], name='tribunal_tr_case_id_21734f_idx'),
        ),
        migrations.AddIndex(
            model_name='tribunalevidence',
            index=models.Index(fields=['submitted_by'], name='tribunal_tr_submitt_0f8368_idx'),
        ),
        migrations.AddIndex(
            model_name='tribunalevidence',
            index=models.Index(fields=['evidence_type'], name='tribunal_tr_evidenc_831cf0_idx'),
        ),
        migrations.AddIndex(
            model_name='tribunalevidence',
            index=models.Index(fields=['related_object'], name='tribunal_tr_related_c40829_idx'),
        ),
        migrations.AddIndex(
            model_name='tribunalevidence',
            index=models.Index(fields=['file_hash'], name='tribunal_tr_file_ha_65fe47_idx'),
        ),
        migrations.AddIndex(
            model_name='tribunalclaim',
            index=models.Index(fields=['case'], name='tribunal_tr_case_id_c83d6c_idx'),
        ),
        migrations.AddIndex(
            model_name='tribunalclaim',
            index=models.Index(fields=['claim_type'], name='tribunal_tr_claim_t_2043aa_idx'),
        ),
        migrations.AddIndex(
            model_name='tribunalclaim',
            index=models.Index(fields=['claimant'], name='tribunal_tr_claiman_eda616_idx'),
        ),
        migrations.AddIndex(
            model_name='tribunalclaim',
            index=models.Index(fields=['currency'], name='tribunal_tr_currenc_e3a90d_idx'),
        ),
        migrations.AddIndex(
            model_name='tribunalcase',
            index=models.Index(fields=['case_number'], name='tribunal_tr_case_nu_233a83_idx'),
        ),
        migrations.AddIndex(
            model_name='tribunalcase',
            index=models.Index(fields=['slug'], name='tribunal_tr_slug_6c6f6a_idx'),
        ),
        migrations.AddIndex(
            model_name='tribunalcase',
            index=models.Index(fields=['status'], name='tribunal_tr_status_8dc59d_idx'),
        ),
        migrations.AddIndex(
            model_name='tribunalcase',
            index=models.Index(fields=['priority'], name='tribunal_tr_priorit_68098d_idx'),
        ),
        migrations.AddIndex(
            model_name='tribunalcase',
            index=models.Index(fields=['opened_by'], name='tribunal_tr_opened__296223_idx'),
        ),
        migrations.AddIndex(
            model_name='tribunalcase',
            index=models.Index(fields=['assigned_to'], name='tribunal_tr_assigne_1a0daa_idx'),
        ),
        migrations.AddIndex(
            model_name='tribunalcase',
            index=models.Index(fields=['related_object'], name='tribunal_tr_related_e0139c_idx'),
        ),
    ]
