# Generated by Django 4.2.23 on 2026-05-19 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_obligation_iscurrency'),
        ('bazaar', '0006_wallet_pin'),
        ('tribunal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tribunalcase',
            name='related_order',
            field=models.ForeignKey(blank=True, help_text='Bazaar order this dispute concerns.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tribunal_cases', to='bazaar.order'),
        ),
        migrations.AddField(
            model_name='tribunalruling',
            name='fine_amount',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='tribunalruling',
            name='fine_asset',
            field=models.ForeignKey(blank=True, help_text='Asset used to pay the fine.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tribunal_fines', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='tribunalruling',
            name='fine_creditor_account',
            field=models.ForeignKey(blank=True, help_text='Account that receives the fine.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tribunal_fines_receivable', to='assets.ledgeraccount'),
        ),
        migrations.AddField(
            model_name='tribunalruling',
            name='fine_debtor_account',
            field=models.ForeignKey(blank=True, help_text='Account that must pay the fine.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tribunal_fines_due', to='assets.ledgeraccount'),
        ),
        migrations.AddField(
            model_name='tribunalruling',
            name='fine_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tribunalruling',
            name='fine_obligation',
            field=models.ForeignKey(blank=True, help_text='Asset obligation created for this fine.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tribunal_rulings', to='assets.obligation'),
        ),
        migrations.AddIndex(
            model_name='tribunalcase',
            index=models.Index(fields=['related_order'], name='tribunal_tr_related_cd0b66_idx'),
        ),
        migrations.AddIndex(
            model_name='tribunalruling',
            index=models.Index(fields=['fine_debtor_account'], name='tribunal_tr_fine_de_7ea0fe_idx'),
        ),
        migrations.AddIndex(
            model_name='tribunalruling',
            index=models.Index(fields=['fine_creditor_account'], name='tribunal_tr_fine_cr_497936_idx'),
        ),
        migrations.AddIndex(
            model_name='tribunalruling',
            index=models.Index(fields=['fine_asset'], name='tribunal_tr_fine_as_115808_idx'),
        ),
        migrations.AddIndex(
            model_name='tribunalruling',
            index=models.Index(fields=['fine_obligation'], name='tribunal_tr_fine_ob_44dc29_idx'),
        ),
    ]
