# Generated by Django 4.2.23 on 2026-05-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_initial'),
        ('tribunal', '0003_jury_session_and_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurysession',
            name='jurors',
            field=models.ManyToManyField(blank=True, help_text='People invited to vote. Leave empty to allow any member to vote.', related_name='jury_session_invites', to='people.person'),
        ),
    ]
