# Generated by Django 4.2.23 on 2026-06-24 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jsonform.models.fields
import toto.api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('gervazy', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='sabbia/avatars/')),
                ('system_prompt', models.TextField(default='You are a helpful, concise assistant.')),
                ('endpoint_type', models.CharField(choices=[('openai', 'OpenAI ChatGPT'), ('ollama', 'Ollama (local, via Vicuna)')], max_length=40)),
                ('model_name', models.CharField(blank=True, help_text='e.g. gpt-4.1-mini, qwen3:1.7b', max_length=120)),
                ('endpoint_config', models.JSONField(blank=True, default=dict, help_text='Non-secret per-endpoint config: base_url, timeout, ...')),
                ('temperature', models.FloatField(default=0.2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlatformChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platform_links', to='sabbia.agent')),
                ('platform', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot', to='core.platform')),
            ],
            options={
                'verbose_name': 'Platform chatbot',
                'verbose_name_plural': 'Platform chatbots',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='sabbia.agent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sabbia_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='sabbia.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('provider', models.CharField(choices=[('generic', 'Generic'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('github', 'GitHub'), ('custom', 'Custom'), ('rule_based', 'Rule-based (no API key)')], default='generic', max_length=40)),
                ('base_url', models.URLField(blank=True, help_text='Base API URL, e.g. https://api.openai.com/v1/')),
                ('auth_type', models.CharField(choices=[('none', 'No authentication'), ('api_key_header', 'API key header'), ('bearer_token', 'Bearer token'), ('query_param', 'Query parameter'), ('hmac', 'HMAC signature'), ('signature', 'Asymmetric request signature'), ('custom', 'Custom')], default='bearer_token', max_length=40)),
                ('auth_config', django_jsonform.models.fields.JSONField(blank=True, default=dict, help_text='Non-secret auth config such as header name or timeout.')),
                ('extra', django_jsonform.models.fields.JSONField(blank=True, default=dict, help_text='Non-secret provider-specific configuration.', validators=[toto.api.models._reject_secret_like_json])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_secret', models.ForeignKey(blank=True, help_text='Encrypted API key/token stored in Gervazy.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_api_connectors', to='gervazy.encryptedsecret')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('signing_key', models.ForeignKey(blank=True, help_text='Encrypted private key for signed API requests.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_signing_keys', to='gervazy.encryptedprivatekey')),
            ],
            options={
                'verbose_name': 'Agent connector',
                'verbose_name_plural': 'Agent connectors',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='connector',
            field=models.ForeignKey(blank=True, help_text='Holds encrypted credentials for API-key endpoints (e.g. OpenAI).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='sabbia.agentconnector'),
        ),
    ]
