# Generated by Django 4.2.23 on 2026-05-13 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('steven', '0001_initial'),
        ('socialhub', '0001_initial'),
        ('enigma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='agents',
            field=models.ManyToManyField(blank=True, related_name='enigma_rooms', through='enigma.Participant', to='steven.agentprofile'),
        ),
        migrations.AddField(
            model_name='room',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='chat_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='enigma_rooms', through='enigma.Participant', to='socialhub.person'),
        ),
        migrations.AddField(
            model_name='participant',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_participations', to='steven.agentprofile'),
        ),
        migrations.AddField(
            model_name='participant',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_participations', to='socialhub.person'),
        ),
        migrations.AddField(
            model_name='participant',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_participants', to='enigma.room'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(condition=models.Q(('person__isnull', False)), fields=('room', 'person'), name='unique_enigma_room_person'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(condition=models.Q(('agent__isnull', False)), fields=('room', 'agent'), name='unique_enigma_room_agent'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('agent__isnull', True), ('person__isnull', False)), models.Q(('agent__isnull', False), ('person__isnull', True)), _connector='OR'), name='valid_enigma_participant_identity'),
        ),
    ]
