# Generated by Django 4.2.23 on 2026-05-16 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('enigma', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='participant',
                    name='person',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_participations', to='people.person'),
                ),
                migrations.AlterField(
                    model_name='room',
                    name='people',
                    field=models.ManyToManyField(blank=True, related_name='enigma_rooms', through='enigma.Participant', to='people.person'),
                ),
            ],
            database_operations=[],
        ),
    ]
