# Generated by Django 4.2.23 on 2026-05-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigma', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='require_encryption',
            field=models.BooleanField(default=False, help_text='If set, this participant may only send MLS-encrypted messages.'),
        ),
    ]
