# Generated by Django 4.2.23 on 2026-05-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigma', '0003_add_participant_require_encryption'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['person__display_name']},
        ),
        migrations.RemoveConstraint(
            model_name='participant',
            name='unique_enigma_room_agent',
        ),
        migrations.RemoveConstraint(
            model_name='participant',
            name='valid_enigma_participant_identity',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='room',
            name='agents',
        ),
        migrations.AlterField(
            model_name='participant',
            name='require_encryption',
            field=models.BooleanField(default=True, help_text='Participant must use MLS end-to-end encryption.'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.CheckConstraint(check=models.Q(('person__isnull', False)), name='enigma_participant_must_have_person'),
        ),
    ]
