# Generated by Django 4.2.23 on 2026-05-25 16:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bazaar', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tracking_number', models.CharField(max_length=100, unique=True)),
                ('carrier', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('created', 'Created'), ('picked_up', 'Picked up'), ('in_transit', 'In transit'), ('at_hub', 'At hub'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('returned', 'Returned')], default='created', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_packages', to='locations.address')),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_packages', to='locations.address')),
                ('shipment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logistics_package', to='bazaar.shipment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('carrier', models.CharField(blank=True, max_length=255)),
                ('mode', models.CharField(choices=[('road', 'Road'), ('rail', 'Rail'), ('air', 'Air'), ('sea', 'Sea'), ('courier', 'Courier'), ('other', 'Other')], default='road', max_length=20)),
                ('identifier', models.CharField(blank=True, help_text='Vehicle ID, flight number, vessel name, etc.', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transports_here', to='locations.address')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transports_to', to='locations.address')),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transports_from', to='locations.address')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PackageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('picked_up', 'Picked up'), ('in_transit', 'In transit'), ('at_hub', 'At hub'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('returned', 'Returned')], max_length=32)),
                ('note', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_events', to='locations.address')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='logistics.package')),
                ('transport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='logistics.transport')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddField(
            model_name='package',
            name='transport',
            field=models.ForeignKey(blank=True, help_text='Current transport carrying this package', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='logistics.transport'),
        ),
    ]
