# Generated by Django 4.2.23 on 2026-10-01 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnastasiaQuotaPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('metric_code', models.CharField(db_index=True, max_length=100)),
                ('limit', models.DecimalField(decimal_places=10, max_digits=30)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime')], default='daily', max_length=20)),
                ('mode', models.CharField(choices=[('track', 'Track only'), ('warn', 'Warn'), ('block', 'Block')], default='block', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compute Capsule quota policy',
                'verbose_name_plural': 'Compute Capsule quota policies',
                'ordering': ['metric_code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComputeLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text='What this Capsule is for — shown wherever you pick one.', max_length=60)),
                ('cpu_millicores', models.PositiveIntegerField()),
                ('ram_mb', models.PositiveIntegerField()),
                ('scratch_mb', models.PositiveIntegerField()),
                ('pids', models.PositiveIntegerField()),
                ('permanent_home', models.BooleanField(default=False, help_text="Keep each workspace's home directory between sessions (shell history, tool configuration, interactive installs).")),
                ('egress', models.BooleanField(default=False, help_text="Let jobs in this Capsule reach the internet, through this platform's filtering proxy. Only the destinations your administrator allows are reachable.")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('release_reason', models.CharField(blank=True, max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compute_leases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'compute lease',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('operation', models.CharField(max_length=40)),
                ('family', models.CharField(max_length=16)),
                ('cpu_millicores', models.PositiveIntegerField()),
                ('ram_mb', models.PositiveIntegerField()),
                ('scratch_mb', models.PositiveIntegerField()),
                ('pids', models.PositiveIntegerField()),
                ('timeout_seconds', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('killed', 'Killed'), ('lost', 'Lost')], default='pending', max_length=12)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('subject_label', models.CharField(blank=True, max_length=100)),
                ('subject_id', models.CharField(blank=True, max_length=64)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='anastasia.computelease')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anastasia_executions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='PoolGuard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('touched', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'pool guard',
            },
        ),
        migrations.CreateModel(
            name='InstallRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('python', 'Python'), ('latex', 'LaTeX')], default='python', max_length=12)),
                ('packages', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('killed', 'Killed'), ('lost', 'Lost')], default='pending', max_length=12)),
                ('phase', models.CharField(blank=True, max_length=32)),
                ('packages_done', models.PositiveIntegerField(default=0)),
                ('packages_total', models.PositiveIntegerField(default=0)),
                ('log', models.TextField(blank=True)),
                ('log_offset', models.PositiveIntegerField(default=0)),
                ('log_truncated', models.BooleanField(default=False)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installs', to='anastasia.execution')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installs', to='anastasia.computelease')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anastasia_installs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='CapsuleToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Which client this is for, so a person can revoke the right one without guessing.', max_length=120)),
                ('selector', models.CharField(db_index=True, max_length=64, unique=True)),
                ('verifier_hash', models.CharField(max_length=255)),
                ('hint', models.CharField(blank=True, max_length=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capsule_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'capsule API token',
                'verbose_name_plural': 'capsule API tokens',
            },
        ),
        migrations.CreateModel(
            name='CapsuleSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('state', models.CharField(blank=True, max_length=20)),
                ('tier', models.CharField(blank=True, max_length=20)),
                ('ram_mb_used', models.PositiveIntegerField(blank=True, null=True)),
                ('pids_used', models.PositiveIntegerField(blank=True, null=True)),
                ('cpu_percent', models.FloatField(blank=True, null=True)),
                ('executions_running', models.PositiveIntegerField(blank=True, null=True)),
                ('storage_bytes', models.BigIntegerField(blank=True, null=True)),
                ('storage_files', models.PositiveIntegerField(blank=True, null=True)),
                ('storage_complete', models.BooleanField(blank=True, null=True)),
                ('net_rx_bytes', models.BigIntegerField(blank=True, null=True)),
                ('net_tx_bytes', models.BigIntegerField(blank=True, null=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='anastasia.computelease')),
            ],
            options={
                'verbose_name': 'capsule sample',
            },
        ),
        migrations.CreateModel(
            name='CapsuleRuntime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('ready', 'Ready'), ('busy', 'Busy'), ('degraded', 'Degraded'), ('dead', 'Dead'), ('unmounted', 'Unmounted')], default='unmounted', max_length=12)),
                ('state_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('mounted_at', models.DateTimeField(blank=True, null=True)),
                ('unmounted_at', models.DateTimeField(blank=True, null=True)),
                ('manager_generation', models.CharField(blank=True, max_length=64)),
                ('tier', models.CharField(blank=True, max_length=32)),
                ('last_sample', models.JSONField(blank=True, default=dict)),
                ('sampled_at', models.DateTimeField(blank=True, null=True)),
                ('detail', models.CharField(blank=True, max_length=200)),
                ('lease', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='runtime', to='anastasia.computelease')),
            ],
            options={
                'verbose_name': 'capsule runtime',
            },
        ),
        migrations.CreateModel(
            name='CapsuleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('reserve', 'Reserved'), ('mount', 'Mounted'), ('unmount', 'Unmounted'), ('release', 'Released'), ('expire', 'Expired'), ('execute', 'Execution'), ('reconcile', 'Reconciled'), ('degrade', 'Degraded')], max_length=12)),
                ('accepted', models.BooleanField(default=True)),
                ('refusal_code', models.CharField(blank=True, max_length=48)),
                ('from_state', models.CharField(blank=True, max_length=12)),
                ('to_state', models.CharField(blank=True, max_length=12)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anastasia_events', to=settings.AUTH_USER_MODEL)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='anastasia.computelease')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='AnastasiaUsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_code', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=30)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('source_type', models.CharField(blank=True, max_length=100)),
                ('source_id', models.CharField(blank=True, max_length=255)),
                ('source_label', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('recorded', 'Recorded'), ('voided', 'Voided')], default='recorded', max_length=20)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compute Capsule usage event',
                'verbose_name_plural': 'Compute Capsule usage events',
                'ordering': ['-occurred_at'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='anastasiaquotapolicy',
            constraint=models.UniqueConstraint(fields=('metric_code',), name='anastasia_anastasiaquotapolicy_one_per_metric'),
        ),
        migrations.AddIndex(
            model_name='installrun',
            index=models.Index(fields=['lease', 'status'], name='anastasia_install_lease_idx'),
        ),
        migrations.AddIndex(
            model_name='execution',
            index=models.Index(fields=['lease', 'status'], name='anastasia_exec_lease_idx'),
        ),
        migrations.AddIndex(
            model_name='execution',
            index=models.Index(fields=['status', 'created_at'], name='anastasia_exec_status_idx'),
        ),
        migrations.AddIndex(
            model_name='execution',
            index=models.Index(fields=['subject_label', 'subject_id'], name='anastasia_exec_subject_idx'),
        ),
        migrations.AddIndex(
            model_name='computelease',
            index=models.Index(fields=['released_at', 'expires_at'], name='anastasia_lease_open_idx'),
        ),
        migrations.AddIndex(
            model_name='computelease',
            index=models.Index(fields=['owner', 'released_at'], name='anastasia_lease_owner_idx'),
        ),
        migrations.AddConstraint(
            model_name='computelease',
            constraint=models.UniqueConstraint(condition=models.Q(('released_at__isnull', True)), fields=('owner', 'name'), name='anastasia_one_live_name_per_owner'),
        ),
        migrations.AddIndex(
            model_name='capsuletoken',
            index=models.Index(fields=['owner', 'revoked_at'], name='anastasia_token_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='capsulesample',
            index=models.Index(fields=['lease', '-taken_at'], name='anastasia_sample_lease_idx'),
        ),
        migrations.AddIndex(
            model_name='capsuleruntime',
            index=models.Index(fields=['state'], name='anastasia_capsule_state_idx'),
        ),
        migrations.AddIndex(
            model_name='capsuleevent',
            index=models.Index(fields=['lease', 'kind'], name='anastasia_event_lease_idx'),
        ),
        migrations.AddIndex(
            model_name='anastasiausageevent',
            index=models.Index(fields=['metric_code', 'occurred_at'], name='anastasiausageevent_mtime'),
        ),
        migrations.AddIndex(
            model_name='anastasiausageevent',
            index=models.Index(fields=['user', 'metric_code'], name='anastasiausageevent_umetric'),
        ),
        migrations.AddConstraint(
            model_name='anastasiausageevent',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('idempotency_key',), name='anastasia_anastasiausageevent_idem'),
        ),
    ]
