# Generated by Django 4.2.23 on 2026-08-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anastasia', '0002_anastasiaquotapolicy_anastasiausageevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computelease',
            name='permanent_home',
            field=models.BooleanField(default=False, help_text="Keep each workspace's home directory between sessions (shell history, tool configuration, interactive installs)."),
        ),
    ]
