# Generated by Django 4.2.23 on 2026-09-10 13:12

from django.conf import settings
"""The API token, plus the verbose-name fallout of the Gear -> Capsule rename.

Two unrelated things in one migration because the autodetector produced them
together and splitting generated operations by hand is how a dependency graph
gets subtly wrong. The Meta changes are cosmetic (admin labels and help text);
the token is the substance.
"""

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anastasia', '0006_capsule_rename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anastasiaquotapolicy',
            options={'ordering': ['metric_code'], 'verbose_name': 'Compute Capsule quota policy', 'verbose_name_plural': 'Compute Capsule quota policies'},
        ),
        migrations.AlterModelOptions(
            name='anastasiausageevent',
            options={'ordering': ['-occurred_at'], 'verbose_name': 'Compute Capsule usage event', 'verbose_name_plural': 'Compute Capsule usage events'},
        ),
        migrations.AlterModelOptions(
            name='capsuleruntime',
            options={'verbose_name': 'capsule runtime'},
        ),
        migrations.AlterField(
            model_name='computelease',
            name='name',
            field=models.CharField(help_text='What this Capsule is for — shown wherever you pick one.', max_length=60),
        ),
        migrations.CreateModel(
            name='CapsuleToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Which client this is for, so a person can revoke the right one without guessing.', max_length=120)),
                ('selector', models.CharField(db_index=True, max_length=64, unique=True)),
                ('verifier_hash', models.CharField(max_length=255)),
                ('hint', models.CharField(blank=True, max_length=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capsule_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'capsule API token',
                'verbose_name_plural': 'capsule API tokens',
                'indexes': [models.Index(fields=['owner', 'revoked_at'], name='anastasia_token_owner_idx')],
            },
        ),
    ]
