# Generated by Django 4.2.23 on 2026-09-10 13:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('anastasia', '0007_capsule_api_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapsuleSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('state', models.CharField(blank=True, max_length=20)),
                ('tier', models.CharField(blank=True, max_length=20)),
                ('ram_mb_used', models.PositiveIntegerField(blank=True, null=True)),
                ('pids_used', models.PositiveIntegerField(blank=True, null=True)),
                ('cpu_percent', models.FloatField(blank=True, null=True)),
                ('executions_running', models.PositiveIntegerField(blank=True, null=True)),
                ('storage_bytes', models.BigIntegerField(blank=True, null=True)),
                ('storage_files', models.PositiveIntegerField(blank=True, null=True)),
                ('storage_complete', models.BooleanField(blank=True, null=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='anastasia.computelease')),
            ],
            options={
                'verbose_name': 'capsule sample',
                'indexes': [models.Index(fields=['lease', '-taken_at'], name='anastasia_sample_lease_idx')],
            },
        ),
    ]
