# Generated by Django 4.2.23 on 2026-09-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anastasia', '0009_computelease_egress'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsulesample',
            name='net_rx_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capsulesample',
            name='net_tx_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
