# Generated by Django 4.2.23 on 2026-09-10 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anastasia', '0010_capsulesample_net_rx_bytes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('packages', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('killed', 'Killed'), ('lost', 'Lost')], default='pending', max_length=12)),
                ('phase', models.CharField(blank=True, max_length=32)),
                ('packages_done', models.PositiveIntegerField(default=0)),
                ('packages_total', models.PositiveIntegerField(default=0)),
                ('log', models.TextField(blank=True)),
                ('log_offset', models.PositiveIntegerField(default=0)),
                ('log_truncated', models.BooleanField(default=False)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installs', to='anastasia.execution')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installs', to='anastasia.computelease')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anastasia_installs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['lease', 'status'], name='anastasia_install_lease_idx')],
            },
        ),
    ]
