# Generated by Django 4.2.23 on 2025-08-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netogami', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='header',
        ),
        migrations.AlterField(
            model_name='template',
            name='content',
            field=models.TextField(help_text='Full Django template content including <head> and body with {{ variables }}'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
