# Generated by Django 4.2.23 on 2025-08-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netogami', '0002_remove_template_header_alter_template_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('repo_url', models.URLField()),
                ('branch', models.CharField(default='main', max_length=100)),
                ('token', models.CharField(default='main', max_length=100)),
            ],
        ),
    ]
