# Generated by Django 4.2.23 on 2025-08-19 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netogami', '0003_templatesource'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(help_text='Relative path to the template file in the repo', max_length=255)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generators', to='netogami.templatesource')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generators', to='netogami.template')),
            ],
        ),
    ]
