# Generated by Django 4.2.23 on 2025-08-19 20:44

from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('netogami', '0004_templategenerator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templategenerator',
            name='file_path',
            field=models.CharField(blank=True, help_text='Relative path to the template file in the repo', max_length=255),
        ),
        migrations.AlterField(
            model_name='templatesource',
            name='token',
            field=encrypted_model_fields.fields.EncryptedCharField(default='main'),
        ),
    ]
