# Generated by Django 4.2.23 on 2025-08-19 21:08

from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('netogami', '0005_alter_templategenerator_file_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codebase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(default='main', max_length=100)),
                ('last_synced', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('repo_url', models.URLField()),
                ('token', encrypted_model_fields.fields.EncryptedCharField(default='main')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(blank=True, help_text='Relative path to the template file in the repo', max_length=255)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact', to='netogami.codebase')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact', to='netogami.template')),
            ],
        ),
        migrations.DeleteModel(
            name='TemplateGenerator',
        ),
        migrations.DeleteModel(
            name='TemplateSource',
        ),
        migrations.AddField(
            model_name='codebase',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generators', to='netogami.repository'),
        ),
    ]
