# Generated by Django 4.2.23 on 2026-10-01 05:49

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vault', '0001_initial'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0003_initial'),
        ('people', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('form', models.CharField(choices=[('generic', 'Generic company'), ('pl_sp_zoo', 'Polish sp. z o.o.'), ('pl_psa', 'Polish P.S.A.')], default='generic', help_text='Starter-rule selector and display fact, not a runtime branch.', max_length=32)),
                ('legal_form_label', models.CharField(blank=True, max_length=200)),
                ('registry_no', models.CharField(blank=True, max_length=64)),
                ('tax_no', models.CharField(blank=True, max_length=32)),
                ('statistical_no', models.CharField(blank=True, max_length=32)),
                ('seat', models.TextField(blank=True)),
                ('share_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('capital_currency', models.CharField(blank=True, default='FLOR', max_length=8)),
                ('logo', models.ImageField(blank=True, help_text='Optional logo for this company.', null=True, upload_to='company_logos/')),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=80)),
                ('statute_text', models.TextField(blank=True)),
                ('community_ref', models.CharField(blank=True, help_text='Optional Social Hub community slug or external community reference.', max_length=255)),
                ('constitutive_document_ref', models.CharField(blank=True, help_text='Optional vault path, document UID, registry URL or external evidence reference.', max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('headquarters', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_headquarters', to='locations.address')),
                ('statute_file', models.ForeignKey(blank=True, help_text="The company's statute, as a file in the vault.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vault.vaultfile')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=80)),
                ('address', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='company.company')),
            ],
            options={
                'ordering': ('company', 'name'),
            },
        ),
        migrations.CreateModel(
            name='OwnershipEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(choices=[('issue', 'Issue'), ('transfer', 'Transfer'), ('split', 'Split'), ('correction', 'Correction')], max_length=24)),
                ('source_units', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('target_units', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('effective_on', models.DateField(default=django.utils.timezone.localdate)),
                ('authority_reference', models.CharField(blank=True, max_length=200)),
                ('evidence_ref', models.CharField(blank=True, help_text='Optional vault path, document UID, registry URL or external evidence reference.', max_length=255)),
                ('evidence_hash', models.CharField(blank=True, max_length=64)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ownership_events', to='company.company')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bc_ownership_events_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-effective_on', '-recorded_at'),
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('is_organisation', models.BooleanField(default=False)),
                ('registry_no', models.CharField(blank=True, max_length=64)),
                ('tax_no', models.CharField(blank=True, max_length=32)),
                ('address', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parties', to='company.company')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_parties_located', to='locations.address')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bc_parties', to='people.person')),
            ],
            options={
                'verbose_name_plural': 'parties',
                'ordering': ('company', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ShareClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('votes_per_unit', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=16)),
                ('nominal_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='share_classes', to='company.company')),
            ],
            options={
                'verbose_name_plural': 'share classes',
                'ordering': ('company', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ShareHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('units', models.DecimalField(decimal_places=6, max_digits=24)),
                ('since', models.DateField(default=django.utils.timezone.localdate)),
                ('until', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='share_holdings', to='company.party')),
                ('share_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='company.shareclass')),
                ('source_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resulting_holdings', to='company.ownershipevent')),
            ],
            options={
                'ordering': ('share_class', 'party'),
            },
        ),
        migrations.AddField(
            model_name='ownershipevent',
            name='source_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ownership_events_out', to='company.party'),
        ),
        migrations.AddField(
            model_name='ownershipevent',
            name='source_share_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ownership_events_from', to='company.shareclass'),
        ),
        migrations.AddField(
            model_name='ownershipevent',
            name='target_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ownership_events_in', to='company.party'),
        ),
        migrations.AddField(
            model_name='ownershipevent',
            name='target_share_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ownership_events_to', to='company.shareclass'),
        ),
        migrations.CreateModel(
            name='DepartmentMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('is_leadership', models.BooleanField(default=False)),
                ('can_record_decisions', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('joined_on', models.DateField(default=django.utils.timezone.localdate)),
                ('left_on', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='company.department')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_memberships', to='company.party')),
            ],
            options={
                'ordering': ('department', '-is_leadership', 'party__name'),
            },
        ),
        migrations.CreateModel(
            name='DepartmentDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final'), ('superseded', 'Superseded')], default='draft', max_length=16)),
                ('body', models.TextField(blank=True)),
                ('content_hash', models.CharField(blank=True, editable=False, max_length=128)),
                ('evidence_ref', models.CharField(blank=True, max_length=255)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bc_department_decisions_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='company.department')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='company.departmentdecision')),
            ],
            options={
                'ordering': ('-decided_at', '-created_at'),
            },
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_headed', to='company.party'),
        ),
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='company.department'),
        ),
        migrations.CreateModel(
            name='CompanyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('job_title', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('joined_on', models.DateField(default=django.utils.timezone.localdate)),
                ('left_on', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='company.company')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bc_company_memberships', to='people.person')),
                ('primary_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_members', to='company.department')),
            ],
            options={
                'ordering': ('company', 'person__display_name'),
            },
        ),
        migrations.CreateModel(
            name='CompanyForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('channel_slug', models.SlugField(help_text="The forum room's slug. Resolved when the page renders.", unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.OneToOneField(help_text='The company whose room this is.', on_delete=django.db.models.deletion.CASCADE, related_name='forum', to='company.company')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='CompanyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(help_text='The company whose calendar shows it.', on_delete=django.db.models.deletion.CASCADE, related_name='calendar', to='company.company')),
                ('event', models.ForeignKey(help_text="The event shown on this company's calendar.", on_delete=django.db.models.deletion.CASCADE, related_name='company_links', to='events.scheduledevent')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='CompanyAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='What was decided. Cite an earlier block by its id if you need to — it stays ordinary text.')),
                ('kind', models.CharField(choices=[('resolution', 'Resolution'), ('appointment', 'Appointment'), ('statement', 'Statement'), ('other', 'Other')], default='resolution', max_length=24)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('recorded', 'Recorded')], default='draft', max_length=16)),
                ('block_uid', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bc_actions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-recorded_at', '-created_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='shareholding',
            constraint=models.UniqueConstraint(condition=models.Q(('until__isnull', True)), fields=('party', 'share_class'), name='bc_one_live_holding_per_party_class'),
        ),
        migrations.AddConstraint(
            model_name='shareholding',
            constraint=models.CheckConstraint(check=models.Q(('units__gt', 0)), name='bc_holding_units_positive'),
        ),
        migrations.AddConstraint(
            model_name='shareholding',
            constraint=models.CheckConstraint(check=models.Q(('until__isnull', True), ('until__gte', models.F('since')), _connector='OR'), name='bc_holding_dates_ordered'),
        ),
        migrations.AddConstraint(
            model_name='shareclass',
            constraint=models.UniqueConstraint(fields=('company', 'slug'), name='bc_one_share_slug_per_company'),
        ),
        migrations.AddConstraint(
            model_name='shareclass',
            constraint=models.CheckConstraint(check=models.Q(('votes_per_unit__gte', 0)), name='bc_votes_per_unit_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='party',
            constraint=models.CheckConstraint(check=models.Q(('is_organisation', False), ('person__isnull', True), _connector='OR'), name='bc_org_party_has_no_person'),
        ),
        migrations.AddConstraint(
            model_name='party',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='bc_one_party_name_per_company'),
        ),
        migrations.AddIndex(
            model_name='ownershipevent',
            index=models.Index(fields=['company', 'event_type', 'effective_on'], name='company_own_company_443881_idx'),
        ),
        migrations.AddIndex(
            model_name='ownershipevent',
            index=models.Index(fields=['source_party', 'target_party'], name='company_own_source__da1f04_idx'),
        ),
        migrations.AddConstraint(
            model_name='departmentmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('department', 'party'), name='bc_one_active_department_membership'),
        ),
        migrations.AddConstraint(
            model_name='departmentmembership',
            constraint=models.CheckConstraint(check=models.Q(('left_on__isnull', True), ('left_on__gte', models.F('joined_on')), _connector='OR'), name='bc_department_membership_dates'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('company', 'slug'), name='bc_one_department_slug_per_company'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.CheckConstraint(check=models.Q(('parent', models.F('id')), _negated=True), name='bc_department_not_own_parent'),
        ),
        migrations.AddConstraint(
            model_name='companymembership',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('company', 'person'), name='bc_one_active_company_membership'),
        ),
        migrations.AddConstraint(
            model_name='companymembership',
            constraint=models.CheckConstraint(check=models.Q(('left_on__isnull', True), ('left_on__gte', models.F('joined_on')), _connector='OR'), name='bc_company_membership_dates'),
        ),
        migrations.AddConstraint(
            model_name='companyevent',
            constraint=models.UniqueConstraint(fields=('event', 'company'), name='bc_one_calendar_link_per_event'),
        ),
        migrations.AddIndex(
            model_name='companyaction',
            index=models.Index(fields=['company', 'status'], name='bc_action_company_idx'),
        ),
    ]
