# Generated by Django 4.2.23 on 2026-08-24 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final'), ('superseded', 'Superseded')], default='draft', max_length=16)),
                ('body', models.TextField(blank=True)),
                ('content_hash', models.CharField(blank=True, editable=False, max_length=128)),
                ('evidence_ref', models.CharField(blank=True, max_length=255)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bc_department_decisions_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='company.department')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='company.departmentdecision')),
            ],
            options={
                'ordering': ('-decided_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='CompanyAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='What was decided. Cite an earlier block by its id if you need to — it stays ordinary text.')),
                ('kind', models.CharField(choices=[('resolution', 'Resolution'), ('appointment', 'Appointment'), ('statement', 'Statement'), ('other', 'Other')], default='resolution', max_length=24)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('recorded', 'Recorded')], default='draft', max_length=16)),
                ('block_uid', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bc_actions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-recorded_at', '-created_at'),
                'indexes': [models.Index(fields=['company', 'status'], name='bc_action_company_idx')],
            },
        ),
    ]
