# Generated by Django 4.2.23 on 2026-08-28 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_address_latlon'),
        ('company', '0002_departmentdecision_companyaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='headquarters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_headquarters', to='locations.address'),
        ),
        migrations.AddField(
            model_name='party',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_parties_located', to='locations.address'),
        ),
    ]
