# Generated by Django 4.2.23 on 2026-09-06 12:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_initial'),
        ('company', '0004_company_description_company_email_company_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(help_text='The company whose calendar shows it.', on_delete=django.db.models.deletion.CASCADE, related_name='calendar', to='company.company')),
                ('event', models.ForeignKey(help_text="The event shown on this company's calendar.", on_delete=django.db.models.deletion.CASCADE, related_name='company_links', to='events.scheduledevent')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='companyevent',
            constraint=models.UniqueConstraint(fields=('event', 'company'), name='bc_one_calendar_link_per_event'),
        ),
    ]
