# Generated by Django 4.2.23 on 2026-09-06 15:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_companyevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('channel_slug', models.SlugField(help_text="The forum room's slug. Resolved when the page renders.", unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.OneToOneField(help_text='The company whose room this is.', on_delete=django.db.models.deletion.CASCADE, related_name='forum', to='company.company')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
    ]
