# Generated by Django 4.2.23 on 2026-05-18 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('bazaar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ledger_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bazaar_orders', to='assets.ledgeraccount'),
        ),
        migrations.AddField(
            model_name='order',
            name='ledger_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bazaar_orders', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='order',
            name='ledger_tx_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shop',
            name='ledger_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bazaar_shops', to='assets.ledgeraccount'),
        ),
    ]
