# Generated by Django 4.2.23 on 2026-05-18 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_obligation_iscurrency'),
        ('bazaar', '0002_order_ledger_account_order_ledger_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='obligation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bazaar_orders', to='assets.obligation'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('transfer', 'Transfer'), ('on_delivery', 'On delivery'), ('bank_transfer', 'Bank transfer'), ('manual', 'Manual')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='shop',
            name='accepted_currencies',
            field=models.ManyToManyField(blank=True, related_name='accepted_by_shops', to='assets.asset'),
        ),
    ]
