# Generated by Django 4.2.23 on 2026-05-18 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0003_shop_currencies_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='accepted_currencies',
        ),
    ]
