# Generated by Django 4.2.23 on 2026-05-20 03:23

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_move_asset_exchange_request_to_bourse'),
        ('locations', '0002_initial'),
        ('people', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bazaar', '0007_alter_product_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('bounty_type', models.CharField(choices=[('task', 'Task'), ('bug_fix', 'Bug Fix'), ('research', 'Research'), ('creative', 'Creative'), ('development', 'Development'), ('testing', 'Testing'), ('content', 'Content'), ('other', 'Other')], default='task', max_length=32)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('claimed', 'Claimed'), ('submitted', 'Submitted'), ('reviewing', 'Reviewing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='draft', max_length=32)),
                ('reward_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('reward_currency', models.CharField(default='PLN', max_length=3)),
                ('max_claims', models.PositiveIntegerField(default=1)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'bounties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BountyBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('description', models.TextField(blank=True)),
                ('currency', models.CharField(default='PLN', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BountyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280)),
                ('description', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BountyClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('working', 'Working'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('paid', 'Paid')], default='pending', max_length=32)),
                ('proposal', models.TextField(blank=True)),
                ('internal_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BountyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(default='PLN', max_length=3)),
                ('ledger_tx_reference', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='BountyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('rating', models.PositiveSmallIntegerField()),
                ('body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BountySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('revision_requested', 'Revision Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=32)),
                ('reviewer_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketCustodian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('scope', models.CharField(choices=[('all', 'All products'), ('type', 'Specific product types'), ('category', 'Specific categories')], default='all', max_length=16)),
                ('regulated_product_types', models.JSONField(blank=True, default=list, help_text='List of product_type values this custodian regulates (used when scope=type).')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending confirmation'), ('confirmed', 'Confirmed by receiver'), ('disputed', 'Disputed'), ('custodian_review', 'Under custodian review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=24)),
                ('receiver_note', models.TextField(blank=True)),
                ('dispute_note', models.TextField(blank=True)),
                ('custodian_approval_status', models.CharField(choices=[('not_required', 'Not required'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_required', max_length=16)),
                ('custodian_note', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'service delivery',
                'verbose_name_plural': 'service deliveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='custodian_approval_status',
            field=models.CharField(choices=[('not_required', 'Not required'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_required', max_length=16),
        ),
        migrations.AddField(
            model_name='product',
            name='custodian_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_regulated',
            field=models.BooleanField(default=False, help_text='Requires custodian approval before publishing or order confirmation.'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_regulated', 'custodian_approval_status'], name='bazaar_prod_is_regu_6ddec3_idx'),
        ),
        migrations.AddField(
            model_name='servicedelivery',
            name='custodian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_deliveries', to='bazaar.marketcustodian'),
        ),
        migrations.AddField(
            model_name='servicedelivery',
            name='order_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_delivery', to='bazaar.orderitem'),
        ),
        migrations.AddField(
            model_name='marketcustodian',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_custodianships', to='people.person'),
        ),
        migrations.AddField(
            model_name='marketcustodian',
            name='regulated_categories',
            field=models.ManyToManyField(blank=True, help_text='Categories this custodian regulates (used when scope=category).', related_name='custodians', to='bazaar.productcategory'),
        ),
        migrations.AddField(
            model_name='marketcustodian',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custodians', to='bazaar.shop'),
        ),
        migrations.AddField(
            model_name='bountysubmission',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='bazaar.bountyclaim'),
        ),
        migrations.AddField(
            model_name='bountyreview',
            name='bounty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bazaar.bounty'),
        ),
        migrations.AddField(
            model_name='bountyreview',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='bazaar.bountyclaim'),
        ),
        migrations.AddField(
            model_name='bountyreview',
            name='hunter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_bounty_reviews', to='people.person'),
        ),
        migrations.AddField(
            model_name='bountyreview',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_bounty_reviews', to='people.person'),
        ),
        migrations.AddField(
            model_name='bountypayment',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bazaar_bounty_payments', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='bountypayment',
            name='claim',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bazaar.bountyclaim'),
        ),
        migrations.AddField(
            model_name='bountypayment',
            name='ledger_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bazaar_bounty_payments', to='assets.ledgeraccount'),
        ),
        migrations.AddField(
            model_name='bountypayment',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounty_payments_issued', to='people.person'),
        ),
        migrations.AddField(
            model_name='bountyclaim',
            name='bounty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='bazaar.bounty'),
        ),
        migrations.AddField(
            model_name='bountyclaim',
            name='hunter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bounty_claims', to='people.person'),
        ),
        migrations.AddField(
            model_name='bountyclaim',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bazaar_bounty_claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bountycategory',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='bazaar.bountyboard'),
        ),
        migrations.AddField(
            model_name='bountycategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='bazaar.bountycategory'),
        ),
        migrations.AddField(
            model_name='bountyboard',
            name='custodian',
            field=models.ForeignKey(blank=True, help_text='Custodian who must approve each submission before reward is released.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounty_boards', to='bazaar.marketcustodian'),
        ),
        migrations.AddField(
            model_name='bountyboard',
            name='ledger_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounty_boards', to='assets.ledgeraccount'),
        ),
        migrations.AddField(
            model_name='bountyboard',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bounty_boards', to='bazaar.shop'),
        ),
        migrations.AddField(
            model_name='bounty',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bounties', to='bazaar.bountyboard'),
        ),
        migrations.AddField(
            model_name='bounty',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounties', to='bazaar.bountycategory'),
        ),
        migrations.AddField(
            model_name='bounty',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bounties', to='people.person'),
        ),
        migrations.AddField(
            model_name='bounty',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bazaar_bounties', to='locations.address'),
        ),
        migrations.AddField(
            model_name='bounty',
            name='reward_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bazaar_bounties', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='bounty',
            name='territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bazaar_bounties', to='locations.territory'),
        ),
        migrations.AddField(
            model_name='product',
            name='custodian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regulated_products', to='bazaar.marketcustodian'),
        ),
        migrations.AddConstraint(
            model_name='bountyreview',
            constraint=models.CheckConstraint(check=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='bazaar_bounty_review_rating_1_to_5'),
        ),
        migrations.AlterUniqueTogether(
            name='bountyclaim',
            unique_together={('bounty', 'hunter')},
        ),
        migrations.AlterUniqueTogether(
            name='bountycategory',
            unique_together={('board', 'slug')},
        ),
        migrations.AddIndex(
            model_name='bounty',
            index=models.Index(fields=['board', 'status', 'is_public'], name='bazaar_boun_board_i_aa2c31_idx'),
        ),
        migrations.AddIndex(
            model_name='bounty',
            index=models.Index(fields=['bounty_type'], name='bazaar_boun_bounty__e4b524_idx'),
        ),
        migrations.AddIndex(
            model_name='bounty',
            index=models.Index(fields=['difficulty'], name='bazaar_boun_difficu_e771ca_idx'),
        ),
        migrations.AddIndex(
            model_name='bounty',
            index=models.Index(fields=['is_featured'], name='bazaar_boun_is_feat_9e1dbf_idx'),
        ),
        migrations.AddIndex(
            model_name='bounty',
            index=models.Index(fields=['deadline'], name='bazaar_boun_deadlin_76ba1e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bounty',
            unique_together={('board', 'slug')},
        ),
    ]
