# Generated by Django 4.2.23 on 2026-05-20 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0008_bounty_bountyboard_bountycategory_bountyclaim_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bountyboard',
            name='custodian',
        ),
        migrations.RemoveField(
            model_name='bountyboard',
            name='ledger_account',
        ),
        migrations.RemoveField(
            model_name='bountyboard',
            name='shop',
        ),
        migrations.AlterUniqueTogether(
            name='bountycategory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='bountycategory',
            name='board',
        ),
        migrations.RemoveField(
            model_name='bountycategory',
            name='parent',
        ),
        migrations.AlterUniqueTogether(
            name='bountyclaim',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='bountyclaim',
            name='bounty',
        ),
        migrations.RemoveField(
            model_name='bountyclaim',
            name='hunter',
        ),
        migrations.RemoveField(
            model_name='bountyclaim',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bountypayment',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='bountypayment',
            name='claim',
        ),
        migrations.RemoveField(
            model_name='bountypayment',
            name='ledger_account',
        ),
        migrations.RemoveField(
            model_name='bountypayment',
            name='paid_by',
        ),
        migrations.RemoveField(
            model_name='bountyreview',
            name='bounty',
        ),
        migrations.RemoveField(
            model_name='bountyreview',
            name='claim',
        ),
        migrations.RemoveField(
            model_name='bountyreview',
            name='hunter',
        ),
        migrations.RemoveField(
            model_name='bountyreview',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='bountysubmission',
            name='claim',
        ),
        migrations.DeleteModel(
            name='Bounty',
        ),
        migrations.DeleteModel(
            name='BountyBoard',
        ),
        migrations.DeleteModel(
            name='BountyCategory',
        ),
        migrations.DeleteModel(
            name='BountyClaim',
        ),
        migrations.DeleteModel(
            name='BountyPayment',
        ),
        migrations.DeleteModel(
            name='BountyReview',
        ),
        migrations.DeleteModel(
            name='BountySubmission',
        ),
    ]
