# Generated by Django 4.2.23 on 2026-10-01 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_hash', models.CharField(max_length=71)),
                ('unit_name', models.CharField(max_length=20)),
                ('max_supply_base_units', models.PositiveBigIntegerField()),
                ('decimals', models.PositiveSmallIntegerField()),
                ('reason', models.TextField()),
                ('genesis_payload', models.JSONField(default=dict)),
                ('genesis_signature', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_issuances', to=settings.AUTH_USER_MODEL)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='issuance', to='assets.asset')),
                ('ledger_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issuance_records', to='assets.ledgertransaction')),
            ],
            options={
                'verbose_name': 'issuance record',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='LedgerAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=200)),
                ('outcome', models.CharField(max_length=16)),
                ('findings', models.JSONField(blank=True, default=list)),
                ('statement', models.JSONField(blank=True, default=dict)),
                ('expected_allocated_base_units', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['node_id', '-created_at'], name='mint_audit_node_idx')],
            },
        ),
        migrations.CreateModel(
            name='CurrencyMintEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveBigIntegerField(unique=True)),
                ('kind', models.CharField(choices=[('mint', 'Mint'), ('burn', 'Burn')], max_length=8)),
                ('currency_hash', models.CharField(max_length=71)),
                ('amount_base_units', models.PositiveBigIntegerField()),
                ('prev_hash', models.CharField(blank=True, default='', max_length=71)),
                ('event_hash', models.CharField(max_length=71, unique=True)),
                ('signature', models.TextField()),
                ('issuer_fingerprint', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('reason', models.TextField()),
                ('external_ref', models.CharField(blank=True, default='', max_length=200)),
                ('backend', models.CharField(blank=True, default='', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mint_events', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mint_events', to='assets.asset')),
                ('ledger_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mint_events', to='assets.ledgertransaction')),
            ],
            options={
                'verbose_name': 'monetary event',
                'ordering': ['sequence'],
                'indexes': [models.Index(fields=['currency_hash', 'sequence'], name='mint_event_currency_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='currencymintevent',
            constraint=models.UniqueConstraint(fields=('prev_hash',), name='mint_one_child_per_event'),
        ),
    ]
