# Generated by Django 4.2.23 on 2026-08-11 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_hash', models.CharField(max_length=71)),
                ('unit_name', models.CharField(max_length=20)),
                ('total_supply_base_units', models.PositiveBigIntegerField()),
                ('decimals', models.PositiveSmallIntegerField()),
                ('reason', models.TextField()),
                ('genesis_payload', models.JSONField(default=dict)),
                ('genesis_signature', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_issuances', to=settings.AUTH_USER_MODEL)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='issuance', to='assets.asset')),
                ('ledger_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issuance_records', to='assets.ledgertransaction')),
            ],
            options={
                'verbose_name': 'issuance record',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
