# Generated by Django 4.2.23 on 2026-08-11 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyMintEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveBigIntegerField(unique=True)),
                ('kind', models.CharField(choices=[('mint', 'Mint'), ('burn', 'Burn')], max_length=8)),
                ('currency_hash', models.CharField(max_length=71)),
                ('amount_base_units', models.PositiveBigIntegerField()),
                ('prev_hash', models.CharField(blank=True, default='', max_length=71)),
                ('event_hash', models.CharField(max_length=71, unique=True)),
                ('signature', models.TextField()),
                ('issuer_fingerprint', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('reason', models.TextField()),
                ('external_ref', models.CharField(blank=True, default='', max_length=200)),
                ('backend', models.CharField(blank=True, default='', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mint_events', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mint_events', to='assets.asset')),
                ('ledger_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mint_events', to='assets.ledgertransaction')),
            ],
            options={
                'verbose_name': 'monetary event',
                'ordering': ['sequence'],
                'indexes': [models.Index(fields=['currency_hash', 'sequence'], name='mint_event_currency_idx')],
            },
        ),
    ]
