# Generated by Django 4.2.23 on 2026-06-04 19:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IdeaBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('body', models.TextField(blank=True)),
                ('is_concept', models.BooleanField(default=False, help_text='Marks this box as a concept/tag-like node rather than a normal captured idea.')),
                ('source_title', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True)),
                ('source_type', models.CharField(blank=True, help_text='Book, article, movie, video, podcast, conversation, etc.', max_length=40)),
                ('quote', models.TextField(blank=True)),
                ('properties', models.JSONField(blank=True, default=dict, help_text="Flexible metadata, e.g. {'topic': 'memory', 'rating': 4, 'status': 'raw'}.")),
                ('is_locked', models.BooleanField(default=False)),
                ('lock_salt', models.BinaryField(blank=True, null=True)),
                ('encrypted_body', models.BinaryField(blank=True, null=True)),
                ('lock_nonce', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idea_boxes', to='bento.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdeaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('label', models.CharField(blank=True, help_text='Free-text relationship label, e.g. about, supports, contradicts, expands.', max_length=80)),
                ('properties', models.JSONField(blank=True, default=dict, help_text='Flexible metadata for the link.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='bento.ideabox')),
                ('to_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='bento.ideabox')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('from_box', 'to_box', 'label')},
            },
        ),
    ]
