# Generated by Django 4.2.23 on 2026-05-31 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideabox',
            name='encrypted_body',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ideabox',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ideabox',
            name='lock_nonce',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ideabox',
            name='lock_salt',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
