# Generated by Django 4.2.23 on 2026-06-08 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bento', '0002_subjectreference_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubjectReference',
        ),
    ]
