# Generated by Django 4.2.23 on 2026-06-09 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bento', '0004_bentocategory_bentoedgetype_remove_ideabox_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bentocategory',
            name='color',
        ),
        migrations.RemoveField(
            model_name='bentocategory',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='bentoedgetype',
            name='color',
        ),
    ]
