# Generated by Django 4.2.23 on 2026-05-29 11:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsageMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('namespace', models.CharField(blank=True, max_length=120)),
                ('default_unit', models.CharField(blank=True, max_length=60)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Usage Metric',
                'verbose_name_plural': 'Usage Metrics',
                'ordering': ['namespace', 'code'],
            },
        ),
        migrations.CreateModel(
            name='UsageQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('subject_type', models.CharField(blank=True, max_length=200)),
                ('subject_id', models.CharField(blank=True, max_length=255)),
                ('subject_label', models.CharField(blank=True, max_length=255)),
                ('limit_quantity', models.DecimalField(decimal_places=10, max_digits=30)),
                ('unit', models.CharField(blank=True, max_length=60)),
                ('period', models.CharField(choices=[('lifetime', 'Lifetime'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('rolling', 'Rolling')], default='monthly', max_length=20)),
                ('rolling_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('track', 'Track only'), ('warn', 'Warn when exceeded'), ('block', 'Block when exceeded')], default='track', max_length=10)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotas', to='metering.usagemetric')),
            ],
            options={
                'verbose_name': 'Usage Quota',
                'verbose_name_plural': 'Usage Quotas',
                'ordering': ['metric', 'code'],
            },
        ),
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=30)),
                ('unit', models.CharField(blank=True, max_length=60)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_type', models.CharField(blank=True, max_length=200)),
                ('source_id', models.CharField(blank=True, max_length=255)),
                ('source_label', models.CharField(blank=True, max_length=255)),
                ('subject_type', models.CharField(blank=True, max_length=200)),
                ('subject_id', models.CharField(blank=True, max_length=255)),
                ('subject_label', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('recorded', 'Recorded'), ('voided', 'Voided'), ('superseded', 'Superseded')], default='recorded', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='metering.usagemetric')),
            ],
            options={
                'verbose_name': 'Usage Event',
                'verbose_name_plural': 'Usage Events',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='usagequota',
            constraint=models.CheckConstraint(check=models.Q(('limit_quantity__gt', 0)), name='metering_quota_limit_positive'),
        ),
        migrations.AddConstraint(
            model_name='usageevent',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('idempotency_key',), name='metering_event_unique_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='usageevent',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='metering_event_quantity_positive'),
        ),
    ]
