# Generated by Django 4.2.23 on 2025-11-19 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CypherQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Human-readable name of the query (e.g. 'All Nodes and Relationships').", max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of what this query does.')),
                ('query', models.TextField(help_text='The Cypher query string to run against Neo4j.')),
                ('category', models.CharField(blank=True, help_text="Optional category (e.g. 'exploration', 'analytics').", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this query.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cypher_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
