# Generated by Django 4.2.23 on 2025-12-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ravioli', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collector',
            name='app_name',
            field=models.CharField(choices=[('kanban', 'kanban'), ('events', 'events'), ('library', 'library'), ('locations', 'locations'), ('community', 'community'), ('finance', 'finance'), ('portfolio', 'portfolio'), ('federal', 'federal')], help_text='Name of the external app or integration.', max_length=150, unique=True),
        ),
    ]
