# Generated by Django 4.2.23 on 2025-11-20 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ravioli', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cypherquery',
            name='category',
        ),
    ]
