# Generated by Django 4.2.23 on 2025-12-24 09:21

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import toto.colors


class Migration(migrations.Migration):

    dependencies = [
        ('ravioli', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', colorfield.fields.ColorField(default=toto.colors.ColorGenerator.random_mpl_color, image_field=None, max_length=25, samples=None)),
                ('size', models.PositiveIntegerField(default=20)),
                ('collection_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='ravioli.collectiontype')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_styles', to='ravioli.graph')),
            ],
            options={
                'unique_together': {('graph', 'collection_type')},
            },
        ),
        migrations.CreateModel(
            name='EdgeStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', colorfield.fields.ColorField(default=toto.colors.ColorGenerator.random_mpl_color, image_field=None, max_length=25, samples=None)),
                ('size', models.PositiveIntegerField(default=2)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edge_styles', to='ravioli.graph')),
                ('relation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='ravioli.relationtype')),
            ],
            options={
                'unique_together': {('graph', 'relation_type')},
            },
        ),
    ]
