# Generated by Django 4.2.23 on 2025-12-19 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ravioli', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataTransform',
        ),
    ]
