# Generated by Django 4.2.23 on 2025-11-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ravioli', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='related_notes', to='ravioli.note'),
        ),
    ]
