# Generated by Django 4.2.23 on 2025-11-11 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('ravioli', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_for_event', to='events.event'),
        ),
    ]
