# Generated by Django 4.2.23 on 2025-12-26 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ravioli', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='edgestyle',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='edgestyle',
            name='cypher_query',
        ),
        migrations.RemoveField(
            model_name='edgestyle',
            name='relation_type',
        ),
        migrations.AlterUniqueTogether(
            name='nodestyle',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='nodestyle',
            name='collection_type',
        ),
        migrations.RemoveField(
            model_name='nodestyle',
            name='cypher_query',
        ),
        migrations.DeleteModel(
            name='CypherQuery',
        ),
        migrations.DeleteModel(
            name='EdgeStyle',
        ),
        migrations.DeleteModel(
            name='NodeStyle',
        ),
    ]
