# Generated by Django 4.2.23 on 2025-12-24 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ravioli', '0002_nodestyle_edgestyle'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='edgestyle',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='nodestyle',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='edgestyle',
            name='cypher_query',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='edge_styles', to='ravioli.cypherquery'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nodestyle',
            name='cypher_query',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='node_styles', to='ravioli.cypherquery'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='edgestyle',
            unique_together={('cypher_query', 'relation_type')},
        ),
        migrations.AlterUniqueTogether(
            name='nodestyle',
            unique_together={('cypher_query', 'collection_type')},
        ),
        migrations.RemoveField(
            model_name='edgestyle',
            name='graph',
        ),
        migrations.RemoveField(
            model_name='nodestyle',
            name='graph',
        ),
    ]
