# Generated by Django 4.2.23 on 2025-12-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ravioli', '0002_alter_edgestyle_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(choices=[('kanban', 'kanban'), ('events', 'events'), ('library', 'library'), ('locations', 'locations'), ('community', 'community'), ('assets', 'assets')], help_text='Name of the external app or integration.', max_length=150, unique=True)),
                ('node_map', models.JSONField(blank=True, help_text='JSON mapping describing how external node data maps to CollectionTypes.', null=True)),
                ('edge_map', models.JSONField(blank=True, help_text='JSON mapping describing how external edge data maps to RelationTypes.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
