# Generated by Django 4.2.23 on 2025-12-18 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ravioli', '0002_graphproposal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GraphProposal',
        ),
    ]
