# Generated by Django 4.2.23 on 2025-11-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ravioli', '0002_note_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Mark note as public'),
        ),
    ]
