# Generated by Django 4.2.23 on 2025-11-20 00:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ravioli', '0002_remove_cypherquery_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cypherquery',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
