# Generated by Django 4.2.23 on 2025-12-25 00:46

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ravioli', '0003_alter_edgestyle_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edgestyle',
            name='color',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='nodestyle',
            name='color',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None),
        ),
    ]
