# Generated by Django 4.2.23 on 2025-12-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ravioli', '0003_delete_graphproposal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationtype',
            name='form_layout',
        ),
        migrations.RemoveField(
            model_name='relationtype',
            name='json_schema',
        ),
        migrations.AddField(
            model_name='relationtype',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
