# Generated by Django 4.2.23 on 2025-11-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ravioli', '0003_note_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Mark note as public'),
        ),
    ]
