# Generated by Django 4.2.23 on 2026-01-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ravioli', '0003_alter_collector_app_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datanode',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='datanode',
            constraint=models.UniqueConstraint(fields=('name', 'graph'), name='unique_node_name_per_graph'),
        ),
    ]
