# Generated by Django 4.2.23 on 2025-11-24 04:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ravioli', '0003_alter_cypherquery_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(choices=[('community', 'community'), ('finance', 'finance'), ('portfolio', 'portfolio'), ('events', 'events'), ('federal', 'federal'), ('notes', 'notes')], help_text='Target app for graph sync', max_length=64)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this sync is scheduled')),
                ('executed_at', models.DateTimeField(blank=True, help_text='When this sync was actually executed', null=True)),
            ],
        ),
    ]
