# Generated by Django 4.2.23 on 2025-12-04 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ravioli', '0004_graphsync'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GraphSync',
        ),
    ]
