# Generated by Django 4.2.23 on 2025-12-25 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ravioli', '0004_alter_edgestyle_color_alter_nodestyle_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='cypherquery',
            name='code',
            field=models.TextField(default='', help_text='Restricted Python code snippet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cypherquery',
            name='test_context',
            field=models.JSONField(blank=True, help_text='Optional JSON context for testing', null=True),
        ),
    ]
