# Generated by Django 4.2.23 on 2025-12-26 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ravioli', '0005_alter_collector_app_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dataedge',
            unique_together={('source', 'target', 'relation_type')},
        ),
        migrations.RemoveField(
            model_name='dataedge',
            name='label',
        ),
    ]
