# Generated by Django 4.2.23 on 2025-12-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ravioli', '0006_alter_appcollector_app_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appcollector',
            name='config',
        ),
        migrations.RemoveField(
            model_name='appcollector',
            name='created_at',
        ),
        migrations.AddField(
            model_name='appcollector',
            name='code',
            field=models.TextField(default='', help_text='Restricted Python code snippet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appcollector',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appcollector',
            name='test_context',
            field=models.JSONField(blank=True, help_text='Optional JSON context for testing', null=True),
        ),
    ]
