# Generated by Django 4.2.23 on 2025-12-18 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ravioli', '0007_remove_appcollector_config_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appcollector',
            name='description',
        ),
    ]
