# Generated by Django 4.2.23 on 2025-12-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ravioli', '0008_remove_appcollector_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appcollector',
            name='code',
        ),
        migrations.RemoveField(
            model_name='appcollector',
            name='test_context',
        ),
        migrations.AddField(
            model_name='appcollector',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
