# Generated by Django 4.2.23 on 2025-12-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ravioli', '0009_remove_appcollector_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppCollector',
        ),
        migrations.AddField(
            model_name='graph',
            name='conversion_rules',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
