# Generated by Django 4.2.23 on 2025-12-18 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ravioli', '0010_delete_appcollector_graph_conversion_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCollector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(choices=[('community', 'community'), ('finance', 'finance'), ('events', 'events'), ('federal', 'federal')], help_text='Select an app from settings.GRAPH_APPS', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='graph',
            name='conversion_rules',
        ),
        migrations.AddField(
            model_name='graph',
            name='collector',
            field=models.ForeignKey(blank=True, help_text='Optionally bind this graph to an AppCollector', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graphs', to='ravioli.appcollector'),
        ),
    ]
