# Generated by Django 4.2.23 on 2025-12-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ravioli', '0011_appcollector_remove_graph_conversion_rules_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcollector',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
