# Generated by Django 4.2.23 on 2025-12-18 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ravioli', '0014_remove_graph_collector_graph_collectors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='collectors',
        ),
        migrations.DeleteModel(
            name='AppCollector',
        ),
    ]
