# Generated by Django 4.2.23 on 2025-12-19 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ravioli', '0015_remove_graph_collectors_delete_appcollector'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTransform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(help_text='Restricted Python code snippet')),
                ('test_context', models.JSONField(blank=True, help_text='Optional JSON context for testing', null=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('test_data', models.JSONField(blank=True, null=True)),
                ('graph', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transforms', to='ravioli.graph')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
