# Generated by Django 4.2.23 on 2026-05-17 08:41

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('extraction', 'Extraction'), ('energy', 'Energy'), ('industry', 'Industry'), ('high_tech', 'High-Tech Industry'), ('food', 'Food'), ('logistics', 'Logistics'), ('population', 'Population'), ('research', 'Research'), ('orbital', 'Orbital')], default='industry', max_length=40)),
                ('cell_cost', models.PositiveIntegerField(default=1)),
                ('base_energy_demand', models.FloatField(default=0.0)),
                ('max_level', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Empire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('credits', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_empire', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GameTick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_tick', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Game Tick',
                'verbose_name_plural': 'Game Tick',
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('tier', models.PositiveSmallIntegerField(choices=[(1, 'Resource'), (2, 'Component')])),
                ('cargo_class', models.CharField(choices=[('bulk', 'Bulk'), ('liquid', 'Liquid'), ('energy', 'Energy'), ('high_value', 'High Value'), ('hazardous', 'Hazardous'), ('people', 'People'), ('orbital', 'Orbital')], default='bulk', max_length=30)),
                ('is_energy', models.BooleanField(default=False)),
                ('is_strategic', models.BooleanField(default=False)),
                ('base_market_value', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['tier', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('planet_type', models.CharField(choices=[('terran', 'Terran'), ('desert', 'Desert'), ('volcanic', 'Volcanic'), ('oceanic', 'Oceanic'), ('ice', 'Ice'), ('barren', 'Barren')], default='terran', max_length=30)),
                ('size_class', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=30)),
                ('habitability', models.FloatField(default=0.5)),
                ('gravity', models.FloatField(default=1.0)),
                ('radiation', models.FloatField(default=0.0)),
                ('max_provinces', models.PositiveIntegerField(default=5)),
                ('policy', models.CharField(choices=[('balanced', 'Balanced Economy'), ('construction', 'Construction Focus'), ('energy', 'Energy Focus'), ('food', 'Food Security'), ('research', 'Research Focus'), ('export', 'Export Economy')], default='balanced', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planets', to='game.empire')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('terrain', models.CharField(choices=[('desert', 'Desert'), ('volcanic', 'Volcanic'), ('forest', 'Forest'), ('oceanic', 'Oceanic'), ('mountain', 'Mountain'), ('tundra', 'Tundra'), ('steppe', 'Steppe'), ('plains', 'Plains')], default='plains', max_length=30)),
                ('biome', models.CharField(blank=True, max_length=40)),
                ('cell_count', models.PositiveIntegerField(default=10)),
                ('habitability', models.FloatField(default=0.5)),
                ('infrastructure_level', models.FloatField(default=1.0)),
                ('specialization', models.CharField(choices=[('none', 'None'), ('mining', 'Mining Province'), ('energy', 'Energy Province'), ('industrial', 'Industrial Province'), ('high_tech', 'High-Tech Province'), ('agriculture', 'Agricultural Province'), ('logistics', 'Logistics Hub'), ('research', 'Research Province')], default='none', max_length=40)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='game.planet')),
            ],
            options={
                'ordering': ['planet', 'name'],
                'unique_together': {('planet', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('output_quantity_per_day', models.FloatField(default=1.0)),
                ('is_default', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('building_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='game.buildingtype')),
                ('output_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produced_by_recipes', to='game.itemtype')),
            ],
            options={
                'ordering': ['building_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TransportLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('road', 'Road'), ('rail', 'Rail'), ('pipeline', 'Pipeline'), ('grid', 'Power Grid')], default='road', max_length=30)),
                ('capacity_per_day', models.FloatField(default=100.0)),
                ('condition', models.FloatField(default=1.0)),
                ('is_active', models.BooleanField(default=True)),
                ('from_province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_out', to='game.province')),
                ('to_province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_in', to='game.province')),
            ],
        ),
        migrations.CreateModel(
            name='ProvincePopulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_population', models.PositiveIntegerField(default=0)),
                ('laborers', models.PositiveIntegerField(default=0)),
                ('technicians', models.PositiveIntegerField(default=0)),
                ('engineers', models.PositiveIntegerField(default=0)),
                ('scientists', models.PositiveIntegerField(default=0)),
                ('administrators', models.PositiveIntegerField(default=0)),
                ('happiness', models.FloatField(default=0.7)),
                ('health', models.FloatField(default=0.7)),
                ('education', models.FloatField(default=0.3)),
                ('province', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='population', to='game.province')),
            ],
        ),
        migrations.CreateModel(
            name='DepositType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('is_renewable', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('produces_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.itemtype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConstructionProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_level', models.PositiveIntegerField(default=1)),
                ('progress', models.FloatField(default=0.0)),
                ('required_work', models.FloatField(default=100.0)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('constructing', 'Constructing'), ('disabled', 'Disabled')], default='constructing', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.buildingtype')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='construction_projects', to='game.province')),
            ],
            options={
                'ordering': ['province', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('constructing', 'Constructing'), ('disabled', 'Disabled')], default='active', max_length=30)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=20)),
                ('efficiency', models.FloatField(default=1.0)),
                ('condition', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.buildingtype')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='game.province')),
                ('selected_recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_by_buildings', to='game.recipe')),
            ],
            options={
                'ordering': ['province', 'building_type'],
            },
        ),
        migrations.CreateModel(
            name='RecipeInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_day', models.FloatField(default=1.0)),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.itemtype')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='game.recipe')),
            ],
            options={
                'ordering': ['recipe', 'item_type'],
                'unique_together': {('recipe', 'item_type')},
            },
        ),
        migrations.CreateModel(
            name='ProvinceInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=24)),
                ('capacity', models.DecimalField(decimal_places=4, default=Decimal('100000.0000'), max_digits=24)),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.itemtype')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='game.province')),
            ],
            options={
                'ordering': ['province', 'item_type'],
                'unique_together': {('province', 'item_type')},
            },
        ),
        migrations.CreateModel(
            name='ProvinceDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abundance', models.FloatField(default=1.0)),
                ('richness', models.FloatField(default=1.0)),
                ('accessibility', models.FloatField(default=1.0)),
                ('depletion', models.FloatField(default=0.0)),
                ('deposit_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.deposittype')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='game.province')),
            ],
            options={
                'ordering': ['province', 'deposit_type'],
                'unique_together': {('province', 'deposit_type')},
            },
        ),
    ]
