# Generated by Django 4.2.23 on 2026-10-01 05:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerPeer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_url', models.URLField(help_text="The peer's public base URL, e.g. https://master.example.com")),
                ('role', models.CharField(choices=[('parent', 'Parent'), ('child', 'Child')], max_length=10)),
                ('platform_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended')], default='pending', max_length=12)),
                ('client_id', models.CharField(max_length=128)),
                ('client_secret_encrypted', models.BinaryField(blank=True, default=b'')),
                ('previous_secret_encrypted', models.BinaryField(blank=True, default=b'')),
                ('secret_cheap_hash', models.CharField(blank=True, default='', max_length=64)),
                ('previous_cheap_hash', models.CharField(blank=True, default='', max_length=64)),
                ('our_private_key_encrypted', models.BinaryField(blank=True, default=b'')),
                ('our_public_key_pem', models.TextField(blank=True, default='')),
                ('peer_public_key_pem', models.TextField(blank=True, default='')),
                ('epoch', models.CharField(default=uuid.uuid4, max_length=36)),
                ('peer_epoch', models.CharField(blank=True, default='', max_length=36)),
                ('send_seq', models.BigIntegerField(default=0)),
                ('recv_seq', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SharedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_here', models.BooleanField()),
                ('enabled', models.BooleanField(default=True)),
                ('max_owed_base_units', models.BigIntegerField(default=0)),
                ('settlement_threshold_base_units', models.BigIntegerField(default=0)),
                ('mirror_cursor', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shared_with', to='assets.asset')),
                ('escrow_account', models.ForeignKey(blank=True, help_text='Both sides: where pending holds park value.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='assets.ledgeraccount')),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shared_assets', to='clearing.ledgerpeer')),
                ('vostro_account', models.ForeignKey(blank=True, help_text="Home side only: the peer platform's aggregate position here.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='assets.ledgeraccount')),
            ],
            options={
                'unique_together': {('asset', 'peer')},
            },
        ),
        migrations.CreateModel(
            name='ClearingHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('purpose', models.CharField(choices=[('transfer', 'Transfer'), ('swap', 'Swap')], max_length=10)),
                ('amount_base_units', models.BigIntegerField()),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('posted', 'Posted'), ('voided', 'Voided'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('remote_ref', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hold_txn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='assets.ledgertransaction')),
                ('origin_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='assets.ledgeraccount')),
                ('settle_txn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='assets.ledgertransaction')),
                ('shared_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holds', to='clearing.sharedasset')),
            ],
        ),
        migrations.CreateModel(
            name='ClearingTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('direction', models.CharField(choices=[('out', 'Outbound'), ('in', 'Inbound')], max_length=3)),
                ('amount_base_units', models.BigIntegerField()),
                ('state', models.CharField(choices=[('prepared', 'Prepared'), ('fulfilled', 'Fulfilled'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='prepared', max_length=10)),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('remote_account_code', models.CharField(max_length=100)),
                ('receipt_signature', models.TextField(blank=True, default='')),
                ('deadline', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hold', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='clearing.clearinghold')),
                ('ledger_txn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='assets.ledgertransaction')),
                ('local_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='assets.ledgeraccount')),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='clearing.ledgerpeer')),
                ('shared_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='clearing.sharedasset')),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'deadline'], name='clearing_cl_state_ab083a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClearingOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('seq', models.BigIntegerField()),
                ('kind', models.CharField(max_length=40)),
                ('payload', models.JSONField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('signature', models.TextField()),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('acked', 'Acked'), ('failed', 'Failed'), ('held', 'Held')], default='queued', max_length=10)),
                ('attempts', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbox', to='clearing.ledgerpeer')),
            ],
            options={
                'ordering': ['seq'],
                'indexes': [models.Index(fields=['state', 'created_at'], name='clearing_cl_state_c95a08_idx')],
                'unique_together': {('peer', 'seq')},
            },
        ),
        migrations.CreateModel(
            name='ClearingInbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(editable=False)),
                ('seq', models.BigIntegerField()),
                ('kind', models.CharField(max_length=40)),
                ('payload', models.JSONField()),
                ('param_hash', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[('received', 'Received'), ('applied', 'Applied'), ('rejected', 'Rejected')], default='received', max_length=10)),
                ('response', models.JSONField(default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbox', to='clearing.ledgerpeer')),
            ],
            options={
                'indexes': [models.Index(fields=['peer', 'seq'], name='clearing_cl_peer_id_3d61ae_idx')],
                'unique_together': {('peer', 'uuid')},
            },
        ),
        migrations.AddIndex(
            model_name='clearinghold',
            index=models.Index(fields=['state', 'expires_at'], name='clearing_cl_state_93386b_idx'),
        ),
    ]
