# Generated by Django 4.2.23 on 2026-08-02 10:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerPeer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_url', models.URLField(help_text="The peer's public base URL, e.g. https://master.example.com")),
                ('role', models.CharField(choices=[('parent', 'Parent'), ('child', 'Child')], max_length=10)),
                ('platform_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended')], default='pending', max_length=12)),
                ('client_id', models.CharField(max_length=128)),
                ('client_secret_encrypted', models.BinaryField(blank=True, default=b'')),
                ('previous_secret_encrypted', models.BinaryField(blank=True, default=b'')),
                ('secret_cheap_hash', models.CharField(blank=True, default='', max_length=64)),
                ('previous_cheap_hash', models.CharField(blank=True, default='', max_length=64)),
                ('our_private_key_encrypted', models.BinaryField(blank=True, default=b'')),
                ('our_public_key_pem', models.TextField(blank=True, default='')),
                ('peer_public_key_pem', models.TextField(blank=True, default='')),
                ('epoch', models.CharField(default=uuid.uuid4, max_length=36)),
                ('peer_epoch', models.CharField(blank=True, default='', max_length=36)),
                ('send_seq', models.BigIntegerField(default=0)),
                ('recv_seq', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
