# Generated by Django 4.2.23 on 2026-08-02 10:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_ledgertransaction_origin_platform_and_more'),
        ('clearing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_here', models.BooleanField()),
                ('enabled', models.BooleanField(default=True)),
                ('max_owed_base_units', models.BigIntegerField(default=0)),
                ('settlement_threshold_base_units', models.BigIntegerField(default=0)),
                ('mirror_cursor', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shared_with', to='assets.asset')),
                ('escrow_account', models.ForeignKey(blank=True, help_text='Both sides: where pending holds park value.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='assets.ledgeraccount')),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shared_assets', to='clearing.ledgerpeer')),
                ('vostro_account', models.ForeignKey(blank=True, help_text="Home side only: the peer platform's aggregate position here.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='assets.ledgeraccount')),
            ],
            options={
                'unique_together': {('asset', 'peer')},
            },
        ),
        migrations.CreateModel(
            name='ClearingHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('purpose', models.CharField(choices=[('transfer', 'Transfer'), ('swap', 'Swap')], max_length=10)),
                ('amount_base_units', models.BigIntegerField()),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('posted', 'Posted'), ('voided', 'Voided'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('remote_ref', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hold_txn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='assets.ledgertransaction')),
                ('origin_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='assets.ledgeraccount')),
                ('settle_txn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='assets.ledgertransaction')),
                ('shared_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holds', to='clearing.sharedasset')),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'expires_at'], name='clearing_cl_state_93386b_idx')],
            },
        ),
    ]
