# Generated by Django 4.2.23 on 2026-08-02 15:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_ledgertransaction_origin_platform_and_more'),
        ('clearing', '0002_sharedasset_clearinghold'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearingTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('direction', models.CharField(choices=[('out', 'Outbound'), ('in', 'Inbound')], max_length=3)),
                ('amount_base_units', models.BigIntegerField()),
                ('state', models.CharField(choices=[('prepared', 'Prepared'), ('fulfilled', 'Fulfilled'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='prepared', max_length=10)),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('remote_account_code', models.CharField(max_length=100)),
                ('receipt_signature', models.TextField(blank=True, default='')),
                ('deadline', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hold', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='clearing.clearinghold')),
                ('ledger_txn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='assets.ledgertransaction')),
                ('local_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='assets.ledgeraccount')),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='clearing.ledgerpeer')),
                ('shared_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='clearing.sharedasset')),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'deadline'], name='clearing_cl_state_ab083a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClearingOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('seq', models.BigIntegerField()),
                ('kind', models.CharField(max_length=40)),
                ('payload', models.JSONField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('signature', models.TextField()),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('acked', 'Acked'), ('failed', 'Failed'), ('held', 'Held')], default='queued', max_length=10)),
                ('attempts', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbox', to='clearing.ledgerpeer')),
            ],
            options={
                'ordering': ['seq'],
                'indexes': [models.Index(fields=['state', 'created_at'], name='clearing_cl_state_c95a08_idx')],
                'unique_together': {('peer', 'seq')},
            },
        ),
        migrations.CreateModel(
            name='ClearingInbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(editable=False)),
                ('seq', models.BigIntegerField()),
                ('kind', models.CharField(max_length=40)),
                ('payload', models.JSONField()),
                ('param_hash', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[('received', 'Received'), ('applied', 'Applied'), ('rejected', 'Rejected')], default='received', max_length=10)),
                ('response', models.JSONField(default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbox', to='clearing.ledgerpeer')),
            ],
            options={
                'indexes': [models.Index(fields=['peer', 'seq'], name='clearing_cl_peer_id_3d61ae_idx')],
                'unique_together': {('peer', 'uuid')},
            },
        ),
    ]
