# Generated by Django 4.2.23 on 2026-07-12 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
        ('gitvault', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitrun',
            name='workflow_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='git_runs', to='workflows.workflowrun'),
        ),
        migrations.AlterField(
            model_name='gitrun',
            name='op',
            field=models.CharField(choices=[('init', 'Init'), ('push', 'Push'), ('pull', 'Pull')], max_length=10),
        ),
    ]
