# Generated by Django 4.2.23 on 2026-10-01 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gervazy', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OIDCProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Portal', max_length=100)),
                ('portal_url', models.URLField()),
                ('client_id', models.CharField(max_length=128)),
                ('scopes', models.CharField(default='openid email profile', max_length=255)),
                ('trusted', models.BooleanField(default=False)),
                ('redirect_uris', models.TextField(blank=True, help_text='One redirect URI per line.')),
                ('active', models.BooleanField(default=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('issuer', models.CharField(blank=True, max_length=255)),
                ('authorization_endpoint', models.CharField(blank=True, max_length=500)),
                ('token_endpoint', models.CharField(blank=True, max_length=500)),
                ('userinfo_endpoint', models.CharField(blank=True, max_length=500)),
                ('jwks_uri', models.CharField(blank=True, max_length=500)),
                ('callback_uri', models.CharField(blank=True, max_length=500)),
                ('remote_client_uuid', models.CharField(blank=True, max_length=64)),
                ('paired_at', models.DateTimeField(blank=True, null=True)),
                ('last_pair_error', models.TextField(blank=True)),
                ('secret', models.ForeignKey(blank=True, help_text='Gervazy EncryptedSecret holding the OIDC client secret.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oidc_provider_configs', to='gervazy.encryptedsecret')),
            ],
            options={
                'verbose_name': 'OIDC Provider Config',
                'verbose_name_plural': 'OIDC Provider Configs',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='FederatedIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=255)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('provisioned', models.BooleanField(default=False)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identities', to='sso_client.oidcproviderconfig')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='federated_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Federated Identity',
                'verbose_name_plural': 'Federated Identities',
            },
        ),
        migrations.AddConstraint(
            model_name='federatedidentity',
            constraint=models.UniqueConstraint(fields=('provider', 'sub'), name='uniq_provider_sub'),
        ),
    ]
