# Generated by Django 4.2.23 on 2026-05-18 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OIDCProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Portal', max_length=100)),
                ('portal_url', models.URLField()),
                ('client_id', models.CharField(max_length=128)),
                ('client_secret', models.CharField(blank=True, max_length=255)),
                ('scopes', models.CharField(default='openid email profile', max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'OIDC Provider Config',
                'verbose_name_plural': 'OIDC Provider Configs',
                'ordering': ['-imported_at'],
            },
        ),
    ]
