# Generated by Django 4.2.23 on 2026-08-01 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gervazy', '0002_initial'),
        ('sso_client', '0003_federatedidentity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oidcproviderconfig',
            name='app_name',
        ),
        migrations.RemoveField(
            model_name='oidcproviderconfig',
            name='client_secret',
        ),
        migrations.AddField(
            model_name='oidcproviderconfig',
            name='authorization_endpoint',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='oidcproviderconfig',
            name='callback_uri',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='oidcproviderconfig',
            name='issuer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='oidcproviderconfig',
            name='jwks_uri',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='oidcproviderconfig',
            name='last_pair_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='oidcproviderconfig',
            name='paired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oidcproviderconfig',
            name='remote_client_uuid',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='oidcproviderconfig',
            name='secret',
            field=models.ForeignKey(blank=True, help_text='Gervazy EncryptedSecret holding the OIDC client secret.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oidc_provider_configs', to='gervazy.encryptedsecret'),
        ),
        migrations.AddField(
            model_name='oidcproviderconfig',
            name='token_endpoint',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='oidcproviderconfig',
            name='userinfo_endpoint',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='federatedidentity',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identities', to='sso_client.oidcproviderconfig'),
        ),
    ]
