# Generated by Django 4.2.23 on 2026-05-15 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraphSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Graph Sync',
                'verbose_name_plural': 'Graph Sync',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CypherQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('query', models.TextField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Cypher Query',
                'verbose_name_plural': 'Cypher Queries',
            },
        ),
        migrations.CreateModel(
            name='CypherQueryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ravioli.cypherquery')),
            ],
            options={
                'verbose_name': 'Graph Viewer',
                'verbose_name_plural': 'Graph Viewer',
            },
        ),
    ]
