# Generated by Django 4.2.23 on 2026-05-25 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraphSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Graph Sync',
                'verbose_name_plural': 'Graph Sync',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CypherQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('query', models.TextField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Cypher Query',
                'verbose_name_plural': 'Cypher Queries',
            },
        ),
        migrations.CreateModel(
            name='GraphProjectionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('applying', 'Applying…'), ('applied', 'Applied'), ('failed', 'Failed')], db_index=True, default='ready', max_length=16)),
                ('scope', models.JSONField(blank=True, default=dict)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('diff', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Graph Projection Plan',
                'verbose_name_plural': 'Graph Projection Plans',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GraphChangeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('upsert_node', 'Upsert node'), ('delete_node', 'Delete node'), ('resync_links', 'Resync outgoing links'), ('resync_link_source', 'Resync one link source'), ('resync_link_full', 'Resync full link'), ('upsert_junction', 'Upsert junction relationship'), ('delete_junction', 'Delete junction relationship')], max_length=32)),
                ('graph_label', models.CharField(blank=True, max_length=128)),
                ('model_path', models.CharField(blank=True, max_length=255)),
                ('object_uuid', models.CharField(blank=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Graph Change Event',
                'verbose_name_plural': 'Graph Change Events',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='ravioli_gra_status_a3663a_idx'), models.Index(fields=['graph_label', 'object_uuid'], name='ravioli_gra_graph_l_ba4a1f_idx')],
            },
        ),
        migrations.CreateModel(
            name='CypherQueryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_nodes', models.JSONField(blank=True, null=True)),
                ('result_edges', models.JSONField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='ravioli.cypherquery')),
            ],
            options={
                'verbose_name': 'Graph Viewer',
                'verbose_name_plural': 'Graph Viewer',
            },
        ),
    ]
